import Project.EulerOutwardSpeed.ArtifactCode0
import Project.EulerOutwardSpeed.ArtifactCode1
import Project.EulerOutwardSpeed.ArtifactCode2
import Project.EulerOutwardSpeed.ArtifactCode3
import Project.EulerOutwardSpeed.ArtifactCode4
import Project.EulerOutwardSpeed.ArtifactCode5
import Project.EulerOutwardSpeed.ArtifactCode6
import Project.EulerOutwardSpeed.ArtifactCode7
