/-
  AUTO-GENERATED by `verifier emit`. Do not edit by hand.
-/

import CodeLib

set_option maxRecDepth 1048576

namespace Project.ClobPostOnly

open Wasm

def func0 : Wasm.Program :=
  [
  .localGet 0,
  .localSet 5,
  .localGet 5
]

def func0Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64], locals := [.i64], body := func0, results := [.i64] }

def func1 : Wasm.Program :=
  [
  .localGet 1,
  .localSet 5,
  .localGet 5
]

def func1Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64], locals := [.i64], body := func1, results := [.i64] }

def func2 : Wasm.Program :=
  [
  .localGet 0,
  .constI64 (0 : UInt64),
  .eqI64,
  .iff 0 1 [
    .constI64 (1 : UInt64)
  ] [
    .constI64 (0 : UInt64)
  ],
  .constI64 (0 : UInt64),
  .eqI64,
  .eqz,
  .iff 0 1 [
    .const (1 : UInt32)
  ] [
    .localGet 0,
    .constI64 (1 : UInt64),
    .eqI64,
    .iff 0 1 [
      .constI64 (1 : UInt64)
    ] [
      .constI64 (0 : UInt64)
    ],
    .constI64 (0 : UInt64),
    .eqI64,
    .eqz
  ],
  .iff 0 1 [
    .constI64 (1 : UInt64)
  ] [
    .constI64 (0 : UInt64)
  ],
  .localSet 1,
  .localGet 1
]

def func2Def : Wasm.Function :=
  { params := [.i64], locals := [.i64], body := func2, results := [.i64] }

def func3 : Wasm.Program :=
  [
  .localGet 2,
  .localSet 5,
  .localGet 5
]

def func3Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64], locals := [.i64], body := func3, results := [.i64] }

def func4 : Wasm.Program :=
  [
  .localGet 4,
  .localSet 5,
  .localGet 5
]

def func4Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64], locals := [.i64], body := func4, results := [.i64] }

def func5 : Wasm.Program :=
  [
  .localGet 1,
  .localSet 9,
  .localGet 9,
  .wrapI64,
  .load64 (0 : UInt32),
  .localSet 10,
  .constI64 (0 : UInt64),
  .localSet 11,
  .localGet 1,
  .localSet 15,
  .localGet 15,
  .wrapI64,
  .load64 (0 : UInt32),
  .localSet 12,
  .constI64 (0 : UInt64),
  .localSet 14,
  .localGet 12,
  .localGet 10,
  .ltUI64,
  .iff 0 1 [
    .localGet 12
  ] [
    .localGet 10
  ],
  .localSet 13,
  .block 0 0 [
    .loop 0 0 [
      .localGet 11,
      .localGet 13,
      .geUI64,
      .br_if 1,
      .localGet 9,
      .localGet 11,
      .constI64 (5 : UInt64),
      .mulI64,
      .constI64 (1 : UInt64),
      .addI64,
      .constI64 (8 : UInt64),
      .mulI64,
      .addI64,
      .wrapI64,
      .load64 (0 : UInt32),
      .localSet 3,
      .localGet 9,
      .localGet 11,
      .constI64 (5 : UInt64),
      .mulI64,
      .constI64 (2 : UInt64),
      .addI64,
      .constI64 (8 : UInt64),
      .mulI64,
      .addI64,
      .wrapI64,
      .load64 (0 : UInt32),
      .localSet 4,
      .localGet 9,
      .localGet 11,
      .constI64 (5 : UInt64),
      .mulI64,
      .constI64 (3 : UInt64),
      .addI64,
      .constI64 (8 : UInt64),
      .mulI64,
      .addI64,
      .wrapI64,
      .load64 (0 : UInt32),
      .localSet 5,
      .localGet 9,
      .localGet 11,
      .constI64 (5 : UInt64),
      .mulI64,
      .constI64 (4 : UInt64),
      .addI64,
      .constI64 (8 : UInt64),
      .mulI64,
      .addI64,
      .wrapI64,
      .load64 (0 : UInt32),
      .localSet 6,
      .localGet 9,
      .localGet 11,
      .constI64 (5 : UInt64),
      .mulI64,
      .constI64 (5 : UInt64),
      .addI64,
      .constI64 (8 : UInt64),
      .mulI64,
      .addI64,
      .wrapI64,
      .load64 (0 : UInt32),
      .localSet 7,
      .localGet 3,
      .localGet 2,
      .eqI64,
      .iff 0 1 [
        .constI64 (1 : UInt64)
      ] [
        .constI64 (0 : UInt64)
      ],
      .constI64 (0 : UInt64),
      .neI64,
      .iff 0 0 [
        .constI64 (1 : UInt64),
        .localSet 14,
        .br 2
      ] [],
      .localGet 11,
      .constI64 (1 : UInt64),
      .addI64,
      .localSet 11,
      .br 0
    ]
  ],
  .localGet 14,
  .localSet 8,
  .localGet 8
]

def func5Def : Wasm.Function :=
  { params := [.i64, .i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func5, results := [.i64] }

def func6 : Wasm.Program :=
  [
  .localGet 2,
  .constI64 (0 : UInt64),
  .eqI64,
  .iff 0 1 [
    .constI64 (1 : UInt64)
  ] [
    .constI64 (0 : UInt64)
  ],
  .constI64 (0 : UInt64),
  .eqI64,
  .eqz,
  .eqz,
  .iff 0 1 [
    .localGet 3,
    .constI64 (0 : UInt64),
    .eqI64,
    .iff 0 1 [
      .constI64 (1 : UInt64)
    ] [
      .constI64 (0 : UInt64)
    ],
    .constI64 (0 : UInt64),
    .eqI64,
    .eqz,
    .eqz
  ] [
    .const (0 : UInt32)
  ],
  .iff 0 1 [
    .localGet 4,
    .localSet 7,
    .localGet 7,
    .call 2,
    .constI64 (0 : UInt64),
    .eqI64,
    .eqz
  ] [
    .const (0 : UInt32)
  ],
  .iff 0 1 [
    .localGet 6,
    .constI64 (0 : UInt64),
    .eqI64,
    .iff 0 1 [
      .constI64 (1 : UInt64)
    ] [
      .constI64 (0 : UInt64)
    ],
    .constI64 (0 : UInt64),
    .eqI64,
    .eqz,
    .eqz
  ] [
    .const (0 : UInt32)
  ],
  .iff 0 1 [
    .localGet 0,
    .localSet 8,
    .localGet 1,
    .localSet 9,
    .localGet 2,
    .localSet 10,
    .localGet 8,
    .localGet 9,
    .localGet 10,
    .call 5,
    .constI64 (0 : UInt64),
    .eqI64,
    .eqz,
    .eqz
  ] [
    .const (0 : UInt32)
  ],
  .iff 0 1 [
    .constI64 (1 : UInt64)
  ] [
    .constI64 (0 : UInt64)
  ],
  .localSet 11,
  .localGet 11
]

def func6Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64], body := func6, results := [.i64] }

def func7 : Wasm.Program :=
  [
  .localGet 0,
  .constI64 (0 : UInt64),
  .eqI64,
  .iff 0 1 [
    .constI64 (1 : UInt64)
  ] [
    .constI64 (0 : UInt64)
  ],
  .constI64 (1 : UInt64),
  .eqI64,
  .iff 0 1 [
    .constI64 (1 : UInt64)
  ] [
    .constI64 (0 : UInt64)
  ],
  .constI64 (0 : UInt64),
  .eqI64,
  .eqz,
  .iff 0 1 [
    .constI64 (1 : UInt64)
  ] [
    .constI64 (0 : UInt64)
  ],
  .localSet 1,
  .localGet 1
]

def func7Def : Wasm.Function :=
  { params := [.i64], locals := [.i64], body := func7, results := [.i64] }

def func8 : Wasm.Program :=
  [
  .localGet 3,
  .localSet 5,
  .localGet 5
]

def func8Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64], locals := [.i64], body := func8, results := [.i64] }

def func9 : Wasm.Program :=
  [
  .localGet 2,
  .constI64 (0 : UInt64),
  .eqI64,
  .iff 0 1 [
    .constI64 (1 : UInt64)
  ] [
    .constI64 (0 : UInt64)
  ],
  .constI64 (1 : UInt64),
  .eqI64,
  .iff 0 1 [
    .constI64 (1 : UInt64)
  ] [
    .constI64 (0 : UInt64)
  ],
  .constI64 (0 : UInt64),
  .eqI64,
  .eqz,
  .iff 0 1 [
    .localGet 8,
    .localGet 3,
    .leUI64,
    .iff 0 1 [
      .constI64 (1 : UInt64)
    ] [
      .constI64 (0 : UInt64)
    ]
  ] [
    .localGet 3,
    .localGet 8,
    .leUI64,
    .iff 0 1 [
      .constI64 (1 : UInt64)
    ] [
      .constI64 (0 : UInt64)
    ]
  ],
  .localSet 10,
  .localGet 10
]

def func9Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], locals := [.i64], body := func9, results := [.i64] }

def func10 : Wasm.Program :=
  [
  .localGet 2,
  .localSet 10,
  .localGet 10,
  .call 7,
  .localSet 11,
  .localGet 7,
  .localGet 11,
  .eqI64,
  .iff 0 1 [
    .constI64 (1 : UInt64)
  ] [
    .constI64 (0 : UInt64)
  ],
  .constI64 (0 : UInt64),
  .eqI64,
  .eqz,
  .iff 0 1 [
    .localGet 6,
    .localGet 1,
    .eqI64,
    .iff 0 1 [
      .constI64 (1 : UInt64)
    ] [
      .constI64 (0 : UInt64)
    ],
    .constI64 (0 : UInt64),
    .eqI64,
    .eqz,
    .eqz
  ] [
    .const (0 : UInt32)
  ],
  .iff 0 1 [
    .localGet 0,
    .localSet 12,
    .localGet 1,
    .localSet 13,
    .localGet 2,
    .localSet 14,
    .localGet 3,
    .localSet 15,
    .localGet 4,
    .localSet 16,
    .localGet 5,
    .localSet 17,
    .localGet 6,
    .localSet 18,
    .localGet 7,
    .localSet 19,
    .localGet 8,
    .localSet 20,
    .localGet 9,
    .localSet 21,
    .localGet 12,
    .localGet 13,
    .localGet 14,
    .localGet 15,
    .localGet 16,
    .localGet 17,
    .localGet 18,
    .localGet 19,
    .localGet 20,
    .localGet 21,
    .call 9,
    .constI64 (0 : UInt64),
    .eqI64,
    .eqz
  ] [
    .const (0 : UInt32)
  ],
  .iff 0 1 [
    .constI64 (1 : UInt64)
  ] [
    .constI64 (0 : UInt64)
  ],
  .localSet 22,
  .localGet 22
]

def func10Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func10, results := [.i64] }

def func11 : Wasm.Program :=
  [
  .localGet 2,
  .constI64 (0 : UInt64),
  .eqI64,
  .iff 0 1 [
    .constI64 (1 : UInt64)
  ] [
    .constI64 (0 : UInt64)
  ],
  .constI64 (1 : UInt64),
  .eqI64,
  .iff 0 1 [
    .constI64 (1 : UInt64)
  ] [
    .constI64 (0 : UInt64)
  ],
  .constI64 (0 : UInt64),
  .eqI64,
  .eqz,
  .iff 0 1 [
    .localGet 8,
    .localGet 13,
    .ltUI64,
    .iff 0 1 [
      .constI64 (1 : UInt64)
    ] [
      .constI64 (0 : UInt64)
    ]
  ] [
    .localGet 13,
    .localGet 8,
    .ltUI64,
    .iff 0 1 [
      .constI64 (1 : UInt64)
    ] [
      .constI64 (0 : UInt64)
    ]
  ],
  .localSet 15,
  .localGet 15
]

def func11Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], locals := [.i64], body := func11, results := [.i64] }

def func12 : Wasm.Program :=
  [
  .constI64 (0 : UInt64),
  .localSet 13,
  .block 0 0 [
    .loop 0 0 [
      .localGet 0,
      .constI64 (0 : UInt64),
      .eqI64,
      .eqz,
      .iff 0 1 [
        .localGet 13,
        .constI64 (0 : UInt64),
        .eqI64
      ] [
        .const (0 : UInt32)
      ],
      .eqz,
      .br_if 1,
      .localGet 8,
      .localGet 2,
      .localSet 55,
      .localGet 55,
      .wrapI64,
      .load64 (0 : UInt32),
      .ltUI64,
      .iff 0 0 [
        .localGet 1,
        .localSet 14,
        .localGet 2,
        .localSet 15,
        .localGet 3,
        .localSet 16,
        .localGet 4,
        .localSet 17,
        .localGet 5,
        .localSet 18,
        .localGet 6,
        .localSet 19,
        .localGet 7,
        .localSet 20,
        .localGet 8,
        .localSet 55,
        .constI64 (1 : UInt64),
        .localSet 56,
        .localGet 55,
        .localGet 56,
        .addI64,
        .localSet 57,
        .localGet 57,
        .localGet 55,
        .ltUI64,
        .iff 0 1 [
          .unreachable
        ] [
          .localGet 57
        ],
        .localSet 21,
        .localGet 9,
        .constI64 (0 : UInt64),
        .eqI64,
        .iff 0 1 [
          .localGet 3,
          .localSet 22,
          .localGet 4,
          .localSet 23,
          .localGet 5,
          .localSet 24,
          .localGet 6,
          .localSet 25,
          .localGet 7,
          .localSet 26,
          .localGet 2,
          .localSet 55,
          .localGet 8,
          .localSet 56,
          .localGet 56,
          .localGet 55,
          .wrapI64,
          .load64 (0 : UInt32),
          .ltUI64,
          .iff 0 1 [
            .localGet 55,
            .localGet 56,
            .constI64 (5 : UInt64),
            .mulI64,
            .constI64 (1 : UInt64),
            .addI64,
            .constI64 (8 : UInt64),
            .mulI64,
            .addI64,
            .wrapI64,
            .load64 (0 : UInt32)
          ] [
            .unreachable
          ],
          .localSet 27,
          .localGet 2,
          .localSet 55,
          .localGet 8,
          .localSet 56,
          .localGet 56,
          .localGet 55,
          .wrapI64,
          .load64 (0 : UInt32),
          .ltUI64,
          .iff 0 1 [
            .localGet 55,
            .localGet 56,
            .constI64 (5 : UInt64),
            .mulI64,
            .constI64 (2 : UInt64),
            .addI64,
            .constI64 (8 : UInt64),
            .mulI64,
            .addI64,
            .wrapI64,
            .load64 (0 : UInt32)
          ] [
            .unreachable
          ],
          .localSet 28,
          .localGet 2,
          .localSet 55,
          .localGet 8,
          .localSet 56,
          .localGet 56,
          .localGet 55,
          .wrapI64,
          .load64 (0 : UInt32),
          .ltUI64,
          .iff 0 1 [
            .localGet 55,
            .localGet 56,
            .constI64 (5 : UInt64),
            .mulI64,
            .constI64 (3 : UInt64),
            .addI64,
            .constI64 (8 : UInt64),
            .mulI64,
            .addI64,
            .wrapI64,
            .load64 (0 : UInt32)
          ] [
            .unreachable
          ],
          .localSet 29,
          .localGet 2,
          .localSet 55,
          .localGet 8,
          .localSet 56,
          .localGet 56,
          .localGet 55,
          .wrapI64,
          .load64 (0 : UInt32),
          .ltUI64,
          .iff 0 1 [
            .localGet 55,
            .localGet 56,
            .constI64 (5 : UInt64),
            .mulI64,
            .constI64 (4 : UInt64),
            .addI64,
            .constI64 (8 : UInt64),
            .mulI64,
            .addI64,
            .wrapI64,
            .load64 (0 : UInt32)
          ] [
            .unreachable
          ],
          .localSet 30,
          .localGet 2,
          .localSet 55,
          .localGet 8,
          .localSet 56,
          .localGet 56,
          .localGet 55,
          .wrapI64,
          .load64 (0 : UInt32),
          .ltUI64,
          .iff 0 1 [
            .localGet 55,
            .localGet 56,
            .constI64 (5 : UInt64),
            .mulI64,
            .constI64 (5 : UInt64),
            .addI64,
            .constI64 (8 : UInt64),
            .mulI64,
            .addI64,
            .wrapI64,
            .load64 (0 : UInt32)
          ] [
            .unreachable
          ],
          .localSet 31,
          .localGet 22,
          .localGet 23,
          .localGet 24,
          .localGet 25,
          .localGet 26,
          .localGet 27,
          .localGet 28,
          .localGet 29,
          .localGet 30,
          .localGet 31,
          .call 10,
          .localSet 32,
          .localGet 32,
          .constI64 (1 : UInt64),
          .eqI64,
          .iff 0 1 [
            .constI64 (1 : UInt64)
          ] [
            .constI64 (0 : UInt64)
          ],
          .constI64 (0 : UInt64),
          .eqI64,
          .eqz,
          .iff 0 1 [
            .constI64 (1 : UInt64)
          ] [
            .constI64 (0 : UInt64)
          ]
        ] [
          .localGet 3,
          .localSet 33,
          .localGet 4,
          .localSet 34,
          .localGet 5,
          .localSet 35,
          .localGet 6,
          .localSet 36,
          .localGet 7,
          .localSet 37,
          .localGet 2,
          .localSet 55,
          .localGet 8,
          .localSet 56,
          .localGet 56,
          .localGet 55,
          .wrapI64,
          .load64 (0 : UInt32),
          .ltUI64,
          .iff 0 1 [
            .localGet 55,
            .localGet 56,
            .constI64 (5 : UInt64),
            .mulI64,
            .constI64 (1 : UInt64),
            .addI64,
            .constI64 (8 : UInt64),
            .mulI64,
            .addI64,
            .wrapI64,
            .load64 (0 : UInt32)
          ] [
            .unreachable
          ],
          .localSet 38,
          .localGet 2,
          .localSet 55,
          .localGet 8,
          .localSet 56,
          .localGet 56,
          .localGet 55,
          .wrapI64,
          .load64 (0 : UInt32),
          .ltUI64,
          .iff 0 1 [
            .localGet 55,
            .localGet 56,
            .constI64 (5 : UInt64),
            .mulI64,
            .constI64 (2 : UInt64),
            .addI64,
            .constI64 (8 : UInt64),
            .mulI64,
            .addI64,
            .wrapI64,
            .load64 (0 : UInt32)
          ] [
            .unreachable
          ],
          .localSet 39,
          .localGet 2,
          .localSet 55,
          .localGet 8,
          .localSet 56,
          .localGet 56,
          .localGet 55,
          .wrapI64,
          .load64 (0 : UInt32),
          .ltUI64,
          .iff 0 1 [
            .localGet 55,
            .localGet 56,
            .constI64 (5 : UInt64),
            .mulI64,
            .constI64 (3 : UInt64),
            .addI64,
            .constI64 (8 : UInt64),
            .mulI64,
            .addI64,
            .wrapI64,
            .load64 (0 : UInt32)
          ] [
            .unreachable
          ],
          .localSet 40,
          .localGet 2,
          .localSet 55,
          .localGet 8,
          .localSet 56,
          .localGet 56,
          .localGet 55,
          .wrapI64,
          .load64 (0 : UInt32),
          .ltUI64,
          .iff 0 1 [
            .localGet 55,
            .localGet 56,
            .constI64 (5 : UInt64),
            .mulI64,
            .constI64 (4 : UInt64),
            .addI64,
            .constI64 (8 : UInt64),
            .mulI64,
            .addI64,
            .wrapI64,
            .load64 (0 : UInt32)
          ] [
            .unreachable
          ],
          .localSet 41,
          .localGet 2,
          .localSet 55,
          .localGet 8,
          .localSet 56,
          .localGet 56,
          .localGet 55,
          .wrapI64,
          .load64 (0 : UInt32),
          .ltUI64,
          .iff 0 1 [
            .localGet 55,
            .localGet 56,
            .constI64 (5 : UInt64),
            .mulI64,
            .constI64 (5 : UInt64),
            .addI64,
            .constI64 (8 : UInt64),
            .mulI64,
            .addI64,
            .wrapI64,
            .load64 (0 : UInt32)
          ] [
            .unreachable
          ],
          .localSet 42,
          .localGet 33,
          .localGet 34,
          .localGet 35,
          .localGet 36,
          .localGet 37,
          .localGet 38,
          .localGet 39,
          .localGet 40,
          .localGet 41,
          .localGet 42,
          .call 10,
          .constI64 (0 : UInt64),
          .eqI64,
          .eqz,
          .iff 0 1 [
            .localGet 5,
            .constI64 (0 : UInt64),
            .eqI64,
            .iff 0 1 [
              .constI64 (1 : UInt64)
            ] [
              .constI64 (0 : UInt64)
            ],
            .constI64 (0 : UInt64),
            .eqI64,
            .eqz,
            .iff 0 1 [
              .constI64 (1 : UInt64)
            ] [
              .constI64 (0 : UInt64)
            ],
            .constI64 (1 : UInt64),
            .eqI64,
            .iff 0 1 [
              .constI64 (1 : UInt64)
            ] [
              .constI64 (0 : UInt64)
            ],
            .constI64 (0 : UInt64),
            .eqI64,
            .eqz,
            .iff 0 1 [
              .localGet 2,
              .localSet 55,
              .localGet 8,
              .localSet 56,
              .localGet 56,
              .localGet 55,
              .wrapI64,
              .load64 (0 : UInt32),
              .ltUI64,
              .iff 0 1 [
                .localGet 55,
                .localGet 56,
                .constI64 (5 : UInt64),
                .mulI64,
                .constI64 (4 : UInt64),
                .addI64,
                .constI64 (8 : UInt64),
                .mulI64,
                .addI64,
                .wrapI64,
                .load64 (0 : UInt32)
              ] [
                .unreachable
              ],
              .localGet 2,
              .localSet 55,
              .localGet 10,
              .localSet 56,
              .localGet 56,
              .localGet 55,
              .wrapI64,
              .load64 (0 : UInt32),
              .ltUI64,
              .iff 0 1 [
                .localGet 55,
                .localGet 56,
                .constI64 (5 : UInt64),
                .mulI64,
                .constI64 (4 : UInt64),
                .addI64,
                .constI64 (8 : UInt64),
                .mulI64,
                .addI64,
                .wrapI64,
                .load64 (0 : UInt32)
              ] [
                .unreachable
              ],
              .ltUI64,
              .iff 0 1 [
                .constI64 (1 : UInt64)
              ] [
                .constI64 (0 : UInt64)
              ]
            ] [
              .localGet 2,
              .localSet 55,
              .localGet 10,
              .localSet 56,
              .localGet 56,
              .localGet 55,
              .wrapI64,
              .load64 (0 : UInt32),
              .ltUI64,
              .iff 0 1 [
                .localGet 55,
                .localGet 56,
                .constI64 (5 : UInt64),
                .mulI64,
                .constI64 (4 : UInt64),
                .addI64,
                .constI64 (8 : UInt64),
                .mulI64,
                .addI64,
                .wrapI64,
                .load64 (0 : UInt32)
              ] [
                .unreachable
              ],
              .localGet 2,
              .localSet 55,
              .localGet 8,
              .localSet 56,
              .localGet 56,
              .localGet 55,
              .wrapI64,
              .load64 (0 : UInt32),
              .ltUI64,
              .iff 0 1 [
                .localGet 55,
                .localGet 56,
                .constI64 (5 : UInt64),
                .mulI64,
                .constI64 (4 : UInt64),
                .addI64,
                .constI64 (8 : UInt64),
                .mulI64,
                .addI64,
                .wrapI64,
                .load64 (0 : UInt32)
              ] [
                .unreachable
              ],
              .ltUI64,
              .iff 0 1 [
                .constI64 (1 : UInt64)
              ] [
                .constI64 (0 : UInt64)
              ]
            ],
            .constI64 (0 : UInt64),
            .eqI64,
            .eqz
          ] [
            .const (0 : UInt32)
          ],
          .iff 0 1 [
            .constI64 (1 : UInt64)
          ] [
            .constI64 (0 : UInt64)
          ],
          .constI64 (1 : UInt64),
          .eqI64,
          .iff 0 1 [
            .constI64 (1 : UInt64)
          ] [
            .constI64 (0 : UInt64)
          ],
          .constI64 (0 : UInt64),
          .eqI64,
          .eqz,
          .iff 0 1 [
            .constI64 (1 : UInt64)
          ] [
            .constI64 (1 : UInt64)
          ]
        ],
        .localSet 43,
        .localGet 9,
        .constI64 (0 : UInt64),
        .eqI64,
        .iff 0 1 [
          .localGet 3,
          .localSet 22,
          .localGet 4,
          .localSet 23,
          .localGet 5,
          .localSet 24,
          .localGet 6,
          .localSet 25,
          .localGet 7,
          .localSet 26,
          .localGet 2,
          .localSet 55,
          .localGet 8,
          .localSet 56,
          .localGet 56,
          .localGet 55,
          .wrapI64,
          .load64 (0 : UInt32),
          .ltUI64,
          .iff 0 1 [
            .localGet 55,
            .localGet 56,
            .constI64 (5 : UInt64),
            .mulI64,
            .constI64 (1 : UInt64),
            .addI64,
            .constI64 (8 : UInt64),
            .mulI64,
            .addI64,
            .wrapI64,
            .load64 (0 : UInt32)
          ] [
            .unreachable
          ],
          .localSet 27,
          .localGet 2,
          .localSet 55,
          .localGet 8,
          .localSet 56,
          .localGet 56,
          .localGet 55,
          .wrapI64,
          .load64 (0 : UInt32),
          .ltUI64,
          .iff 0 1 [
            .localGet 55,
            .localGet 56,
            .constI64 (5 : UInt64),
            .mulI64,
            .constI64 (2 : UInt64),
            .addI64,
            .constI64 (8 : UInt64),
            .mulI64,
            .addI64,
            .wrapI64,
            .load64 (0 : UInt32)
          ] [
            .unreachable
          ],
          .localSet 28,
          .localGet 2,
          .localSet 55,
          .localGet 8,
          .localSet 56,
          .localGet 56,
          .localGet 55,
          .wrapI64,
          .load64 (0 : UInt32),
          .ltUI64,
          .iff 0 1 [
            .localGet 55,
            .localGet 56,
            .constI64 (5 : UInt64),
            .mulI64,
            .constI64 (3 : UInt64),
            .addI64,
            .constI64 (8 : UInt64),
            .mulI64,
            .addI64,
            .wrapI64,
            .load64 (0 : UInt32)
          ] [
            .unreachable
          ],
          .localSet 29,
          .localGet 2,
          .localSet 55,
          .localGet 8,
          .localSet 56,
          .localGet 56,
          .localGet 55,
          .wrapI64,
          .load64 (0 : UInt32),
          .ltUI64,
          .iff 0 1 [
            .localGet 55,
            .localGet 56,
            .constI64 (5 : UInt64),
            .mulI64,
            .constI64 (4 : UInt64),
            .addI64,
            .constI64 (8 : UInt64),
            .mulI64,
            .addI64,
            .wrapI64,
            .load64 (0 : UInt32)
          ] [
            .unreachable
          ],
          .localSet 30,
          .localGet 2,
          .localSet 55,
          .localGet 8,
          .localSet 56,
          .localGet 56,
          .localGet 55,
          .wrapI64,
          .load64 (0 : UInt32),
          .ltUI64,
          .iff 0 1 [
            .localGet 55,
            .localGet 56,
            .constI64 (5 : UInt64),
            .mulI64,
            .constI64 (5 : UInt64),
            .addI64,
            .constI64 (8 : UInt64),
            .mulI64,
            .addI64,
            .wrapI64,
            .load64 (0 : UInt32)
          ] [
            .unreachable
          ],
          .localSet 31,
          .localGet 22,
          .localGet 23,
          .localGet 24,
          .localGet 25,
          .localGet 26,
          .localGet 27,
          .localGet 28,
          .localGet 29,
          .localGet 30,
          .localGet 31,
          .call 10,
          .localSet 32,
          .localGet 32,
          .constI64 (1 : UInt64),
          .eqI64,
          .iff 0 1 [
            .constI64 (1 : UInt64)
          ] [
            .constI64 (0 : UInt64)
          ],
          .constI64 (0 : UInt64),
          .eqI64,
          .eqz,
          .iff 0 1 [
            .localGet 8
          ] [
            .constI64 (0 : UInt64)
          ]
        ] [
          .localGet 3,
          .localSet 33,
          .localGet 4,
          .localSet 34,
          .localGet 5,
          .localSet 35,
          .localGet 6,
          .localSet 36,
          .localGet 7,
          .localSet 37,
          .localGet 2,
          .localSet 55,
          .localGet 8,
          .localSet 56,
          .localGet 56,
          .localGet 55,
          .wrapI64,
          .load64 (0 : UInt32),
          .ltUI64,
          .iff 0 1 [
            .localGet 55,
            .localGet 56,
            .constI64 (5 : UInt64),
            .mulI64,
            .constI64 (1 : UInt64),
            .addI64,
            .constI64 (8 : UInt64),
            .mulI64,
            .addI64,
            .wrapI64,
            .load64 (0 : UInt32)
          ] [
            .unreachable
          ],
          .localSet 38,
          .localGet 2,
          .localSet 55,
          .localGet 8,
          .localSet 56,
          .localGet 56,
          .localGet 55,
          .wrapI64,
          .load64 (0 : UInt32),
          .ltUI64,
          .iff 0 1 [
            .localGet 55,
            .localGet 56,
            .constI64 (5 : UInt64),
            .mulI64,
            .constI64 (2 : UInt64),
            .addI64,
            .constI64 (8 : UInt64),
            .mulI64,
            .addI64,
            .wrapI64,
            .load64 (0 : UInt32)
          ] [
            .unreachable
          ],
          .localSet 39,
          .localGet 2,
          .localSet 55,
          .localGet 8,
          .localSet 56,
          .localGet 56,
          .localGet 55,
          .wrapI64,
          .load64 (0 : UInt32),
          .ltUI64,
          .iff 0 1 [
            .localGet 55,
            .localGet 56,
            .constI64 (5 : UInt64),
            .mulI64,
            .constI64 (3 : UInt64),
            .addI64,
            .constI64 (8 : UInt64),
            .mulI64,
            .addI64,
            .wrapI64,
            .load64 (0 : UInt32)
          ] [
            .unreachable
          ],
          .localSet 40,
          .localGet 2,
          .localSet 55,
          .localGet 8,
          .localSet 56,
          .localGet 56,
          .localGet 55,
          .wrapI64,
          .load64 (0 : UInt32),
          .ltUI64,
          .iff 0 1 [
            .localGet 55,
            .localGet 56,
            .constI64 (5 : UInt64),
            .mulI64,
            .constI64 (4 : UInt64),
            .addI64,
            .constI64 (8 : UInt64),
            .mulI64,
            .addI64,
            .wrapI64,
            .load64 (0 : UInt32)
          ] [
            .unreachable
          ],
          .localSet 41,
          .localGet 2,
          .localSet 55,
          .localGet 8,
          .localSet 56,
          .localGet 56,
          .localGet 55,
          .wrapI64,
          .load64 (0 : UInt32),
          .ltUI64,
          .iff 0 1 [
            .localGet 55,
            .localGet 56,
            .constI64 (5 : UInt64),
            .mulI64,
            .constI64 (5 : UInt64),
            .addI64,
            .constI64 (8 : UInt64),
            .mulI64,
            .addI64,
            .wrapI64,
            .load64 (0 : UInt32)
          ] [
            .unreachable
          ],
          .localSet 42,
          .localGet 33,
          .localGet 34,
          .localGet 35,
          .localGet 36,
          .localGet 37,
          .localGet 38,
          .localGet 39,
          .localGet 40,
          .localGet 41,
          .localGet 42,
          .call 10,
          .constI64 (0 : UInt64),
          .eqI64,
          .eqz,
          .iff 0 1 [
            .localGet 5,
            .constI64 (0 : UInt64),
            .eqI64,
            .iff 0 1 [
              .constI64 (1 : UInt64)
            ] [
              .constI64 (0 : UInt64)
            ],
            .constI64 (0 : UInt64),
            .eqI64,
            .eqz,
            .iff 0 1 [
              .constI64 (1 : UInt64)
            ] [
              .constI64 (0 : UInt64)
            ],
            .constI64 (1 : UInt64),
            .eqI64,
            .iff 0 1 [
              .constI64 (1 : UInt64)
            ] [
              .constI64 (0 : UInt64)
            ],
            .constI64 (0 : UInt64),
            .eqI64,
            .eqz,
            .iff 0 1 [
              .localGet 2,
              .localSet 55,
              .localGet 8,
              .localSet 56,
              .localGet 56,
              .localGet 55,
              .wrapI64,
              .load64 (0 : UInt32),
              .ltUI64,
              .iff 0 1 [
                .localGet 55,
                .localGet 56,
                .constI64 (5 : UInt64),
                .mulI64,
                .constI64 (4 : UInt64),
                .addI64,
                .constI64 (8 : UInt64),
                .mulI64,
                .addI64,
                .wrapI64,
                .load64 (0 : UInt32)
              ] [
                .unreachable
              ],
              .localGet 2,
              .localSet 55,
              .localGet 10,
              .localSet 56,
              .localGet 56,
              .localGet 55,
              .wrapI64,
              .load64 (0 : UInt32),
              .ltUI64,
              .iff 0 1 [
                .localGet 55,
                .localGet 56,
                .constI64 (5 : UInt64),
                .mulI64,
                .constI64 (4 : UInt64),
                .addI64,
                .constI64 (8 : UInt64),
                .mulI64,
                .addI64,
                .wrapI64,
                .load64 (0 : UInt32)
              ] [
                .unreachable
              ],
              .ltUI64,
              .iff 0 1 [
                .constI64 (1 : UInt64)
              ] [
                .constI64 (0 : UInt64)
              ]
            ] [
              .localGet 2,
              .localSet 55,
              .localGet 10,
              .localSet 56,
              .localGet 56,
              .localGet 55,
              .wrapI64,
              .load64 (0 : UInt32),
              .ltUI64,
              .iff 0 1 [
                .localGet 55,
                .localGet 56,
                .constI64 (5 : UInt64),
                .mulI64,
                .constI64 (4 : UInt64),
                .addI64,
                .constI64 (8 : UInt64),
                .mulI64,
                .addI64,
                .wrapI64,
                .load64 (0 : UInt32)
              ] [
                .unreachable
              ],
              .localGet 2,
              .localSet 55,
              .localGet 8,
              .localSet 56,
              .localGet 56,
              .localGet 55,
              .wrapI64,
              .load64 (0 : UInt32),
              .ltUI64,
              .iff 0 1 [
                .localGet 55,
                .localGet 56,
                .constI64 (5 : UInt64),
                .mulI64,
                .constI64 (4 : UInt64),
                .addI64,
                .constI64 (8 : UInt64),
                .mulI64,
                .addI64,
                .wrapI64,
                .load64 (0 : UInt32)
              ] [
                .unreachable
              ],
              .ltUI64,
              .iff 0 1 [
                .constI64 (1 : UInt64)
              ] [
                .constI64 (0 : UInt64)
              ]
            ],
            .constI64 (0 : UInt64),
            .eqI64,
            .eqz
          ] [
            .const (0 : UInt32)
          ],
          .iff 0 1 [
            .constI64 (1 : UInt64)
          ] [
            .constI64 (0 : UInt64)
          ],
          .constI64 (1 : UInt64),
          .eqI64,
          .iff 0 1 [
            .constI64 (1 : UInt64)
          ] [
            .constI64 (0 : UInt64)
          ],
          .constI64 (0 : UInt64),
          .eqI64,
          .eqz,
          .iff 0 1 [
            .localGet 8
          ] [
            .localGet 10
          ]
        ],
        .localSet 44,
        .localGet 14,
        .localSet 45,
        .localGet 15,
        .localSet 46,
        .localGet 16,
        .localSet 47,
        .localGet 17,
        .localSet 48,
        .localGet 18,
        .localSet 49,
        .localGet 19,
        .localSet 50,
        .localGet 20,
        .localSet 51,
        .localGet 21,
        .localSet 52,
        .localGet 43,
        .localSet 53,
        .localGet 44,
        .localSet 54,
        .localGet 45,
        .localSet 1,
        .localGet 46,
        .localSet 2,
        .localGet 47,
        .localSet 3,
        .localGet 48,
        .localSet 4,
        .localGet 49,
        .localSet 5,
        .localGet 50,
        .localSet 6,
        .localGet 51,
        .localSet 7,
        .localGet 52,
        .localSet 8,
        .localGet 53,
        .localSet 9,
        .localGet 54,
        .localSet 10,
        .localGet 0,
        .constI64 (1 : UInt64),
        .subI64,
        .localSet 0
      ] [
        .localGet 9,
        .localSet 11,
        .localGet 10,
        .localSet 12,
        .constI64 (1 : UInt64),
        .localSet 13
      ],
      .br 0
    ]
  ],
  .localGet 13,
  .constI64 (0 : UInt64),
  .eqI64,
  .iff 0 0 [
    .localGet 9,
    .localSet 11,
    .localGet 10,
    .localSet 12
  ] [],
  .localGet 11,
  .localGet 12
]

def func12Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func12, results := [.i64, .i64] }

def func13 : Wasm.Program :=
  [
  .localGet 1,
  .localSet 25,
  .localGet 25,
  .wrapI64,
  .load64 (0 : UInt32),
  .localSet 22,
  .constI64 (1 : UInt64),
  .localSet 23,
  .localGet 22,
  .localGet 23,
  .addI64,
  .localSet 24,
  .localGet 24,
  .localGet 22,
  .ltUI64,
  .iff 0 1 [
    .unreachable
  ] [
    .localGet 24
  ],
  .localSet 7,
  .localGet 0,
  .localSet 8,
  .localGet 1,
  .localSet 9,
  .localGet 2,
  .localSet 10,
  .localGet 3,
  .localSet 11,
  .localGet 4,
  .localSet 12,
  .localGet 5,
  .localSet 13,
  .localGet 6,
  .localSet 14,
  .constI64 (0 : UInt64),
  .localSet 15,
  .constI64 (0 : UInt64),
  .localSet 16,
  .constI64 (0 : UInt64),
  .localSet 17,
  .localGet 7,
  .localGet 8,
  .localGet 9,
  .localGet 10,
  .localGet 11,
  .localGet 12,
  .localGet 13,
  .localGet 14,
  .localGet 15,
  .localGet 16,
  .localGet 17,
  .call 12,
  .localSet 19,
  .localSet 18,
  .localGet 18,
  .localSet 20,
  .localGet 19,
  .localSet 21,
  .localGet 20,
  .localGet 21
]

def func13Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func13, results := [.i64, .i64] }

def func14 : Wasm.Program :=
  [
  .constI64 (2 : UInt64),
  .localSet 0,
  .localGet 0
]

def func14Def : Wasm.Function :=
  { params := [], locals := [.i64], body := func14, results := [.i64] }

def func15 : Wasm.Program :=
  [
  .constI64 (0 : UInt64),
  .localSet 0,
  .localGet 0
]

def func15Def : Wasm.Function :=
  { params := [], locals := [.i64], body := func15, results := [.i64] }

def func16 : Wasm.Program :=
  [
  .constI64 (1 : UInt64),
  .localSet 0,
  .localGet 0
]

def func16Def : Wasm.Function :=
  { params := [], locals := [.i64], body := func16, results := [.i64] }

/-- export: postOnly -/
def func17 : Wasm.Program :=
  [
  .constI64 (0 : UInt64),
  .localSet 6,
  .localGet 0,
  .localSet 7,
  .localGet 1,
  .localSet 8,
  .localGet 2,
  .localSet 9,
  .localGet 3,
  .localSet 10,
  .localGet 4,
  .localSet 11,
  .localGet 5,
  .localSet 12,
  .localGet 6,
  .localGet 7,
  .localGet 8,
  .localGet 9,
  .localGet 10,
  .localGet 11,
  .localGet 12,
  .call 6,
  .localSet 13,
  .localGet 13,
  .constI64 (1 : UInt64),
  .eqI64,
  .iff 0 1 [
    .constI64 (1 : UInt64)
  ] [
    .constI64 (0 : UInt64)
  ],
  .constI64 (0 : UInt64),
  .eqI64,
  .eqz,
  .iff 0 0 [
    .constI64 (0 : UInt64),
    .localSet 14,
    .localGet 0,
    .localSet 15,
    .localGet 1,
    .localSet 16,
    .localGet 2,
    .localSet 17,
    .localGet 3,
    .localSet 18,
    .localGet 4,
    .localSet 19,
    .localGet 5,
    .localSet 20,
    .localGet 14,
    .localGet 15,
    .localGet 16,
    .localGet 17,
    .localGet 18,
    .localGet 19,
    .localGet 20,
    .call 13,
    .localSet 22,
    .localSet 21,
    .localGet 21,
    .constI64 (0 : UInt64),
    .eqI64,
    .iff 0 0 [
      .call 15,
      .localSet 23,
      .localGet 23,
      .localSet 31,
      .localGet 0,
      .localSet 24,
      .localGet 24,
      .localSet 34,
      .localGet 1,
      .localSet 40,
      .localGet 2,
      .localSet 41,
      .localGet 3,
      .localSet 42,
      .localGet 4,
      .localSet 43,
      .localGet 5,
      .localSet 44,
      .localGet 34,
      .wrapI64,
      .load64 (0 : UInt32),
      .localSet 35,
      .localGet 35,
      .constI64 (5 : UInt64),
      .mulI64,
      .localSet 36,
      .localGet 35,
      .constI64 (1 : UInt64),
      .addI64,
      .localSet 37,
      .constI64 (8 : UInt64),
      .localGet 37,
      .constI64 (5 : UInt64),
      .mulI64,
      .constI64 (8 : UInt64),
      .mulI64,
      .addI64,
      .constI64 (7 : UInt64),
      .addI64,
      .constI64 (8 : UInt64),
      .divUI64,
      .constI64 (8 : UInt64),
      .mulI64,
      .localSet 47,
      .localGet 47,
      .constI64 (8 : UInt64),
      .ltUI64,
      .iff 0 0 [
        .constI64 (8 : UInt64),
        .localSet 47
      ] [],
      .constI64 (0 : UInt64),
      .localSet 52,
      .constI64 (0 : UInt64),
      .localSet 48,
      .globalGet 1,
      .localSet 49,
      .block 0 0 [
        .loop 0 0 [
          .localGet 49,
          .constI64 (0 : UInt64),
          .eqI64,
          .br_if 1,
          .localGet 52,
          .constI64 (0 : UInt64),
          .neI64,
          .br_if 1,
          .localGet 49,
          .constI64 (32 : UInt64),
          .subI64,
          .wrapI64,
          .load64 (0 : UInt32),
          .localSet 50,
          .localGet 49,
          .constI64 (8 : UInt64),
          .subI64,
          .wrapI64,
          .load64 (0 : UInt32),
          .localSet 51,
          .localGet 50,
          .localGet 47,
          .geUI64,
          .iff 0 0 [
            .localGet 48,
            .constI64 (0 : UInt64),
            .eqI64,
            .iff 0 0 [
              .localGet 51,
              .globalSet 1
            ] [
              .localGet 48,
              .constI64 (8 : UInt64),
              .subI64,
              .wrapI64,
              .localGet 51,
              .store64 (0 : UInt32)
            ],
            .localGet 49,
            .constI64 (48 : UInt64),
            .subI64,
            .wrapI64,
            .constI64 (5501223100278326855 : UInt64),
            .store64 (0 : UInt32),
            .localGet 49,
            .constI64 (40 : UInt64),
            .subI64,
            .wrapI64,
            .constI64 (1 : UInt64),
            .store64 (0 : UInt32),
            .localGet 49,
            .constI64 (32 : UInt64),
            .subI64,
            .wrapI64,
            .localGet 50,
            .store64 (0 : UInt32),
            .localGet 49,
            .constI64 (24 : UInt64),
            .subI64,
            .wrapI64,
            .constI64 (2 : UInt64),
            .store64 (0 : UInt32),
            .localGet 49,
            .constI64 (16 : UInt64),
            .subI64,
            .wrapI64,
            .constI64 (5 : UInt64),
            .store64 (0 : UInt32),
            .localGet 49,
            .constI64 (8 : UInt64),
            .subI64,
            .wrapI64,
            .constI64 (0 : UInt64),
            .store64 (0 : UInt32),
            .localGet 49,
            .localSet 52
          ] [
            .localGet 49,
            .localSet 48,
            .localGet 51,
            .localSet 49
          ],
          .br 0
        ]
      ],
      .localGet 52,
      .constI64 (0 : UInt64),
      .eqI64,
      .iff 0 0 [
        .globalGet 0,
        .constI64 (48 : UInt64),
        .addI64,
        .localGet 47,
        .addI64,
        .localSet 50,
        .localGet 50,
        .globalGet 0,
        .ltUI64,
        .iff 0 0 [
          .unreachable
        ] [],
        .localGet 50,
        .constI64 (1 : UInt64),
        .subI64,
        .constI64 (65536 : UInt64),
        .divUI64,
        .constI64 (1 : UInt64),
        .addI64,
        .localSet 51,
        .memorySize,
        .extendUI32,
        .localGet 51,
        .ltUI64,
        .iff 0 0 [
          .localGet 51,
          .memorySize,
          .extendUI32,
          .subI64,
          .wrapI64,
          .memoryGrow,
          .const (4294967295 : UInt32),
          .eq,
          .iff 0 0 [
            .unreachable
          ] []
        ] [],
        .globalGet 0,
        .constI64 (48 : UInt64),
        .addI64,
        .localSet 52,
        .localGet 50,
        .globalSet 0,
        .localGet 52,
        .constI64 (48 : UInt64),
        .subI64,
        .wrapI64,
        .constI64 (5501223100278326855 : UInt64),
        .store64 (0 : UInt32),
        .localGet 52,
        .constI64 (40 : UInt64),
        .subI64,
        .wrapI64,
        .constI64 (1 : UInt64),
        .store64 (0 : UInt32),
        .localGet 52,
        .constI64 (32 : UInt64),
        .subI64,
        .wrapI64,
        .localGet 47,
        .store64 (0 : UInt32),
        .localGet 52,
        .constI64 (24 : UInt64),
        .subI64,
        .wrapI64,
        .constI64 (2 : UInt64),
        .store64 (0 : UInt32),
        .localGet 52,
        .constI64 (16 : UInt64),
        .subI64,
        .wrapI64,
        .constI64 (5 : UInt64),
        .store64 (0 : UInt32),
        .localGet 52,
        .constI64 (8 : UInt64),
        .subI64,
        .wrapI64,
        .constI64 (0 : UInt64),
        .store64 (0 : UInt32)
      ] [],
      .globalGet 2,
      .constI64 (1 : UInt64),
      .addI64,
      .globalSet 2,
      .localGet 52,
      .localSet 38,
      .localGet 38,
      .wrapI64,
      .localGet 37,
      .store64 (0 : UInt32),
      .constI64 (0 : UInt64),
      .localSet 39,
      .block 0 0 [
        .loop 0 0 [
          .localGet 39,
          .localGet 36,
          .geUI64,
          .br_if 1,
          .localGet 38,
          .localGet 39,
          .constI64 (1 : UInt64),
          .addI64,
          .constI64 (8 : UInt64),
          .mulI64,
          .addI64,
          .wrapI64,
          .localGet 34,
          .localGet 39,
          .constI64 (1 : UInt64),
          .addI64,
          .constI64 (8 : UInt64),
          .mulI64,
          .addI64,
          .wrapI64,
          .load64 (0 : UInt32),
          .store64 (0 : UInt32),
          .localGet 39,
          .constI64 (1 : UInt64),
          .addI64,
          .localSet 39,
          .br 0
        ]
      ],
      .localGet 38,
      .localGet 35,
      .constI64 (5 : UInt64),
      .mulI64,
      .constI64 (1 : UInt64),
      .addI64,
      .constI64 (8 : UInt64),
      .mulI64,
      .addI64,
      .wrapI64,
      .localGet 40,
      .store64 (0 : UInt32),
      .localGet 38,
      .localGet 35,
      .constI64 (5 : UInt64),
      .mulI64,
      .constI64 (2 : UInt64),
      .addI64,
      .constI64 (8 : UInt64),
      .mulI64,
      .addI64,
      .wrapI64,
      .localGet 41,
      .store64 (0 : UInt32),
      .localGet 38,
      .localGet 35,
      .constI64 (5 : UInt64),
      .mulI64,
      .constI64 (3 : UInt64),
      .addI64,
      .constI64 (8 : UInt64),
      .mulI64,
      .addI64,
      .wrapI64,
      .localGet 42,
      .store64 (0 : UInt32),
      .localGet 38,
      .localGet 35,
      .constI64 (5 : UInt64),
      .mulI64,
      .constI64 (4 : UInt64),
      .addI64,
      .constI64 (8 : UInt64),
      .mulI64,
      .addI64,
      .wrapI64,
      .localGet 43,
      .store64 (0 : UInt32),
      .localGet 38,
      .localGet 35,
      .constI64 (5 : UInt64),
      .mulI64,
      .constI64 (5 : UInt64),
      .addI64,
      .constI64 (8 : UInt64),
      .mulI64,
      .addI64,
      .wrapI64,
      .localGet 44,
      .store64 (0 : UInt32),
      .localGet 38,
      .localSet 25,
      .localGet 25,
      .localSet 32,
      .constI64 (8 : UInt64),
      .constI64 (0 : UInt64),
      .constI64 (4 : UInt64),
      .mulI64,
      .constI64 (8 : UInt64),
      .mulI64,
      .addI64,
      .constI64 (7 : UInt64),
      .addI64,
      .constI64 (8 : UInt64),
      .divUI64,
      .constI64 (8 : UInt64),
      .mulI64,
      .localSet 41,
      .localGet 41,
      .constI64 (8 : UInt64),
      .ltUI64,
      .iff 0 0 [
        .constI64 (8 : UInt64),
        .localSet 41
      ] [],
      .constI64 (0 : UInt64),
      .localSet 46,
      .constI64 (0 : UInt64),
      .localSet 42,
      .globalGet 1,
      .localSet 43,
      .block 0 0 [
        .loop 0 0 [
          .localGet 43,
          .constI64 (0 : UInt64),
          .eqI64,
          .br_if 1,
          .localGet 46,
          .constI64 (0 : UInt64),
          .neI64,
          .br_if 1,
          .localGet 43,
          .constI64 (32 : UInt64),
          .subI64,
          .wrapI64,
          .load64 (0 : UInt32),
          .localSet 44,
          .localGet 43,
          .constI64 (8 : UInt64),
          .subI64,
          .wrapI64,
          .load64 (0 : UInt32),
          .localSet 45,
          .localGet 44,
          .localGet 41,
          .geUI64,
          .iff 0 0 [
            .localGet 42,
            .constI64 (0 : UInt64),
            .eqI64,
            .iff 0 0 [
              .localGet 45,
              .globalSet 1
            ] [
              .localGet 42,
              .constI64 (8 : UInt64),
              .subI64,
              .wrapI64,
              .localGet 45,
              .store64 (0 : UInt32)
            ],
            .localGet 43,
            .constI64 (48 : UInt64),
            .subI64,
            .wrapI64,
            .constI64 (5501223100278326855 : UInt64),
            .store64 (0 : UInt32),
            .localGet 43,
            .constI64 (40 : UInt64),
            .subI64,
            .wrapI64,
            .constI64 (1 : UInt64),
            .store64 (0 : UInt32),
            .localGet 43,
            .constI64 (32 : UInt64),
            .subI64,
            .wrapI64,
            .localGet 44,
            .store64 (0 : UInt32),
            .localGet 43,
            .constI64 (24 : UInt64),
            .subI64,
            .wrapI64,
            .constI64 (2 : UInt64),
            .store64 (0 : UInt32),
            .localGet 43,
            .constI64 (16 : UInt64),
            .subI64,
            .wrapI64,
            .constI64 (4 : UInt64),
            .store64 (0 : UInt32),
            .localGet 43,
            .constI64 (8 : UInt64),
            .subI64,
            .wrapI64,
            .constI64 (0 : UInt64),
            .store64 (0 : UInt32),
            .localGet 43,
            .localSet 46
          ] [
            .localGet 43,
            .localSet 42,
            .localGet 45,
            .localSet 43
          ],
          .br 0
        ]
      ],
      .localGet 46,
      .constI64 (0 : UInt64),
      .eqI64,
      .iff 0 0 [
        .globalGet 0,
        .constI64 (48 : UInt64),
        .addI64,
        .localGet 41,
        .addI64,
        .localSet 44,
        .localGet 44,
        .globalGet 0,
        .ltUI64,
        .iff 0 0 [
          .unreachable
        ] [],
        .localGet 44,
        .constI64 (1 : UInt64),
        .subI64,
        .constI64 (65536 : UInt64),
        .divUI64,
        .constI64 (1 : UInt64),
        .addI64,
        .localSet 45,
        .memorySize,
        .extendUI32,
        .localGet 45,
        .ltUI64,
        .iff 0 0 [
          .localGet 45,
          .memorySize,
          .extendUI32,
          .subI64,
          .wrapI64,
          .memoryGrow,
          .const (4294967295 : UInt32),
          .eq,
          .iff 0 0 [
            .unreachable
          ] []
        ] [],
        .globalGet 0,
        .constI64 (48 : UInt64),
        .addI64,
        .localSet 46,
        .localGet 44,
        .globalSet 0,
        .localGet 46,
        .constI64 (48 : UInt64),
        .subI64,
        .wrapI64,
        .constI64 (5501223100278326855 : UInt64),
        .store64 (0 : UInt32),
        .localGet 46,
        .constI64 (40 : UInt64),
        .subI64,
        .wrapI64,
        .constI64 (1 : UInt64),
        .store64 (0 : UInt32),
        .localGet 46,
        .constI64 (32 : UInt64),
        .subI64,
        .wrapI64,
        .localGet 41,
        .store64 (0 : UInt32),
        .localGet 46,
        .constI64 (24 : UInt64),
        .subI64,
        .wrapI64,
        .constI64 (2 : UInt64),
        .store64 (0 : UInt32),
        .localGet 46,
        .constI64 (16 : UInt64),
        .subI64,
        .wrapI64,
        .constI64 (4 : UInt64),
        .store64 (0 : UInt32),
        .localGet 46,
        .constI64 (8 : UInt64),
        .subI64,
        .wrapI64,
        .constI64 (0 : UInt64),
        .store64 (0 : UInt32)
      ] [],
      .globalGet 2,
      .constI64 (1 : UInt64),
      .addI64,
      .globalSet 2,
      .localGet 46,
      .localSet 34,
      .localGet 34,
      .wrapI64,
      .constI64 (0 : UInt64),
      .store64 (0 : UInt32),
      .localGet 34,
      .localSet 26,
      .localGet 26,
      .localSet 33
    ] [
      .call 14,
      .localSet 27,
      .localGet 27,
      .localSet 31,
      .localGet 0,
      .localSet 32,
      .constI64 (8 : UInt64),
      .constI64 (0 : UInt64),
      .constI64 (4 : UInt64),
      .mulI64,
      .constI64 (8 : UInt64),
      .mulI64,
      .addI64,
      .constI64 (7 : UInt64),
      .addI64,
      .constI64 (8 : UInt64),
      .divUI64,
      .constI64 (8 : UInt64),
      .mulI64,
      .localSet 41,
      .localGet 41,
      .constI64 (8 : UInt64),
      .ltUI64,
      .iff 0 0 [
        .constI64 (8 : UInt64),
        .localSet 41
      ] [],
      .constI64 (0 : UInt64),
      .localSet 46,
      .constI64 (0 : UInt64),
      .localSet 42,
      .globalGet 1,
      .localSet 43,
      .block 0 0 [
        .loop 0 0 [
          .localGet 43,
          .constI64 (0 : UInt64),
          .eqI64,
          .br_if 1,
          .localGet 46,
          .constI64 (0 : UInt64),
          .neI64,
          .br_if 1,
          .localGet 43,
          .constI64 (32 : UInt64),
          .subI64,
          .wrapI64,
          .load64 (0 : UInt32),
          .localSet 44,
          .localGet 43,
          .constI64 (8 : UInt64),
          .subI64,
          .wrapI64,
          .load64 (0 : UInt32),
          .localSet 45,
          .localGet 44,
          .localGet 41,
          .geUI64,
          .iff 0 0 [
            .localGet 42,
            .constI64 (0 : UInt64),
            .eqI64,
            .iff 0 0 [
              .localGet 45,
              .globalSet 1
            ] [
              .localGet 42,
              .constI64 (8 : UInt64),
              .subI64,
              .wrapI64,
              .localGet 45,
              .store64 (0 : UInt32)
            ],
            .localGet 43,
            .constI64 (48 : UInt64),
            .subI64,
            .wrapI64,
            .constI64 (5501223100278326855 : UInt64),
            .store64 (0 : UInt32),
            .localGet 43,
            .constI64 (40 : UInt64),
            .subI64,
            .wrapI64,
            .constI64 (1 : UInt64),
            .store64 (0 : UInt32),
            .localGet 43,
            .constI64 (32 : UInt64),
            .subI64,
            .wrapI64,
            .localGet 44,
            .store64 (0 : UInt32),
            .localGet 43,
            .constI64 (24 : UInt64),
            .subI64,
            .wrapI64,
            .constI64 (2 : UInt64),
            .store64 (0 : UInt32),
            .localGet 43,
            .constI64 (16 : UInt64),
            .subI64,
            .wrapI64,
            .constI64 (4 : UInt64),
            .store64 (0 : UInt32),
            .localGet 43,
            .constI64 (8 : UInt64),
            .subI64,
            .wrapI64,
            .constI64 (0 : UInt64),
            .store64 (0 : UInt32),
            .localGet 43,
            .localSet 46
          ] [
            .localGet 43,
            .localSet 42,
            .localGet 45,
            .localSet 43
          ],
          .br 0
        ]
      ],
      .localGet 46,
      .constI64 (0 : UInt64),
      .eqI64,
      .iff 0 0 [
        .globalGet 0,
        .constI64 (48 : UInt64),
        .addI64,
        .localGet 41,
        .addI64,
        .localSet 44,
        .localGet 44,
        .globalGet 0,
        .ltUI64,
        .iff 0 0 [
          .unreachable
        ] [],
        .localGet 44,
        .constI64 (1 : UInt64),
        .subI64,
        .constI64 (65536 : UInt64),
        .divUI64,
        .constI64 (1 : UInt64),
        .addI64,
        .localSet 45,
        .memorySize,
        .extendUI32,
        .localGet 45,
        .ltUI64,
        .iff 0 0 [
          .localGet 45,
          .memorySize,
          .extendUI32,
          .subI64,
          .wrapI64,
          .memoryGrow,
          .const (4294967295 : UInt32),
          .eq,
          .iff 0 0 [
            .unreachable
          ] []
        ] [],
        .globalGet 0,
        .constI64 (48 : UInt64),
        .addI64,
        .localSet 46,
        .localGet 44,
        .globalSet 0,
        .localGet 46,
        .constI64 (48 : UInt64),
        .subI64,
        .wrapI64,
        .constI64 (5501223100278326855 : UInt64),
        .store64 (0 : UInt32),
        .localGet 46,
        .constI64 (40 : UInt64),
        .subI64,
        .wrapI64,
        .constI64 (1 : UInt64),
        .store64 (0 : UInt32),
        .localGet 46,
        .constI64 (32 : UInt64),
        .subI64,
        .wrapI64,
        .localGet 41,
        .store64 (0 : UInt32),
        .localGet 46,
        .constI64 (24 : UInt64),
        .subI64,
        .wrapI64,
        .constI64 (2 : UInt64),
        .store64 (0 : UInt32),
        .localGet 46,
        .constI64 (16 : UInt64),
        .subI64,
        .wrapI64,
        .constI64 (4 : UInt64),
        .store64 (0 : UInt32),
        .localGet 46,
        .constI64 (8 : UInt64),
        .subI64,
        .wrapI64,
        .constI64 (0 : UInt64),
        .store64 (0 : UInt32)
      ] [],
      .globalGet 2,
      .constI64 (1 : UInt64),
      .addI64,
      .globalSet 2,
      .localGet 46,
      .localSet 34,
      .localGet 34,
      .wrapI64,
      .constI64 (0 : UInt64),
      .store64 (0 : UInt32),
      .localGet 34,
      .localSet 28,
      .localGet 28,
      .localSet 33
    ]
  ] [
    .call 16,
    .localSet 29,
    .localGet 29,
    .localSet 31,
    .localGet 0,
    .localSet 32,
    .constI64 (8 : UInt64),
    .constI64 (0 : UInt64),
    .constI64 (4 : UInt64),
    .mulI64,
    .constI64 (8 : UInt64),
    .mulI64,
    .addI64,
    .constI64 (7 : UInt64),
    .addI64,
    .constI64 (8 : UInt64),
    .divUI64,
    .constI64 (8 : UInt64),
    .mulI64,
    .localSet 41,
    .localGet 41,
    .constI64 (8 : UInt64),
    .ltUI64,
    .iff 0 0 [
      .constI64 (8 : UInt64),
      .localSet 41
    ] [],
    .constI64 (0 : UInt64),
    .localSet 46,
    .constI64 (0 : UInt64),
    .localSet 42,
    .globalGet 1,
    .localSet 43,
    .block 0 0 [
      .loop 0 0 [
        .localGet 43,
        .constI64 (0 : UInt64),
        .eqI64,
        .br_if 1,
        .localGet 46,
        .constI64 (0 : UInt64),
        .neI64,
        .br_if 1,
        .localGet 43,
        .constI64 (32 : UInt64),
        .subI64,
        .wrapI64,
        .load64 (0 : UInt32),
        .localSet 44,
        .localGet 43,
        .constI64 (8 : UInt64),
        .subI64,
        .wrapI64,
        .load64 (0 : UInt32),
        .localSet 45,
        .localGet 44,
        .localGet 41,
        .geUI64,
        .iff 0 0 [
          .localGet 42,
          .constI64 (0 : UInt64),
          .eqI64,
          .iff 0 0 [
            .localGet 45,
            .globalSet 1
          ] [
            .localGet 42,
            .constI64 (8 : UInt64),
            .subI64,
            .wrapI64,
            .localGet 45,
            .store64 (0 : UInt32)
          ],
          .localGet 43,
          .constI64 (48 : UInt64),
          .subI64,
          .wrapI64,
          .constI64 (5501223100278326855 : UInt64),
          .store64 (0 : UInt32),
          .localGet 43,
          .constI64 (40 : UInt64),
          .subI64,
          .wrapI64,
          .constI64 (1 : UInt64),
          .store64 (0 : UInt32),
          .localGet 43,
          .constI64 (32 : UInt64),
          .subI64,
          .wrapI64,
          .localGet 44,
          .store64 (0 : UInt32),
          .localGet 43,
          .constI64 (24 : UInt64),
          .subI64,
          .wrapI64,
          .constI64 (2 : UInt64),
          .store64 (0 : UInt32),
          .localGet 43,
          .constI64 (16 : UInt64),
          .subI64,
          .wrapI64,
          .constI64 (4 : UInt64),
          .store64 (0 : UInt32),
          .localGet 43,
          .constI64 (8 : UInt64),
          .subI64,
          .wrapI64,
          .constI64 (0 : UInt64),
          .store64 (0 : UInt32),
          .localGet 43,
          .localSet 46
        ] [
          .localGet 43,
          .localSet 42,
          .localGet 45,
          .localSet 43
        ],
        .br 0
      ]
    ],
    .localGet 46,
    .constI64 (0 : UInt64),
    .eqI64,
    .iff 0 0 [
      .globalGet 0,
      .constI64 (48 : UInt64),
      .addI64,
      .localGet 41,
      .addI64,
      .localSet 44,
      .localGet 44,
      .globalGet 0,
      .ltUI64,
      .iff 0 0 [
        .unreachable
      ] [],
      .localGet 44,
      .constI64 (1 : UInt64),
      .subI64,
      .constI64 (65536 : UInt64),
      .divUI64,
      .constI64 (1 : UInt64),
      .addI64,
      .localSet 45,
      .memorySize,
      .extendUI32,
      .localGet 45,
      .ltUI64,
      .iff 0 0 [
        .localGet 45,
        .memorySize,
        .extendUI32,
        .subI64,
        .wrapI64,
        .memoryGrow,
        .const (4294967295 : UInt32),
        .eq,
        .iff 0 0 [
          .unreachable
        ] []
      ] [],
      .globalGet 0,
      .constI64 (48 : UInt64),
      .addI64,
      .localSet 46,
      .localGet 44,
      .globalSet 0,
      .localGet 46,
      .constI64 (48 : UInt64),
      .subI64,
      .wrapI64,
      .constI64 (5501223100278326855 : UInt64),
      .store64 (0 : UInt32),
      .localGet 46,
      .constI64 (40 : UInt64),
      .subI64,
      .wrapI64,
      .constI64 (1 : UInt64),
      .store64 (0 : UInt32),
      .localGet 46,
      .constI64 (32 : UInt64),
      .subI64,
      .wrapI64,
      .localGet 41,
      .store64 (0 : UInt32),
      .localGet 46,
      .constI64 (24 : UInt64),
      .subI64,
      .wrapI64,
      .constI64 (2 : UInt64),
      .store64 (0 : UInt32),
      .localGet 46,
      .constI64 (16 : UInt64),
      .subI64,
      .wrapI64,
      .constI64 (4 : UInt64),
      .store64 (0 : UInt32),
      .localGet 46,
      .constI64 (8 : UInt64),
      .subI64,
      .wrapI64,
      .constI64 (0 : UInt64),
      .store64 (0 : UInt32)
    ] [],
    .globalGet 2,
    .constI64 (1 : UInt64),
    .addI64,
    .globalSet 2,
    .localGet 46,
    .localSet 34,
    .localGet 34,
    .wrapI64,
    .constI64 (0 : UInt64),
    .store64 (0 : UInt32),
    .localGet 34,
    .localSet 30,
    .localGet 30,
    .localSet 33
  ],
  .localGet 31,
  .localGet 32,
  .localGet 33
]

def func17Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func17, results := [.i64, .i64, .i64] }

/-- export: alloc -/
def func18 : Wasm.Program :=
  [
  .localGet 0,
  .constI64 (7 : UInt64),
  .addI64,
  .constI64 (8 : UInt64),
  .divUI64,
  .constI64 (8 : UInt64),
  .mulI64,
  .localSet 1,
  .localGet 1,
  .constI64 (8 : UInt64),
  .ltUI64,
  .iff 0 0 [
    .constI64 (8 : UInt64),
    .localSet 1
  ] [],
  .constI64 (0 : UInt64),
  .localSet 6,
  .constI64 (0 : UInt64),
  .localSet 2,
  .globalGet 1,
  .localSet 3,
  .block 0 0 [
    .loop 0 0 [
      .localGet 3,
      .constI64 (0 : UInt64),
      .eqI64,
      .br_if 1,
      .localGet 6,
      .constI64 (0 : UInt64),
      .neI64,
      .br_if 1,
      .localGet 3,
      .constI64 (32 : UInt64),
      .subI64,
      .wrapI64,
      .load64 (0 : UInt32),
      .localSet 4,
      .localGet 3,
      .constI64 (8 : UInt64),
      .subI64,
      .wrapI64,
      .load64 (0 : UInt32),
      .localSet 5,
      .localGet 4,
      .localGet 1,
      .geUI64,
      .iff 0 0 [
        .localGet 2,
        .constI64 (0 : UInt64),
        .eqI64,
        .iff 0 0 [
          .localGet 5,
          .globalSet 1
        ] [
          .localGet 2,
          .constI64 (8 : UInt64),
          .subI64,
          .wrapI64,
          .localGet 5,
          .store64 (0 : UInt32)
        ],
        .localGet 3,
        .constI64 (48 : UInt64),
        .subI64,
        .wrapI64,
        .constI64 (5501223100278326855 : UInt64),
        .store64 (0 : UInt32),
        .localGet 3,
        .constI64 (40 : UInt64),
        .subI64,
        .wrapI64,
        .constI64 (1 : UInt64),
        .store64 (0 : UInt32),
        .localGet 3,
        .constI64 (32 : UInt64),
        .subI64,
        .wrapI64,
        .localGet 4,
        .store64 (0 : UInt32),
        .localGet 3,
        .constI64 (24 : UInt64),
        .subI64,
        .wrapI64,
        .constI64 (0 : UInt64),
        .store64 (0 : UInt32),
        .localGet 3,
        .constI64 (16 : UInt64),
        .subI64,
        .wrapI64,
        .constI64 (0 : UInt64),
        .store64 (0 : UInt32),
        .localGet 3,
        .constI64 (8 : UInt64),
        .subI64,
        .wrapI64,
        .constI64 (0 : UInt64),
        .store64 (0 : UInt32),
        .localGet 3,
        .localSet 6
      ] [
        .localGet 3,
        .localSet 2,
        .localGet 5,
        .localSet 3
      ],
      .br 0
    ]
  ],
  .localGet 6,
  .constI64 (0 : UInt64),
  .eqI64,
  .iff 0 0 [
    .globalGet 0,
    .constI64 (48 : UInt64),
    .addI64,
    .localGet 1,
    .addI64,
    .localSet 4,
    .localGet 4,
    .globalGet 0,
    .ltUI64,
    .iff 0 0 [
      .unreachable
    ] [],
    .localGet 4,
    .constI64 (1 : UInt64),
    .subI64,
    .constI64 (65536 : UInt64),
    .divUI64,
    .constI64 (1 : UInt64),
    .addI64,
    .localSet 5,
    .memorySize,
    .extendUI32,
    .localGet 5,
    .ltUI64,
    .iff 0 0 [
      .localGet 5,
      .memorySize,
      .extendUI32,
      .subI64,
      .wrapI64,
      .memoryGrow,
      .const (4294967295 : UInt32),
      .eq,
      .iff 0 0 [
        .unreachable
      ] []
    ] [],
    .globalGet 0,
    .constI64 (48 : UInt64),
    .addI64,
    .localSet 6,
    .localGet 4,
    .globalSet 0,
    .localGet 6,
    .constI64 (48 : UInt64),
    .subI64,
    .wrapI64,
    .constI64 (5501223100278326855 : UInt64),
    .store64 (0 : UInt32),
    .localGet 6,
    .constI64 (40 : UInt64),
    .subI64,
    .wrapI64,
    .constI64 (1 : UInt64),
    .store64 (0 : UInt32),
    .localGet 6,
    .constI64 (32 : UInt64),
    .subI64,
    .wrapI64,
    .localGet 1,
    .store64 (0 : UInt32),
    .localGet 6,
    .constI64 (24 : UInt64),
    .subI64,
    .wrapI64,
    .constI64 (0 : UInt64),
    .store64 (0 : UInt32),
    .localGet 6,
    .constI64 (16 : UInt64),
    .subI64,
    .wrapI64,
    .constI64 (0 : UInt64),
    .store64 (0 : UInt32),
    .localGet 6,
    .constI64 (8 : UInt64),
    .subI64,
    .wrapI64,
    .constI64 (0 : UInt64),
    .store64 (0 : UInt32)
  ] [],
  .globalGet 2,
  .constI64 (1 : UInt64),
  .addI64,
  .globalSet 2,
  .localGet 6
]

def func18Def : Wasm.Function :=
  { params := [.i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64], body := func18, results := [.i64] }

/-- export: reset -/
def func19 : Wasm.Program :=
  [
  .constI64 (4096 : UInt64),
  .globalSet 0,
  .constI64 (0 : UInt64),
  .globalSet 1,
  .constI64 (0 : UInt64),
  .globalSet 2,
  .constI64 (0 : UInt64),
  .globalSet 3,
  .constI64 (0 : UInt64),
  .globalSet 4,
  .constI64 (0 : UInt64),
  .globalSet 5
]

def func19Def : Wasm.Function :=
  { params := [], locals := [], body := func19, results := [] }

/-- export: retain -/
def func20 : Wasm.Program :=
  [
  .localGet 0,
  .constI64 (0 : UInt64),
  .neI64,
  .iff 0 0 [
    .localGet 0,
    .constI64 (48 : UInt64),
    .subI64,
    .wrapI64,
    .load64 (0 : UInt32),
    .constI64 (5501223100278326855 : UInt64),
    .neI64,
    .iff 0 0 [
      .unreachable
    ] [],
    .localGet 0,
    .constI64 (40 : UInt64),
    .subI64,
    .wrapI64,
    .load64 (0 : UInt32),
    .localSet 1,
    .localGet 1,
    .constI64 (0 : UInt64),
    .eqI64,
    .iff 0 0 [
      .unreachable
    ] [],
    .globalGet 3,
    .constI64 (1 : UInt64),
    .addI64,
    .globalSet 3,
    .localGet 0,
    .constI64 (40 : UInt64),
    .subI64,
    .wrapI64,
    .localGet 1,
    .constI64 (1 : UInt64),
    .addI64,
    .store64 (0 : UInt32)
  ] [],
  .localGet 0
]

def func20Def : Wasm.Function :=
  { params := [.i64], locals := [.i64], body := func20, results := [.i64] }

/-- exports: release, free -/
def func21 : Wasm.Program :=
  [
  .localGet 0,
  .constI64 (0 : UInt64),
  .eqI64,
  .iff 0 0 [
    .ret
  ] [],
  .localGet 0,
  .constI64 (48 : UInt64),
  .subI64,
  .wrapI64,
  .load64 (0 : UInt32),
  .constI64 (5501223100278326855 : UInt64),
  .neI64,
  .iff 0 0 [
    .unreachable
  ] [],
  .localGet 0,
  .constI64 (40 : UInt64),
  .subI64,
  .wrapI64,
  .load64 (0 : UInt32),
  .localSet 1,
  .localGet 1,
  .constI64 (0 : UInt64),
  .eqI64,
  .iff 0 0 [
    .unreachable
  ] [],
  .globalGet 4,
  .constI64 (1 : UInt64),
  .addI64,
  .globalSet 4,
  .constI64 (1 : UInt64),
  .localGet 1,
  .ltUI64,
  .iff 0 0 [
    .localGet 0,
    .constI64 (40 : UInt64),
    .subI64,
    .wrapI64,
    .localGet 1,
    .constI64 (1 : UInt64),
    .subI64,
    .store64 (0 : UInt32),
    .ret
  ] [],
  .localGet 0,
  .constI64 (24 : UInt64),
  .subI64,
  .wrapI64,
  .load64 (0 : UInt32),
  .localSet 2,
  .localGet 2,
  .constI64 (1 : UInt64),
  .eqI64,
  .iff 0 0 [
    .localGet 0,
    .constI64 (16 : UInt64),
    .subI64,
    .wrapI64,
    .load64 (0 : UInt32),
    .localSet 3,
    .localGet 0,
    .constI64 (8 : UInt64),
    .subI64,
    .wrapI64,
    .load64 (0 : UInt32),
    .localSet 5,
    .constI64 (0 : UInt64),
    .localSet 6,
    .block 0 0 [
      .loop 0 0 [
        .localGet 6,
        .localGet 3,
        .geUI64,
        .br_if 1,
        .localGet 5,
        .localGet 6,
        .shrUI64,
        .constI64 (1 : UInt64),
        .andI64,
        .constI64 (0 : UInt64),
        .neI64,
        .iff 0 0 [
          .localGet 0,
          .localGet 6,
          .constI64 (8 : UInt64),
          .mulI64,
          .addI64,
          .wrapI64,
          .load64 (0 : UInt32),
          .localSet 8,
          .localGet 8,
          .call 21
        ] [],
        .localGet 6,
        .constI64 (1 : UInt64),
        .addI64,
        .localSet 6,
        .br 0
      ]
    ]
  ] [],
  .localGet 2,
  .constI64 (2 : UInt64),
  .eqI64,
  .iff 0 0 [
    .localGet 0,
    .wrapI64,
    .load64 (0 : UInt32),
    .localSet 3,
    .localGet 0,
    .constI64 (16 : UInt64),
    .subI64,
    .wrapI64,
    .load64 (0 : UInt32),
    .localSet 4,
    .localGet 0,
    .constI64 (8 : UInt64),
    .subI64,
    .wrapI64,
    .load64 (0 : UInt32),
    .localSet 5,
    .constI64 (0 : UInt64),
    .localSet 7,
    .block 0 0 [
      .loop 0 0 [
        .localGet 7,
        .localGet 3,
        .geUI64,
        .br_if 1,
        .constI64 (0 : UInt64),
        .localSet 6,
        .block 0 0 [
          .loop 0 0 [
            .localGet 6,
            .localGet 4,
            .geUI64,
            .br_if 1,
            .localGet 5,
            .localGet 6,
            .shrUI64,
            .constI64 (1 : UInt64),
            .andI64,
            .constI64 (0 : UInt64),
            .neI64,
            .iff 0 0 [
              .localGet 0,
              .constI64 (8 : UInt64),
              .addI64,
              .localGet 7,
              .localGet 4,
              .mulI64,
              .localGet 6,
              .addI64,
              .constI64 (8 : UInt64),
              .mulI64,
              .addI64,
              .wrapI64,
              .load64 (0 : UInt32),
              .localSet 8,
              .localGet 8,
              .call 21
            ] [],
            .localGet 6,
            .constI64 (1 : UInt64),
            .addI64,
            .localSet 6,
            .br 0
          ]
        ],
        .localGet 7,
        .constI64 (1 : UInt64),
        .addI64,
        .localSet 7,
        .br 0
      ]
    ]
  ] [],
  .globalGet 5,
  .constI64 (1 : UInt64),
  .addI64,
  .globalSet 5,
  .localGet 0,
  .constI64 (40 : UInt64),
  .subI64,
  .wrapI64,
  .constI64 (0 : UInt64),
  .store64 (0 : UInt32),
  .localGet 0,
  .constI64 (8 : UInt64),
  .subI64,
  .wrapI64,
  .globalGet 1,
  .store64 (0 : UInt32),
  .localGet 0,
  .globalSet 1
]

def func21Def : Wasm.Function :=
  { params := [.i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func21, results := [] }

def «module» : Wasm.Module :=
{
  imports := [],
  funcs := [
    func0Def,
    func1Def,
    func2Def,
    func3Def,
    func4Def,
    func5Def,
    func6Def,
    func7Def,
    func8Def,
    func9Def,
    func10Def,
    func11Def,
    func12Def,
    func13Def,
    func14Def,
    func15Def,
    func16Def,
    func17Def,
    func18Def,
    func19Def,
    func20Def,
    func21Def
  ],
  exports := [
    { name := "postOnly", funcIdx := 17 },
    { name := "alloc", funcIdx := 18 },
    { name := "reset", funcIdx := 19 },
    { name := "retain", funcIdx := 20 },
    { name := "release", funcIdx := 21 },
    { name := "free", funcIdx := 21 }
  ],
  memory := some { pagesMin := (16 : UInt32), pagesMax := none, data := [] },
  globals := [
    { init := .i64 (4096 : UInt64) },
    { init := .i64 (0 : UInt64) },
    { init := .i64 (0 : UInt64) },
    { init := .i64 (0 : UInt64) },
    { init := .i64 (0 : UInt64) },
    { init := .i64 (0 : UInt64) }
  ],
  types := [
    { params := [.i64, .i64, .i64, .i64, .i64], results := [.i64] },
    { params := [.i64, .i64, .i64, .i64, .i64], results := [.i64] },
    { params := [.i64], results := [.i64] },
    { params := [.i64, .i64, .i64, .i64, .i64], results := [.i64] },
    { params := [.i64, .i64, .i64, .i64, .i64], results := [.i64] },
    { params := [.i64, .i64, .i64], results := [.i64] },
    { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64] },
    { params := [.i64], results := [.i64] },
    { params := [.i64, .i64, .i64, .i64, .i64], results := [.i64] },
    { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64] },
    { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64] },
    { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64] },
    { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64, .i64] },
    { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64, .i64] },
    { params := [], results := [.i64] },
    { params := [], results := [.i64] },
    { params := [], results := [.i64] },
    { params := [.i64, .i64, .i64, .i64, .i64, .i64], results := [.i64, .i64, .i64] },
    { params := [.i64], results := [.i64] },
    { params := [], results := [] },
    { params := [.i64], results := [.i64] },
    { params := [.i64], results := [] }
  ],
  tables := [],
  elements := []
}

end Project.ClobPostOnly
