name = "Project"
version = "0.1.0"
defaultTargets = ["Project"]

[[require]]
name = "CodeLib"
git = "https://github.com/jsmorph/talos"
subDir = "codelib"
rev = "87e3aa5e8f6e6f3b3eb5e7e4c5aba43071002d47"

[[require]]
name = "leanexe"
path = "../../.."

[[lean_lib]]
name = "Project"
