name = "Project"
version = "0.1.0"
defaultTargets = ["Project"]

[[require]]
name = "CodeLib"
git = "https://github.com/cajal-technologies/talos"
subDir = "codelib"
rev = "fda69ca67a81ea4f1fa4e376bdc5861d9fe5479a"

[[require]]
name = "leanexe"
path = "../../.."

[[lean_lib]]
name = "Project"
