/-
  AUTO-GENERATED by `verifier emit`. Do not edit by hand.
-/

import Project.TalosPrelude

set_option maxRecDepth 1048576

namespace Project.EulerGridStep

open Wasm

def func0 : Wasm.Program :=
  [
  .constI64 0,
  .localGet 0,
  .ltUI64,
  .iff 0 1 [
   .localGet 0,
   .constI64 9218868437227405312,
   .ltUI64
  ] [
   .const 0
  ] [] [.i32],
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .localSet 1,
  .localGet 1
 ]

def func0Def : Wasm.Function :=
  { params := [.i64], locals := [.i64], body := func0, results := [.i64], typeIdx := some 0 }

def func1 : Wasm.Program :=
  [
  .localGet 0,
  .constI64 9223372036854775807,
  .andI64,
  .localSet 1,
  .localGet 1
 ]

def func1Def : Wasm.Function :=
  { params := [.i64], locals := [.i64], body := func1, results := [.i64], typeIdx := some 1 }

def func2 : Wasm.Program :=
  [
  .localGet 0,
  .localSet 1,
  .localGet 1,
  .call 1,
  .constI64 9218868437227405312,
  .ltUI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .localSet 2,
  .localGet 2
 ]

def func2Def : Wasm.Function :=
  { params := [.i64], locals := [.i64, .i64], body := func2, results := [.i64], typeIdx := some 2 }

def func3 : Wasm.Program :=
  [
  .localGet 0,
  .localSet 3,
  .localGet 3,
  .call 0,
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 1 [
   .localGet 1,
   .localSet 4,
   .localGet 4,
   .call 2,
   .constI64 0,
   .eqI64,
   .eqz
  ] [
   .const 0
  ] [] [.i32],
  .iff 0 1 [
   .localGet 2,
   .localSet 5,
   .localGet 5,
   .call 0,
   .constI64 0,
   .eqI64,
   .eqz
  ] [
   .const 0
  ] [] [.i32],
  .iff 0 1 [
   .localGet 1,
   .localSet 6,
   .localGet 6,
   .call 1,
   .localGet 0,
   .leUI64
  ] [
   .const 0
  ] [] [.i32],
  .iff 0 1 [
   .localGet 0,
   .localGet 2,
   .leUI64
  ] [
   .const 0
  ] [] [.i32],
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .localSet 7,
  .localGet 7
 ]

def func3Def : Wasm.Function :=
  { params := [.i64, .i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64], body := func3, results := [.i64], typeIdx := some 3 }

def func4 : Wasm.Program :=
  [
  .constI64 1,
  .localSet 0,
  .constI64 0,
  .localSet 1,
  .constI64 0,
  .localSet 2,
  .constI64 0,
  .localSet 3,
  .constI64 0,
  .localSet 4,
  .constI64 0,
  .localSet 5,
  .constI64 0,
  .localSet 6,
  .localGet 0,
  .localGet 1,
  .localGet 2,
  .localGet 3,
  .localGet 4,
  .localGet 5,
  .localGet 6
 ]

def func4Def : Wasm.Function :=
  { locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func4, results := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], typeIdx := some 4 }

def func5 : Wasm.Program :=
  [
  .localGet 0,
  .localSet 3,
  .localGet 1,
  .localSet 4,
  .localGet 2,
  .localSet 5,
  .localGet 3,
  .localGet 4,
  .localGet 5,
  .call 3,
  .localSet 6,
  .localGet 6,
  .constI64 1,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 0 [
   .localGet 1,
   .f64ReinterpretI64,
   .localGet 0,
   .f64ReinterpretI64,
   .f64Div,
   .i64ReinterpretF64,
   .localSet 7,
   .localGet 1,
   .f64ReinterpretI64,
   .localGet 7,
   .f64ReinterpretI64,
   .f64Mul,
   .i64ReinterpretF64,
   .localSet 8,
   .constI64 4602678819172646912,
   .f64ReinterpretI64,
   .localGet 8,
   .f64ReinterpretI64,
   .f64Mul,
   .i64ReinterpretF64,
   .localSet 9,
   .localGet 2,
   .f64ReinterpretI64,
   .localGet 9,
   .f64ReinterpretI64,
   .f64Sub,
   .i64ReinterpretF64,
   .localSet 10,
   .localGet 7,
   .localSet 11,
   .localGet 11,
   .call 2,
   .constI64 0,
   .eqI64,
   .eqz,
   .iff 0 1 [
    .localGet 8,
    .localSet 12,
    .localGet 12,
    .call 2,
    .constI64 0,
    .eqI64,
    .eqz
   ] [
    .const 0
   ] [] [.i32],
   .iff 0 1 [
    .localGet 9,
    .localSet 13,
    .localGet 13,
    .call 2,
    .constI64 0,
    .eqI64,
    .eqz
   ] [
    .const 0
   ] [] [.i32],
   .iff 0 1 [
    .localGet 10,
    .localSet 14,
    .localGet 14,
    .call 0,
    .constI64 0,
    .eqI64,
    .eqz
   ] [
    .const 0
   ] [] [.i32],
   .iff 0 1 [
    .constI64 1
   ] [
    .constI64 0
   ] [] [.i64],
   .constI64 1,
   .eqI64,
   .iff 0 1 [
    .constI64 1
   ] [
    .constI64 0
   ] [] [.i64],
   .constI64 0,
   .eqI64,
   .eqz,
   .iff 0 0 [
    .constI64 4600877379321698714,
    .f64ReinterpretI64,
    .localGet 10,
    .f64ReinterpretI64,
    .f64Mul,
    .i64ReinterpretF64,
    .localSet 15,
    .localGet 15,
    .f64ReinterpretI64,
    .localGet 0,
    .f64ReinterpretI64,
    .f64Div,
    .i64ReinterpretF64,
    .localSet 16,
    .constI64 4608983858650965606,
    .f64ReinterpretI64,
    .localGet 16,
    .f64ReinterpretI64,
    .f64Mul,
    .i64ReinterpretF64,
    .localSet 17,
    .localGet 15,
    .localSet 18,
    .localGet 18,
    .call 0,
    .constI64 0,
    .eqI64,
    .eqz,
    .iff 0 1 [
     .localGet 16,
     .localSet 19,
     .localGet 19,
     .call 0,
     .constI64 0,
     .eqI64,
     .eqz
    ] [
     .const 0
    ] [] [.i32],
    .iff 0 1 [
     .localGet 17,
     .localSet 20,
     .localGet 20,
     .call 0,
     .constI64 0,
     .eqI64,
     .eqz
    ] [
     .const 0
    ] [] [.i32],
    .iff 0 1 [
     .constI64 1
    ] [
     .constI64 0
    ] [] [.i64],
    .constI64 1,
    .eqI64,
    .iff 0 1 [
     .constI64 1
    ] [
     .constI64 0
    ] [] [.i64],
    .constI64 0,
    .eqI64,
    .eqz,
    .iff 0 0 [
     .localGet 17,
     .f64ReinterpretI64,
     .f64Sqrt,
     .i64ReinterpretF64,
     .localSet 21,
     .localGet 7,
     .localSet 22,
     .localGet 22,
     .call 1,
     .f64ReinterpretI64,
     .localGet 21,
     .f64ReinterpretI64,
     .f64Add,
     .i64ReinterpretF64,
     .localSet 23,
     .localGet 8,
     .f64ReinterpretI64,
     .localGet 15,
     .f64ReinterpretI64,
     .f64Add,
     .i64ReinterpretF64,
     .localSet 24,
     .localGet 2,
     .f64ReinterpretI64,
     .localGet 15,
     .f64ReinterpretI64,
     .f64Add,
     .i64ReinterpretF64,
     .localSet 25,
     .localGet 7,
     .f64ReinterpretI64,
     .localGet 25,
     .f64ReinterpretI64,
     .f64Mul,
     .i64ReinterpretF64,
     .localSet 26,
     .localGet 21,
     .localSet 27,
     .localGet 27,
     .call 0,
     .constI64 0,
     .eqI64,
     .eqz,
     .iff 0 1 [
      .localGet 23,
      .localSet 28,
      .localGet 28,
      .call 0,
      .constI64 0,
      .eqI64,
      .eqz
     ] [
      .const 0
     ] [] [.i32],
     .iff 0 1 [
      .localGet 24,
      .localSet 29,
      .localGet 29,
      .call 2,
      .constI64 0,
      .eqI64,
      .eqz
     ] [
      .const 0
     ] [] [.i32],
     .iff 0 1 [
      .localGet 25,
      .localSet 30,
      .localGet 30,
      .call 2,
      .constI64 0,
      .eqI64,
      .eqz
     ] [
      .const 0
     ] [] [.i32],
     .iff 0 1 [
      .localGet 26,
      .localSet 31,
      .localGet 31,
      .call 2,
      .constI64 0,
      .eqI64,
      .eqz
     ] [
      .const 0
     ] [] [.i32],
     .iff 0 1 [
      .constI64 1
     ] [
      .constI64 0
     ] [] [.i64],
     .constI64 1,
     .eqI64,
     .iff 0 1 [
      .constI64 1
     ] [
      .constI64 0
     ] [] [.i64],
     .constI64 0,
     .eqI64,
     .eqz,
     .iff 0 0 [
      .constI64 0,
      .localSet 60,
      .localGet 7,
      .localSet 61,
      .localGet 15,
      .localSet 62,
      .localGet 23,
      .localSet 63,
      .localGet 1,
      .localSet 64,
      .localGet 24,
      .localSet 65,
      .localGet 26,
      .localSet 66
     ] [
      .call 4,
      .localSet 38,
      .localSet 37,
      .localSet 36,
      .localSet 35,
      .localSet 34,
      .localSet 33,
      .localSet 32,
      .localGet 32,
      .localSet 60,
      .localGet 33,
      .localSet 61,
      .localGet 34,
      .localSet 62,
      .localGet 35,
      .localSet 63,
      .localGet 36,
      .localSet 64,
      .localGet 37,
      .localSet 65,
      .localGet 38,
      .localSet 66
     ]
    ] [
     .call 4,
     .localSet 45,
     .localSet 44,
     .localSet 43,
     .localSet 42,
     .localSet 41,
     .localSet 40,
     .localSet 39,
     .localGet 39,
     .localSet 60,
     .localGet 40,
     .localSet 61,
     .localGet 41,
     .localSet 62,
     .localGet 42,
     .localSet 63,
     .localGet 43,
     .localSet 64,
     .localGet 44,
     .localSet 65,
     .localGet 45,
     .localSet 66
    ]
   ] [
    .call 4,
    .localSet 52,
    .localSet 51,
    .localSet 50,
    .localSet 49,
    .localSet 48,
    .localSet 47,
    .localSet 46,
    .localGet 46,
    .localSet 60,
    .localGet 47,
    .localSet 61,
    .localGet 48,
    .localSet 62,
    .localGet 49,
    .localSet 63,
    .localGet 50,
    .localSet 64,
    .localGet 51,
    .localSet 65,
    .localGet 52,
    .localSet 66
   ]
  ] [
   .call 4,
   .localSet 59,
   .localSet 58,
   .localSet 57,
   .localSet 56,
   .localSet 55,
   .localSet 54,
   .localSet 53,
   .localGet 53,
   .localSet 60,
   .localGet 54,
   .localSet 61,
   .localGet 55,
   .localSet 62,
   .localGet 56,
   .localSet 63,
   .localGet 57,
   .localSet 64,
   .localGet 58,
   .localSet 65,
   .localGet 59,
   .localSet 66
  ],
  .localGet 60,
  .localGet 61,
  .localGet 62,
  .localGet 63,
  .localGet 64,
  .localGet 65,
  .localGet 66
 ]

def func5Def : Wasm.Function :=
  { params := [.i64, .i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func5, results := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], typeIdx := some 5 }

def func6 : Wasm.Program :=
  [
  .localGet 0,
  .localSet 7,
  .localGet 7
 ]

def func6Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], locals := [.i64], body := func6, results := [.i64], typeIdx := some 6 }

def func7 : Wasm.Program :=
  [
  .localGet 3,
  .localSet 7,
  .localGet 7
 ]

def func7Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], locals := [.i64], body := func7, results := [.i64], typeIdx := some 7 }

def func8 : Wasm.Program :=
  [
  .constI64 1,
  .localSet 0,
  .constI64 0,
  .localSet 1,
  .localGet 0,
  .localGet 1
 ]

def func8Def : Wasm.Function :=
  { locals := [.i64, .i64], body := func8, results := [.i64, .i64], typeIdx := some 8 }

def func9 : Wasm.Program :=
  [
  .localGet 0,
  .localSet 5,
  .localGet 5,
  .call 0,
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 1 [
   .localGet 1,
   .localSet 6,
   .localGet 6,
   .call 2,
   .constI64 0,
   .eqI64,
   .eqz
  ] [
   .const 0
  ] [] [.i32],
  .iff 0 1 [
   .localGet 2,
   .localSet 7,
   .localGet 7,
   .call 2,
   .constI64 0,
   .eqI64,
   .eqz
  ] [
   .const 0
  ] [] [.i32],
  .iff 0 1 [
   .localGet 3,
   .localSet 8,
   .localGet 8,
   .call 2,
   .constI64 0,
   .eqI64,
   .eqz
  ] [
   .const 0
  ] [] [.i32],
  .iff 0 1 [
   .localGet 4,
   .localSet 9,
   .localGet 9,
   .call 2,
   .constI64 0,
   .eqI64,
   .eqz
  ] [
   .const 0
  ] [] [.i32],
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 1,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 0 [
   .localGet 1,
   .f64ReinterpretI64,
   .localGet 2,
   .f64ReinterpretI64,
   .f64Add,
   .i64ReinterpretF64,
   .localSet 10,
   .constI64 4602678819172646912,
   .f64ReinterpretI64,
   .localGet 10,
   .f64ReinterpretI64,
   .f64Mul,
   .i64ReinterpretF64,
   .localSet 11,
   .localGet 4,
   .f64ReinterpretI64,
   .localGet 3,
   .f64ReinterpretI64,
   .f64Sub,
   .i64ReinterpretF64,
   .localSet 12,
   .localGet 0,
   .f64ReinterpretI64,
   .localGet 12,
   .f64ReinterpretI64,
   .f64Mul,
   .i64ReinterpretF64,
   .localSet 13,
   .constI64 4602678819172646912,
   .f64ReinterpretI64,
   .localGet 13,
   .f64ReinterpretI64,
   .f64Mul,
   .i64ReinterpretF64,
   .localSet 14,
   .localGet 11,
   .f64ReinterpretI64,
   .localGet 14,
   .f64ReinterpretI64,
   .f64Sub,
   .i64ReinterpretF64,
   .localSet 15,
   .localGet 10,
   .localSet 16,
   .localGet 16,
   .call 2,
   .constI64 0,
   .eqI64,
   .eqz,
   .iff 0 1 [
    .localGet 11,
    .localSet 17,
    .localGet 17,
    .call 2,
    .constI64 0,
    .eqI64,
    .eqz
   ] [
    .const 0
   ] [] [.i32],
   .iff 0 1 [
    .localGet 12,
    .localSet 18,
    .localGet 18,
    .call 2,
    .constI64 0,
    .eqI64,
    .eqz
   ] [
    .const 0
   ] [] [.i32],
   .iff 0 1 [
    .localGet 13,
    .localSet 19,
    .localGet 19,
    .call 2,
    .constI64 0,
    .eqI64,
    .eqz
   ] [
    .const 0
   ] [] [.i32],
   .iff 0 1 [
    .localGet 14,
    .localSet 20,
    .localGet 20,
    .call 2,
    .constI64 0,
    .eqI64,
    .eqz
   ] [
    .const 0
   ] [] [.i32],
   .iff 0 1 [
    .localGet 15,
    .localSet 21,
    .localGet 21,
    .call 2,
    .constI64 0,
    .eqI64,
    .eqz
   ] [
    .const 0
   ] [] [.i32],
   .iff 0 1 [
    .constI64 1
   ] [
    .constI64 0
   ] [] [.i64],
   .constI64 1,
   .eqI64,
   .iff 0 1 [
    .constI64 1
   ] [
    .constI64 0
   ] [] [.i64],
   .constI64 0,
   .eqI64,
   .eqz,
   .iff 0 0 [
    .constI64 0,
    .localSet 26,
    .localGet 15,
    .localSet 27
   ] [
    .call 8,
    .localSet 23,
    .localSet 22,
    .localGet 22,
    .localSet 26,
    .localGet 23,
    .localSet 27
   ]
  ] [
   .call 8,
   .localSet 25,
   .localSet 24,
   .localGet 24,
   .localSet 26,
   .localGet 25,
   .localSet 27
  ],
  .localGet 26,
  .localGet 27
 ]

def func9Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func9, results := [.i64, .i64], typeIdx := some 9 }

def func10 : Wasm.Program :=
  [
  .localGet 4,
  .localSet 7,
  .localGet 7
 ]

def func10Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], locals := [.i64], body := func10, results := [.i64], typeIdx := some 10 }

def func11 : Wasm.Program :=
  [
  .localGet 5,
  .localSet 7,
  .localGet 7
 ]

def func11Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], locals := [.i64], body := func11, results := [.i64], typeIdx := some 11 }

def func12 : Wasm.Program :=
  [
  .localGet 6,
  .localSet 7,
  .localGet 7
 ]

def func12Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], locals := [.i64], body := func12, results := [.i64], typeIdx := some 12 }

def func13 : Wasm.Program :=
  [
  .localGet 0,
  .localSet 2,
  .localGet 2
 ]

def func13Def : Wasm.Function :=
  { params := [.i64, .i64], locals := [.i64], body := func13, results := [.i64], typeIdx := some 13 }

def func14 : Wasm.Program :=
  [
  .localGet 1,
  .localSet 2,
  .localGet 2
 ]

def func14Def : Wasm.Function :=
  { params := [.i64, .i64], locals := [.i64], body := func14, results := [.i64], typeIdx := some 14 }

def func15 : Wasm.Program :=
  [
  .constI64 1,
  .localSet 0,
  .constI64 0,
  .localSet 1,
  .constI64 0,
  .localSet 2,
  .constI64 0,
  .localSet 3,
  .constI64 0,
  .localSet 4,
  .localGet 0,
  .localGet 1,
  .localGet 2,
  .localGet 3,
  .localGet 4
 ]

def func15Def : Wasm.Function :=
  { locals := [.i64, .i64, .i64, .i64, .i64], body := func15, results := [.i64, .i64, .i64, .i64, .i64], typeIdx := some 15 }

def func16 : Wasm.Program :=
  [
  .localGet 0,
  .localSet 6,
  .localGet 1,
  .localSet 7,
  .localGet 2,
  .localSet 8,
  .localGet 6,
  .localGet 7,
  .localGet 8,
  .call 5,
  .localSet 15,
  .localSet 14,
  .localSet 13,
  .localSet 12,
  .localSet 11,
  .localSet 10,
  .localSet 9,
  .localGet 9,
  .localSet 16,
  .localGet 12,
  .localSet 19,
  .localGet 13,
  .localSet 20,
  .localGet 14,
  .localSet 21,
  .localGet 15,
  .localSet 22,
  .localGet 16,
  .constI64 0,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 1,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 0 [
   .localGet 3,
   .localSet 23,
   .localGet 4,
   .localSet 24,
   .localGet 5,
   .localSet 25,
   .localGet 23,
   .localGet 24,
   .localGet 25,
   .call 5,
   .localSet 32,
   .localSet 31,
   .localSet 30,
   .localSet 29,
   .localSet 28,
   .localSet 27,
   .localSet 26,
   .localGet 26,
   .localSet 33,
   .localGet 29,
   .localSet 36,
   .localGet 30,
   .localSet 37,
   .localGet 31,
   .localSet 38,
   .localGet 32,
   .localSet 39,
   .localGet 33,
   .constI64 0,
   .eqI64,
   .iff 0 1 [
    .constI64 1
   ] [
    .constI64 0
   ] [] [.i64],
   .constI64 1,
   .eqI64,
   .iff 0 1 [
    .constI64 1
   ] [
    .constI64 0
   ] [] [.i64],
   .constI64 0,
   .eqI64,
   .eqz,
   .iff 0 0 [
    .localGet 19,
    .localGet 36,
    .leUI64,
    .iff 0 1 [
     .localGet 36
    ] [
     .localGet 19
    ] [] [.i64],
    .localSet 40,
    .localGet 40,
    .localSet 41,
    .localGet 20,
    .localSet 42,
    .localGet 37,
    .localSet 43,
    .localGet 0,
    .localSet 44,
    .localGet 3,
    .localSet 45,
    .localGet 41,
    .localGet 42,
    .localGet 43,
    .localGet 44,
    .localGet 45,
    .call 9,
    .localSet 47,
    .localSet 46,
    .localGet 46,
    .localSet 48,
    .localGet 47,
    .localSet 49,
    .localGet 40,
    .localSet 50,
    .localGet 21,
    .localSet 51,
    .localGet 38,
    .localSet 52,
    .localGet 1,
    .localSet 53,
    .localGet 4,
    .localSet 54,
    .localGet 50,
    .localGet 51,
    .localGet 52,
    .localGet 53,
    .localGet 54,
    .call 9,
    .localSet 56,
    .localSet 55,
    .localGet 55,
    .localSet 57,
    .localGet 56,
    .localSet 58,
    .localGet 40,
    .localSet 59,
    .localGet 22,
    .localSet 60,
    .localGet 39,
    .localSet 61,
    .localGet 2,
    .localSet 62,
    .localGet 5,
    .localSet 63,
    .localGet 59,
    .localGet 60,
    .localGet 61,
    .localGet 62,
    .localGet 63,
    .call 9,
    .localSet 65,
    .localSet 64,
    .localGet 64,
    .localSet 66,
    .localGet 65,
    .localSet 67,
    .localGet 48,
    .constI64 0,
    .eqI64,
    .iff 0 1 [
     .constI64 1
    ] [
     .constI64 0
    ] [] [.i64],
    .constI64 0,
    .eqI64,
    .eqz,
    .iff 0 1 [
     .localGet 57,
     .constI64 0,
     .eqI64,
     .iff 0 1 [
      .constI64 1
     ] [
      .constI64 0
     ] [] [.i64],
     .constI64 0,
     .eqI64,
     .eqz
    ] [
     .const 0
    ] [] [.i32],
    .iff 0 1 [
     .localGet 66,
     .constI64 0,
     .eqI64,
     .iff 0 1 [
      .constI64 1
     ] [
      .constI64 0
     ] [] [.i64],
     .constI64 0,
     .eqI64,
     .eqz
    ] [
     .const 0
    ] [] [.i32],
    .iff 0 1 [
     .constI64 1
    ] [
     .constI64 0
    ] [] [.i64],
    .constI64 1,
    .eqI64,
    .iff 0 1 [
     .constI64 1
    ] [
     .constI64 0
    ] [] [.i64],
    .constI64 0,
    .eqI64,
    .eqz,
    .iff 0 0 [
     .constI64 0,
     .localSet 83,
     .localGet 49,
     .localSet 84,
     .localGet 58,
     .localSet 85,
     .localGet 67,
     .localSet 86,
     .localGet 40,
     .localSet 87
    ] [
     .call 15,
     .localSet 72,
     .localSet 71,
     .localSet 70,
     .localSet 69,
     .localSet 68,
     .localGet 68,
     .localSet 83,
     .localGet 69,
     .localSet 84,
     .localGet 70,
     .localSet 85,
     .localGet 71,
     .localSet 86,
     .localGet 72,
     .localSet 87
    ]
   ] [
    .call 15,
    .localSet 77,
    .localSet 76,
    .localSet 75,
    .localSet 74,
    .localSet 73,
    .localGet 73,
    .localSet 83,
    .localGet 74,
    .localSet 84,
    .localGet 75,
    .localSet 85,
    .localGet 76,
    .localSet 86,
    .localGet 77,
    .localSet 87
   ]
  ] [
   .call 15,
   .localSet 82,
   .localSet 81,
   .localSet 80,
   .localSet 79,
   .localSet 78,
   .localGet 78,
   .localSet 83,
   .localGet 79,
   .localSet 84,
   .localGet 80,
   .localSet 85,
   .localGet 81,
   .localSet 86,
   .localGet 82,
   .localSet 87
  ],
  .localGet 83,
  .localGet 84,
  .localGet 85,
  .localGet 86,
  .localGet 87
 ]

def func16Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func16, results := [.i64, .i64, .i64, .i64, .i64], typeIdx := some 16 }

def func17 : Wasm.Program :=
  [
  .localGet 0,
  .localSet 5,
  .localGet 5
 ]

def func17Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64], locals := [.i64], body := func17, results := [.i64], typeIdx := some 17 }

def func18 : Wasm.Program :=
  [
  .localGet 4,
  .localSet 5,
  .localGet 5
 ]

def func18Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64], locals := [.i64], body := func18, results := [.i64], typeIdx := some 18 }

def func19 : Wasm.Program :=
  [
  .localGet 0,
  .localSet 4,
  .localGet 4,
  .call 0,
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 1 [
   .localGet 1,
   .localSet 5,
   .localGet 5,
   .call 2,
   .constI64 0,
   .eqI64,
   .eqz
  ] [
   .const 0
  ] [] [.i32],
  .iff 0 1 [
   .localGet 2,
   .localSet 6,
   .localGet 6,
   .call 2,
   .constI64 0,
   .eqI64,
   .eqz
  ] [
   .const 0
  ] [] [.i32],
  .iff 0 1 [
   .localGet 3,
   .localSet 7,
   .localGet 7,
   .call 2,
   .constI64 0,
   .eqI64,
   .eqz
  ] [
   .const 0
  ] [] [.i32],
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 1,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 0 [
   .localGet 3,
   .f64ReinterpretI64,
   .localGet 2,
   .f64ReinterpretI64,
   .f64Sub,
   .i64ReinterpretF64,
   .localSet 8,
   .localGet 0,
   .f64ReinterpretI64,
   .localGet 8,
   .f64ReinterpretI64,
   .f64Mul,
   .i64ReinterpretF64,
   .localSet 9,
   .localGet 1,
   .f64ReinterpretI64,
   .localGet 9,
   .f64ReinterpretI64,
   .f64Sub,
   .i64ReinterpretF64,
   .localSet 10,
   .localGet 8,
   .localSet 11,
   .localGet 11,
   .call 2,
   .constI64 0,
   .eqI64,
   .eqz,
   .iff 0 1 [
    .localGet 9,
    .localSet 12,
    .localGet 12,
    .call 2,
    .constI64 0,
    .eqI64,
    .eqz
   ] [
    .const 0
   ] [] [.i32],
   .iff 0 1 [
    .localGet 10,
    .localSet 13,
    .localGet 13,
    .call 2,
    .constI64 0,
    .eqI64,
    .eqz
   ] [
    .const 0
   ] [] [.i32],
   .iff 0 1 [
    .constI64 1
   ] [
    .constI64 0
   ] [] [.i64],
   .constI64 1,
   .eqI64,
   .iff 0 1 [
    .constI64 1
   ] [
    .constI64 0
   ] [] [.i64],
   .constI64 0,
   .eqI64,
   .eqz,
   .iff 0 0 [
    .constI64 0,
    .localSet 18,
    .localGet 10,
    .localSet 19
   ] [
    .call 8,
    .localSet 15,
    .localSet 14,
    .localGet 14,
    .localSet 18,
    .localGet 15,
    .localSet 19
   ]
  ] [
   .call 8,
   .localSet 17,
   .localSet 16,
   .localGet 16,
   .localSet 18,
   .localGet 17,
   .localSet 19
  ],
  .localGet 18,
  .localGet 19
 ]

def func19Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func19, results := [.i64, .i64], typeIdx := some 19 }

def func20 : Wasm.Program :=
  [
  .localGet 1,
  .localSet 5,
  .localGet 5
 ]

def func20Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64], locals := [.i64], body := func20, results := [.i64], typeIdx := some 20 }

def func21 : Wasm.Program :=
  [
  .localGet 2,
  .localSet 5,
  .localGet 5
 ]

def func21Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64], locals := [.i64], body := func21, results := [.i64], typeIdx := some 21 }

def func22 : Wasm.Program :=
  [
  .localGet 3,
  .localSet 5,
  .localGet 5
 ]

def func22Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64], locals := [.i64], body := func22, results := [.i64], typeIdx := some 22 }

def func23 : Wasm.Program :=
  [
  .localGet 2,
  .localSet 7,
  .localGet 7
 ]

def func23Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], locals := [.i64], body := func23, results := [.i64], typeIdx := some 23 }

def func24 : Wasm.Program :=
  [
  .constI64 1,
  .localSet 0,
  .constI64 0,
  .localSet 1,
  .constI64 0,
  .localSet 2,
  .constI64 0,
  .localSet 3,
  .constI64 0,
  .localSet 4,
  .constI64 0,
  .localSet 5,
  .constI64 0,
  .localSet 6,
  .localGet 0,
  .localGet 1,
  .localGet 2,
  .localGet 3,
  .localGet 4,
  .localGet 5,
  .localGet 6
 ]

def func24Def : Wasm.Function :=
  { locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func24, results := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], typeIdx := some 24 }

def func25 : Wasm.Program :=
  [
  .localGet 0,
  .localSet 10,
  .localGet 10,
  .call 0,
  .localSet 11,
  .localGet 11,
  .constI64 1,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 0 [
   .localGet 1,
   .localSet 12,
   .localGet 2,
   .localSet 13,
   .localGet 3,
   .localSet 14,
   .localGet 4,
   .localSet 15,
   .localGet 5,
   .localSet 16,
   .localGet 6,
   .localSet 17,
   .localGet 12,
   .localGet 13,
   .localGet 14,
   .localGet 15,
   .localGet 16,
   .localGet 17,
   .call 16,
   .localSet 22,
   .localSet 21,
   .localSet 20,
   .localSet 19,
   .localSet 18,
   .localGet 18,
   .localSet 23,
   .localGet 19,
   .localSet 24,
   .localGet 20,
   .localSet 25,
   .localGet 21,
   .localSet 26,
   .localGet 22,
   .localSet 27,
   .localGet 23,
   .constI64 0,
   .eqI64,
   .iff 0 1 [
    .constI64 1
   ] [
    .constI64 0
   ] [] [.i64],
   .constI64 1,
   .eqI64,
   .iff 0 1 [
    .constI64 1
   ] [
    .constI64 0
   ] [] [.i64],
   .constI64 0,
   .eqI64,
   .eqz,
   .iff 0 0 [
    .localGet 4,
    .localSet 28,
    .localGet 5,
    .localSet 29,
    .localGet 6,
    .localSet 30,
    .localGet 7,
    .localSet 31,
    .localGet 8,
    .localSet 32,
    .localGet 9,
    .localSet 33,
    .localGet 28,
    .localGet 29,
    .localGet 30,
    .localGet 31,
    .localGet 32,
    .localGet 33,
    .call 16,
    .localSet 38,
    .localSet 37,
    .localSet 36,
    .localSet 35,
    .localSet 34,
    .localGet 34,
    .localSet 39,
    .localGet 35,
    .localSet 40,
    .localGet 36,
    .localSet 41,
    .localGet 37,
    .localSet 42,
    .localGet 38,
    .localSet 43,
    .localGet 39,
    .constI64 0,
    .eqI64,
    .iff 0 1 [
     .constI64 1
    ] [
     .constI64 0
    ] [] [.i64],
    .constI64 1,
    .eqI64,
    .iff 0 1 [
     .constI64 1
    ] [
     .constI64 0
    ] [] [.i64],
    .constI64 0,
    .eqI64,
    .eqz,
    .iff 0 0 [
     .localGet 27,
     .localGet 43,
     .leUI64,
     .iff 0 1 [
      .localGet 43
     ] [
      .localGet 27
     ] [] [.i64],
     .localSet 44,
     .localGet 0,
     .f64ReinterpretI64,
     .localGet 44,
     .f64ReinterpretI64,
     .f64Mul,
     .i64ReinterpretF64,
     .localSet 45,
     .localGet 45,
     .localSet 46,
     .localGet 46,
     .call 0,
     .constI64 0,
     .eqI64,
     .eqz,
     .iff 0 1 [
      .localGet 45,
      .constI64 4602678819172646912,
      .leUI64
     ] [
      .const 0
     ] [] [.i32],
     .iff 0 1 [
      .constI64 1
     ] [
      .constI64 0
     ] [] [.i64],
     .constI64 1,
     .eqI64,
     .iff 0 1 [
      .constI64 1
     ] [
      .constI64 0
     ] [] [.i64],
     .constI64 0,
     .eqI64,
     .eqz,
     .iff 0 0 [
      .localGet 0,
      .localSet 47,
      .localGet 4,
      .localSet 48,
      .localGet 24,
      .localSet 49,
      .localGet 40,
      .localSet 50,
      .localGet 47,
      .localGet 48,
      .localGet 49,
      .localGet 50,
      .call 19,
      .localSet 52,
      .localSet 51,
      .localGet 51,
      .localSet 53,
      .localGet 52,
      .localSet 54,
      .localGet 0,
      .localSet 55,
      .localGet 5,
      .localSet 56,
      .localGet 25,
      .localSet 57,
      .localGet 41,
      .localSet 58,
      .localGet 55,
      .localGet 56,
      .localGet 57,
      .localGet 58,
      .call 19,
      .localSet 60,
      .localSet 59,
      .localGet 59,
      .localSet 61,
      .localGet 60,
      .localSet 62,
      .localGet 0,
      .localSet 63,
      .localGet 6,
      .localSet 64,
      .localGet 26,
      .localSet 65,
      .localGet 42,
      .localSet 66,
      .localGet 63,
      .localGet 64,
      .localGet 65,
      .localGet 66,
      .call 19,
      .localSet 68,
      .localSet 67,
      .localGet 67,
      .localSet 69,
      .localGet 68,
      .localSet 70,
      .localGet 53,
      .constI64 0,
      .eqI64,
      .iff 0 1 [
       .constI64 1
      ] [
       .constI64 0
      ] [] [.i64],
      .constI64 0,
      .eqI64,
      .eqz,
      .iff 0 1 [
       .localGet 61,
       .constI64 0,
       .eqI64,
       .iff 0 1 [
        .constI64 1
       ] [
        .constI64 0
       ] [] [.i64],
       .constI64 0,
       .eqI64,
       .eqz
      ] [
       .const 0
      ] [] [.i32],
      .iff 0 1 [
       .localGet 69,
       .constI64 0,
       .eqI64,
       .iff 0 1 [
        .constI64 1
       ] [
        .constI64 0
       ] [] [.i64],
       .constI64 0,
       .eqI64,
       .eqz
      ] [
       .const 0
      ] [] [.i32],
      .iff 0 1 [
       .constI64 1
      ] [
       .constI64 0
      ] [] [.i64],
      .constI64 1,
      .eqI64,
      .iff 0 1 [
       .constI64 1
      ] [
       .constI64 0
      ] [] [.i64],
      .constI64 0,
      .eqI64,
      .eqz,
      .iff 0 0 [
       .localGet 54,
       .localSet 71,
       .localGet 62,
       .localSet 72,
       .localGet 70,
       .localSet 73,
       .localGet 71,
       .localGet 72,
       .localGet 73,
       .call 5,
       .localSet 80,
       .localSet 79,
       .localSet 78,
       .localSet 77,
       .localSet 76,
       .localSet 75,
       .localSet 74,
       .localGet 74,
       .localSet 81,
       .localGet 76,
       .localSet 83,
       .localGet 81,
       .constI64 0,
       .eqI64,
       .iff 0 1 [
        .constI64 1
       ] [
        .constI64 0
       ] [] [.i64],
       .constI64 1,
       .eqI64,
       .iff 0 1 [
        .constI64 1
       ] [
        .constI64 0
       ] [] [.i64],
       .constI64 0,
       .eqI64,
       .eqz,
       .iff 0 0 [
        .constI64 0,
        .localSet 130,
        .localGet 54,
        .localSet 131,
        .localGet 62,
        .localSet 132,
        .localGet 70,
        .localSet 133,
        .localGet 83,
        .localSet 134,
        .localGet 44,
        .localSet 135,
        .localGet 45,
        .localSet 136
       ] [
        .call 24,
        .localSet 94,
        .localSet 93,
        .localSet 92,
        .localSet 91,
        .localSet 90,
        .localSet 89,
        .localSet 88,
        .localGet 88,
        .localSet 130,
        .localGet 89,
        .localSet 131,
        .localGet 90,
        .localSet 132,
        .localGet 91,
        .localSet 133,
        .localGet 92,
        .localSet 134,
        .localGet 93,
        .localSet 135,
        .localGet 94,
        .localSet 136
       ]
      ] [
       .call 24,
       .localSet 101,
       .localSet 100,
       .localSet 99,
       .localSet 98,
       .localSet 97,
       .localSet 96,
       .localSet 95,
       .localGet 95,
       .localSet 130,
       .localGet 96,
       .localSet 131,
       .localGet 97,
       .localSet 132,
       .localGet 98,
       .localSet 133,
       .localGet 99,
       .localSet 134,
       .localGet 100,
       .localSet 135,
       .localGet 101,
       .localSet 136
      ]
     ] [
      .call 24,
      .localSet 108,
      .localSet 107,
      .localSet 106,
      .localSet 105,
      .localSet 104,
      .localSet 103,
      .localSet 102,
      .localGet 102,
      .localSet 130,
      .localGet 103,
      .localSet 131,
      .localGet 104,
      .localSet 132,
      .localGet 105,
      .localSet 133,
      .localGet 106,
      .localSet 134,
      .localGet 107,
      .localSet 135,
      .localGet 108,
      .localSet 136
     ]
    ] [
     .call 24,
     .localSet 115,
     .localSet 114,
     .localSet 113,
     .localSet 112,
     .localSet 111,
     .localSet 110,
     .localSet 109,
     .localGet 109,
     .localSet 130,
     .localGet 110,
     .localSet 131,
     .localGet 111,
     .localSet 132,
     .localGet 112,
     .localSet 133,
     .localGet 113,
     .localSet 134,
     .localGet 114,
     .localSet 135,
     .localGet 115,
     .localSet 136
    ]
   ] [
    .call 24,
    .localSet 122,
    .localSet 121,
    .localSet 120,
    .localSet 119,
    .localSet 118,
    .localSet 117,
    .localSet 116,
    .localGet 116,
    .localSet 130,
    .localGet 117,
    .localSet 131,
    .localGet 118,
    .localSet 132,
    .localGet 119,
    .localSet 133,
    .localGet 120,
    .localSet 134,
    .localGet 121,
    .localSet 135,
    .localGet 122,
    .localSet 136
   ]
  ] [
   .call 24,
   .localSet 129,
   .localSet 128,
   .localSet 127,
   .localSet 126,
   .localSet 125,
   .localSet 124,
   .localSet 123,
   .localGet 123,
   .localSet 130,
   .localGet 124,
   .localSet 131,
   .localGet 125,
   .localSet 132,
   .localGet 126,
   .localSet 133,
   .localGet 127,
   .localSet 134,
   .localGet 128,
   .localSet 135,
   .localGet 129,
   .localSet 136
  ],
  .localGet 130,
  .localGet 131,
  .localGet 132,
  .localGet 133,
  .localGet 134,
  .localGet 135,
  .localGet 136
 ]

def func25Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func25, results := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], typeIdx := some 25 }

def func26 : Wasm.Program :=
  [
  .localGet 0,
  .localSet 7,
  .localGet 7
 ]

def func26Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], locals := [.i64], body := func26, results := [.i64], typeIdx := some 26 }

def func27 : Wasm.Program :=
  [
  .localGet 1,
  .localSet 5,
  .constI64 1,
  .localSet 13,
  .constI64 6,
  .localSet 16,
  .localGet 2,
  .localSet 17,
  .localGet 17,
  .constI64 0,
  .eqI64,
  .iff 0 1 [
   .constI64 0
  ] [
   .constI64 (-1),
   .localGet 17,
   .divUI64,
   .localGet 16,
   .ltUI64,
   .iff 0 1 [
    .unreachable
   ] [
    .localGet 16,
    .localGet 17,
    .mulI64
   ] [] [.i64]
  ] [] [.i64],
  .localSet 14,
  .localGet 13,
  .localGet 14,
  .addI64,
  .localTee 15,
  .localGet 13,
  .ltUI64,
  .iff 0 1 [
   .unreachable
  ] [
   .localGet 15
  ] [] [.i64],
  .localSet 10,
  .localGet 3,
  .localSet 11,
  .localGet 10,
  .localGet 11,
  .addI64,
  .localTee 12,
  .localGet 10,
  .ltUI64,
  .iff 0 1 [
   .unreachable
  ] [
   .localGet 12
  ] [] [.i64],
  .localSet 6,
  .localGet 5,
  .localSet 10,
  .localGet 6,
  .localSet 11,
  .localGet 4,
  .localSet 16,
  .localGet 10,
  .wrapI64,
  .load64 0,
  .localSet 12,
  .localGet 11,
  .localGet 12,
  .ltUI64,
  .iff 0 1 [
   .localGet 12,
   .constI64 1,
   .mulI64,
   .localSet 13,
   .constI64 8,
   .localGet 12,
   .constI64 1,
   .mulI64,
   .constI64 8,
   .mulI64,
   .addI64,
   .constI64 7,
   .addI64,
   .constI64 8,
   .divUI64,
   .constI64 8,
   .mulI64,
   .localSet 19,
   .localGet 19,
   .constI64 8,
   .ltUI64,
   .iff 0 0 [
    .constI64 8,
    .localSet 19
   ] [],
   .constI64 0,
   .localSet 24,
   .constI64 0,
   .localSet 20,
   .globalGet 1,
   .localSet 21,
   .block 0 0 [
    .loop 0 0 [
     .localGet 21,
     .constI64 0,
     .eqI64,
     .br_if 1,
     .localGet 24,
     .constI64 0,
     .neI64,
     .br_if 1,
     .localGet 21,
     .constI64 32,
     .subI64,
     .wrapI64,
     .load64 0,
     .localSet 22,
     .localGet 21,
     .constI64 8,
     .subI64,
     .wrapI64,
     .load64 0,
     .localSet 23,
     .localGet 22,
     .localGet 19,
     .geUI64,
     .iff 0 0 [
      .localGet 20,
      .constI64 0,
      .eqI64,
      .iff 0 0 [
       .localGet 23,
       .globalSet 1
      ] [
       .localGet 20,
       .constI64 8,
       .subI64,
       .wrapI64,
       .localGet 23,
       .store64 0
      ],
      .localGet 21,
      .constI64 48,
      .subI64,
      .wrapI64,
      .constI64 5501223100278326855,
      .store64 0,
      .localGet 21,
      .constI64 40,
      .subI64,
      .wrapI64,
      .constI64 1,
      .store64 0,
      .localGet 21,
      .constI64 32,
      .subI64,
      .wrapI64,
      .localGet 22,
      .store64 0,
      .localGet 21,
      .constI64 24,
      .subI64,
      .wrapI64,
      .constI64 2,
      .store64 0,
      .localGet 21,
      .constI64 16,
      .subI64,
      .wrapI64,
      .constI64 1,
      .store64 0,
      .localGet 21,
      .constI64 8,
      .subI64,
      .wrapI64,
      .constI64 0,
      .store64 0,
      .localGet 21,
      .localSet 24
     ] [
      .localGet 21,
      .localSet 20,
      .localGet 23,
      .localSet 21
     ],
     .br 0
    ]
   ],
   .localGet 24,
   .constI64 0,
   .eqI64,
   .iff 0 0 [
    .globalGet 0,
    .constI64 48,
    .addI64,
    .localGet 19,
    .addI64,
    .localTee 22,
    .globalGet 0,
    .ltUI64,
    .iff 0 0 [
     .unreachable
    ] [],
    .localGet 22,
    .constI64 1,
    .subI64,
    .constI64 65536,
    .divUI64,
    .constI64 1,
    .addI64,
    .localSet 23,
    .memorySize,
    .extendUI32,
    .localGet 23,
    .ltUI64,
    .iff 0 0 [
     .localGet 23,
     .memorySize,
     .extendUI32,
     .subI64,
     .wrapI64,
     .memoryGrow,
     .const (-1),
     .eq,
     .iff 0 0 [
      .unreachable
     ] []
    ] [],
    .globalGet 0,
    .constI64 48,
    .addI64,
    .localSet 24,
    .localGet 22,
    .globalSet 0,
    .localGet 24,
    .constI64 48,
    .subI64,
    .wrapI64,
    .constI64 5501223100278326855,
    .store64 0,
    .localGet 24,
    .constI64 40,
    .subI64,
    .wrapI64,
    .constI64 1,
    .store64 0,
    .localGet 24,
    .constI64 32,
    .subI64,
    .wrapI64,
    .localGet 19,
    .store64 0,
    .localGet 24,
    .constI64 24,
    .subI64,
    .wrapI64,
    .constI64 2,
    .store64 0,
    .localGet 24,
    .constI64 16,
    .subI64,
    .wrapI64,
    .constI64 1,
    .store64 0,
    .localGet 24,
    .constI64 8,
    .subI64,
    .wrapI64,
    .constI64 0,
    .store64 0
   ] [],
   .globalGet 2,
   .constI64 1,
   .addI64,
   .globalSet 2,
   .localGet 24,
   .localSet 14,
   .localGet 14,
   .wrapI64,
   .localGet 12,
   .store64 0,
   .constI64 0,
   .localSet 15,
   .block 0 0 [
    .loop 0 0 [
     .localGet 15,
     .localGet 13,
     .geUI64,
     .br_if 1,
     .localGet 14,
     .localGet 15,
     .constI64 1,
     .addI64,
     .constI64 8,
     .mulI64,
     .addI64,
     .wrapI64,
     .localGet 10,
     .localGet 15,
     .constI64 1,
     .addI64,
     .constI64 8,
     .mulI64,
     .addI64,
     .wrapI64,
     .load64 0,
     .store64 0,
     .localGet 15,
     .constI64 1,
     .addI64,
     .localSet 15,
     .br 0
    ]
   ],
   .localGet 14,
   .localGet 11,
   .constI64 1,
   .mulI64,
   .constI64 1,
   .addI64,
   .constI64 8,
   .mulI64,
   .addI64,
   .wrapI64,
   .localGet 16,
   .store64 0,
   .localGet 14
  ] [
   .unreachable
  ] [] [.i64],
  .localSet 7,
  .localGet 7,
  .localSet 8,
  .localGet 7,
  .localSet 9,
  .localGet 8,
  .localGet 9
 ]

def func27Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func27, results := [.i64, .i64], typeIdx := some 27 }

def func28 : Wasm.Program :=
  [
  .localGet 1,
  .localSet 7,
  .localGet 7
 ]

def func28Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], locals := [.i64], body := func28, results := [.i64], typeIdx := some 28 }

def func29 : Wasm.Program :=
  [
  .localGet 2,
  .localSet 7,
  .localGet 7
 ]

def func29Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], locals := [.i64], body := func29, results := [.i64], typeIdx := some 29 }

def func30 : Wasm.Program :=
  [
  .localGet 3,
  .localSet 7,
  .localGet 7
 ]

def func30Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], locals := [.i64], body := func30, results := [.i64], typeIdx := some 30 }

def func31 : Wasm.Program :=
  [
  .localGet 4,
  .localSet 7,
  .localGet 7
 ]

def func31Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], locals := [.i64], body := func31, results := [.i64], typeIdx := some 31 }

def func32 : Wasm.Program :=
  [
  .localGet 5,
  .localSet 7,
  .localGet 7
 ]

def func32Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], locals := [.i64], body := func32, results := [.i64], typeIdx := some 32 }

def func33 : Wasm.Program :=
  [
  .localGet 6,
  .localSet 7,
  .localGet 7
 ]

def func33Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], locals := [.i64], body := func33, results := [.i64], typeIdx := some 33 }

def func34 : Wasm.Program :=
  [
  .localGet 3,
  .constI64 0,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 1,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 0 [
   .localGet 0,
   .localSet 10,
   .localGet 1,
   .localSet 11,
   .localGet 2,
   .localSet 12,
   .constI64 0,
   .localSet 13,
   .localGet 4,
   .localSet 14,
   .localGet 10,
   .localGet 11,
   .localGet 12,
   .localGet 13,
   .localGet 14,
   .call 27,
   .localSet 16,
   .localSet 15,
   .localGet 15,
   .localSet 17,
   .localGet 16,
   .localSet 18,
   .localGet 17,
   .localSet 19,
   .localGet 18,
   .localSet 20,
   .localGet 2,
   .localSet 21,
   .constI64 1,
   .localSet 22,
   .localGet 5,
   .localSet 23,
   .localGet 19,
   .localGet 20,
   .localGet 21,
   .localGet 22,
   .localGet 23,
   .call 27,
   .localSet 25,
   .localSet 24,
   .localGet 24,
   .localSet 26,
   .localGet 25,
   .localSet 27,
   .localGet 26,
   .localSet 28,
   .localGet 27,
   .localSet 29,
   .localGet 2,
   .localSet 30,
   .constI64 2,
   .localSet 31,
   .localGet 6,
   .localSet 32,
   .localGet 28,
   .localGet 29,
   .localGet 30,
   .localGet 31,
   .localGet 32,
   .call 27,
   .localSet 34,
   .localSet 33,
   .localGet 33,
   .localSet 35,
   .localGet 34,
   .localSet 36,
   .localGet 35,
   .localSet 37,
   .localGet 36,
   .localSet 38,
   .localGet 2,
   .localSet 39,
   .constI64 3,
   .localSet 40,
   .localGet 7,
   .localSet 41,
   .localGet 37,
   .localGet 38,
   .localGet 39,
   .localGet 40,
   .localGet 41,
   .call 27,
   .localSet 43,
   .localSet 42,
   .localGet 42,
   .localSet 44,
   .localGet 43,
   .localSet 45,
   .localGet 44,
   .localSet 46,
   .localGet 45,
   .localSet 47,
   .localGet 2,
   .localSet 48,
   .constI64 4,
   .localSet 49,
   .localGet 8,
   .localSet 50,
   .localGet 46,
   .localGet 47,
   .localGet 48,
   .localGet 49,
   .localGet 50,
   .call 27,
   .localSet 52,
   .localSet 51,
   .localGet 51,
   .localSet 53,
   .localGet 52,
   .localSet 54,
   .localGet 53,
   .localSet 55,
   .localGet 54,
   .localSet 56,
   .localGet 2,
   .localSet 57,
   .constI64 5,
   .localSet 58,
   .localGet 9,
   .localSet 59,
   .localGet 55,
   .localGet 56,
   .localGet 57,
   .localGet 58,
   .localGet 59,
   .call 27,
   .localSet 61,
   .localSet 60,
   .localGet 60,
   .localSet 65,
   .localGet 61,
   .localSet 66,
   .localGet 51,
   .constI64 0,
   .eqI64,
   .eqz,
   .iff 0 0 [
    .localGet 51,
    .call 40
   ] [],
   .localGet 42,
   .constI64 0,
   .eqI64,
   .eqz,
   .iff 0 0 [
    .localGet 42,
    .call 40
   ] [],
   .localGet 33,
   .constI64 0,
   .eqI64,
   .eqz,
   .iff 0 0 [
    .localGet 33,
    .call 40
   ] [],
   .localGet 24,
   .constI64 0,
   .eqI64,
   .eqz,
   .iff 0 0 [
    .localGet 24,
    .call 40
   ] [],
   .localGet 15,
   .constI64 0,
   .eqI64,
   .eqz,
   .iff 0 0 [
    .localGet 15,
    .call 40
   ] []
  ] [
   .localGet 1,
   .localSet 62,
   .constI64 0,
   .localSet 63,
   .localGet 62,
   .localSet 67,
   .localGet 63,
   .localSet 68,
   .constI64 1,
   .localSet 73,
   .localGet 67,
   .wrapI64,
   .load64 0,
   .localSet 69,
   .localGet 68,
   .localGet 69,
   .ltUI64,
   .iff 0 1 [
    .localGet 69,
    .constI64 1,
    .mulI64,
    .localSet 70,
    .constI64 8,
    .localGet 69,
    .constI64 1,
    .mulI64,
    .constI64 8,
    .mulI64,
    .addI64,
    .constI64 7,
    .addI64,
    .constI64 8,
    .divUI64,
    .constI64 8,
    .mulI64,
    .localSet 76,
    .localGet 76,
    .constI64 8,
    .ltUI64,
    .iff 0 0 [
     .constI64 8,
     .localSet 76
    ] [],
    .constI64 0,
    .localSet 81,
    .constI64 0,
    .localSet 77,
    .globalGet 1,
    .localSet 78,
    .block 0 0 [
     .loop 0 0 [
      .localGet 78,
      .constI64 0,
      .eqI64,
      .br_if 1,
      .localGet 81,
      .constI64 0,
      .neI64,
      .br_if 1,
      .localGet 78,
      .constI64 32,
      .subI64,
      .wrapI64,
      .load64 0,
      .localSet 79,
      .localGet 78,
      .constI64 8,
      .subI64,
      .wrapI64,
      .load64 0,
      .localSet 80,
      .localGet 79,
      .localGet 76,
      .geUI64,
      .iff 0 0 [
       .localGet 77,
       .constI64 0,
       .eqI64,
       .iff 0 0 [
        .localGet 80,
        .globalSet 1
       ] [
        .localGet 77,
        .constI64 8,
        .subI64,
        .wrapI64,
        .localGet 80,
        .store64 0
       ],
       .localGet 78,
       .constI64 48,
       .subI64,
       .wrapI64,
       .constI64 5501223100278326855,
       .store64 0,
       .localGet 78,
       .constI64 40,
       .subI64,
       .wrapI64,
       .constI64 1,
       .store64 0,
       .localGet 78,
       .constI64 32,
       .subI64,
       .wrapI64,
       .localGet 79,
       .store64 0,
       .localGet 78,
       .constI64 24,
       .subI64,
       .wrapI64,
       .constI64 2,
       .store64 0,
       .localGet 78,
       .constI64 16,
       .subI64,
       .wrapI64,
       .constI64 1,
       .store64 0,
       .localGet 78,
       .constI64 8,
       .subI64,
       .wrapI64,
       .constI64 0,
       .store64 0,
       .localGet 78,
       .localSet 81
      ] [
       .localGet 78,
       .localSet 77,
       .localGet 80,
       .localSet 78
      ],
      .br 0
     ]
    ],
    .localGet 81,
    .constI64 0,
    .eqI64,
    .iff 0 0 [
     .globalGet 0,
     .constI64 48,
     .addI64,
     .localGet 76,
     .addI64,
     .localTee 79,
     .globalGet 0,
     .ltUI64,
     .iff 0 0 [
      .unreachable
     ] [],
     .localGet 79,
     .constI64 1,
     .subI64,
     .constI64 65536,
     .divUI64,
     .constI64 1,
     .addI64,
     .localSet 80,
     .memorySize,
     .extendUI32,
     .localGet 80,
     .ltUI64,
     .iff 0 0 [
      .localGet 80,
      .memorySize,
      .extendUI32,
      .subI64,
      .wrapI64,
      .memoryGrow,
      .const (-1),
      .eq,
      .iff 0 0 [
       .unreachable
      ] []
     ] [],
     .globalGet 0,
     .constI64 48,
     .addI64,
     .localSet 81,
     .localGet 79,
     .globalSet 0,
     .localGet 81,
     .constI64 48,
     .subI64,
     .wrapI64,
     .constI64 5501223100278326855,
     .store64 0,
     .localGet 81,
     .constI64 40,
     .subI64,
     .wrapI64,
     .constI64 1,
     .store64 0,
     .localGet 81,
     .constI64 32,
     .subI64,
     .wrapI64,
     .localGet 76,
     .store64 0,
     .localGet 81,
     .constI64 24,
     .subI64,
     .wrapI64,
     .constI64 2,
     .store64 0,
     .localGet 81,
     .constI64 16,
     .subI64,
     .wrapI64,
     .constI64 1,
     .store64 0,
     .localGet 81,
     .constI64 8,
     .subI64,
     .wrapI64,
     .constI64 0,
     .store64 0
    ] [],
    .globalGet 2,
    .constI64 1,
    .addI64,
    .globalSet 2,
    .localGet 81,
    .localSet 71,
    .localGet 71,
    .wrapI64,
    .localGet 69,
    .store64 0,
    .constI64 0,
    .localSet 72,
    .block 0 0 [
     .loop 0 0 [
      .localGet 72,
      .localGet 70,
      .geUI64,
      .br_if 1,
      .localGet 71,
      .localGet 72,
      .constI64 1,
      .addI64,
      .constI64 8,
      .mulI64,
      .addI64,
      .wrapI64,
      .localGet 67,
      .localGet 72,
      .constI64 1,
      .addI64,
      .constI64 8,
      .mulI64,
      .addI64,
      .wrapI64,
      .load64 0,
      .store64 0,
      .localGet 72,
      .constI64 1,
      .addI64,
      .localSet 72,
      .br 0
     ]
    ],
    .localGet 71,
    .localGet 68,
    .constI64 1,
    .mulI64,
    .constI64 1,
    .addI64,
    .constI64 8,
    .mulI64,
    .addI64,
    .wrapI64,
    .localGet 73,
    .store64 0,
    .localGet 71
   ] [
    .unreachable
   ] [] [.i64],
   .localSet 64,
   .localGet 64,
   .localSet 65,
   .localGet 64,
   .localSet 66
  ],
  .localGet 65,
  .localGet 66
 ]

def func34Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func34, results := [.i64, .i64], typeIdx := some 34 }

def func35 : Wasm.Program :=
  [
  .constI64 3,
  .localSet 65,
  .localGet 5,
  .localSet 66,
  .localGet 66,
  .constI64 0,
  .eqI64,
  .iff 0 1 [
   .constI64 0
  ] [
   .constI64 (-1),
   .localGet 66,
   .divUI64,
   .localGet 65,
   .ltUI64,
   .iff 0 1 [
    .unreachable
   ] [
    .localGet 65,
    .localGet 66,
    .mulI64
   ] [] [.i64]
  ] [] [.i64],
  .localSet 6,
  .localGet 5,
  .constI64 0,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 1,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 1 [
   .localGet 6
  ] [
   .localGet 6,
   .localSet 65,
   .constI64 3,
   .localSet 66,
   .localGet 65,
   .localGet 66,
   .ltUI64,
   .iff 0 1 [
    .constI64 0
   ] [
    .localGet 65,
    .localGet 66,
    .subI64
   ] [] [.i64]
  ] [] [.i64],
  .localSet 7,
  .localGet 5,
  .localSet 65,
  .constI64 1,
  .localSet 66,
  .localGet 65,
  .localGet 66,
  .addI64,
  .localTee 67,
  .localGet 65,
  .ltUI64,
  .iff 0 1 [
   .unreachable
  ] [
   .localGet 67
  ] [] [.i64],
  .localGet 2,
  .localSet 67,
  .localGet 67,
  .wrapI64,
  .load64 0,
  .localSet 65,
  .constI64 3,
  .localSet 66,
  .localGet 66,
  .constI64 0,
  .eqI64,
  .iff 0 1 [
   .constI64 0
  ] [
   .localGet 65,
   .localGet 66,
   .divUI64
  ] [] [.i64],
  .ltUI64,
  .iff 0 1 [
   .localGet 6,
   .localSet 65,
   .constI64 3,
   .localSet 66,
   .localGet 65,
   .localGet 66,
   .addI64,
   .localTee 67,
   .localGet 65,
   .ltUI64,
   .iff 0 1 [
    .unreachable
   ] [
    .localGet 67
   ] [] [.i64]
  ] [
   .localGet 6
  ] [] [.i64],
  .localSet 8,
  .localGet 0,
  .localSet 9,
  .localGet 2,
  .localSet 10,
  .localGet 7,
  .localSet 11,
  .localGet 11,
  .localGet 10,
  .localSet 65,
  .localGet 65,
  .wrapI64,
  .load64 0,
  .ltUI64,
  .iff 0 1 [
   .localGet 10,
   .localSet 65,
   .localGet 11,
   .localSet 66,
   .localGet 66,
   .localGet 65,
   .wrapI64,
   .load64 0,
   .ltUI64,
   .iff 0 1 [
    .localGet 65,
    .localGet 66,
    .constI64 1,
    .mulI64,
    .constI64 1,
    .addI64,
    .constI64 8,
    .mulI64,
    .addI64,
    .wrapI64,
    .load64 0
   ] [
    .unreachable
   ] [] [.i64]
  ] [
   .constI64 0
  ] [] [.i64],
  .localSet 12,
  .localGet 2,
  .localSet 13,
  .localGet 7,
  .localSet 65,
  .constI64 1,
  .localSet 66,
  .localGet 65,
  .localGet 66,
  .addI64,
  .localTee 67,
  .localGet 65,
  .ltUI64,
  .iff 0 1 [
   .unreachable
  ] [
   .localGet 67
  ] [] [.i64],
  .localSet 14,
  .localGet 14,
  .localGet 13,
  .localSet 65,
  .localGet 65,
  .wrapI64,
  .load64 0,
  .ltUI64,
  .iff 0 1 [
   .localGet 13,
   .localSet 65,
   .localGet 14,
   .localSet 66,
   .localGet 66,
   .localGet 65,
   .wrapI64,
   .load64 0,
   .ltUI64,
   .iff 0 1 [
    .localGet 65,
    .localGet 66,
    .constI64 1,
    .mulI64,
    .constI64 1,
    .addI64,
    .constI64 8,
    .mulI64,
    .addI64,
    .wrapI64,
    .load64 0
   ] [
    .unreachable
   ] [] [.i64]
  ] [
   .constI64 0
  ] [] [.i64],
  .localSet 15,
  .localGet 2,
  .localSet 16,
  .localGet 7,
  .localSet 65,
  .constI64 2,
  .localSet 66,
  .localGet 65,
  .localGet 66,
  .addI64,
  .localTee 67,
  .localGet 65,
  .ltUI64,
  .iff 0 1 [
   .unreachable
  ] [
   .localGet 67
  ] [] [.i64],
  .localSet 17,
  .localGet 17,
  .localGet 16,
  .localSet 65,
  .localGet 65,
  .wrapI64,
  .load64 0,
  .ltUI64,
  .iff 0 1 [
   .localGet 16,
   .localSet 65,
   .localGet 17,
   .localSet 66,
   .localGet 66,
   .localGet 65,
   .wrapI64,
   .load64 0,
   .ltUI64,
   .iff 0 1 [
    .localGet 65,
    .localGet 66,
    .constI64 1,
    .mulI64,
    .constI64 1,
    .addI64,
    .constI64 8,
    .mulI64,
    .addI64,
    .wrapI64,
    .load64 0
   ] [
    .unreachable
   ] [] [.i64]
  ] [
   .constI64 0
  ] [] [.i64],
  .localSet 18,
  .localGet 2,
  .localSet 19,
  .localGet 6,
  .localSet 20,
  .localGet 20,
  .localGet 19,
  .localSet 65,
  .localGet 65,
  .wrapI64,
  .load64 0,
  .ltUI64,
  .iff 0 1 [
   .localGet 19,
   .localSet 65,
   .localGet 20,
   .localSet 66,
   .localGet 66,
   .localGet 65,
   .wrapI64,
   .load64 0,
   .ltUI64,
   .iff 0 1 [
    .localGet 65,
    .localGet 66,
    .constI64 1,
    .mulI64,
    .constI64 1,
    .addI64,
    .constI64 8,
    .mulI64,
    .addI64,
    .wrapI64,
    .load64 0
   ] [
    .unreachable
   ] [] [.i64]
  ] [
   .constI64 0
  ] [] [.i64],
  .localSet 21,
  .localGet 2,
  .localSet 22,
  .localGet 6,
  .localSet 65,
  .constI64 1,
  .localSet 66,
  .localGet 65,
  .localGet 66,
  .addI64,
  .localTee 67,
  .localGet 65,
  .ltUI64,
  .iff 0 1 [
   .unreachable
  ] [
   .localGet 67
  ] [] [.i64],
  .localSet 23,
  .localGet 23,
  .localGet 22,
  .localSet 65,
  .localGet 65,
  .wrapI64,
  .load64 0,
  .ltUI64,
  .iff 0 1 [
   .localGet 22,
   .localSet 65,
   .localGet 23,
   .localSet 66,
   .localGet 66,
   .localGet 65,
   .wrapI64,
   .load64 0,
   .ltUI64,
   .iff 0 1 [
    .localGet 65,
    .localGet 66,
    .constI64 1,
    .mulI64,
    .constI64 1,
    .addI64,
    .constI64 8,
    .mulI64,
    .addI64,
    .wrapI64,
    .load64 0
   ] [
    .unreachable
   ] [] [.i64]
  ] [
   .constI64 0
  ] [] [.i64],
  .localSet 24,
  .localGet 2,
  .localSet 25,
  .localGet 6,
  .localSet 65,
  .constI64 2,
  .localSet 66,
  .localGet 65,
  .localGet 66,
  .addI64,
  .localTee 67,
  .localGet 65,
  .ltUI64,
  .iff 0 1 [
   .unreachable
  ] [
   .localGet 67
  ] [] [.i64],
  .localSet 26,
  .localGet 26,
  .localGet 25,
  .localSet 65,
  .localGet 65,
  .wrapI64,
  .load64 0,
  .ltUI64,
  .iff 0 1 [
   .localGet 25,
   .localSet 65,
   .localGet 26,
   .localSet 66,
   .localGet 66,
   .localGet 65,
   .wrapI64,
   .load64 0,
   .ltUI64,
   .iff 0 1 [
    .localGet 65,
    .localGet 66,
    .constI64 1,
    .mulI64,
    .constI64 1,
    .addI64,
    .constI64 8,
    .mulI64,
    .addI64,
    .wrapI64,
    .load64 0
   ] [
    .unreachable
   ] [] [.i64]
  ] [
   .constI64 0
  ] [] [.i64],
  .localSet 27,
  .localGet 2,
  .localSet 28,
  .localGet 8,
  .localSet 29,
  .localGet 29,
  .localGet 28,
  .localSet 65,
  .localGet 65,
  .wrapI64,
  .load64 0,
  .ltUI64,
  .iff 0 1 [
   .localGet 28,
   .localSet 65,
   .localGet 29,
   .localSet 66,
   .localGet 66,
   .localGet 65,
   .wrapI64,
   .load64 0,
   .ltUI64,
   .iff 0 1 [
    .localGet 65,
    .localGet 66,
    .constI64 1,
    .mulI64,
    .constI64 1,
    .addI64,
    .constI64 8,
    .mulI64,
    .addI64,
    .wrapI64,
    .load64 0
   ] [
    .unreachable
   ] [] [.i64]
  ] [
   .constI64 0
  ] [] [.i64],
  .localSet 30,
  .localGet 2,
  .localSet 31,
  .localGet 8,
  .localSet 65,
  .constI64 1,
  .localSet 66,
  .localGet 65,
  .localGet 66,
  .addI64,
  .localTee 67,
  .localGet 65,
  .ltUI64,
  .iff 0 1 [
   .unreachable
  ] [
   .localGet 67
  ] [] [.i64],
  .localSet 32,
  .localGet 32,
  .localGet 31,
  .localSet 65,
  .localGet 65,
  .wrapI64,
  .load64 0,
  .ltUI64,
  .iff 0 1 [
   .localGet 31,
   .localSet 65,
   .localGet 32,
   .localSet 66,
   .localGet 66,
   .localGet 65,
   .wrapI64,
   .load64 0,
   .ltUI64,
   .iff 0 1 [
    .localGet 65,
    .localGet 66,
    .constI64 1,
    .mulI64,
    .constI64 1,
    .addI64,
    .constI64 8,
    .mulI64,
    .addI64,
    .wrapI64,
    .load64 0
   ] [
    .unreachable
   ] [] [.i64]
  ] [
   .constI64 0
  ] [] [.i64],
  .localSet 33,
  .localGet 2,
  .localSet 34,
  .localGet 8,
  .localSet 65,
  .constI64 2,
  .localSet 66,
  .localGet 65,
  .localGet 66,
  .addI64,
  .localTee 67,
  .localGet 65,
  .ltUI64,
  .iff 0 1 [
   .unreachable
  ] [
   .localGet 67
  ] [] [.i64],
  .localSet 35,
  .localGet 35,
  .localGet 34,
  .localSet 65,
  .localGet 65,
  .wrapI64,
  .load64 0,
  .ltUI64,
  .iff 0 1 [
   .localGet 34,
   .localSet 65,
   .localGet 35,
   .localSet 66,
   .localGet 66,
   .localGet 65,
   .wrapI64,
   .load64 0,
   .ltUI64,
   .iff 0 1 [
    .localGet 65,
    .localGet 66,
    .constI64 1,
    .mulI64,
    .constI64 1,
    .addI64,
    .constI64 8,
    .mulI64,
    .addI64,
    .wrapI64,
    .load64 0
   ] [
    .unreachable
   ] [] [.i64]
  ] [
   .constI64 0
  ] [] [.i64],
  .localSet 36,
  .localGet 9,
  .localGet 12,
  .localGet 15,
  .localGet 18,
  .localGet 21,
  .localGet 24,
  .localGet 27,
  .localGet 30,
  .localGet 33,
  .localGet 36,
  .call 25,
  .localSet 43,
  .localSet 42,
  .localSet 41,
  .localSet 40,
  .localSet 39,
  .localSet 38,
  .localSet 37,
  .localGet 37,
  .localSet 44,
  .localGet 38,
  .localSet 45,
  .localGet 39,
  .localSet 46,
  .localGet 40,
  .localSet 47,
  .localGet 41,
  .localSet 48,
  .localGet 42,
  .localSet 49,
  .localGet 43,
  .localSet 50,
  .localGet 3,
  .localSet 51,
  .localGet 4,
  .localSet 52,
  .localGet 5,
  .localSet 53,
  .localGet 44,
  .localSet 54,
  .localGet 45,
  .localSet 55,
  .localGet 46,
  .localSet 56,
  .localGet 47,
  .localSet 57,
  .localGet 48,
  .localSet 58,
  .localGet 49,
  .localSet 59,
  .localGet 50,
  .localSet 60,
  .localGet 51,
  .localGet 52,
  .localGet 53,
  .localGet 54,
  .localGet 55,
  .localGet 56,
  .localGet 57,
  .localGet 58,
  .localGet 59,
  .localGet 60,
  .call 34,
  .localSet 62,
  .localSet 61,
  .localGet 61,
  .localSet 63,
  .localGet 62,
  .localSet 64,
  .localGet 63,
  .localGet 64
 ]

def func35Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func35, results := [.i64, .i64], typeIdx := some 35 }

/-- Exported function. -/
def func36 : Wasm.Program :=
  [
  .localGet 0,
  .localSet 2,
  .localGet 2,
  .call 0,
  .constI64 0,
  .eqI64,
  .eqz,
  .eqz,
  .iff 0 1 [
   .const 1
  ] [
   .localGet 1,
   .localSet 33,
   .localGet 33,
   .wrapI64,
   .load64 0,
   .constI64 0,
   .eqI64,
   .iff 0 1 [
    .constI64 1
   ] [
    .constI64 0
   ] [] [.i64],
   .constI64 0,
   .eqI64,
   .eqz
  ] [] [.i32],
  .iff 0 1 [
   .const 1
  ] [
   .localGet 1,
   .localSet 35,
   .localGet 35,
   .wrapI64,
   .load64 0,
   .localSet 33,
   .constI64 3,
   .localSet 34,
   .localGet 34,
   .constI64 0,
   .eqI64,
   .iff 0 1 [
    .localGet 33
   ] [
    .localGet 33,
    .localGet 34,
    .remUI64
   ] [] [.i64],
   .constI64 0,
   .eqI64,
   .iff 0 1 [
    .constI64 1
   ] [
    .constI64 0
   ] [] [.i64],
   .constI64 0,
   .eqI64,
   .eqz,
   .eqz
  ] [] [.i32],
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 1,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 0 [
   .constI64 8,
   .constI64 1,
   .constI64 1,
   .mulI64,
   .constI64 8,
   .mulI64,
   .addI64,
   .constI64 7,
   .addI64,
   .constI64 8,
   .divUI64,
   .constI64 8,
   .mulI64,
   .localSet 37,
   .localGet 37,
   .constI64 8,
   .ltUI64,
   .iff 0 0 [
    .constI64 8,
    .localSet 37
   ] [],
   .constI64 0,
   .localSet 42,
   .constI64 0,
   .localSet 38,
   .globalGet 1,
   .localSet 39,
   .block 0 0 [
    .loop 0 0 [
     .localGet 39,
     .constI64 0,
     .eqI64,
     .br_if 1,
     .localGet 42,
     .constI64 0,
     .neI64,
     .br_if 1,
     .localGet 39,
     .constI64 32,
     .subI64,
     .wrapI64,
     .load64 0,
     .localSet 40,
     .localGet 39,
     .constI64 8,
     .subI64,
     .wrapI64,
     .load64 0,
     .localSet 41,
     .localGet 40,
     .localGet 37,
     .geUI64,
     .iff 0 0 [
      .localGet 38,
      .constI64 0,
      .eqI64,
      .iff 0 0 [
       .localGet 41,
       .globalSet 1
      ] [
       .localGet 38,
       .constI64 8,
       .subI64,
       .wrapI64,
       .localGet 41,
       .store64 0
      ],
      .localGet 39,
      .constI64 48,
      .subI64,
      .wrapI64,
      .constI64 5501223100278326855,
      .store64 0,
      .localGet 39,
      .constI64 40,
      .subI64,
      .wrapI64,
      .constI64 1,
      .store64 0,
      .localGet 39,
      .constI64 32,
      .subI64,
      .wrapI64,
      .localGet 40,
      .store64 0,
      .localGet 39,
      .constI64 24,
      .subI64,
      .wrapI64,
      .constI64 2,
      .store64 0,
      .localGet 39,
      .constI64 16,
      .subI64,
      .wrapI64,
      .constI64 1,
      .store64 0,
      .localGet 39,
      .constI64 8,
      .subI64,
      .wrapI64,
      .constI64 0,
      .store64 0,
      .localGet 39,
      .localSet 42
     ] [
      .localGet 39,
      .localSet 38,
      .localGet 41,
      .localSet 39
     ],
     .br 0
    ]
   ],
   .localGet 42,
   .constI64 0,
   .eqI64,
   .iff 0 0 [
    .globalGet 0,
    .constI64 48,
    .addI64,
    .localGet 37,
    .addI64,
    .localTee 40,
    .globalGet 0,
    .ltUI64,
    .iff 0 0 [
     .unreachable
    ] [],
    .localGet 40,
    .constI64 1,
    .subI64,
    .constI64 65536,
    .divUI64,
    .constI64 1,
    .addI64,
    .localSet 41,
    .memorySize,
    .extendUI32,
    .localGet 41,
    .ltUI64,
    .iff 0 0 [
     .localGet 41,
     .memorySize,
     .extendUI32,
     .subI64,
     .wrapI64,
     .memoryGrow,
     .const (-1),
     .eq,
     .iff 0 0 [
      .unreachable
     ] []
    ] [],
    .globalGet 0,
    .constI64 48,
    .addI64,
    .localSet 42,
    .localGet 40,
    .globalSet 0,
    .localGet 42,
    .constI64 48,
    .subI64,
    .wrapI64,
    .constI64 5501223100278326855,
    .store64 0,
    .localGet 42,
    .constI64 40,
    .subI64,
    .wrapI64,
    .constI64 1,
    .store64 0,
    .localGet 42,
    .constI64 32,
    .subI64,
    .wrapI64,
    .localGet 37,
    .store64 0,
    .localGet 42,
    .constI64 24,
    .subI64,
    .wrapI64,
    .constI64 2,
    .store64 0,
    .localGet 42,
    .constI64 16,
    .subI64,
    .wrapI64,
    .constI64 1,
    .store64 0,
    .localGet 42,
    .constI64 8,
    .subI64,
    .wrapI64,
    .constI64 0,
    .store64 0
   ] [],
   .globalGet 2,
   .constI64 1,
   .addI64,
   .globalSet 2,
   .localGet 42,
   .localSet 33,
   .localGet 33,
   .wrapI64,
   .constI64 1,
   .store64 0,
   .constI64 1,
   .localSet 36,
   .localGet 33,
   .constI64 0,
   .constI64 1,
   .mulI64,
   .constI64 1,
   .addI64,
   .constI64 8,
   .mulI64,
   .addI64,
   .wrapI64,
   .localGet 36,
   .store64 0,
   .localGet 33,
   .localSet 3,
   .localGet 3,
   .localSet 32
  ] [
   .localGet 1,
   .localSet 35,
   .localGet 35,
   .wrapI64,
   .load64 0,
   .localSet 33,
   .constI64 3,
   .localSet 34,
   .localGet 34,
   .constI64 0,
   .eqI64,
   .iff 0 1 [
    .constI64 0
   ] [
    .localGet 33,
    .localGet 34,
    .divUI64
   ] [] [.i64],
   .localSet 4,
   .constI64 1,
   .localSet 33,
   .constI64 6,
   .localSet 36,
   .localGet 4,
   .localSet 37,
   .localGet 37,
   .constI64 0,
   .eqI64,
   .iff 0 1 [
    .constI64 0
   ] [
    .constI64 (-1),
    .localGet 37,
    .divUI64,
    .localGet 36,
    .ltUI64,
    .iff 0 1 [
     .unreachable
    ] [
     .localGet 36,
     .localGet 37,
     .mulI64
    ] [] [.i64]
   ] [] [.i64],
   .localSet 34,
   .localGet 33,
   .localGet 34,
   .addI64,
   .localTee 35,
   .localGet 33,
   .ltUI64,
   .iff 0 1 [
    .unreachable
   ] [
    .localGet 35
   ] [] [.i64],
   .localSet 5,
   .localGet 5,
   .localSet 33,
   .constI64 0,
   .localSet 36,
   .constI64 8,
   .localGet 33,
   .constI64 1,
   .mulI64,
   .constI64 8,
   .mulI64,
   .addI64,
   .constI64 7,
   .addI64,
   .constI64 8,
   .divUI64,
   .constI64 8,
   .mulI64,
   .localSet 39,
   .localGet 39,
   .constI64 8,
   .ltUI64,
   .iff 0 0 [
    .constI64 8,
    .localSet 39
   ] [],
   .constI64 0,
   .localSet 44,
   .constI64 0,
   .localSet 40,
   .globalGet 1,
   .localSet 41,
   .block 0 0 [
    .loop 0 0 [
     .localGet 41,
     .constI64 0,
     .eqI64,
     .br_if 1,
     .localGet 44,
     .constI64 0,
     .neI64,
     .br_if 1,
     .localGet 41,
     .constI64 32,
     .subI64,
     .wrapI64,
     .load64 0,
     .localSet 42,
     .localGet 41,
     .constI64 8,
     .subI64,
     .wrapI64,
     .load64 0,
     .localSet 43,
     .localGet 42,
     .localGet 39,
     .geUI64,
     .iff 0 0 [
      .localGet 40,
      .constI64 0,
      .eqI64,
      .iff 0 0 [
       .localGet 43,
       .globalSet 1
      ] [
       .localGet 40,
       .constI64 8,
       .subI64,
       .wrapI64,
       .localGet 43,
       .store64 0
      ],
      .localGet 41,
      .constI64 48,
      .subI64,
      .wrapI64,
      .constI64 5501223100278326855,
      .store64 0,
      .localGet 41,
      .constI64 40,
      .subI64,
      .wrapI64,
      .constI64 1,
      .store64 0,
      .localGet 41,
      .constI64 32,
      .subI64,
      .wrapI64,
      .localGet 42,
      .store64 0,
      .localGet 41,
      .constI64 24,
      .subI64,
      .wrapI64,
      .constI64 2,
      .store64 0,
      .localGet 41,
      .constI64 16,
      .subI64,
      .wrapI64,
      .constI64 1,
      .store64 0,
      .localGet 41,
      .constI64 8,
      .subI64,
      .wrapI64,
      .constI64 0,
      .store64 0,
      .localGet 41,
      .localSet 44
     ] [
      .localGet 41,
      .localSet 40,
      .localGet 43,
      .localSet 41
     ],
     .br 0
    ]
   ],
   .localGet 44,
   .constI64 0,
   .eqI64,
   .iff 0 0 [
    .globalGet 0,
    .constI64 48,
    .addI64,
    .localGet 39,
    .addI64,
    .localTee 42,
    .globalGet 0,
    .ltUI64,
    .iff 0 0 [
     .unreachable
    ] [],
    .localGet 42,
    .constI64 1,
    .subI64,
    .constI64 65536,
    .divUI64,
    .constI64 1,
    .addI64,
    .localSet 43,
    .memorySize,
    .extendUI32,
    .localGet 43,
    .ltUI64,
    .iff 0 0 [
     .localGet 43,
     .memorySize,
     .extendUI32,
     .subI64,
     .wrapI64,
     .memoryGrow,
     .const (-1),
     .eq,
     .iff 0 0 [
      .unreachable
     ] []
    ] [],
    .globalGet 0,
    .constI64 48,
    .addI64,
    .localSet 44,
    .localGet 42,
    .globalSet 0,
    .localGet 44,
    .constI64 48,
    .subI64,
    .wrapI64,
    .constI64 5501223100278326855,
    .store64 0,
    .localGet 44,
    .constI64 40,
    .subI64,
    .wrapI64,
    .constI64 1,
    .store64 0,
    .localGet 44,
    .constI64 32,
    .subI64,
    .wrapI64,
    .localGet 39,
    .store64 0,
    .localGet 44,
    .constI64 24,
    .subI64,
    .wrapI64,
    .constI64 2,
    .store64 0,
    .localGet 44,
    .constI64 16,
    .subI64,
    .wrapI64,
    .constI64 1,
    .store64 0,
    .localGet 44,
    .constI64 8,
    .subI64,
    .wrapI64,
    .constI64 0,
    .store64 0
   ] [],
   .globalGet 2,
   .constI64 1,
   .addI64,
   .globalSet 2,
   .localGet 44,
   .localSet 34,
   .localGet 34,
   .wrapI64,
   .localGet 33,
   .store64 0,
   .constI64 0,
   .localSet 35,
   .block 0 0 [
    .loop 0 0 [
     .localGet 35,
     .localGet 33,
     .geUI64,
     .br_if 1,
     .localGet 34,
     .localGet 35,
     .constI64 1,
     .mulI64,
     .constI64 1,
     .addI64,
     .constI64 8,
     .mulI64,
     .addI64,
     .wrapI64,
     .localGet 36,
     .store64 0,
     .localGet 35,
     .constI64 1,
     .addI64,
     .localSet 35,
     .br 0
    ]
   ],
   .localGet 34,
   .localSet 7,
   .localGet 7,
   .localSet 8,
   .constI64 0,
   .localSet 9,
   .localGet 7,
   .localSet 10,
   .localGet 8,
   .localSet 11,
   .localGet 9,
   .localSet 12,
   .constI64 0,
   .localSet 40,
   .block 0 0 [
    .loop 0 0 [
     .localGet 10,
     .localSet 13,
     .localGet 11,
     .localSet 14,
     .localGet 12,
     .localSet 15,
     .localGet 15,
     .localGet 4,
     .ltUI64,
     .iff 0 1 [
      .localGet 14,
      .localSet 33,
      .constI64 0,
      .localSet 34,
      .localGet 34,
      .localGet 33,
      .wrapI64,
      .load64 0,
      .ltUI64,
      .iff 0 1 [
       .localGet 33,
       .localGet 34,
       .constI64 1,
       .mulI64,
       .constI64 1,
       .addI64,
       .constI64 8,
       .mulI64,
       .addI64,
       .wrapI64,
       .load64 0
      ] [
       .unreachable
      ] [] [.i64],
      .constI64 0,
      .eqI64,
      .iff 0 1 [
       .constI64 1
      ] [
       .constI64 0
      ] [] [.i64],
      .constI64 0,
      .eqI64,
      .eqz
     ] [
      .const 0
     ] [] [.i32],
     .iff 0 1 [
      .constI64 1
     ] [
      .constI64 0
     ] [] [.i64],
     .constI64 1,
     .eqI64,
     .iff 0 1 [
      .constI64 1
     ] [
      .constI64 0
     ] [] [.i64],
     .constI64 0,
     .eqI64,
     .eqz,
     .iff 0 0 [
      .localGet 0,
      .localSet 16,
      .constI64 0,
      .localSet 17,
      .localGet 1,
      .localSet 18,
      .localGet 13,
      .localSet 19,
      .localGet 14,
      .localSet 20,
      .localGet 15,
      .localSet 21,
      .localGet 16,
      .localGet 17,
      .localGet 18,
      .localGet 19,
      .localGet 20,
      .localGet 21,
      .call 35,
      .localSet 23,
      .localSet 22,
      .localGet 22,
      .localSet 24,
      .localGet 23,
      .localSet 25,
      .localGet 15,
      .localSet 33,
      .constI64 1,
      .localSet 34,
      .localGet 33,
      .localGet 34,
      .addI64,
      .localTee 35,
      .localGet 33,
      .ltUI64,
      .iff 0 1 [
       .unreachable
      ] [
       .localGet 35
      ] [] [.i64],
      .localSet 26,
      .localGet 24,
      .localSet 27,
      .localGet 25,
      .localSet 28,
      .localGet 26,
      .localSet 29
     ] [
      .localGet 13,
      .localSet 27,
      .localGet 14,
      .localSet 28,
      .localGet 15,
      .localSet 29
     ],
     .localGet 27,
     .localSet 37,
     .localGet 28,
     .localSet 38,
     .localGet 29,
     .localSet 39,
     .localGet 12,
     .localGet 4,
     .ltUI64,
     .iff 0 1 [
      .localGet 11,
      .localSet 33,
      .constI64 0,
      .localSet 34,
      .localGet 34,
      .localGet 33,
      .wrapI64,
      .load64 0,
      .ltUI64,
      .iff 0 1 [
       .localGet 33,
       .localGet 34,
       .constI64 1,
       .mulI64,
       .constI64 1,
       .addI64,
       .constI64 8,
       .mulI64,
       .addI64,
       .wrapI64,
       .load64 0
      ] [
       .unreachable
      ] [] [.i64],
      .constI64 0,
      .eqI64,
      .iff 0 1 [
       .constI64 1
      ] [
       .constI64 0
      ] [] [.i64],
      .constI64 0,
      .eqI64,
      .eqz
     ] [
      .const 0
     ] [] [.i32],
     .iff 0 1 [
      .constI64 1
     ] [
      .constI64 0
     ] [] [.i64],
     .constI64 1,
     .eqI64,
     .iff 0 1 [
      .constI64 1
     ] [
      .constI64 0
     ] [] [.i64],
     .constI64 0,
     .eqI64,
     .eqz,
     .iff 0 1 [
      .constI64 0
     ] [
      .constI64 1
     ] [] [.i64],
     .localSet 36,
     .localGet 37,
     .localSet 10,
     .localGet 38,
     .localSet 11,
     .localGet 39,
     .localSet 12,
     .constI64 1,
     .localSet 40,
     .localGet 36,
     .constI64 0,
     .neI64,
     .br_if 1,
     .br 0
    ]
   ],
   .localGet 11,
   .localSet 31,
   .localGet 31,
   .localSet 32,
   .localGet 7,
   .constI64 0,
   .eqI64,
   .eqz,
   .iff 0 0 [
    .localGet 7,
    .call 40
   ] []
  ],
  .localGet 32
 ]

def func36Def : Wasm.Function :=
  { params := [.i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func36, results := [.i64], typeIdx := some 36 }

/-- Exported function. -/
def func37 : Wasm.Program :=
  [
  .localGet 0,
  .constI64 7,
  .addI64,
  .constI64 8,
  .divUI64,
  .constI64 8,
  .mulI64,
  .localSet 1,
  .localGet 1,
  .constI64 8,
  .ltUI64,
  .iff 0 0 [
   .constI64 8,
   .localSet 1
  ] [],
  .constI64 0,
  .localSet 6,
  .constI64 0,
  .localSet 2,
  .globalGet 1,
  .localSet 3,
  .block 0 0 [
   .loop 0 0 [
    .localGet 3,
    .constI64 0,
    .eqI64,
    .br_if 1,
    .localGet 6,
    .constI64 0,
    .neI64,
    .br_if 1,
    .localGet 3,
    .constI64 32,
    .subI64,
    .wrapI64,
    .load64 0,
    .localSet 4,
    .localGet 3,
    .constI64 8,
    .subI64,
    .wrapI64,
    .load64 0,
    .localSet 5,
    .localGet 4,
    .localGet 1,
    .geUI64,
    .iff 0 0 [
     .localGet 2,
     .constI64 0,
     .eqI64,
     .iff 0 0 [
      .localGet 5,
      .globalSet 1
     ] [
      .localGet 2,
      .constI64 8,
      .subI64,
      .wrapI64,
      .localGet 5,
      .store64 0
     ],
     .localGet 3,
     .constI64 48,
     .subI64,
     .wrapI64,
     .constI64 5501223100278326855,
     .store64 0,
     .localGet 3,
     .constI64 40,
     .subI64,
     .wrapI64,
     .constI64 1,
     .store64 0,
     .localGet 3,
     .constI64 32,
     .subI64,
     .wrapI64,
     .localGet 4,
     .store64 0,
     .localGet 3,
     .constI64 24,
     .subI64,
     .wrapI64,
     .constI64 0,
     .store64 0,
     .localGet 3,
     .constI64 16,
     .subI64,
     .wrapI64,
     .constI64 0,
     .store64 0,
     .localGet 3,
     .constI64 8,
     .subI64,
     .wrapI64,
     .constI64 0,
     .store64 0,
     .localGet 3,
     .localSet 6
    ] [
     .localGet 3,
     .localSet 2,
     .localGet 5,
     .localSet 3
    ],
    .br 0
   ]
  ],
  .localGet 6,
  .constI64 0,
  .eqI64,
  .iff 0 0 [
   .globalGet 0,
   .constI64 48,
   .addI64,
   .localGet 1,
   .addI64,
   .localTee 4,
   .globalGet 0,
   .ltUI64,
   .iff 0 0 [
    .unreachable
   ] [],
   .localGet 4,
   .constI64 1,
   .subI64,
   .constI64 65536,
   .divUI64,
   .constI64 1,
   .addI64,
   .localSet 5,
   .memorySize,
   .extendUI32,
   .localGet 5,
   .ltUI64,
   .iff 0 0 [
    .localGet 5,
    .memorySize,
    .extendUI32,
    .subI64,
    .wrapI64,
    .memoryGrow,
    .const (-1),
    .eq,
    .iff 0 0 [
     .unreachable
    ] []
   ] [],
   .globalGet 0,
   .constI64 48,
   .addI64,
   .localSet 6,
   .localGet 4,
   .globalSet 0,
   .localGet 6,
   .constI64 48,
   .subI64,
   .wrapI64,
   .constI64 5501223100278326855,
   .store64 0,
   .localGet 6,
   .constI64 40,
   .subI64,
   .wrapI64,
   .constI64 1,
   .store64 0,
   .localGet 6,
   .constI64 32,
   .subI64,
   .wrapI64,
   .localGet 1,
   .store64 0,
   .localGet 6,
   .constI64 24,
   .subI64,
   .wrapI64,
   .constI64 0,
   .store64 0,
   .localGet 6,
   .constI64 16,
   .subI64,
   .wrapI64,
   .constI64 0,
   .store64 0,
   .localGet 6,
   .constI64 8,
   .subI64,
   .wrapI64,
   .constI64 0,
   .store64 0
  ] [],
  .globalGet 2,
  .constI64 1,
  .addI64,
  .globalSet 2,
  .localGet 6
 ]

def func37Def : Wasm.Function :=
  { params := [.i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64], body := func37, results := [.i64], typeIdx := some 37 }

/-- Exported function. -/
def func38 : Wasm.Program :=
  [
  .constI64 4096,
  .globalSet 0,
  .constI64 0,
  .globalSet 1,
  .constI64 0,
  .globalSet 2,
  .constI64 0,
  .globalSet 3,
  .constI64 0,
  .globalSet 4,
  .constI64 0,
  .globalSet 5
 ]

def func38Def : Wasm.Function :=
  { body := func38, typeIdx := some 38 }

/-- Exported function. -/
def func39 : Wasm.Program :=
  [
  .localGet 0,
  .constI64 0,
  .neI64,
  .iff 0 0 [
   .localGet 0,
   .constI64 48,
   .subI64,
   .wrapI64,
   .load64 0,
   .constI64 5501223100278326855,
   .neI64,
   .iff 0 0 [
    .unreachable
   ] [],
   .localGet 0,
   .constI64 40,
   .subI64,
   .wrapI64,
   .load64 0,
   .localSet 1,
   .localGet 1,
   .constI64 0,
   .eqI64,
   .iff 0 0 [
    .unreachable
   ] [],
   .globalGet 3,
   .constI64 1,
   .addI64,
   .globalSet 3,
   .localGet 0,
   .constI64 40,
   .subI64,
   .wrapI64,
   .localGet 1,
   .constI64 1,
   .addI64,
   .store64 0
  ] [],
  .localGet 0
 ]

def func39Def : Wasm.Function :=
  { params := [.i64], locals := [.i64], body := func39, results := [.i64], typeIdx := some 39 }

/-- Exported function. -/
def func40 : Wasm.Program :=
  [
  .localGet 0,
  .constI64 0,
  .eqI64,
  .iff 0 0 [
   .ret
  ] [],
  .localGet 0,
  .constI64 48,
  .subI64,
  .wrapI64,
  .load64 0,
  .constI64 5501223100278326855,
  .neI64,
  .iff 0 0 [
   .unreachable
  ] [],
  .localGet 0,
  .constI64 40,
  .subI64,
  .wrapI64,
  .load64 0,
  .localSet 1,
  .localGet 1,
  .constI64 0,
  .eqI64,
  .iff 0 0 [
   .unreachable
  ] [],
  .globalGet 4,
  .constI64 1,
  .addI64,
  .globalSet 4,
  .constI64 1,
  .localGet 1,
  .ltUI64,
  .iff 0 0 [
   .localGet 0,
   .constI64 40,
   .subI64,
   .wrapI64,
   .localGet 1,
   .constI64 1,
   .subI64,
   .store64 0,
   .ret
  ] [],
  .localGet 0,
  .constI64 24,
  .subI64,
  .wrapI64,
  .load64 0,
  .localSet 2,
  .localGet 2,
  .constI64 1,
  .eqI64,
  .iff 0 0 [
   .localGet 0,
   .constI64 16,
   .subI64,
   .wrapI64,
   .load64 0,
   .localSet 3,
   .localGet 0,
   .constI64 8,
   .subI64,
   .wrapI64,
   .load64 0,
   .localSet 5,
   .constI64 0,
   .localSet 6,
   .block 0 0 [
    .loop 0 0 [
     .localGet 6,
     .localGet 3,
     .geUI64,
     .br_if 1,
     .localGet 5,
     .localGet 6,
     .shrUI64,
     .constI64 1,
     .andI64,
     .constI64 0,
     .neI64,
     .iff 0 0 [
      .localGet 0,
      .localGet 6,
      .constI64 8,
      .mulI64,
      .addI64,
      .wrapI64,
      .load64 0,
      .localSet 8,
      .localGet 8,
      .call 40
     ] [],
     .localGet 6,
     .constI64 1,
     .addI64,
     .localSet 6,
     .br 0
    ]
   ]
  ] [],
  .localGet 2,
  .constI64 2,
  .eqI64,
  .iff 0 0 [
   .localGet 0,
   .wrapI64,
   .load64 0,
   .localSet 3,
   .localGet 0,
   .constI64 16,
   .subI64,
   .wrapI64,
   .load64 0,
   .localSet 4,
   .localGet 0,
   .constI64 8,
   .subI64,
   .wrapI64,
   .load64 0,
   .localSet 5,
   .constI64 0,
   .localSet 7,
   .block 0 0 [
    .loop 0 0 [
     .localGet 7,
     .localGet 3,
     .geUI64,
     .br_if 1,
     .constI64 0,
     .localSet 6,
     .block 0 0 [
      .loop 0 0 [
       .localGet 6,
       .localGet 4,
       .geUI64,
       .br_if 1,
       .localGet 5,
       .localGet 6,
       .shrUI64,
       .constI64 1,
       .andI64,
       .constI64 0,
       .neI64,
       .iff 0 0 [
        .localGet 0,
        .constI64 8,
        .addI64,
        .localGet 7,
        .localGet 4,
        .mulI64,
        .localGet 6,
        .addI64,
        .constI64 8,
        .mulI64,
        .addI64,
        .wrapI64,
        .load64 0,
        .localSet 8,
        .localGet 8,
        .call 40
       ] [],
       .localGet 6,
       .constI64 1,
       .addI64,
       .localSet 6,
       .br 0
      ]
     ],
     .localGet 7,
     .constI64 1,
     .addI64,
     .localSet 7,
     .br 0
    ]
   ]
  ] [],
  .globalGet 5,
  .constI64 1,
  .addI64,
  .globalSet 5,
  .localGet 0,
  .constI64 40,
  .subI64,
  .wrapI64,
  .constI64 0,
  .store64 0,
  .localGet 0,
  .constI64 8,
  .subI64,
  .wrapI64,
  .globalGet 1,
  .store64 0,
  .localGet 0,
  .globalSet 1
 ]

def func40Def : Wasm.Function :=
  { params := [.i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func40, typeIdx := some 40 }

def «module» : Wasm.Module :=
{
  funcs := [
   func0Def,
   func1Def,
   func2Def,
   func3Def,
   func4Def,
   func5Def,
   func6Def,
   func7Def,
   func8Def,
   func9Def,
   func10Def,
   func11Def,
   func12Def,
   func13Def,
   func14Def,
   func15Def,
   func16Def,
   func17Def,
   func18Def,
   func19Def,
   func20Def,
   func21Def,
   func22Def,
   func23Def,
   func24Def,
   func25Def,
   func26Def,
   func27Def,
   func28Def,
   func29Def,
   func30Def,
   func31Def,
   func32Def,
   func33Def,
   func34Def,
   func35Def,
   func36Def,
   func37Def,
   func38Def,
   func39Def,
   func40Def
  ],
  exports := [
   { name := "stepCheckedBits", funcIdx := 36 },
   { name := "alloc", funcIdx := 37 },
   { name := "reset", funcIdx := 38 },
   { name := "retain", funcIdx := 39 },
   { name := "release", funcIdx := 40 },
   { name := "free", funcIdx := 40 }
  ],
  memory := some ({ pagesMin := 16 }),
  globals := [
   { init := .i64 4096, declaredType := some (.i64), sourceInit := some ([
     .constI64 4096
    ]) },
   { init := .i64 0, declaredType := some (.i64), sourceInit := some ([
     .constI64 0
    ]) },
   { init := .i64 0, declaredType := some (.i64), sourceInit := some ([
     .constI64 0
    ]) },
   { init := .i64 0, declaredType := some (.i64), sourceInit := some ([
     .constI64 0
    ]) },
   { init := .i64 0, declaredType := some (.i64), sourceInit := some ([
     .constI64 0
    ]) },
   { init := .i64 0, declaredType := some (.i64), sourceInit := some ([
     .constI64 0
    ]) }
  ],
  types := [
   { params := [.i64], results := [.i64] },
   { params := [.i64], results := [.i64] },
   { params := [.i64], results := [.i64] },
   { params := [.i64, .i64, .i64], results := [.i64] },
   { results := [.i64, .i64, .i64, .i64, .i64, .i64, .i64] },
   { params := [.i64, .i64, .i64], results := [.i64, .i64, .i64, .i64, .i64, .i64, .i64] },
   { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64] },
   { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64] },
   { results := [.i64, .i64] },
   { params := [.i64, .i64, .i64, .i64, .i64], results := [.i64, .i64] },
   { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64] },
   { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64] },
   { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64] },
   { params := [.i64, .i64], results := [.i64] },
   { params := [.i64, .i64], results := [.i64] },
   { results := [.i64, .i64, .i64, .i64, .i64] },
   { params := [.i64, .i64, .i64, .i64, .i64, .i64], results := [.i64, .i64, .i64, .i64, .i64] },
   { params := [.i64, .i64, .i64, .i64, .i64], results := [.i64] },
   { params := [.i64, .i64, .i64, .i64, .i64], results := [.i64] },
   { params := [.i64, .i64, .i64, .i64], results := [.i64, .i64] },
   { params := [.i64, .i64, .i64, .i64, .i64], results := [.i64] },
   { params := [.i64, .i64, .i64, .i64, .i64], results := [.i64] },
   { params := [.i64, .i64, .i64, .i64, .i64], results := [.i64] },
   { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64] },
   { results := [.i64, .i64, .i64, .i64, .i64, .i64, .i64] },
   { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64, .i64, .i64, .i64, .i64, .i64, .i64] },
   { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64] },
   { params := [.i64, .i64, .i64, .i64, .i64], results := [.i64, .i64] },
   { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64] },
   { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64] },
   { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64] },
   { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64] },
   { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64] },
   { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64] },
   { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64, .i64] },
   { params := [.i64, .i64, .i64, .i64, .i64, .i64], results := [.i64, .i64] },
   { params := [.i64, .i64], results := [.i64] },
   { params := [.i64], results := [.i64] },
   {},
   { params := [.i64], results := [.i64] },
   { params := [.i64] }
  ],
  gcTypes := [
   { comp := .func ({ params := [.i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64], results := [.i64] }) },
   { comp := .func ({ results := [.i64, .i64, .i64, .i64, .i64, .i64, .i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64], results := [.i64, .i64, .i64, .i64, .i64, .i64, .i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64] }) },
   { comp := .func ({ results := [.i64, .i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64, .i64], results := [.i64, .i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64], results := [.i64] }) },
   { comp := .func ({ results := [.i64, .i64, .i64, .i64, .i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64, .i64, .i64], results := [.i64, .i64, .i64, .i64, .i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64], results := [.i64, .i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64] }) },
   { comp := .func ({ results := [.i64, .i64, .i64, .i64, .i64, .i64, .i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64, .i64, .i64, .i64, .i64, .i64, .i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64, .i64], results := [.i64, .i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64, .i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64, .i64, .i64], results := [.i64, .i64] }) },
   { comp := .func ({ params := [.i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64], results := [.i64] }) },
   { comp := .func ({}) },
   { comp := .func ({ params := [.i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64] }) }
  ],
  globalExports := [
   ("allocCount", 2),
   ("retainCount", 3),
   ("releaseCount", 4),
   ("freeCount", 5)
  ],
  memoryExports := [
   ("memory", 0)
  ]
}

end Project.EulerGridStep
