import Project.Artifact.Binary.Syntax

namespace Project.EulerRusanov.Artifact.Cache

def raw : Wasm.Binary.RawModule :=
{ sections := [Wasm.Binary.SectionId.type,
               Wasm.Binary.SectionId.function,
               Wasm.Binary.SectionId.memory,
               Wasm.Binary.SectionId.global,
               Wasm.Binary.SectionId.export,
               Wasm.Binary.SectionId.code],
  types := [{ params := [Wasm.Binary.ValType.i64,
                         Wasm.Binary.ValType.i64,
                         Wasm.Binary.ValType.i64,
                         Wasm.Binary.ValType.i64,
                         Wasm.Binary.ValType.i64,
                         Wasm.Binary.ValType.i64],
              results := [Wasm.Binary.ValType.i64,
                          Wasm.Binary.ValType.i64,
                          Wasm.Binary.ValType.i64,
                          Wasm.Binary.ValType.i64] },
            { params := [Wasm.Binary.ValType.i64], results := [Wasm.Binary.ValType.i64] },
            { params := [], results := [] },
            { params := [Wasm.Binary.ValType.i64], results := [Wasm.Binary.ValType.i64] },
            { params := [Wasm.Binary.ValType.i64], results := [] }],
  functionTypeIndices := [0, 1, 2, 3, 4],
  memories := [{ limits := { min := 16, max := none } }],
  globals := [{ type := { type := Wasm.Binary.ValType.i64, mutability := Wasm.Binary.Mutability.mutable },
                init := Wasm.Binary.ConstExpr.i64Const 4096 },
              { type := { type := Wasm.Binary.ValType.i64, mutability := Wasm.Binary.Mutability.mutable },
                init := Wasm.Binary.ConstExpr.i64Const 0 },
              { type := { type := Wasm.Binary.ValType.i64, mutability := Wasm.Binary.Mutability.mutable },
                init := Wasm.Binary.ConstExpr.i64Const 0 },
              { type := { type := Wasm.Binary.ValType.i64, mutability := Wasm.Binary.Mutability.mutable },
                init := Wasm.Binary.ConstExpr.i64Const 0 },
              { type := { type := Wasm.Binary.ValType.i64, mutability := Wasm.Binary.Mutability.mutable },
                init := Wasm.Binary.ConstExpr.i64Const 0 },
              { type := { type := Wasm.Binary.ValType.i64, mutability := Wasm.Binary.Mutability.mutable },
                init := Wasm.Binary.ConstExpr.i64Const 0 }],
  exports := [{ name := { bytes := [109, 101, 109, 111, 114, 121], text := "memory" },
                desc := Wasm.Binary.ExportDesc.memory 0 },
              { name := { bytes := [114, 117, 115, 97, 110, 111, 118, 70, 108, 117, 120, 67, 104, 101, 99, 107, 101,
                                    100, 66, 105, 116, 115],
                          text := "rusanovFluxCheckedBits" },
                desc := Wasm.Binary.ExportDesc.func 0 },
              { name := { bytes := [97, 108, 108, 111, 99], text := "alloc" }, desc := Wasm.Binary.ExportDesc.func 1 },
              { name := { bytes := [114, 101, 115, 101, 116], text := "reset" },
                desc := Wasm.Binary.ExportDesc.func 2 },
              { name := { bytes := [114, 101, 116, 97, 105, 110], text := "retain" },
                desc := Wasm.Binary.ExportDesc.func 3 },
              { name := { bytes := [114, 101, 108, 101, 97, 115, 101], text := "release" },
                desc := Wasm.Binary.ExportDesc.func 4 },
              { name := { bytes := [102, 114, 101, 101], text := "free" }, desc := Wasm.Binary.ExportDesc.func 4 },
              { name := { bytes := [97, 108, 108, 111, 99, 67, 111, 117, 110, 116], text := "allocCount" },
                desc := Wasm.Binary.ExportDesc.global 2 },
              { name := { bytes := [114, 101, 116, 97, 105, 110, 67, 111, 117, 110, 116], text := "retainCount" },
                desc := Wasm.Binary.ExportDesc.global 3 },
              { name := { bytes := [114, 101, 108, 101, 97, 115, 101, 67, 111, 117, 110, 116], text := "releaseCount" },
                desc := Wasm.Binary.ExportDesc.global 4 },
              { name := { bytes := [102, 114, 101, 101, 67, 111, 117, 110, 116], text := "freeCount" },
                desc := Wasm.Binary.ExportDesc.global 5 }],
  codes := [{ locals := [{ count := 42, type := Wasm.Binary.ValType.i64 }],
              body := [Wasm.Binary.Instr.i64Const 4593671619917905920,
                       Wasm.Binary.Instr.localGet 0,
                       Wasm.Binary.Instr.i64LeU,
                       Wasm.Binary.Instr.iff
                         (Wasm.Binary.BlockType.value (Wasm.Binary.ValType.i32))
                         [Wasm.Binary.Instr.localGet 0,
                          Wasm.Binary.Instr.i64Const 4607182418800017408,
                          Wasm.Binary.Instr.i64LeU]
                         (some [Wasm.Binary.Instr.i32Const 0]),
                       Wasm.Binary.Instr.iff
                         (Wasm.Binary.BlockType.value (Wasm.Binary.ValType.i32))
                         [Wasm.Binary.Instr.i64Const 4589168020290535424,
                          Wasm.Binary.Instr.localGet 2,
                          Wasm.Binary.Instr.i64LeU]
                         (some [Wasm.Binary.Instr.i32Const 0]),
                       Wasm.Binary.Instr.iff
                         (Wasm.Binary.BlockType.value (Wasm.Binary.ValType.i32))
                         [Wasm.Binary.Instr.localGet 2, Wasm.Binary.Instr.localGet 0, Wasm.Binary.Instr.i64LeU]
                         (some [Wasm.Binary.Instr.i32Const 0]),
                       Wasm.Binary.Instr.iff
                         (Wasm.Binary.BlockType.value (Wasm.Binary.ValType.i32))
                         [Wasm.Binary.Instr.localGet 1,
                          Wasm.Binary.Instr.i64Const 9223372036854775807,
                          Wasm.Binary.Instr.i64And,
                          Wasm.Binary.Instr.i64Const 4602678819172646912,
                          Wasm.Binary.Instr.i64LeU]
                         (some [Wasm.Binary.Instr.i32Const 0]),
                       Wasm.Binary.Instr.iff
                         (Wasm.Binary.BlockType.value (Wasm.Binary.ValType.i32))
                         [Wasm.Binary.Instr.i64Const 4593671619917905920,
                          Wasm.Binary.Instr.localGet 3,
                          Wasm.Binary.Instr.i64LeU]
                         (some [Wasm.Binary.Instr.i32Const 0]),
                       Wasm.Binary.Instr.iff
                         (Wasm.Binary.BlockType.value (Wasm.Binary.ValType.i32))
                         [Wasm.Binary.Instr.localGet 3,
                          Wasm.Binary.Instr.i64Const 4607182418800017408,
                          Wasm.Binary.Instr.i64LeU]
                         (some [Wasm.Binary.Instr.i32Const 0]),
                       Wasm.Binary.Instr.iff
                         (Wasm.Binary.BlockType.value (Wasm.Binary.ValType.i32))
                         [Wasm.Binary.Instr.i64Const 4589168020290535424,
                          Wasm.Binary.Instr.localGet 5,
                          Wasm.Binary.Instr.i64LeU]
                         (some [Wasm.Binary.Instr.i32Const 0]),
                       Wasm.Binary.Instr.iff
                         (Wasm.Binary.BlockType.value (Wasm.Binary.ValType.i32))
                         [Wasm.Binary.Instr.localGet 5, Wasm.Binary.Instr.localGet 3, Wasm.Binary.Instr.i64LeU]
                         (some [Wasm.Binary.Instr.i32Const 0]),
                       Wasm.Binary.Instr.iff
                         (Wasm.Binary.BlockType.value (Wasm.Binary.ValType.i32))
                         [Wasm.Binary.Instr.localGet 4,
                          Wasm.Binary.Instr.i64Const 9223372036854775807,
                          Wasm.Binary.Instr.i64And,
                          Wasm.Binary.Instr.i64Const 4602678819172646912,
                          Wasm.Binary.Instr.i64LeU]
                         (some [Wasm.Binary.Instr.i32Const 0]),
                       Wasm.Binary.Instr.iff
                         (Wasm.Binary.BlockType.value (Wasm.Binary.ValType.i64))
                         [Wasm.Binary.Instr.i64Const 1]
                         (some [Wasm.Binary.Instr.i64Const 0]),
                       Wasm.Binary.Instr.i64Const 1,
                       Wasm.Binary.Instr.i64Eq,
                       Wasm.Binary.Instr.iff
                         (Wasm.Binary.BlockType.value (Wasm.Binary.ValType.i64))
                         [Wasm.Binary.Instr.i64Const 1]
                         (some [Wasm.Binary.Instr.i64Const 0]),
                       Wasm.Binary.Instr.i64Const 0,
                       Wasm.Binary.Instr.i64Eq,
                       Wasm.Binary.Instr.i32Eqz,
                       Wasm.Binary.Instr.iff
                         (Wasm.Binary.BlockType.empty)
                         [Wasm.Binary.Instr.i64Const 4602678819172646912,
                          Wasm.Binary.Instr.localSet 6,
                          Wasm.Binary.Instr.i64Const 4598175219545276416,
                          Wasm.Binary.Instr.localSet 7,
                          Wasm.Binary.Instr.i64Const 4593671619917905920,
                          Wasm.Binary.Instr.localSet 8,
                          Wasm.Binary.Instr.i64Const (-9223372036854775808),
                          Wasm.Binary.Instr.localSet 9,
                          Wasm.Binary.Instr.localGet 0,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 1,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Mul,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.localSet 10,
                          Wasm.Binary.Instr.localGet 10,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 1,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Mul,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.localSet 11,
                          Wasm.Binary.Instr.localGet 6,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 11,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Mul,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.localSet 12,
                          Wasm.Binary.Instr.localGet 6,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 2,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Mul,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.localSet 13,
                          Wasm.Binary.Instr.localGet 2,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 2,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Add,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.localSet 14,
                          Wasm.Binary.Instr.localGet 14,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 13,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Add,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.localSet 15,
                          Wasm.Binary.Instr.localGet 15,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 12,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Add,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.localSet 16,
                          Wasm.Binary.Instr.localGet 15,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 2,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Add,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.localSet 17,
                          Wasm.Binary.Instr.localGet 17,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 12,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Add,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.localSet 18,
                          Wasm.Binary.Instr.localGet 11,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 2,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Add,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.localSet 19,
                          Wasm.Binary.Instr.localGet 18,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 1,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Mul,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.localSet 20,
                          Wasm.Binary.Instr.localGet 3,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 4,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Mul,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.localSet 21,
                          Wasm.Binary.Instr.localGet 21,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 4,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Mul,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.localSet 22,
                          Wasm.Binary.Instr.localGet 6,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 22,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Mul,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.localSet 23,
                          Wasm.Binary.Instr.localGet 6,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 5,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Mul,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.localSet 24,
                          Wasm.Binary.Instr.localGet 5,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 5,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Add,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.localSet 25,
                          Wasm.Binary.Instr.localGet 25,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 24,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Add,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.localSet 26,
                          Wasm.Binary.Instr.localGet 26,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 23,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Add,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.localSet 27,
                          Wasm.Binary.Instr.localGet 26,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 5,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Add,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.localSet 28,
                          Wasm.Binary.Instr.localGet 28,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 23,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Add,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.localSet 29,
                          Wasm.Binary.Instr.localGet 22,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 5,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Add,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.localSet 30,
                          Wasm.Binary.Instr.localGet 29,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 4,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Mul,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.localSet 31,
                          Wasm.Binary.Instr.localGet 0,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 3,
                          Wasm.Binary.Instr.localGet 9,
                          Wasm.Binary.Instr.i64Xor,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Add,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.localSet 32,
                          Wasm.Binary.Instr.localGet 6,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 10,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 21,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Add,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Mul,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.localSet 33,
                          Wasm.Binary.Instr.localGet 6,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 32,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Mul,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 7,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 32,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Mul,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Add,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 8,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 32,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Mul,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Add,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.localSet 34,
                          Wasm.Binary.Instr.localGet 33,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 34,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Add,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.localSet 35,
                          Wasm.Binary.Instr.localGet 10,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 21,
                          Wasm.Binary.Instr.localGet 9,
                          Wasm.Binary.Instr.i64Xor,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Add,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.localSet 36,
                          Wasm.Binary.Instr.localGet 6,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 19,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 30,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Add,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Mul,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.localSet 37,
                          Wasm.Binary.Instr.localGet 6,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 36,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Mul,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 7,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 36,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Mul,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Add,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 8,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 36,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Mul,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Add,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.localSet 38,
                          Wasm.Binary.Instr.localGet 37,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 38,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Add,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.localSet 39,
                          Wasm.Binary.Instr.localGet 16,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 27,
                          Wasm.Binary.Instr.localGet 9,
                          Wasm.Binary.Instr.i64Xor,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Add,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.localSet 40,
                          Wasm.Binary.Instr.localGet 6,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 20,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 31,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Add,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Mul,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.localSet 41,
                          Wasm.Binary.Instr.localGet 6,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 40,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Mul,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 7,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 40,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Mul,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Add,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 8,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 40,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Mul,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Add,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.localSet 42,
                          Wasm.Binary.Instr.localGet 41,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.localGet 42,
                          Wasm.Binary.Instr.f64ReinterpretI64,
                          Wasm.Binary.Instr.f64Add,
                          Wasm.Binary.Instr.i64ReinterpretF64,
                          Wasm.Binary.Instr.localSet 43,
                          Wasm.Binary.Instr.i64Const 0,
                          Wasm.Binary.Instr.localSet 44,
                          Wasm.Binary.Instr.localGet 35,
                          Wasm.Binary.Instr.localSet 45,
                          Wasm.Binary.Instr.localGet 39,
                          Wasm.Binary.Instr.localSet 46,
                          Wasm.Binary.Instr.localGet 43,
                          Wasm.Binary.Instr.localSet 47]
                         (some [Wasm.Binary.Instr.i64Const 1,
                           Wasm.Binary.Instr.localSet 44,
                           Wasm.Binary.Instr.i64Const 0,
                           Wasm.Binary.Instr.localSet 45,
                           Wasm.Binary.Instr.i64Const 0,
                           Wasm.Binary.Instr.localSet 46,
                           Wasm.Binary.Instr.i64Const 0,
                           Wasm.Binary.Instr.localSet 47]),
                       Wasm.Binary.Instr.localGet 44,
                       Wasm.Binary.Instr.localGet 45,
                       Wasm.Binary.Instr.localGet 46,
                       Wasm.Binary.Instr.localGet 47] },
            { locals := [{ count := 6, type := Wasm.Binary.ValType.i64 }],
              body := [Wasm.Binary.Instr.localGet 0,
                       Wasm.Binary.Instr.i64Const 7,
                       Wasm.Binary.Instr.i64Add,
                       Wasm.Binary.Instr.i64Const 8,
                       Wasm.Binary.Instr.i64DivU,
                       Wasm.Binary.Instr.i64Const 8,
                       Wasm.Binary.Instr.i64Mul,
                       Wasm.Binary.Instr.localSet 1,
                       Wasm.Binary.Instr.localGet 1,
                       Wasm.Binary.Instr.i64Const 8,
                       Wasm.Binary.Instr.i64LtU,
                       Wasm.Binary.Instr.iff
                         (Wasm.Binary.BlockType.empty)
                         [Wasm.Binary.Instr.i64Const 8, Wasm.Binary.Instr.localSet 1]
                         none,
                       Wasm.Binary.Instr.i64Const 0,
                       Wasm.Binary.Instr.localSet 6,
                       Wasm.Binary.Instr.i64Const 0,
                       Wasm.Binary.Instr.localSet 2,
                       Wasm.Binary.Instr.globalGet 1,
                       Wasm.Binary.Instr.localSet 3,
                       Wasm.Binary.Instr.block
                         (Wasm.Binary.BlockType.empty)
                         [Wasm.Binary.Instr.loop
                            (Wasm.Binary.BlockType.empty)
                            [Wasm.Binary.Instr.localGet 3,
                             Wasm.Binary.Instr.i64Const 0,
                             Wasm.Binary.Instr.i64Eq,
                             Wasm.Binary.Instr.brIf 1,
                             Wasm.Binary.Instr.localGet 6,
                             Wasm.Binary.Instr.i64Const 0,
                             Wasm.Binary.Instr.i64Ne,
                             Wasm.Binary.Instr.brIf 1,
                             Wasm.Binary.Instr.localGet 3,
                             Wasm.Binary.Instr.i64Const 32,
                             Wasm.Binary.Instr.i64Sub,
                             Wasm.Binary.Instr.i32WrapI64,
                             Wasm.Binary.Instr.i64Load { align := 3, offset := 0 },
                             Wasm.Binary.Instr.localSet 4,
                             Wasm.Binary.Instr.localGet 3,
                             Wasm.Binary.Instr.i64Const 8,
                             Wasm.Binary.Instr.i64Sub,
                             Wasm.Binary.Instr.i32WrapI64,
                             Wasm.Binary.Instr.i64Load { align := 3, offset := 0 },
                             Wasm.Binary.Instr.localSet 5,
                             Wasm.Binary.Instr.localGet 4,
                             Wasm.Binary.Instr.localGet 1,
                             Wasm.Binary.Instr.i64GeU,
                             Wasm.Binary.Instr.iff
                               (Wasm.Binary.BlockType.empty)
                               [Wasm.Binary.Instr.localGet 2,
                                Wasm.Binary.Instr.i64Const 0,
                                Wasm.Binary.Instr.i64Eq,
                                Wasm.Binary.Instr.iff
                                  (Wasm.Binary.BlockType.empty)
                                  [Wasm.Binary.Instr.localGet 5, Wasm.Binary.Instr.globalSet 1]
                                  (some [Wasm.Binary.Instr.localGet 2,
                                    Wasm.Binary.Instr.i64Const 8,
                                    Wasm.Binary.Instr.i64Sub,
                                    Wasm.Binary.Instr.i32WrapI64,
                                    Wasm.Binary.Instr.localGet 5,
                                    Wasm.Binary.Instr.i64Store { align := 3, offset := 0 }]),
                                Wasm.Binary.Instr.localGet 3,
                                Wasm.Binary.Instr.i64Const 48,
                                Wasm.Binary.Instr.i64Sub,
                                Wasm.Binary.Instr.i32WrapI64,
                                Wasm.Binary.Instr.i64Const 5501223100278326855,
                                Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
                                Wasm.Binary.Instr.localGet 3,
                                Wasm.Binary.Instr.i64Const 40,
                                Wasm.Binary.Instr.i64Sub,
                                Wasm.Binary.Instr.i32WrapI64,
                                Wasm.Binary.Instr.i64Const 1,
                                Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
                                Wasm.Binary.Instr.localGet 3,
                                Wasm.Binary.Instr.i64Const 32,
                                Wasm.Binary.Instr.i64Sub,
                                Wasm.Binary.Instr.i32WrapI64,
                                Wasm.Binary.Instr.localGet 4,
                                Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
                                Wasm.Binary.Instr.localGet 3,
                                Wasm.Binary.Instr.i64Const 24,
                                Wasm.Binary.Instr.i64Sub,
                                Wasm.Binary.Instr.i32WrapI64,
                                Wasm.Binary.Instr.i64Const 0,
                                Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
                                Wasm.Binary.Instr.localGet 3,
                                Wasm.Binary.Instr.i64Const 16,
                                Wasm.Binary.Instr.i64Sub,
                                Wasm.Binary.Instr.i32WrapI64,
                                Wasm.Binary.Instr.i64Const 0,
                                Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
                                Wasm.Binary.Instr.localGet 3,
                                Wasm.Binary.Instr.i64Const 8,
                                Wasm.Binary.Instr.i64Sub,
                                Wasm.Binary.Instr.i32WrapI64,
                                Wasm.Binary.Instr.i64Const 0,
                                Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
                                Wasm.Binary.Instr.localGet 3,
                                Wasm.Binary.Instr.localSet 6]
                               (some [Wasm.Binary.Instr.localGet 3,
                                 Wasm.Binary.Instr.localSet 2,
                                 Wasm.Binary.Instr.localGet 5,
                                 Wasm.Binary.Instr.localSet 3]),
                             Wasm.Binary.Instr.br 0]],
                       Wasm.Binary.Instr.localGet 6,
                       Wasm.Binary.Instr.i64Const 0,
                       Wasm.Binary.Instr.i64Eq,
                       Wasm.Binary.Instr.iff
                         (Wasm.Binary.BlockType.empty)
                         [Wasm.Binary.Instr.globalGet 0,
                          Wasm.Binary.Instr.i64Const 48,
                          Wasm.Binary.Instr.i64Add,
                          Wasm.Binary.Instr.localGet 1,
                          Wasm.Binary.Instr.i64Add,
                          Wasm.Binary.Instr.localTee 4,
                          Wasm.Binary.Instr.globalGet 0,
                          Wasm.Binary.Instr.i64LtU,
                          Wasm.Binary.Instr.iff (Wasm.Binary.BlockType.empty) [Wasm.Binary.Instr.unreachable] none,
                          Wasm.Binary.Instr.localGet 4,
                          Wasm.Binary.Instr.i64Const 1,
                          Wasm.Binary.Instr.i64Sub,
                          Wasm.Binary.Instr.i64Const 65536,
                          Wasm.Binary.Instr.i64DivU,
                          Wasm.Binary.Instr.i64Const 1,
                          Wasm.Binary.Instr.i64Add,
                          Wasm.Binary.Instr.localSet 5,
                          Wasm.Binary.Instr.memorySize 0,
                          Wasm.Binary.Instr.i64ExtendI32U,
                          Wasm.Binary.Instr.localGet 5,
                          Wasm.Binary.Instr.i64LtU,
                          Wasm.Binary.Instr.iff
                            (Wasm.Binary.BlockType.empty)
                            [Wasm.Binary.Instr.localGet 5,
                             Wasm.Binary.Instr.memorySize 0,
                             Wasm.Binary.Instr.i64ExtendI32U,
                             Wasm.Binary.Instr.i64Sub,
                             Wasm.Binary.Instr.i32WrapI64,
                             Wasm.Binary.Instr.memoryGrow 0,
                             Wasm.Binary.Instr.i32Const (-1),
                             Wasm.Binary.Instr.i32Eq,
                             Wasm.Binary.Instr.iff (Wasm.Binary.BlockType.empty) [Wasm.Binary.Instr.unreachable] none]
                            none,
                          Wasm.Binary.Instr.globalGet 0,
                          Wasm.Binary.Instr.i64Const 48,
                          Wasm.Binary.Instr.i64Add,
                          Wasm.Binary.Instr.localSet 6,
                          Wasm.Binary.Instr.localGet 4,
                          Wasm.Binary.Instr.globalSet 0,
                          Wasm.Binary.Instr.localGet 6,
                          Wasm.Binary.Instr.i64Const 48,
                          Wasm.Binary.Instr.i64Sub,
                          Wasm.Binary.Instr.i32WrapI64,
                          Wasm.Binary.Instr.i64Const 5501223100278326855,
                          Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
                          Wasm.Binary.Instr.localGet 6,
                          Wasm.Binary.Instr.i64Const 40,
                          Wasm.Binary.Instr.i64Sub,
                          Wasm.Binary.Instr.i32WrapI64,
                          Wasm.Binary.Instr.i64Const 1,
                          Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
                          Wasm.Binary.Instr.localGet 6,
                          Wasm.Binary.Instr.i64Const 32,
                          Wasm.Binary.Instr.i64Sub,
                          Wasm.Binary.Instr.i32WrapI64,
                          Wasm.Binary.Instr.localGet 1,
                          Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
                          Wasm.Binary.Instr.localGet 6,
                          Wasm.Binary.Instr.i64Const 24,
                          Wasm.Binary.Instr.i64Sub,
                          Wasm.Binary.Instr.i32WrapI64,
                          Wasm.Binary.Instr.i64Const 0,
                          Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
                          Wasm.Binary.Instr.localGet 6,
                          Wasm.Binary.Instr.i64Const 16,
                          Wasm.Binary.Instr.i64Sub,
                          Wasm.Binary.Instr.i32WrapI64,
                          Wasm.Binary.Instr.i64Const 0,
                          Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
                          Wasm.Binary.Instr.localGet 6,
                          Wasm.Binary.Instr.i64Const 8,
                          Wasm.Binary.Instr.i64Sub,
                          Wasm.Binary.Instr.i32WrapI64,
                          Wasm.Binary.Instr.i64Const 0,
                          Wasm.Binary.Instr.i64Store { align := 3, offset := 0 }]
                         none,
                       Wasm.Binary.Instr.globalGet 2,
                       Wasm.Binary.Instr.i64Const 1,
                       Wasm.Binary.Instr.i64Add,
                       Wasm.Binary.Instr.globalSet 2,
                       Wasm.Binary.Instr.localGet 6] },
            { locals := [],
              body := [Wasm.Binary.Instr.i64Const 4096,
                       Wasm.Binary.Instr.globalSet 0,
                       Wasm.Binary.Instr.i64Const 0,
                       Wasm.Binary.Instr.globalSet 1,
                       Wasm.Binary.Instr.i64Const 0,
                       Wasm.Binary.Instr.globalSet 2,
                       Wasm.Binary.Instr.i64Const 0,
                       Wasm.Binary.Instr.globalSet 3,
                       Wasm.Binary.Instr.i64Const 0,
                       Wasm.Binary.Instr.globalSet 4,
                       Wasm.Binary.Instr.i64Const 0,
                       Wasm.Binary.Instr.globalSet 5] },
            { locals := [{ count := 1, type := Wasm.Binary.ValType.i64 }],
              body := [Wasm.Binary.Instr.localGet 0,
                       Wasm.Binary.Instr.i64Const 0,
                       Wasm.Binary.Instr.i64Ne,
                       Wasm.Binary.Instr.iff
                         (Wasm.Binary.BlockType.empty)
                         [Wasm.Binary.Instr.localGet 0,
                          Wasm.Binary.Instr.i64Const 48,
                          Wasm.Binary.Instr.i64Sub,
                          Wasm.Binary.Instr.i32WrapI64,
                          Wasm.Binary.Instr.i64Load { align := 3, offset := 0 },
                          Wasm.Binary.Instr.i64Const 5501223100278326855,
                          Wasm.Binary.Instr.i64Ne,
                          Wasm.Binary.Instr.iff (Wasm.Binary.BlockType.empty) [Wasm.Binary.Instr.unreachable] none,
                          Wasm.Binary.Instr.localGet 0,
                          Wasm.Binary.Instr.i64Const 40,
                          Wasm.Binary.Instr.i64Sub,
                          Wasm.Binary.Instr.i32WrapI64,
                          Wasm.Binary.Instr.i64Load { align := 3, offset := 0 },
                          Wasm.Binary.Instr.localSet 1,
                          Wasm.Binary.Instr.localGet 1,
                          Wasm.Binary.Instr.i64Const 0,
                          Wasm.Binary.Instr.i64Eq,
                          Wasm.Binary.Instr.iff (Wasm.Binary.BlockType.empty) [Wasm.Binary.Instr.unreachable] none,
                          Wasm.Binary.Instr.globalGet 3,
                          Wasm.Binary.Instr.i64Const 1,
                          Wasm.Binary.Instr.i64Add,
                          Wasm.Binary.Instr.globalSet 3,
                          Wasm.Binary.Instr.localGet 0,
                          Wasm.Binary.Instr.i64Const 40,
                          Wasm.Binary.Instr.i64Sub,
                          Wasm.Binary.Instr.i32WrapI64,
                          Wasm.Binary.Instr.localGet 1,
                          Wasm.Binary.Instr.i64Const 1,
                          Wasm.Binary.Instr.i64Add,
                          Wasm.Binary.Instr.i64Store { align := 3, offset := 0 }]
                         none,
                       Wasm.Binary.Instr.localGet 0] },
            { locals := [{ count := 8, type := Wasm.Binary.ValType.i64 }],
              body := [Wasm.Binary.Instr.localGet 0,
                       Wasm.Binary.Instr.i64Const 0,
                       Wasm.Binary.Instr.i64Eq,
                       Wasm.Binary.Instr.iff (Wasm.Binary.BlockType.empty) [Wasm.Binary.Instr.ret] none,
                       Wasm.Binary.Instr.localGet 0,
                       Wasm.Binary.Instr.i64Const 48,
                       Wasm.Binary.Instr.i64Sub,
                       Wasm.Binary.Instr.i32WrapI64,
                       Wasm.Binary.Instr.i64Load { align := 3, offset := 0 },
                       Wasm.Binary.Instr.i64Const 5501223100278326855,
                       Wasm.Binary.Instr.i64Ne,
                       Wasm.Binary.Instr.iff (Wasm.Binary.BlockType.empty) [Wasm.Binary.Instr.unreachable] none,
                       Wasm.Binary.Instr.localGet 0,
                       Wasm.Binary.Instr.i64Const 40,
                       Wasm.Binary.Instr.i64Sub,
                       Wasm.Binary.Instr.i32WrapI64,
                       Wasm.Binary.Instr.i64Load { align := 3, offset := 0 },
                       Wasm.Binary.Instr.localSet 1,
                       Wasm.Binary.Instr.localGet 1,
                       Wasm.Binary.Instr.i64Const 0,
                       Wasm.Binary.Instr.i64Eq,
                       Wasm.Binary.Instr.iff (Wasm.Binary.BlockType.empty) [Wasm.Binary.Instr.unreachable] none,
                       Wasm.Binary.Instr.globalGet 4,
                       Wasm.Binary.Instr.i64Const 1,
                       Wasm.Binary.Instr.i64Add,
                       Wasm.Binary.Instr.globalSet 4,
                       Wasm.Binary.Instr.i64Const 1,
                       Wasm.Binary.Instr.localGet 1,
                       Wasm.Binary.Instr.i64LtU,
                       Wasm.Binary.Instr.iff
                         (Wasm.Binary.BlockType.empty)
                         [Wasm.Binary.Instr.localGet 0,
                          Wasm.Binary.Instr.i64Const 40,
                          Wasm.Binary.Instr.i64Sub,
                          Wasm.Binary.Instr.i32WrapI64,
                          Wasm.Binary.Instr.localGet 1,
                          Wasm.Binary.Instr.i64Const 1,
                          Wasm.Binary.Instr.i64Sub,
                          Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
                          Wasm.Binary.Instr.ret]
                         none,
                       Wasm.Binary.Instr.localGet 0,
                       Wasm.Binary.Instr.i64Const 24,
                       Wasm.Binary.Instr.i64Sub,
                       Wasm.Binary.Instr.i32WrapI64,
                       Wasm.Binary.Instr.i64Load { align := 3, offset := 0 },
                       Wasm.Binary.Instr.localSet 2,
                       Wasm.Binary.Instr.localGet 2,
                       Wasm.Binary.Instr.i64Const 1,
                       Wasm.Binary.Instr.i64Eq,
                       Wasm.Binary.Instr.iff
                         (Wasm.Binary.BlockType.empty)
                         [Wasm.Binary.Instr.localGet 0,
                          Wasm.Binary.Instr.i64Const 16,
                          Wasm.Binary.Instr.i64Sub,
                          Wasm.Binary.Instr.i32WrapI64,
                          Wasm.Binary.Instr.i64Load { align := 3, offset := 0 },
                          Wasm.Binary.Instr.localSet 3,
                          Wasm.Binary.Instr.localGet 0,
                          Wasm.Binary.Instr.i64Const 8,
                          Wasm.Binary.Instr.i64Sub,
                          Wasm.Binary.Instr.i32WrapI64,
                          Wasm.Binary.Instr.i64Load { align := 3, offset := 0 },
                          Wasm.Binary.Instr.localSet 5,
                          Wasm.Binary.Instr.i64Const 0,
                          Wasm.Binary.Instr.localSet 6,
                          Wasm.Binary.Instr.block
                            (Wasm.Binary.BlockType.empty)
                            [Wasm.Binary.Instr.loop
                               (Wasm.Binary.BlockType.empty)
                               [Wasm.Binary.Instr.localGet 6,
                                Wasm.Binary.Instr.localGet 3,
                                Wasm.Binary.Instr.i64GeU,
                                Wasm.Binary.Instr.brIf 1,
                                Wasm.Binary.Instr.localGet 5,
                                Wasm.Binary.Instr.localGet 6,
                                Wasm.Binary.Instr.i64ShrU,
                                Wasm.Binary.Instr.i64Const 1,
                                Wasm.Binary.Instr.i64And,
                                Wasm.Binary.Instr.i64Const 0,
                                Wasm.Binary.Instr.i64Ne,
                                Wasm.Binary.Instr.iff
                                  (Wasm.Binary.BlockType.empty)
                                  [Wasm.Binary.Instr.localGet 0,
                                   Wasm.Binary.Instr.localGet 6,
                                   Wasm.Binary.Instr.i64Const 8,
                                   Wasm.Binary.Instr.i64Mul,
                                   Wasm.Binary.Instr.i64Add,
                                   Wasm.Binary.Instr.i32WrapI64,
                                   Wasm.Binary.Instr.i64Load { align := 3, offset := 0 },
                                   Wasm.Binary.Instr.localSet 8,
                                   Wasm.Binary.Instr.localGet 8,
                                   Wasm.Binary.Instr.call 4]
                                  none,
                                Wasm.Binary.Instr.localGet 6,
                                Wasm.Binary.Instr.i64Const 1,
                                Wasm.Binary.Instr.i64Add,
                                Wasm.Binary.Instr.localSet 6,
                                Wasm.Binary.Instr.br 0]]]
                         none,
                       Wasm.Binary.Instr.localGet 2,
                       Wasm.Binary.Instr.i64Const 2,
                       Wasm.Binary.Instr.i64Eq,
                       Wasm.Binary.Instr.iff
                         (Wasm.Binary.BlockType.empty)
                         [Wasm.Binary.Instr.localGet 0,
                          Wasm.Binary.Instr.i32WrapI64,
                          Wasm.Binary.Instr.i64Load { align := 3, offset := 0 },
                          Wasm.Binary.Instr.localSet 3,
                          Wasm.Binary.Instr.localGet 0,
                          Wasm.Binary.Instr.i64Const 16,
                          Wasm.Binary.Instr.i64Sub,
                          Wasm.Binary.Instr.i32WrapI64,
                          Wasm.Binary.Instr.i64Load { align := 3, offset := 0 },
                          Wasm.Binary.Instr.localSet 4,
                          Wasm.Binary.Instr.localGet 0,
                          Wasm.Binary.Instr.i64Const 8,
                          Wasm.Binary.Instr.i64Sub,
                          Wasm.Binary.Instr.i32WrapI64,
                          Wasm.Binary.Instr.i64Load { align := 3, offset := 0 },
                          Wasm.Binary.Instr.localSet 5,
                          Wasm.Binary.Instr.i64Const 0,
                          Wasm.Binary.Instr.localSet 7,
                          Wasm.Binary.Instr.block
                            (Wasm.Binary.BlockType.empty)
                            [Wasm.Binary.Instr.loop
                               (Wasm.Binary.BlockType.empty)
                               [Wasm.Binary.Instr.localGet 7,
                                Wasm.Binary.Instr.localGet 3,
                                Wasm.Binary.Instr.i64GeU,
                                Wasm.Binary.Instr.brIf 1,
                                Wasm.Binary.Instr.i64Const 0,
                                Wasm.Binary.Instr.localSet 6,
                                Wasm.Binary.Instr.block
                                  (Wasm.Binary.BlockType.empty)
                                  [Wasm.Binary.Instr.loop
                                     (Wasm.Binary.BlockType.empty)
                                     [Wasm.Binary.Instr.localGet 6,
                                      Wasm.Binary.Instr.localGet 4,
                                      Wasm.Binary.Instr.i64GeU,
                                      Wasm.Binary.Instr.brIf 1,
                                      Wasm.Binary.Instr.localGet 5,
                                      Wasm.Binary.Instr.localGet 6,
                                      Wasm.Binary.Instr.i64ShrU,
                                      Wasm.Binary.Instr.i64Const 1,
                                      Wasm.Binary.Instr.i64And,
                                      Wasm.Binary.Instr.i64Const 0,
                                      Wasm.Binary.Instr.i64Ne,
                                      Wasm.Binary.Instr.iff
                                        (Wasm.Binary.BlockType.empty)
                                        [Wasm.Binary.Instr.localGet 0,
                                         Wasm.Binary.Instr.i64Const 8,
                                         Wasm.Binary.Instr.i64Add,
                                         Wasm.Binary.Instr.localGet 7,
                                         Wasm.Binary.Instr.localGet 4,
                                         Wasm.Binary.Instr.i64Mul,
                                         Wasm.Binary.Instr.localGet 6,
                                         Wasm.Binary.Instr.i64Add,
                                         Wasm.Binary.Instr.i64Const 8,
                                         Wasm.Binary.Instr.i64Mul,
                                         Wasm.Binary.Instr.i64Add,
                                         Wasm.Binary.Instr.i32WrapI64,
                                         Wasm.Binary.Instr.i64Load { align := 3, offset := 0 },
                                         Wasm.Binary.Instr.localSet 8,
                                         Wasm.Binary.Instr.localGet 8,
                                         Wasm.Binary.Instr.call 4]
                                        none,
                                      Wasm.Binary.Instr.localGet 6,
                                      Wasm.Binary.Instr.i64Const 1,
                                      Wasm.Binary.Instr.i64Add,
                                      Wasm.Binary.Instr.localSet 6,
                                      Wasm.Binary.Instr.br 0]],
                                Wasm.Binary.Instr.localGet 7,
                                Wasm.Binary.Instr.i64Const 1,
                                Wasm.Binary.Instr.i64Add,
                                Wasm.Binary.Instr.localSet 7,
                                Wasm.Binary.Instr.br 0]]]
                         none,
                       Wasm.Binary.Instr.globalGet 5,
                       Wasm.Binary.Instr.i64Const 1,
                       Wasm.Binary.Instr.i64Add,
                       Wasm.Binary.Instr.globalSet 5,
                       Wasm.Binary.Instr.localGet 0,
                       Wasm.Binary.Instr.i64Const 40,
                       Wasm.Binary.Instr.i64Sub,
                       Wasm.Binary.Instr.i32WrapI64,
                       Wasm.Binary.Instr.i64Const 0,
                       Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
                       Wasm.Binary.Instr.localGet 0,
                       Wasm.Binary.Instr.i64Const 8,
                       Wasm.Binary.Instr.i64Sub,
                       Wasm.Binary.Instr.i32WrapI64,
                       Wasm.Binary.Instr.globalGet 1,
                       Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
                       Wasm.Binary.Instr.localGet 0,
                       Wasm.Binary.Instr.globalSet 1] }] }

end Project.EulerRusanov.Artifact.Cache
