import Project.Correct.Scalar64.Module
import LeanExe.Correct.Scalar64.Source
import Project.Artifact.Binary.Evidence
import Project.Artifact.Binary.Proof.Decode
import Project.Artifact.Binary.Proof.Validate

namespace Project.Correct.Scalar64
open Wasm
open Project.ProofKit.ScalarTransition

/-- A translation certificate names the original Lean function, its independent
core, the entire scalar IR module, the ABI, and the universal IR execution proof.
The source and IR proofs may be generated by untrusted tools. -/
structure Certificate (Input : Type) (args : Input → List UInt64) (source : Input → UInt64) where
  core : LeanExe.TypeSafety.Program
  signatures : LeanExe.TypeSafety.Signatures
  coreEntry : Nat
  sourceProof : LeanExe.Correct.Scalar64.SourceCertificate Input args source core signatures coreEntry
  functions : List Function
  entry : Nat
  exportName : String
  function : Function
  found : functions[entry]? = some function
  arity : function.arity = sourceProof.arity
  admitted : checkModule functions entry = true
  lowering : ∀ input, ∃ afterBody afterResult,
    Executes functions function.scratch function.body (function.initial (args input)) afterBody ∧
    function.result.eval function.scratch afterBody = some (source input, afterResult)

def Certificate.module (certificate : Certificate Input args source) : Module :=
  assemble certificate.functions certificate.exportName certificate.entry

theorem Certificate.correct (certificate : Certificate Input args source) (input : Input)
    (env : HostEnv α) (store : Store α) :
    TerminatesWith env certificate.module certificate.entry store
      ((args input).map Value.i64).reverse
      (fun final values => final = store ∧ values = [.i64 (source input)]) := by
  obtain ⟨afterBody, afterResult, bodyRun, resultRun⟩ := certificate.lowering input
  have implemented := assemble_implements (functions := certificate.functions)
    (exportName := certificate.exportName) (entry := certificate.entry)
  have found := implemented.2 certificate.entry certificate.function certificate.found
  have arity : ((args input).map Value.i64).reverse.length =
      (certificate.function.lower certificate.entry).numParams := by
    simpa [Function.lower, Wasm.Function.numParams, certificate.arity] using
      certificate.sourceProof.argsLength input
  apply terminates_of_body (by simp [Certificate.module, assemble])
    (by simpa [Certificate.module, assemble] using found) arity
  rw [List.reverse_reverse, initial_frame]
  change wp certificate.module (certificate.function.body.lower certificate.function.scratch ++
    certificate.function.result.lower certificate.function.scratch) _ store _ env
  apply Executes.lower_spec bodyRun [] certificate.module implemented env store _ _
  rw [← List.append_nil (certificate.function.result.lower certificate.function.scratch)]
  apply Expr.lower_spec certificate.function.result certificate.function.scratch
    afterBody afterResult (source input) [] certificate.module env store [] _ resultRun
  simp [wp_simp, State.toLocals, ScalarType.value, Function.lower]

/-- Exact closure includes decoding, validation, and equality of the full module. -/
def Artifact (certificate : Certificate Input args source) (bytes : ByteArray) : Prop :=
  Wasm.Binary.verifiedModule? bytes = some certificate.module

/-- Small, separately checked equalities avoid reducing the decoder and the
entire compiler in the same kernel conversion problem. -/
theorem Artifact.of_parts (certificate : Certificate Input args source)
    (decoded : Wasm.Binary.decode bytes = .ok raw)
    (valid : Wasm.Binary.Validator.validateRaw raw = .ok ())
    (same : Wasm.Binary.Translation.module raw = certificate.module) :
    Artifact certificate bytes := by
  simp [Artifact, Wasm.Binary.verifiedModule?, decoded, Except.toOption,
    Wasm.Binary.validate, valid, Wasm.Binary.ValidatedModule.toTalos, same]

theorem Artifact.valid_and_correct (certificate : Certificate Input args source)
    (closed : Artifact certificate bytes) :
    ∃ raw validated,
      Wasm.Binary.decode bytes = .ok raw ∧
      Wasm.Binary.Grammar.Encodes bytes raw ∧
      Wasm.Binary.validate raw = .ok validated ∧
      Wasm.Binary.CoreValid raw ∧
      validated.toTalos = certificate.module ∧
      ∀ input (env : HostEnv α) (store : Store α),
        LeanExe.Correct.Scalar64.Runs certificate.core certificate.sourceProof.body
          (LeanExe.Correct.Scalar64.encodeArgs (args input))
          (LeanExe.Correct.Scalar64.encodeWord (source input)) ∧
        TerminatesWith env validated.toTalos certificate.entry store
          ((args input).map Value.i64).reverse
          (fun final values => final = store ∧ values = [.i64 (source input)]) := by
  have present : (Wasm.Binary.verifiedModule? bytes).isSome = true := by rw [closed]; rfl
  obtain ⟨raw, validated, decoded, valid, same⟩ := Wasm.Binary.evidenceOfIsSome bytes present
  have moduleEq : validated.toTalos = certificate.module := Option.some.inj (same.symm.trans closed)
  refine ⟨raw, validated, decoded, Wasm.Binary.Proof.decode_sound decoded, valid,
    Wasm.Binary.Proof.validate_sound valid, moduleEq, ?_⟩
  intro input env store
  exact ⟨certificate.sourceProof.computes input, moduleEq.symm ▸ certificate.correct input env store⟩

end Project.Correct.Scalar64
