import Project.ByteIO.Binary

namespace Project.ByteIO.Artifact

def raw : Binary.Raw :=
{ core := { sections := [Wasm.Binary.SectionId.type,
                         Wasm.Binary.SectionId.function,
                         Wasm.Binary.SectionId.memory,
                         Wasm.Binary.SectionId.global,
                         Wasm.Binary.SectionId.export,
                         Wasm.Binary.SectionId.code],
            types := [{ params := [Wasm.Binary.ValType.i32,
                                   Wasm.Binary.ValType.i32,
                                   Wasm.Binary.ValType.i32,
                                   Wasm.Binary.ValType.i32],
                        results := [Wasm.Binary.ValType.i32] },
                      { params := [Wasm.Binary.ValType.i32, Wasm.Binary.ValType.i32],
                        results := [Wasm.Binary.ValType.i32] },
                      { params := [Wasm.Binary.ValType.i32, Wasm.Binary.ValType.i64, Wasm.Binary.ValType.i32],
                        results := [Wasm.Binary.ValType.i32] },
                      { params := [Wasm.Binary.ValType.i32], results := [] },
                      { params := [], results := [Wasm.Binary.ValType.i64] },
                      { params := [Wasm.Binary.ValType.i64, Wasm.Binary.ValType.i64],
                        results := [Wasm.Binary.ValType.i64,
                                    Wasm.Binary.ValType.i64,
                                    Wasm.Binary.ValType.i64,
                                    Wasm.Binary.ValType.i64,
                                    Wasm.Binary.ValType.i64] },
                      { params := [Wasm.Binary.ValType.i64,
                                   Wasm.Binary.ValType.i64,
                                   Wasm.Binary.ValType.i64,
                                   Wasm.Binary.ValType.i64],
                        results := [Wasm.Binary.ValType.i64] },
                      { params := [], results := [] },
                      { params := [Wasm.Binary.ValType.i64], results := [] },
                      { params := [Wasm.Binary.ValType.i64, Wasm.Binary.ValType.i64],
                        results := [Wasm.Binary.ValType.i64] }],
            functionTypeIndices := [4, 5, 6, 7, 8, 9],
            memories := [{ limits := { min := 16, max := none } }],
            globals := [{ type := { type := Wasm.Binary.ValType.i64, mutability := Wasm.Binary.Mutability.mutable },
                          init := Wasm.Binary.ConstExpr.i64Const 4096 },
                        { type := { type := Wasm.Binary.ValType.i64, mutability := Wasm.Binary.Mutability.mutable },
                          init := Wasm.Binary.ConstExpr.i64Const 0 },
                        { type := { type := Wasm.Binary.ValType.i64, mutability := Wasm.Binary.Mutability.mutable },
                          init := Wasm.Binary.ConstExpr.i64Const 0 },
                        { type := { type := Wasm.Binary.ValType.i64, mutability := Wasm.Binary.Mutability.mutable },
                          init := Wasm.Binary.ConstExpr.i64Const 0 },
                        { type := { type := Wasm.Binary.ValType.i64, mutability := Wasm.Binary.Mutability.mutable },
                          init := Wasm.Binary.ConstExpr.i64Const 0 },
                        { type := { type := Wasm.Binary.ValType.i64, mutability := Wasm.Binary.Mutability.mutable },
                          init := Wasm.Binary.ConstExpr.i64Const 0 }],
            exports := [{ name := { bytes := [109, 101, 109, 111, 114, 121], text := "memory" },
                          desc := Wasm.Binary.ExportDesc.memory 0 },
                        { name := { bytes := [95, 115, 116, 97, 114, 116], text := "_start" },
                          desc := Wasm.Binary.ExportDesc.func 9 }],
            codes := [{ locals := [{ count := 18, type := Wasm.Binary.ValType.i64 }],
                        body := [Wasm.Binary.Instr.i64Const 4,
                                 Wasm.Binary.Instr.localSet 0,
                                 Wasm.Binary.Instr.i64Const 1000000000,
                                 Wasm.Binary.Instr.localSet 1,
                                 Wasm.Binary.Instr.localGet 0,
                                 Wasm.Binary.Instr.localGet 1,
                                 Wasm.Binary.Instr.call 7,
                                 Wasm.Binary.Instr.localSet 6,
                                 Wasm.Binary.Instr.localSet 5,
                                 Wasm.Binary.Instr.localSet 4,
                                 Wasm.Binary.Instr.localSet 3,
                                 Wasm.Binary.Instr.localSet 2,
                                 Wasm.Binary.Instr.localGet 2,
                                 Wasm.Binary.Instr.localSet 7,
                                 Wasm.Binary.Instr.localGet 3,
                                 Wasm.Binary.Instr.localSet 8,
                                 Wasm.Binary.Instr.localGet 4,
                                 Wasm.Binary.Instr.localSet 9,
                                 Wasm.Binary.Instr.localGet 5,
                                 Wasm.Binary.Instr.localSet 10,
                                 Wasm.Binary.Instr.localGet 6,
                                 Wasm.Binary.Instr.localSet 11,
                                 Wasm.Binary.Instr.localGet 7,
                                 Wasm.Binary.Instr.i64Const 0,
                                 Wasm.Binary.Instr.i64Eq,
                                 Wasm.Binary.Instr.iff
                                   (Wasm.Binary.BlockType.empty)
                                   [Wasm.Binary.Instr.localGet 8, Wasm.Binary.Instr.localSet 17]
                                   (some [Wasm.Binary.Instr.localGet 9,
                                     Wasm.Binary.Instr.localSet 12,
                                     Wasm.Binary.Instr.localGet 10,
                                     Wasm.Binary.Instr.localSet 13,
                                     Wasm.Binary.Instr.localGet 11,
                                     Wasm.Binary.Instr.localSet 14,
                                     Wasm.Binary.Instr.i64Const 1000000000,
                                     Wasm.Binary.Instr.localSet 15,
                                     Wasm.Binary.Instr.localGet 12,
                                     Wasm.Binary.Instr.localGet 13,
                                     Wasm.Binary.Instr.localGet 14,
                                     Wasm.Binary.Instr.localGet 15,
                                     Wasm.Binary.Instr.call 8,
                                     Wasm.Binary.Instr.localSet 16,
                                     Wasm.Binary.Instr.localGet 16,
                                     Wasm.Binary.Instr.localSet 17]),
                                 Wasm.Binary.Instr.localGet 4,
                                 Wasm.Binary.Instr.i64Const 0,
                                 Wasm.Binary.Instr.i64Eq,
                                 Wasm.Binary.Instr.i32Eqz,
                                 Wasm.Binary.Instr.iff
                                   (Wasm.Binary.BlockType.empty)
                                   [Wasm.Binary.Instr.localGet 4, Wasm.Binary.Instr.call 10]
                                   (some []),
                                 Wasm.Binary.Instr.localGet 17] },
                      { locals := [{ count := 10, type := Wasm.Binary.ValType.i64 }],
                        body := [Wasm.Binary.Instr.localGet 0,
                                 Wasm.Binary.Instr.i64Eqz,
                                 Wasm.Binary.Instr.iff
                                   (Wasm.Binary.BlockType.empty)
                                   [Wasm.Binary.Instr.i64Const 28,
                                    Wasm.Binary.Instr.localSet 2,
                                    Wasm.Binary.Instr.localGet 4,
                                    Wasm.Binary.Instr.call 10,
                                    Wasm.Binary.Instr.i64Const 0,
                                    Wasm.Binary.Instr.localGet 2,
                                    Wasm.Binary.Instr.i64Const 0,
                                    Wasm.Binary.Instr.i64Const 0,
                                    Wasm.Binary.Instr.i64Const 0,
                                    Wasm.Binary.Instr.ret]
                                   none,
                                 Wasm.Binary.Instr.i64Const 4294967295,
                                 Wasm.Binary.Instr.localGet 0,
                                 Wasm.Binary.Instr.i64LtU,
                                 Wasm.Binary.Instr.iff
                                   (Wasm.Binary.BlockType.empty)
                                   [Wasm.Binary.Instr.i64Const 28,
                                    Wasm.Binary.Instr.localSet 2,
                                    Wasm.Binary.Instr.localGet 4,
                                    Wasm.Binary.Instr.call 10,
                                    Wasm.Binary.Instr.i64Const 0,
                                    Wasm.Binary.Instr.localGet 2,
                                    Wasm.Binary.Instr.i64Const 0,
                                    Wasm.Binary.Instr.i64Const 0,
                                    Wasm.Binary.Instr.i64Const 0,
                                    Wasm.Binary.Instr.ret]
                                   none,
                                 Wasm.Binary.Instr.i32Const 1,
                                 Wasm.Binary.Instr.i64Const 0,
                                 Wasm.Binary.Instr.i32Const 16,
                                 Wasm.Binary.Instr.call 3,
                                 Wasm.Binary.Instr.i64ExtendI32U,
                                 Wasm.Binary.Instr.localTee 2,
                                 Wasm.Binary.Instr.i64Eqz,
                                 Wasm.Binary.Instr.iff
                                   (Wasm.Binary.BlockType.empty)
                                   []
                                   (some [Wasm.Binary.Instr.localGet 4,
                                     Wasm.Binary.Instr.call 10,
                                     Wasm.Binary.Instr.i64Const 0,
                                     Wasm.Binary.Instr.localGet 2,
                                     Wasm.Binary.Instr.i64Const 0,
                                     Wasm.Binary.Instr.i64Const 0,
                                     Wasm.Binary.Instr.i64Const 0,
                                     Wasm.Binary.Instr.ret]),
                                 Wasm.Binary.Instr.i32Const 16,
                                 Wasm.Binary.Instr.i64Load { align := 3, offset := 0 },
                                 Wasm.Binary.Instr.localGet 1,
                                 Wasm.Binary.Instr.i64Add,
                                 Wasm.Binary.Instr.localSet 3,
                                 Wasm.Binary.Instr.localGet 3,
                                 Wasm.Binary.Instr.i32Const 16,
                                 Wasm.Binary.Instr.i64Load { align := 3, offset := 0 },
                                 Wasm.Binary.Instr.i64LtU,
                                 Wasm.Binary.Instr.iff
                                   (Wasm.Binary.BlockType.empty)
                                   [Wasm.Binary.Instr.i64Const (-1), Wasm.Binary.Instr.localSet 3]
                                   none,
                                 Wasm.Binary.Instr.i32Const 0,
                                 Wasm.Binary.Instr.i32Const 4,
                                 Wasm.Binary.Instr.call 2,
                                 Wasm.Binary.Instr.i64ExtendI32U,
                                 Wasm.Binary.Instr.localTee 2,
                                 Wasm.Binary.Instr.i64Eqz,
                                 Wasm.Binary.Instr.iff
                                   (Wasm.Binary.BlockType.empty)
                                   []
                                   (some [Wasm.Binary.Instr.localGet 4,
                                     Wasm.Binary.Instr.call 10,
                                     Wasm.Binary.Instr.i64Const 0,
                                     Wasm.Binary.Instr.localGet 2,
                                     Wasm.Binary.Instr.i64Const 0,
                                     Wasm.Binary.Instr.i64Const 0,
                                     Wasm.Binary.Instr.i64Const 0,
                                     Wasm.Binary.Instr.ret]),
                                 Wasm.Binary.Instr.localGet 0,
                                 Wasm.Binary.Instr.i64Const 7,
                                 Wasm.Binary.Instr.i64Add,
                                 Wasm.Binary.Instr.i64Const 8,
                                 Wasm.Binary.Instr.i64DivU,
                                 Wasm.Binary.Instr.i64Const 8,
                                 Wasm.Binary.Instr.i64Mul,
                                 Wasm.Binary.Instr.localSet 6,
                                 Wasm.Binary.Instr.localGet 6,
                                 Wasm.Binary.Instr.i64Const 8,
                                 Wasm.Binary.Instr.i64LtU,
                                 Wasm.Binary.Instr.iff
                                   (Wasm.Binary.BlockType.empty)
                                   [Wasm.Binary.Instr.i64Const 8, Wasm.Binary.Instr.localSet 6]
                                   none,
                                 Wasm.Binary.Instr.i64Const 0,
                                 Wasm.Binary.Instr.localSet 11,
                                 Wasm.Binary.Instr.i64Const 0,
                                 Wasm.Binary.Instr.localSet 7,
                                 Wasm.Binary.Instr.globalGet 1,
                                 Wasm.Binary.Instr.localSet 8,
                                 Wasm.Binary.Instr.block
                                   (Wasm.Binary.BlockType.empty)
                                   [Wasm.Binary.Instr.loop
                                      (Wasm.Binary.BlockType.empty)
                                      [Wasm.Binary.Instr.localGet 8,
                                       Wasm.Binary.Instr.i64Const 0,
                                       Wasm.Binary.Instr.i64Eq,
                                       Wasm.Binary.Instr.brIf 1,
                                       Wasm.Binary.Instr.localGet 11,
                                       Wasm.Binary.Instr.i64Const 0,
                                       Wasm.Binary.Instr.i64Ne,
                                       Wasm.Binary.Instr.brIf 1,
                                       Wasm.Binary.Instr.localGet 8,
                                       Wasm.Binary.Instr.i64Const 32,
                                       Wasm.Binary.Instr.i64Sub,
                                       Wasm.Binary.Instr.i32WrapI64,
                                       Wasm.Binary.Instr.i64Load { align := 3, offset := 0 },
                                       Wasm.Binary.Instr.localSet 9,
                                       Wasm.Binary.Instr.localGet 8,
                                       Wasm.Binary.Instr.i64Const 8,
                                       Wasm.Binary.Instr.i64Sub,
                                       Wasm.Binary.Instr.i32WrapI64,
                                       Wasm.Binary.Instr.i64Load { align := 3, offset := 0 },
                                       Wasm.Binary.Instr.localSet 10,
                                       Wasm.Binary.Instr.localGet 9,
                                       Wasm.Binary.Instr.localGet 6,
                                       Wasm.Binary.Instr.i64GeU,
                                       Wasm.Binary.Instr.iff
                                         (Wasm.Binary.BlockType.empty)
                                         [Wasm.Binary.Instr.localGet 7,
                                          Wasm.Binary.Instr.i64Const 0,
                                          Wasm.Binary.Instr.i64Eq,
                                          Wasm.Binary.Instr.iff
                                            (Wasm.Binary.BlockType.empty)
                                            [Wasm.Binary.Instr.localGet 10, Wasm.Binary.Instr.globalSet 1]
                                            (some [Wasm.Binary.Instr.localGet 7,
                                              Wasm.Binary.Instr.i64Const 8,
                                              Wasm.Binary.Instr.i64Sub,
                                              Wasm.Binary.Instr.i32WrapI64,
                                              Wasm.Binary.Instr.localGet 10,
                                              Wasm.Binary.Instr.i64Store { align := 3, offset := 0 }]),
                                          Wasm.Binary.Instr.localGet 8,
                                          Wasm.Binary.Instr.i64Const 48,
                                          Wasm.Binary.Instr.i64Sub,
                                          Wasm.Binary.Instr.i32WrapI64,
                                          Wasm.Binary.Instr.i64Const 5501223100278326855,
                                          Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
                                          Wasm.Binary.Instr.localGet 8,
                                          Wasm.Binary.Instr.i64Const 40,
                                          Wasm.Binary.Instr.i64Sub,
                                          Wasm.Binary.Instr.i32WrapI64,
                                          Wasm.Binary.Instr.i64Const 1,
                                          Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
                                          Wasm.Binary.Instr.localGet 8,
                                          Wasm.Binary.Instr.i64Const 32,
                                          Wasm.Binary.Instr.i64Sub,
                                          Wasm.Binary.Instr.i32WrapI64,
                                          Wasm.Binary.Instr.localGet 9,
                                          Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
                                          Wasm.Binary.Instr.localGet 8,
                                          Wasm.Binary.Instr.i64Const 24,
                                          Wasm.Binary.Instr.i64Sub,
                                          Wasm.Binary.Instr.i32WrapI64,
                                          Wasm.Binary.Instr.i64Const 0,
                                          Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
                                          Wasm.Binary.Instr.localGet 8,
                                          Wasm.Binary.Instr.i64Const 16,
                                          Wasm.Binary.Instr.i64Sub,
                                          Wasm.Binary.Instr.i32WrapI64,
                                          Wasm.Binary.Instr.i64Const 0,
                                          Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
                                          Wasm.Binary.Instr.localGet 8,
                                          Wasm.Binary.Instr.i64Const 8,
                                          Wasm.Binary.Instr.i64Sub,
                                          Wasm.Binary.Instr.i32WrapI64,
                                          Wasm.Binary.Instr.i64Const 0,
                                          Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
                                          Wasm.Binary.Instr.localGet 8,
                                          Wasm.Binary.Instr.localSet 11]
                                         (some [Wasm.Binary.Instr.localGet 8,
                                           Wasm.Binary.Instr.localSet 7,
                                           Wasm.Binary.Instr.localGet 10,
                                           Wasm.Binary.Instr.localSet 8]),
                                       Wasm.Binary.Instr.br 0]],
                                 Wasm.Binary.Instr.localGet 11,
                                 Wasm.Binary.Instr.i64Const 0,
                                 Wasm.Binary.Instr.i64Eq,
                                 Wasm.Binary.Instr.iff
                                   (Wasm.Binary.BlockType.empty)
                                   [Wasm.Binary.Instr.globalGet 0,
                                    Wasm.Binary.Instr.i64Const 48,
                                    Wasm.Binary.Instr.i64Add,
                                    Wasm.Binary.Instr.localGet 6,
                                    Wasm.Binary.Instr.i64Add,
                                    Wasm.Binary.Instr.localTee 9,
                                    Wasm.Binary.Instr.globalGet 0,
                                    Wasm.Binary.Instr.i64LtU,
                                    Wasm.Binary.Instr.iff
                                      (Wasm.Binary.BlockType.empty)
                                      [Wasm.Binary.Instr.unreachable]
                                      none,
                                    Wasm.Binary.Instr.localGet 9,
                                    Wasm.Binary.Instr.i64Const 1,
                                    Wasm.Binary.Instr.i64Sub,
                                    Wasm.Binary.Instr.i64Const 65536,
                                    Wasm.Binary.Instr.i64DivU,
                                    Wasm.Binary.Instr.i64Const 1,
                                    Wasm.Binary.Instr.i64Add,
                                    Wasm.Binary.Instr.localSet 10,
                                    Wasm.Binary.Instr.memorySize 0,
                                    Wasm.Binary.Instr.i64ExtendI32U,
                                    Wasm.Binary.Instr.localGet 10,
                                    Wasm.Binary.Instr.i64LtU,
                                    Wasm.Binary.Instr.iff
                                      (Wasm.Binary.BlockType.empty)
                                      [Wasm.Binary.Instr.localGet 10,
                                       Wasm.Binary.Instr.memorySize 0,
                                       Wasm.Binary.Instr.i64ExtendI32U,
                                       Wasm.Binary.Instr.i64Sub,
                                       Wasm.Binary.Instr.i32WrapI64,
                                       Wasm.Binary.Instr.memoryGrow 0,
                                       Wasm.Binary.Instr.i32Const (-1),
                                       Wasm.Binary.Instr.i32Eq,
                                       Wasm.Binary.Instr.iff
                                         (Wasm.Binary.BlockType.empty)
                                         [Wasm.Binary.Instr.unreachable]
                                         none]
                                      none,
                                    Wasm.Binary.Instr.globalGet 0,
                                    Wasm.Binary.Instr.i64Const 48,
                                    Wasm.Binary.Instr.i64Add,
                                    Wasm.Binary.Instr.localSet 11,
                                    Wasm.Binary.Instr.localGet 9,
                                    Wasm.Binary.Instr.globalSet 0,
                                    Wasm.Binary.Instr.localGet 11,
                                    Wasm.Binary.Instr.i64Const 48,
                                    Wasm.Binary.Instr.i64Sub,
                                    Wasm.Binary.Instr.i32WrapI64,
                                    Wasm.Binary.Instr.i64Const 5501223100278326855,
                                    Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
                                    Wasm.Binary.Instr.localGet 11,
                                    Wasm.Binary.Instr.i64Const 40,
                                    Wasm.Binary.Instr.i64Sub,
                                    Wasm.Binary.Instr.i32WrapI64,
                                    Wasm.Binary.Instr.i64Const 1,
                                    Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
                                    Wasm.Binary.Instr.localGet 11,
                                    Wasm.Binary.Instr.i64Const 32,
                                    Wasm.Binary.Instr.i64Sub,
                                    Wasm.Binary.Instr.i32WrapI64,
                                    Wasm.Binary.Instr.localGet 6,
                                    Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
                                    Wasm.Binary.Instr.localGet 11,
                                    Wasm.Binary.Instr.i64Const 24,
                                    Wasm.Binary.Instr.i64Sub,
                                    Wasm.Binary.Instr.i32WrapI64,
                                    Wasm.Binary.Instr.i64Const 0,
                                    Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
                                    Wasm.Binary.Instr.localGet 11,
                                    Wasm.Binary.Instr.i64Const 16,
                                    Wasm.Binary.Instr.i64Sub,
                                    Wasm.Binary.Instr.i32WrapI64,
                                    Wasm.Binary.Instr.i64Const 0,
                                    Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
                                    Wasm.Binary.Instr.localGet 11,
                                    Wasm.Binary.Instr.i64Const 8,
                                    Wasm.Binary.Instr.i64Sub,
                                    Wasm.Binary.Instr.i32WrapI64,
                                    Wasm.Binary.Instr.i64Const 0,
                                    Wasm.Binary.Instr.i64Store { align := 3, offset := 0 }]
                                   none,
                                 Wasm.Binary.Instr.globalGet 2,
                                 Wasm.Binary.Instr.i64Const 1,
                                 Wasm.Binary.Instr.i64Add,
                                 Wasm.Binary.Instr.globalSet 2,
                                 Wasm.Binary.Instr.localGet 11,
                                 Wasm.Binary.Instr.localSet 4,
                                 Wasm.Binary.Instr.loop
                                   (Wasm.Binary.BlockType.empty)
                                   [Wasm.Binary.Instr.i32Const 0,
                                    Wasm.Binary.Instr.localGet 4,
                                    Wasm.Binary.Instr.i32WrapI64,
                                    Wasm.Binary.Instr.i32Store { align := 2, offset := 0 },
                                    Wasm.Binary.Instr.i32Const 4,
                                    Wasm.Binary.Instr.localGet 0,
                                    Wasm.Binary.Instr.i32WrapI64,
                                    Wasm.Binary.Instr.i32Store { align := 2, offset := 0 },
                                    Wasm.Binary.Instr.i32Const 0,
                                    Wasm.Binary.Instr.i32Const 0,
                                    Wasm.Binary.Instr.i32Const 1,
                                    Wasm.Binary.Instr.i32Const 8,
                                    Wasm.Binary.Instr.call 0,
                                    Wasm.Binary.Instr.i64ExtendI32U,
                                    Wasm.Binary.Instr.localSet 2,
                                    Wasm.Binary.Instr.localGet 2,
                                    Wasm.Binary.Instr.i64Eqz,
                                    Wasm.Binary.Instr.iff
                                      (Wasm.Binary.BlockType.empty)
                                      [Wasm.Binary.Instr.i32Const 8,
                                       Wasm.Binary.Instr.i32Load { align := 2, offset := 0 },
                                       Wasm.Binary.Instr.i64ExtendI32U,
                                       Wasm.Binary.Instr.localSet 5,
                                       Wasm.Binary.Instr.localGet 0,
                                       Wasm.Binary.Instr.localGet 5,
                                       Wasm.Binary.Instr.i64LtU,
                                       Wasm.Binary.Instr.iff
                                         (Wasm.Binary.BlockType.empty)
                                         [Wasm.Binary.Instr.i64Const 29,
                                          Wasm.Binary.Instr.localSet 2,
                                          Wasm.Binary.Instr.localGet 4,
                                          Wasm.Binary.Instr.call 10,
                                          Wasm.Binary.Instr.i64Const 0,
                                          Wasm.Binary.Instr.localGet 2,
                                          Wasm.Binary.Instr.i64Const 0,
                                          Wasm.Binary.Instr.i64Const 0,
                                          Wasm.Binary.Instr.i64Const 0,
                                          Wasm.Binary.Instr.ret]
                                         none,
                                       Wasm.Binary.Instr.localGet 5,
                                       Wasm.Binary.Instr.i64Eqz,
                                       Wasm.Binary.Instr.iff
                                         (Wasm.Binary.BlockType.empty)
                                         [Wasm.Binary.Instr.localGet 4,
                                          Wasm.Binary.Instr.call 10,
                                          Wasm.Binary.Instr.i64Const 0,
                                          Wasm.Binary.Instr.localSet 4]
                                         none,
                                       Wasm.Binary.Instr.i64Const 1,
                                       Wasm.Binary.Instr.i64Const 0,
                                       Wasm.Binary.Instr.localGet 4,
                                       Wasm.Binary.Instr.localGet 4,
                                       Wasm.Binary.Instr.localGet 5,
                                       Wasm.Binary.Instr.ret]
                                      none,
                                    Wasm.Binary.Instr.localGet 2,
                                    Wasm.Binary.Instr.i64Const 6,
                                    Wasm.Binary.Instr.i64Eq,
                                    Wasm.Binary.Instr.iff
                                      (Wasm.Binary.BlockType.empty)
                                      []
                                      (some [Wasm.Binary.Instr.localGet 2,
                                        Wasm.Binary.Instr.i64Const 27,
                                        Wasm.Binary.Instr.i64Ne,
                                        Wasm.Binary.Instr.iff
                                          (Wasm.Binary.BlockType.empty)
                                          [Wasm.Binary.Instr.localGet 4,
                                           Wasm.Binary.Instr.call 10,
                                           Wasm.Binary.Instr.i64Const 0,
                                           Wasm.Binary.Instr.localGet 2,
                                           Wasm.Binary.Instr.i64Const 0,
                                           Wasm.Binary.Instr.i64Const 0,
                                           Wasm.Binary.Instr.i64Const 0,
                                           Wasm.Binary.Instr.ret]
                                          none]),
                                    Wasm.Binary.Instr.i64Const 1,
                                    Wasm.Binary.Instr.localGet 3,
                                    Wasm.Binary.Instr.call 11,
                                    Wasm.Binary.Instr.localTee 2,
                                    Wasm.Binary.Instr.i64Eqz,
                                    Wasm.Binary.Instr.iff
                                      (Wasm.Binary.BlockType.empty)
                                      []
                                      (some [Wasm.Binary.Instr.localGet 4,
                                        Wasm.Binary.Instr.call 10,
                                        Wasm.Binary.Instr.i64Const 0,
                                        Wasm.Binary.Instr.localGet 2,
                                        Wasm.Binary.Instr.i64Const 0,
                                        Wasm.Binary.Instr.i64Const 0,
                                        Wasm.Binary.Instr.i64Const 0,
                                        Wasm.Binary.Instr.ret]),
                                    Wasm.Binary.Instr.br 0],
                                 Wasm.Binary.Instr.unreachable] },
                      { locals := [{ count := 5, type := Wasm.Binary.ValType.i64 }],
                        body := [Wasm.Binary.Instr.localGet 2,
                                 Wasm.Binary.Instr.i64Eqz,
                                 Wasm.Binary.Instr.iff
                                   (Wasm.Binary.BlockType.empty)
                                   [Wasm.Binary.Instr.i64Const 0, Wasm.Binary.Instr.ret]
                                   none,
                                 Wasm.Binary.Instr.i32Const 1,
                                 Wasm.Binary.Instr.i64Const 0,
                                 Wasm.Binary.Instr.i32Const 16,
                                 Wasm.Binary.Instr.call 3,
                                 Wasm.Binary.Instr.i64ExtendI32U,
                                 Wasm.Binary.Instr.localTee 4,
                                 Wasm.Binary.Instr.i64Eqz,
                                 Wasm.Binary.Instr.iff
                                   (Wasm.Binary.BlockType.empty)
                                   []
                                   (some [Wasm.Binary.Instr.localGet 4, Wasm.Binary.Instr.ret]),
                                 Wasm.Binary.Instr.i32Const 16,
                                 Wasm.Binary.Instr.i64Load { align := 3, offset := 0 },
                                 Wasm.Binary.Instr.localGet 3,
                                 Wasm.Binary.Instr.i64Add,
                                 Wasm.Binary.Instr.localSet 5,
                                 Wasm.Binary.Instr.localGet 5,
                                 Wasm.Binary.Instr.i32Const 16,
                                 Wasm.Binary.Instr.i64Load { align := 3, offset := 0 },
                                 Wasm.Binary.Instr.i64LtU,
                                 Wasm.Binary.Instr.iff
                                   (Wasm.Binary.BlockType.empty)
                                   [Wasm.Binary.Instr.i64Const (-1), Wasm.Binary.Instr.localSet 5]
                                   none,
                                 Wasm.Binary.Instr.i32Const 1,
                                 Wasm.Binary.Instr.i32Const 4,
                                 Wasm.Binary.Instr.call 2,
                                 Wasm.Binary.Instr.i64ExtendI32U,
                                 Wasm.Binary.Instr.localTee 4,
                                 Wasm.Binary.Instr.i64Eqz,
                                 Wasm.Binary.Instr.iff
                                   (Wasm.Binary.BlockType.empty)
                                   []
                                   (some [Wasm.Binary.Instr.localGet 4, Wasm.Binary.Instr.ret]),
                                 Wasm.Binary.Instr.localGet 1,
                                 Wasm.Binary.Instr.localSet 6,
                                 Wasm.Binary.Instr.localGet 2,
                                 Wasm.Binary.Instr.localSet 7,
                                 Wasm.Binary.Instr.loop
                                   (Wasm.Binary.BlockType.empty)
                                   [Wasm.Binary.Instr.i32Const 0,
                                    Wasm.Binary.Instr.localGet 6,
                                    Wasm.Binary.Instr.i32WrapI64,
                                    Wasm.Binary.Instr.i32Store { align := 2, offset := 0 },
                                    Wasm.Binary.Instr.i32Const 4,
                                    Wasm.Binary.Instr.localGet 7,
                                    Wasm.Binary.Instr.i32WrapI64,
                                    Wasm.Binary.Instr.i32Store { align := 2, offset := 0 },
                                    Wasm.Binary.Instr.i32Const 1,
                                    Wasm.Binary.Instr.i32Const 0,
                                    Wasm.Binary.Instr.i32Const 1,
                                    Wasm.Binary.Instr.i32Const 8,
                                    Wasm.Binary.Instr.call 1,
                                    Wasm.Binary.Instr.i64ExtendI32U,
                                    Wasm.Binary.Instr.localSet 4,
                                    Wasm.Binary.Instr.localGet 4,
                                    Wasm.Binary.Instr.i64Eqz,
                                    Wasm.Binary.Instr.iff
                                      (Wasm.Binary.BlockType.empty)
                                      [Wasm.Binary.Instr.i32Const 8,
                                       Wasm.Binary.Instr.i32Load { align := 2, offset := 0 },
                                       Wasm.Binary.Instr.i64ExtendI32U,
                                       Wasm.Binary.Instr.localSet 8,
                                       Wasm.Binary.Instr.localGet 8,
                                       Wasm.Binary.Instr.i64Eqz,
                                       Wasm.Binary.Instr.iff
                                         (Wasm.Binary.BlockType.empty)
                                         [Wasm.Binary.Instr.i64Const 29,
                                          Wasm.Binary.Instr.localSet 4,
                                          Wasm.Binary.Instr.localGet 4,
                                          Wasm.Binary.Instr.ret]
                                         none,
                                       Wasm.Binary.Instr.localGet 7,
                                       Wasm.Binary.Instr.localGet 8,
                                       Wasm.Binary.Instr.i64LtU,
                                       Wasm.Binary.Instr.iff
                                         (Wasm.Binary.BlockType.empty)
                                         [Wasm.Binary.Instr.i64Const 29,
                                          Wasm.Binary.Instr.localSet 4,
                                          Wasm.Binary.Instr.localGet 4,
                                          Wasm.Binary.Instr.ret]
                                         none,
                                       Wasm.Binary.Instr.localGet 6,
                                       Wasm.Binary.Instr.localGet 8,
                                       Wasm.Binary.Instr.i64Add,
                                       Wasm.Binary.Instr.localSet 6,
                                       Wasm.Binary.Instr.localGet 7,
                                       Wasm.Binary.Instr.localGet 8,
                                       Wasm.Binary.Instr.i64Sub,
                                       Wasm.Binary.Instr.localTee 7,
                                       Wasm.Binary.Instr.i64Eqz,
                                       Wasm.Binary.Instr.iff
                                         (Wasm.Binary.BlockType.empty)
                                         [Wasm.Binary.Instr.i64Const 0, Wasm.Binary.Instr.ret]
                                         none,
                                       Wasm.Binary.Instr.i32Const 1,
                                       Wasm.Binary.Instr.i64Const 0,
                                       Wasm.Binary.Instr.i32Const 16,
                                       Wasm.Binary.Instr.call 3,
                                       Wasm.Binary.Instr.i64ExtendI32U,
                                       Wasm.Binary.Instr.localTee 4,
                                       Wasm.Binary.Instr.i64Eqz,
                                       Wasm.Binary.Instr.iff
                                         (Wasm.Binary.BlockType.empty)
                                         []
                                         (some [Wasm.Binary.Instr.localGet 4, Wasm.Binary.Instr.ret]),
                                       Wasm.Binary.Instr.i32Const 16,
                                       Wasm.Binary.Instr.i64Load { align := 3, offset := 0 },
                                       Wasm.Binary.Instr.localGet 5,
                                       Wasm.Binary.Instr.i64GeU,
                                       Wasm.Binary.Instr.iff
                                         (Wasm.Binary.BlockType.empty)
                                         [Wasm.Binary.Instr.i64Const 73,
                                          Wasm.Binary.Instr.localSet 4,
                                          Wasm.Binary.Instr.localGet 4,
                                          Wasm.Binary.Instr.ret]
                                         none,
                                       Wasm.Binary.Instr.br 1]
                                      none,
                                    Wasm.Binary.Instr.localGet 4,
                                    Wasm.Binary.Instr.i64Const 6,
                                    Wasm.Binary.Instr.i64Eq,
                                    Wasm.Binary.Instr.iff
                                      (Wasm.Binary.BlockType.empty)
                                      []
                                      (some [Wasm.Binary.Instr.localGet 4,
                                        Wasm.Binary.Instr.i64Const 27,
                                        Wasm.Binary.Instr.i64Ne,
                                        Wasm.Binary.Instr.iff
                                          (Wasm.Binary.BlockType.empty)
                                          [Wasm.Binary.Instr.localGet 4, Wasm.Binary.Instr.ret]
                                          none]),
                                    Wasm.Binary.Instr.i64Const 2,
                                    Wasm.Binary.Instr.localGet 5,
                                    Wasm.Binary.Instr.call 11,
                                    Wasm.Binary.Instr.localTee 4,
                                    Wasm.Binary.Instr.i64Eqz,
                                    Wasm.Binary.Instr.iff
                                      (Wasm.Binary.BlockType.empty)
                                      []
                                      (some [Wasm.Binary.Instr.localGet 4, Wasm.Binary.Instr.ret]),
                                    Wasm.Binary.Instr.br 0],
                                 Wasm.Binary.Instr.unreachable] },
                      { locals := [],
                        body := [Wasm.Binary.Instr.call 6,
                                 Wasm.Binary.Instr.i32WrapI64,
                                 Wasm.Binary.Instr.call 5,
                                 Wasm.Binary.Instr.unreachable] },
                      { locals := [{ count := 8, type := Wasm.Binary.ValType.i64 }],
                        body := [Wasm.Binary.Instr.localGet 0,
                                 Wasm.Binary.Instr.i64Const 0,
                                 Wasm.Binary.Instr.i64Eq,
                                 Wasm.Binary.Instr.iff (Wasm.Binary.BlockType.empty) [Wasm.Binary.Instr.ret] none,
                                 Wasm.Binary.Instr.localGet 0,
                                 Wasm.Binary.Instr.i64Const 48,
                                 Wasm.Binary.Instr.i64Sub,
                                 Wasm.Binary.Instr.i32WrapI64,
                                 Wasm.Binary.Instr.i64Load { align := 3, offset := 0 },
                                 Wasm.Binary.Instr.i64Const 5501223100278326855,
                                 Wasm.Binary.Instr.i64Ne,
                                 Wasm.Binary.Instr.iff
                                   (Wasm.Binary.BlockType.empty)
                                   [Wasm.Binary.Instr.unreachable]
                                   none,
                                 Wasm.Binary.Instr.localGet 0,
                                 Wasm.Binary.Instr.i64Const 40,
                                 Wasm.Binary.Instr.i64Sub,
                                 Wasm.Binary.Instr.i32WrapI64,
                                 Wasm.Binary.Instr.i64Load { align := 3, offset := 0 },
                                 Wasm.Binary.Instr.localSet 1,
                                 Wasm.Binary.Instr.localGet 1,
                                 Wasm.Binary.Instr.i64Const 0,
                                 Wasm.Binary.Instr.i64Eq,
                                 Wasm.Binary.Instr.iff
                                   (Wasm.Binary.BlockType.empty)
                                   [Wasm.Binary.Instr.unreachable]
                                   none,
                                 Wasm.Binary.Instr.globalGet 4,
                                 Wasm.Binary.Instr.i64Const 1,
                                 Wasm.Binary.Instr.i64Add,
                                 Wasm.Binary.Instr.globalSet 4,
                                 Wasm.Binary.Instr.i64Const 1,
                                 Wasm.Binary.Instr.localGet 1,
                                 Wasm.Binary.Instr.i64LtU,
                                 Wasm.Binary.Instr.iff
                                   (Wasm.Binary.BlockType.empty)
                                   [Wasm.Binary.Instr.localGet 0,
                                    Wasm.Binary.Instr.i64Const 40,
                                    Wasm.Binary.Instr.i64Sub,
                                    Wasm.Binary.Instr.i32WrapI64,
                                    Wasm.Binary.Instr.localGet 1,
                                    Wasm.Binary.Instr.i64Const 1,
                                    Wasm.Binary.Instr.i64Sub,
                                    Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
                                    Wasm.Binary.Instr.ret]
                                   none,
                                 Wasm.Binary.Instr.localGet 0,
                                 Wasm.Binary.Instr.i64Const 24,
                                 Wasm.Binary.Instr.i64Sub,
                                 Wasm.Binary.Instr.i32WrapI64,
                                 Wasm.Binary.Instr.i64Load { align := 3, offset := 0 },
                                 Wasm.Binary.Instr.localSet 2,
                                 Wasm.Binary.Instr.localGet 2,
                                 Wasm.Binary.Instr.i64Const 1,
                                 Wasm.Binary.Instr.i64Eq,
                                 Wasm.Binary.Instr.iff
                                   (Wasm.Binary.BlockType.empty)
                                   [Wasm.Binary.Instr.localGet 0,
                                    Wasm.Binary.Instr.i64Const 16,
                                    Wasm.Binary.Instr.i64Sub,
                                    Wasm.Binary.Instr.i32WrapI64,
                                    Wasm.Binary.Instr.i64Load { align := 3, offset := 0 },
                                    Wasm.Binary.Instr.localSet 3,
                                    Wasm.Binary.Instr.localGet 0,
                                    Wasm.Binary.Instr.i64Const 8,
                                    Wasm.Binary.Instr.i64Sub,
                                    Wasm.Binary.Instr.i32WrapI64,
                                    Wasm.Binary.Instr.i64Load { align := 3, offset := 0 },
                                    Wasm.Binary.Instr.localSet 5,
                                    Wasm.Binary.Instr.i64Const 0,
                                    Wasm.Binary.Instr.localSet 6,
                                    Wasm.Binary.Instr.block
                                      (Wasm.Binary.BlockType.empty)
                                      [Wasm.Binary.Instr.loop
                                         (Wasm.Binary.BlockType.empty)
                                         [Wasm.Binary.Instr.localGet 6,
                                          Wasm.Binary.Instr.localGet 3,
                                          Wasm.Binary.Instr.i64GeU,
                                          Wasm.Binary.Instr.brIf 1,
                                          Wasm.Binary.Instr.localGet 5,
                                          Wasm.Binary.Instr.localGet 6,
                                          Wasm.Binary.Instr.i64ShrU,
                                          Wasm.Binary.Instr.i64Const 1,
                                          Wasm.Binary.Instr.i64And,
                                          Wasm.Binary.Instr.i64Const 0,
                                          Wasm.Binary.Instr.i64Ne,
                                          Wasm.Binary.Instr.iff
                                            (Wasm.Binary.BlockType.empty)
                                            [Wasm.Binary.Instr.localGet 0,
                                             Wasm.Binary.Instr.localGet 6,
                                             Wasm.Binary.Instr.i64Const 8,
                                             Wasm.Binary.Instr.i64Mul,
                                             Wasm.Binary.Instr.i64Add,
                                             Wasm.Binary.Instr.i32WrapI64,
                                             Wasm.Binary.Instr.i64Load { align := 3, offset := 0 },
                                             Wasm.Binary.Instr.localSet 8,
                                             Wasm.Binary.Instr.localGet 8,
                                             Wasm.Binary.Instr.call 10]
                                            none,
                                          Wasm.Binary.Instr.localGet 6,
                                          Wasm.Binary.Instr.i64Const 1,
                                          Wasm.Binary.Instr.i64Add,
                                          Wasm.Binary.Instr.localSet 6,
                                          Wasm.Binary.Instr.br 0]]]
                                   none,
                                 Wasm.Binary.Instr.localGet 2,
                                 Wasm.Binary.Instr.i64Const 2,
                                 Wasm.Binary.Instr.i64Eq,
                                 Wasm.Binary.Instr.iff
                                   (Wasm.Binary.BlockType.empty)
                                   [Wasm.Binary.Instr.localGet 0,
                                    Wasm.Binary.Instr.i32WrapI64,
                                    Wasm.Binary.Instr.i64Load { align := 3, offset := 0 },
                                    Wasm.Binary.Instr.localSet 3,
                                    Wasm.Binary.Instr.localGet 0,
                                    Wasm.Binary.Instr.i64Const 16,
                                    Wasm.Binary.Instr.i64Sub,
                                    Wasm.Binary.Instr.i32WrapI64,
                                    Wasm.Binary.Instr.i64Load { align := 3, offset := 0 },
                                    Wasm.Binary.Instr.localSet 4,
                                    Wasm.Binary.Instr.localGet 0,
                                    Wasm.Binary.Instr.i64Const 8,
                                    Wasm.Binary.Instr.i64Sub,
                                    Wasm.Binary.Instr.i32WrapI64,
                                    Wasm.Binary.Instr.i64Load { align := 3, offset := 0 },
                                    Wasm.Binary.Instr.localSet 5,
                                    Wasm.Binary.Instr.i64Const 0,
                                    Wasm.Binary.Instr.localSet 7,
                                    Wasm.Binary.Instr.block
                                      (Wasm.Binary.BlockType.empty)
                                      [Wasm.Binary.Instr.loop
                                         (Wasm.Binary.BlockType.empty)
                                         [Wasm.Binary.Instr.localGet 7,
                                          Wasm.Binary.Instr.localGet 3,
                                          Wasm.Binary.Instr.i64GeU,
                                          Wasm.Binary.Instr.brIf 1,
                                          Wasm.Binary.Instr.i64Const 0,
                                          Wasm.Binary.Instr.localSet 6,
                                          Wasm.Binary.Instr.block
                                            (Wasm.Binary.BlockType.empty)
                                            [Wasm.Binary.Instr.loop
                                               (Wasm.Binary.BlockType.empty)
                                               [Wasm.Binary.Instr.localGet 6,
                                                Wasm.Binary.Instr.localGet 4,
                                                Wasm.Binary.Instr.i64GeU,
                                                Wasm.Binary.Instr.brIf 1,
                                                Wasm.Binary.Instr.localGet 5,
                                                Wasm.Binary.Instr.localGet 6,
                                                Wasm.Binary.Instr.i64ShrU,
                                                Wasm.Binary.Instr.i64Const 1,
                                                Wasm.Binary.Instr.i64And,
                                                Wasm.Binary.Instr.i64Const 0,
                                                Wasm.Binary.Instr.i64Ne,
                                                Wasm.Binary.Instr.iff
                                                  (Wasm.Binary.BlockType.empty)
                                                  [Wasm.Binary.Instr.localGet 0,
                                                   Wasm.Binary.Instr.i64Const 8,
                                                   Wasm.Binary.Instr.i64Add,
                                                   Wasm.Binary.Instr.localGet 7,
                                                   Wasm.Binary.Instr.localGet 4,
                                                   Wasm.Binary.Instr.i64Mul,
                                                   Wasm.Binary.Instr.localGet 6,
                                                   Wasm.Binary.Instr.i64Add,
                                                   Wasm.Binary.Instr.i64Const 8,
                                                   Wasm.Binary.Instr.i64Mul,
                                                   Wasm.Binary.Instr.i64Add,
                                                   Wasm.Binary.Instr.i32WrapI64,
                                                   Wasm.Binary.Instr.i64Load { align := 3, offset := 0 },
                                                   Wasm.Binary.Instr.localSet 8,
                                                   Wasm.Binary.Instr.localGet 8,
                                                   Wasm.Binary.Instr.call 10]
                                                  none,
                                                Wasm.Binary.Instr.localGet 6,
                                                Wasm.Binary.Instr.i64Const 1,
                                                Wasm.Binary.Instr.i64Add,
                                                Wasm.Binary.Instr.localSet 6,
                                                Wasm.Binary.Instr.br 0]],
                                          Wasm.Binary.Instr.localGet 7,
                                          Wasm.Binary.Instr.i64Const 1,
                                          Wasm.Binary.Instr.i64Add,
                                          Wasm.Binary.Instr.localSet 7,
                                          Wasm.Binary.Instr.br 0]]]
                                   none,
                                 Wasm.Binary.Instr.globalGet 5,
                                 Wasm.Binary.Instr.i64Const 1,
                                 Wasm.Binary.Instr.i64Add,
                                 Wasm.Binary.Instr.globalSet 5,
                                 Wasm.Binary.Instr.localGet 0,
                                 Wasm.Binary.Instr.i64Const 40,
                                 Wasm.Binary.Instr.i64Sub,
                                 Wasm.Binary.Instr.i32WrapI64,
                                 Wasm.Binary.Instr.i64Const 0,
                                 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
                                 Wasm.Binary.Instr.localGet 0,
                                 Wasm.Binary.Instr.i64Const 8,
                                 Wasm.Binary.Instr.i64Sub,
                                 Wasm.Binary.Instr.i32WrapI64,
                                 Wasm.Binary.Instr.globalGet 1,
                                 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
                                 Wasm.Binary.Instr.localGet 0,
                                 Wasm.Binary.Instr.globalSet 1] },
                      { locals := [{ count := 1, type := Wasm.Binary.ValType.i64 }],
                        body := [Wasm.Binary.Instr.i32Const 1,
                                 Wasm.Binary.Instr.i64Const 0,
                                 Wasm.Binary.Instr.i32Const 16,
                                 Wasm.Binary.Instr.call 3,
                                 Wasm.Binary.Instr.i64ExtendI32U,
                                 Wasm.Binary.Instr.localTee 2,
                                 Wasm.Binary.Instr.i64Eqz,
                                 Wasm.Binary.Instr.iff
                                   (Wasm.Binary.BlockType.empty)
                                   []
                                   (some [Wasm.Binary.Instr.localGet 2, Wasm.Binary.Instr.ret]),
                                 Wasm.Binary.Instr.i32Const 16,
                                 Wasm.Binary.Instr.i64Load { align := 3, offset := 0 },
                                 Wasm.Binary.Instr.localGet 1,
                                 Wasm.Binary.Instr.i64GeU,
                                 Wasm.Binary.Instr.iff
                                   (Wasm.Binary.BlockType.empty)
                                   [Wasm.Binary.Instr.i64Const 73, Wasm.Binary.Instr.ret]
                                   none,
                                 Wasm.Binary.Instr.i32Const 64,
                                 Wasm.Binary.Instr.i64Const 0,
                                 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
                                 Wasm.Binary.Instr.i32Const 72,
                                 Wasm.Binary.Instr.i64Const 0,
                                 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
                                 Wasm.Binary.Instr.i32Const 80,
                                 Wasm.Binary.Instr.i64Const 0,
                                 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
                                 Wasm.Binary.Instr.i32Const 88,
                                 Wasm.Binary.Instr.i64Const 0,
                                 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
                                 Wasm.Binary.Instr.i32Const 96,
                                 Wasm.Binary.Instr.i64Const 0,
                                 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
                                 Wasm.Binary.Instr.i32Const 104,
                                 Wasm.Binary.Instr.i64Const 0,
                                 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
                                 Wasm.Binary.Instr.i32Const 112,
                                 Wasm.Binary.Instr.i64Const 0,
                                 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
                                 Wasm.Binary.Instr.i32Const 120,
                                 Wasm.Binary.Instr.i64Const 0,
                                 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
                                 Wasm.Binary.Instr.i32Const 128,
                                 Wasm.Binary.Instr.i64Const 0,
                                 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
                                 Wasm.Binary.Instr.i32Const 136,
                                 Wasm.Binary.Instr.i64Const 0,
                                 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
                                 Wasm.Binary.Instr.i32Const 144,
                                 Wasm.Binary.Instr.i64Const 0,
                                 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
                                 Wasm.Binary.Instr.i32Const 152,
                                 Wasm.Binary.Instr.i64Const 0,
                                 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
                                 Wasm.Binary.Instr.i32Const 80,
                                 Wasm.Binary.Instr.i32Const 1,
                                 Wasm.Binary.Instr.i32Store { align := 2, offset := 0 },
                                 Wasm.Binary.Instr.i32Const 88,
                                 Wasm.Binary.Instr.localGet 1,
                                 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
                                 Wasm.Binary.Instr.i32Const 104,
                                 Wasm.Binary.Instr.i32Const 1,
                                 Wasm.Binary.Instr.i32Store { align := 2, offset := 0 },
                                 Wasm.Binary.Instr.i32Const 112,
                                 Wasm.Binary.Instr.i64Const 1,
                                 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
                                 Wasm.Binary.Instr.i32Const 120,
                                 Wasm.Binary.Instr.localGet 0,
                                 Wasm.Binary.Instr.i32WrapI64,
                                 Wasm.Binary.Instr.i32Store { align := 2, offset := 0 },
                                 Wasm.Binary.Instr.i32Const 128,
                                 Wasm.Binary.Instr.localGet 0,
                                 Wasm.Binary.Instr.i64Const 1,
                                 Wasm.Binary.Instr.i64Sub,
                                 Wasm.Binary.Instr.i32WrapI64,
                                 Wasm.Binary.Instr.i32Store { align := 2, offset := 0 },
                                 Wasm.Binary.Instr.i32Const 64,
                                 Wasm.Binary.Instr.i32Const 160,
                                 Wasm.Binary.Instr.i32Const 2,
                                 Wasm.Binary.Instr.i32Const 224,
                                 Wasm.Binary.Instr.call 4,
                                 Wasm.Binary.Instr.i64ExtendI32U,
                                 Wasm.Binary.Instr.localTee 2,
                                 Wasm.Binary.Instr.i64Eqz,
                                 Wasm.Binary.Instr.iff
                                   (Wasm.Binary.BlockType.empty)
                                   []
                                   (some [Wasm.Binary.Instr.localGet 2, Wasm.Binary.Instr.ret]),
                                 Wasm.Binary.Instr.i32Const 1,
                                 Wasm.Binary.Instr.i64Const 0,
                                 Wasm.Binary.Instr.i32Const 16,
                                 Wasm.Binary.Instr.call 3,
                                 Wasm.Binary.Instr.i64ExtendI32U,
                                 Wasm.Binary.Instr.localTee 2,
                                 Wasm.Binary.Instr.i64Eqz,
                                 Wasm.Binary.Instr.iff
                                   (Wasm.Binary.BlockType.empty)
                                   []
                                   (some [Wasm.Binary.Instr.localGet 2, Wasm.Binary.Instr.ret]),
                                 Wasm.Binary.Instr.i32Const 16,
                                 Wasm.Binary.Instr.i64Load { align := 3, offset := 0 },
                                 Wasm.Binary.Instr.localGet 1,
                                 Wasm.Binary.Instr.i64GeU,
                                 Wasm.Binary.Instr.iff
                                   (Wasm.Binary.BlockType.empty)
                                   [Wasm.Binary.Instr.i64Const 73, Wasm.Binary.Instr.ret]
                                   none,
                                 Wasm.Binary.Instr.i32Const 160,
                                 Wasm.Binary.Instr.i64Load { align := 3, offset := 0 },
                                 Wasm.Binary.Instr.i64Const 1,
                                 Wasm.Binary.Instr.i64Eq,
                                 Wasm.Binary.Instr.iff
                                   (Wasm.Binary.BlockType.empty)
                                   [Wasm.Binary.Instr.i32Const 168,
                                    Wasm.Binary.Instr.i32Load { align := 2, offset := 0 },
                                    Wasm.Binary.Instr.i64ExtendI32U,
                                    Wasm.Binary.Instr.i64Const 65535,
                                    Wasm.Binary.Instr.i64And,
                                    Wasm.Binary.Instr.ret]
                                   none,
                                 Wasm.Binary.Instr.i32Const 224,
                                 Wasm.Binary.Instr.i32Load { align := 2, offset := 0 },
                                 Wasm.Binary.Instr.i32Const 2,
                                 Wasm.Binary.Instr.i32Eq,
                                 Wasm.Binary.Instr.iff
                                   (Wasm.Binary.BlockType.empty)
                                   [Wasm.Binary.Instr.i32Const 200,
                                    Wasm.Binary.Instr.i32Load { align := 2, offset := 0 },
                                    Wasm.Binary.Instr.i64ExtendI32U,
                                    Wasm.Binary.Instr.i64Const 65535,
                                    Wasm.Binary.Instr.i64And,
                                    Wasm.Binary.Instr.ret]
                                   none,
                                 Wasm.Binary.Instr.i64Const 73,
                                 Wasm.Binary.Instr.ret] }] },
  imports := [{ moduleName := { bytes := [119, 97, 115, 105, 95, 115, 110, 97, 112, 115, 104, 111, 116, 95, 112, 114,
                                          101, 118, 105, 101, 119, 49],
                                text := "wasi_snapshot_preview1" },
                fieldName := { bytes := [102, 100, 95, 114, 101, 97, 100], text := "fd_read" },
                typeIndex := 0 },
              { moduleName := { bytes := [119, 97, 115, 105, 95, 115, 110, 97, 112, 115, 104, 111, 116, 95, 112, 114,
                                          101, 118, 105, 101, 119, 49],
                                text := "wasi_snapshot_preview1" },
                fieldName := { bytes := [102, 100, 95, 119, 114, 105, 116, 101], text := "fd_write" },
                typeIndex := 0 },
              { moduleName := { bytes := [119, 97, 115, 105, 95, 115, 110, 97, 112, 115, 104, 111, 116, 95, 112, 114,
                                          101, 118, 105, 101, 119, 49],
                                text := "wasi_snapshot_preview1" },
                fieldName := { bytes := [102, 100, 95, 102, 100, 115, 116, 97, 116, 95, 115, 101, 116, 95, 102, 108, 97,
                                         103, 115],
                               text := "fd_fdstat_set_flags" },
                typeIndex := 1 },
              { moduleName := { bytes := [119, 97, 115, 105, 95, 115, 110, 97, 112, 115, 104, 111, 116, 95, 112, 114,
                                          101, 118, 105, 101, 119, 49],
                                text := "wasi_snapshot_preview1" },
                fieldName := { bytes := [99, 108, 111, 99, 107, 95, 116, 105, 109, 101, 95, 103, 101, 116],
                               text := "clock_time_get" },
                typeIndex := 2 },
              { moduleName := { bytes := [119, 97, 115, 105, 95, 115, 110, 97, 112, 115, 104, 111, 116, 95, 112, 114,
                                          101, 118, 105, 101, 119, 49],
                                text := "wasi_snapshot_preview1" },
                fieldName := { bytes := [112, 111, 108, 108, 95, 111, 110, 101, 111, 102, 102], text := "poll_oneoff" },
                typeIndex := 0 },
              { moduleName := { bytes := [119, 97, 115, 105, 95, 115, 110, 97, 112, 115, 104, 111, 116, 95, 112, 114,
                                          101, 118, 105, 101, 119, 49],
                                text := "wasi_snapshot_preview1" },
                fieldName := { bytes := [112, 114, 111, 99, 95, 101, 120, 105, 116], text := "proc_exit" },
                typeIndex := 3 }] }

end Project.ByteIO.Artifact
