/-
  AUTO-GENERATED by `verifier emit`. Do not edit by hand.
-/

import Project.TalosPrelude

set_option maxRecDepth 1048576

namespace Project.ClobCancel

open Wasm

def func0 : Wasm.Program :=
  [
  .localGet 0,
  .localSet 5,
  .localGet 5
 ]

def func0Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64], locals := [.i64], body := func0, results := [.i64], typeIdx := some 0 }

def func1 : Wasm.Program :=
  [
  .constI64 0,
  .localSet 0,
  .localGet 0
 ]

def func1Def : Wasm.Function :=
  { locals := [.i64], body := func1, results := [.i64], typeIdx := some 1 }

def func2 : Wasm.Program :=
  [
  .constI64 3,
  .localSet 0,
  .localGet 0
 ]

def func2Def : Wasm.Function :=
  { locals := [.i64], body := func2, results := [.i64], typeIdx := some 2 }

/-- Exported function. -/
def func3 : Wasm.Program :=
  [
  .localGet 0,
  .localSet 16,
  .localGet 16,
  .wrapI64,
  .load64 0,
  .localSet 17,
  .constI64 0,
  .localSet 18,
  .constI64 0,
  .localSet 19,
  .block 0 0 [
   .loop 0 0 [
    .localGet 18,
    .localGet 17,
    .geUI64,
    .br_if 1,
    .localGet 16,
    .localGet 18,
    .constI64 5,
    .mulI64,
    .constI64 1,
    .addI64,
    .constI64 8,
    .mulI64,
    .addI64,
    .wrapI64,
    .load64 0,
    .localSet 2,
    .localGet 16,
    .localGet 18,
    .constI64 5,
    .mulI64,
    .constI64 2,
    .addI64,
    .constI64 8,
    .mulI64,
    .addI64,
    .wrapI64,
    .load64 0,
    .localSet 3,
    .localGet 16,
    .localGet 18,
    .constI64 5,
    .mulI64,
    .constI64 3,
    .addI64,
    .constI64 8,
    .mulI64,
    .addI64,
    .wrapI64,
    .load64 0,
    .localSet 4,
    .localGet 16,
    .localGet 18,
    .constI64 5,
    .mulI64,
    .constI64 4,
    .addI64,
    .constI64 8,
    .mulI64,
    .addI64,
    .wrapI64,
    .load64 0,
    .localSet 5,
    .localGet 16,
    .localGet 18,
    .constI64 5,
    .mulI64,
    .constI64 5,
    .addI64,
    .constI64 8,
    .mulI64,
    .addI64,
    .wrapI64,
    .load64 0,
    .localSet 6,
    .localGet 2,
    .localGet 1,
    .eqI64,
    .iff 0 1 [
     .constI64 1
    ] [
     .constI64 0
    ] [] [.i64],
    .constI64 0,
    .neI64,
    .iff 0 0 [
     .localGet 18,
     .constI64 1,
     .addI64,
     .localSet 19,
     .br 2
    ] [],
    .localGet 18,
    .constI64 1,
    .addI64,
    .localSet 18,
    .br 0
   ]
  ],
  .localGet 19,
  .localSet 7,
  .localGet 7,
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 0,
  .eqI64,
  .iff 0 0 [
   .call 2,
   .localSet 8,
   .localGet 8,
   .localSet 13,
   .constI64 0,
   .localSet 14,
   .localGet 0,
   .localSet 15
  ] [
   .call 1,
   .localSet 9,
   .localGet 9,
   .localSet 13,
   .localGet 0,
   .localSet 10,
   .localGet 7,
   .constI64 0,
   .eqI64,
   .eqz,
   .iff 0 1 [
    .localGet 7,
    .localSet 16,
    .constI64 1,
    .localSet 17,
    .localGet 16,
    .localGet 17,
    .ltUI64,
    .iff 0 1 [
     .constI64 0
    ] [
     .localGet 16,
     .localGet 17,
     .subI64
    ] [] [.i64]
   ] [
    .constI64 0
   ] [] [.i64],
   .localSet 11,
   .localGet 11,
   .localGet 10,
   .localSet 16,
   .localGet 16,
   .wrapI64,
   .load64 0,
   .ltUI64,
   .iff 0 1 [
    .localGet 10,
    .localSet 16,
    .localGet 11,
    .localSet 17,
    .localGet 16,
    .wrapI64,
    .load64 0,
    .localSet 18,
    .localGet 17,
    .localGet 18,
    .ltUI64,
    .iff 0 1 [
     .localGet 18,
     .constI64 1,
     .subI64,
     .localSet 21,
     .localGet 17,
     .constI64 5,
     .mulI64,
     .localSet 19,
     .localGet 21,
     .localGet 17,
     .subI64,
     .constI64 5,
     .mulI64,
     .localSet 20,
     .constI64 8,
     .localGet 21,
     .constI64 5,
     .mulI64,
     .constI64 8,
     .mulI64,
     .addI64,
     .constI64 7,
     .addI64,
     .constI64 8,
     .divUI64,
     .constI64 8,
     .mulI64,
     .localSet 26,
     .localGet 26,
     .constI64 8,
     .ltUI64,
     .iff 0 0 [
      .constI64 8,
      .localSet 26
     ] [],
     .constI64 0,
     .localSet 31,
     .constI64 0,
     .localSet 27,
     .globalGet 1,
     .localSet 28,
     .block 0 0 [
      .loop 0 0 [
       .localGet 28,
       .constI64 0,
       .eqI64,
       .br_if 1,
       .localGet 31,
       .constI64 0,
       .neI64,
       .br_if 1,
       .localGet 28,
       .constI64 32,
       .subI64,
       .wrapI64,
       .load64 0,
       .localSet 29,
       .localGet 28,
       .constI64 8,
       .subI64,
       .wrapI64,
       .load64 0,
       .localSet 30,
       .localGet 29,
       .localGet 26,
       .geUI64,
       .iff 0 0 [
        .localGet 27,
        .constI64 0,
        .eqI64,
        .iff 0 0 [
         .localGet 30,
         .globalSet 1
        ] [
         .localGet 27,
         .constI64 8,
         .subI64,
         .wrapI64,
         .localGet 30,
         .store64 0
        ],
        .localGet 28,
        .constI64 48,
        .subI64,
        .wrapI64,
        .constI64 5501223100278326855,
        .store64 0,
        .localGet 28,
        .constI64 40,
        .subI64,
        .wrapI64,
        .constI64 1,
        .store64 0,
        .localGet 28,
        .constI64 32,
        .subI64,
        .wrapI64,
        .localGet 29,
        .store64 0,
        .localGet 28,
        .constI64 24,
        .subI64,
        .wrapI64,
        .constI64 2,
        .store64 0,
        .localGet 28,
        .constI64 16,
        .subI64,
        .wrapI64,
        .constI64 5,
        .store64 0,
        .localGet 28,
        .constI64 8,
        .subI64,
        .wrapI64,
        .constI64 0,
        .store64 0,
        .localGet 28,
        .localSet 31
       ] [
        .localGet 28,
        .localSet 27,
        .localGet 30,
        .localSet 28
       ],
       .br 0
      ]
     ],
     .localGet 31,
     .constI64 0,
     .eqI64,
     .iff 0 0 [
      .globalGet 0,
      .constI64 48,
      .addI64,
      .localGet 26,
      .addI64,
      .localTee 29,
      .globalGet 0,
      .ltUI64,
      .iff 0 0 [
       .unreachable
      ] [],
      .localGet 29,
      .constI64 1,
      .subI64,
      .constI64 65536,
      .divUI64,
      .constI64 1,
      .addI64,
      .localSet 30,
      .memorySize,
      .extendUI32,
      .localGet 30,
      .ltUI64,
      .iff 0 0 [
       .localGet 30,
       .memorySize,
       .extendUI32,
       .subI64,
       .wrapI64,
       .memoryGrow,
       .const (-1),
       .eq,
       .iff 0 0 [
        .unreachable
       ] []
      ] [],
      .globalGet 0,
      .constI64 48,
      .addI64,
      .localSet 31,
      .localGet 29,
      .globalSet 0,
      .localGet 31,
      .constI64 48,
      .subI64,
      .wrapI64,
      .constI64 5501223100278326855,
      .store64 0,
      .localGet 31,
      .constI64 40,
      .subI64,
      .wrapI64,
      .constI64 1,
      .store64 0,
      .localGet 31,
      .constI64 32,
      .subI64,
      .wrapI64,
      .localGet 26,
      .store64 0,
      .localGet 31,
      .constI64 24,
      .subI64,
      .wrapI64,
      .constI64 2,
      .store64 0,
      .localGet 31,
      .constI64 16,
      .subI64,
      .wrapI64,
      .constI64 5,
      .store64 0,
      .localGet 31,
      .constI64 8,
      .subI64,
      .wrapI64,
      .constI64 0,
      .store64 0
     ] [],
     .globalGet 2,
     .constI64 1,
     .addI64,
     .globalSet 2,
     .localGet 31,
     .localSet 22,
     .localGet 22,
     .wrapI64,
     .localGet 21,
     .store64 0,
     .constI64 0,
     .localSet 23,
     .block 0 0 [
      .loop 0 0 [
       .localGet 23,
       .localGet 19,
       .geUI64,
       .br_if 1,
       .localGet 22,
       .localGet 23,
       .constI64 1,
       .addI64,
       .constI64 8,
       .mulI64,
       .addI64,
       .wrapI64,
       .localGet 16,
       .localGet 23,
       .constI64 1,
       .addI64,
       .constI64 8,
       .mulI64,
       .addI64,
       .wrapI64,
       .load64 0,
       .store64 0,
       .localGet 23,
       .constI64 1,
       .addI64,
       .localSet 23,
       .br 0
      ]
     ],
     .constI64 0,
     .localSet 23,
     .block 0 0 [
      .loop 0 0 [
       .localGet 23,
       .localGet 20,
       .geUI64,
       .br_if 1,
       .localGet 22,
       .localGet 19,
       .localGet 23,
       .addI64,
       .constI64 1,
       .addI64,
       .constI64 8,
       .mulI64,
       .addI64,
       .wrapI64,
       .localGet 16,
       .localGet 19,
       .constI64 5,
       .addI64,
       .localGet 23,
       .addI64,
       .constI64 1,
       .addI64,
       .constI64 8,
       .mulI64,
       .addI64,
       .wrapI64,
       .load64 0,
       .store64 0,
       .localGet 23,
       .constI64 1,
       .addI64,
       .localSet 23,
       .br 0
      ]
     ],
     .localGet 22
    ] [
     .localGet 16
    ] [] [.i64]
   ] [
    .unreachable
   ] [] [.i64],
   .localSet 14,
   .localGet 14,
   .localSet 15
  ],
  .localGet 13,
  .localGet 15
 ]

def func3Def : Wasm.Function :=
  { params := [.i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func3, results := [.i64, .i64], typeIdx := some 3 }

/-- Exported function. -/
def func4 : Wasm.Program :=
  [
  .localGet 0,
  .constI64 7,
  .addI64,
  .constI64 8,
  .divUI64,
  .constI64 8,
  .mulI64,
  .localSet 1,
  .localGet 1,
  .constI64 8,
  .ltUI64,
  .iff 0 0 [
   .constI64 8,
   .localSet 1
  ] [],
  .constI64 0,
  .localSet 6,
  .constI64 0,
  .localSet 2,
  .globalGet 1,
  .localSet 3,
  .block 0 0 [
   .loop 0 0 [
    .localGet 3,
    .constI64 0,
    .eqI64,
    .br_if 1,
    .localGet 6,
    .constI64 0,
    .neI64,
    .br_if 1,
    .localGet 3,
    .constI64 32,
    .subI64,
    .wrapI64,
    .load64 0,
    .localSet 4,
    .localGet 3,
    .constI64 8,
    .subI64,
    .wrapI64,
    .load64 0,
    .localSet 5,
    .localGet 4,
    .localGet 1,
    .geUI64,
    .iff 0 0 [
     .localGet 2,
     .constI64 0,
     .eqI64,
     .iff 0 0 [
      .localGet 5,
      .globalSet 1
     ] [
      .localGet 2,
      .constI64 8,
      .subI64,
      .wrapI64,
      .localGet 5,
      .store64 0
     ],
     .localGet 3,
     .constI64 48,
     .subI64,
     .wrapI64,
     .constI64 5501223100278326855,
     .store64 0,
     .localGet 3,
     .constI64 40,
     .subI64,
     .wrapI64,
     .constI64 1,
     .store64 0,
     .localGet 3,
     .constI64 32,
     .subI64,
     .wrapI64,
     .localGet 4,
     .store64 0,
     .localGet 3,
     .constI64 24,
     .subI64,
     .wrapI64,
     .constI64 0,
     .store64 0,
     .localGet 3,
     .constI64 16,
     .subI64,
     .wrapI64,
     .constI64 0,
     .store64 0,
     .localGet 3,
     .constI64 8,
     .subI64,
     .wrapI64,
     .constI64 0,
     .store64 0,
     .localGet 3,
     .localSet 6
    ] [
     .localGet 3,
     .localSet 2,
     .localGet 5,
     .localSet 3
    ],
    .br 0
   ]
  ],
  .localGet 6,
  .constI64 0,
  .eqI64,
  .iff 0 0 [
   .globalGet 0,
   .constI64 48,
   .addI64,
   .localGet 1,
   .addI64,
   .localTee 4,
   .globalGet 0,
   .ltUI64,
   .iff 0 0 [
    .unreachable
   ] [],
   .localGet 4,
   .constI64 1,
   .subI64,
   .constI64 65536,
   .divUI64,
   .constI64 1,
   .addI64,
   .localSet 5,
   .memorySize,
   .extendUI32,
   .localGet 5,
   .ltUI64,
   .iff 0 0 [
    .localGet 5,
    .memorySize,
    .extendUI32,
    .subI64,
    .wrapI64,
    .memoryGrow,
    .const (-1),
    .eq,
    .iff 0 0 [
     .unreachable
    ] []
   ] [],
   .globalGet 0,
   .constI64 48,
   .addI64,
   .localSet 6,
   .localGet 4,
   .globalSet 0,
   .localGet 6,
   .constI64 48,
   .subI64,
   .wrapI64,
   .constI64 5501223100278326855,
   .store64 0,
   .localGet 6,
   .constI64 40,
   .subI64,
   .wrapI64,
   .constI64 1,
   .store64 0,
   .localGet 6,
   .constI64 32,
   .subI64,
   .wrapI64,
   .localGet 1,
   .store64 0,
   .localGet 6,
   .constI64 24,
   .subI64,
   .wrapI64,
   .constI64 0,
   .store64 0,
   .localGet 6,
   .constI64 16,
   .subI64,
   .wrapI64,
   .constI64 0,
   .store64 0,
   .localGet 6,
   .constI64 8,
   .subI64,
   .wrapI64,
   .constI64 0,
   .store64 0
  ] [],
  .globalGet 2,
  .constI64 1,
  .addI64,
  .globalSet 2,
  .localGet 6
 ]

def func4Def : Wasm.Function :=
  { params := [.i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64], body := func4, results := [.i64], typeIdx := some 4 }

/-- Exported function. -/
def func5 : Wasm.Program :=
  [
  .constI64 4096,
  .globalSet 0,
  .constI64 0,
  .globalSet 1,
  .constI64 0,
  .globalSet 2,
  .constI64 0,
  .globalSet 3,
  .constI64 0,
  .globalSet 4,
  .constI64 0,
  .globalSet 5
 ]

def func5Def : Wasm.Function :=
  { body := func5, typeIdx := some 5 }

/-- Exported function. -/
def func6 : Wasm.Program :=
  [
  .localGet 0,
  .constI64 0,
  .neI64,
  .iff 0 0 [
   .localGet 0,
   .constI64 48,
   .subI64,
   .wrapI64,
   .load64 0,
   .constI64 5501223100278326855,
   .neI64,
   .iff 0 0 [
    .unreachable
   ] [],
   .localGet 0,
   .constI64 40,
   .subI64,
   .wrapI64,
   .load64 0,
   .localSet 1,
   .localGet 1,
   .constI64 0,
   .eqI64,
   .iff 0 0 [
    .unreachable
   ] [],
   .globalGet 3,
   .constI64 1,
   .addI64,
   .globalSet 3,
   .localGet 0,
   .constI64 40,
   .subI64,
   .wrapI64,
   .localGet 1,
   .constI64 1,
   .addI64,
   .store64 0
  ] [],
  .localGet 0
 ]

def func6Def : Wasm.Function :=
  { params := [.i64], locals := [.i64], body := func6, results := [.i64], typeIdx := some 6 }

/-- Exported function. -/
def func7 : Wasm.Program :=
  [
  .localGet 0,
  .constI64 0,
  .eqI64,
  .iff 0 0 [
   .ret
  ] [],
  .localGet 0,
  .constI64 48,
  .subI64,
  .wrapI64,
  .load64 0,
  .constI64 5501223100278326855,
  .neI64,
  .iff 0 0 [
   .unreachable
  ] [],
  .localGet 0,
  .constI64 40,
  .subI64,
  .wrapI64,
  .load64 0,
  .localSet 1,
  .localGet 1,
  .constI64 0,
  .eqI64,
  .iff 0 0 [
   .unreachable
  ] [],
  .globalGet 4,
  .constI64 1,
  .addI64,
  .globalSet 4,
  .constI64 1,
  .localGet 1,
  .ltUI64,
  .iff 0 0 [
   .localGet 0,
   .constI64 40,
   .subI64,
   .wrapI64,
   .localGet 1,
   .constI64 1,
   .subI64,
   .store64 0,
   .ret
  ] [],
  .localGet 0,
  .constI64 24,
  .subI64,
  .wrapI64,
  .load64 0,
  .localSet 2,
  .localGet 2,
  .constI64 1,
  .eqI64,
  .iff 0 0 [
   .localGet 0,
   .constI64 16,
   .subI64,
   .wrapI64,
   .load64 0,
   .localSet 3,
   .localGet 0,
   .constI64 8,
   .subI64,
   .wrapI64,
   .load64 0,
   .localSet 5,
   .constI64 0,
   .localSet 6,
   .block 0 0 [
    .loop 0 0 [
     .localGet 6,
     .localGet 3,
     .geUI64,
     .br_if 1,
     .localGet 5,
     .localGet 6,
     .shrUI64,
     .constI64 1,
     .andI64,
     .constI64 0,
     .neI64,
     .iff 0 0 [
      .localGet 0,
      .localGet 6,
      .constI64 8,
      .mulI64,
      .addI64,
      .wrapI64,
      .load64 0,
      .localSet 8,
      .localGet 8,
      .call 7
     ] [],
     .localGet 6,
     .constI64 1,
     .addI64,
     .localSet 6,
     .br 0
    ]
   ]
  ] [],
  .localGet 2,
  .constI64 2,
  .eqI64,
  .iff 0 0 [
   .localGet 0,
   .wrapI64,
   .load64 0,
   .localSet 3,
   .localGet 0,
   .constI64 16,
   .subI64,
   .wrapI64,
   .load64 0,
   .localSet 4,
   .localGet 0,
   .constI64 8,
   .subI64,
   .wrapI64,
   .load64 0,
   .localSet 5,
   .constI64 0,
   .localSet 7,
   .block 0 0 [
    .loop 0 0 [
     .localGet 7,
     .localGet 3,
     .geUI64,
     .br_if 1,
     .constI64 0,
     .localSet 6,
     .block 0 0 [
      .loop 0 0 [
       .localGet 6,
       .localGet 4,
       .geUI64,
       .br_if 1,
       .localGet 5,
       .localGet 6,
       .shrUI64,
       .constI64 1,
       .andI64,
       .constI64 0,
       .neI64,
       .iff 0 0 [
        .localGet 0,
        .constI64 8,
        .addI64,
        .localGet 7,
        .localGet 4,
        .mulI64,
        .localGet 6,
        .addI64,
        .constI64 8,
        .mulI64,
        .addI64,
        .wrapI64,
        .load64 0,
        .localSet 8,
        .localGet 8,
        .call 7
       ] [],
       .localGet 6,
       .constI64 1,
       .addI64,
       .localSet 6,
       .br 0
      ]
     ],
     .localGet 7,
     .constI64 1,
     .addI64,
     .localSet 7,
     .br 0
    ]
   ]
  ] [],
  .globalGet 5,
  .constI64 1,
  .addI64,
  .globalSet 5,
  .localGet 0,
  .constI64 40,
  .subI64,
  .wrapI64,
  .constI64 0,
  .store64 0,
  .localGet 0,
  .constI64 8,
  .subI64,
  .wrapI64,
  .globalGet 1,
  .store64 0,
  .localGet 0,
  .globalSet 1
 ]

def func7Def : Wasm.Function :=
  { params := [.i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func7, typeIdx := some 7 }

def «module» : Wasm.Module :=
{
  funcs := [
   func0Def,
   func1Def,
   func2Def,
   func3Def,
   func4Def,
   func5Def,
   func6Def,
   func7Def
  ],
  exports := [
   { name := "cancel", funcIdx := 3 },
   { name := "alloc", funcIdx := 4 },
   { name := "reset", funcIdx := 5 },
   { name := "retain", funcIdx := 6 },
   { name := "release", funcIdx := 7 },
   { name := "free", funcIdx := 7 }
  ],
  memory := some ({ pagesMin := 16 }),
  globals := [
   { init := .i64 4096, declaredType := some (.i64), sourceInit := some ([
     .constI64 4096
    ]) },
   { init := .i64 0, declaredType := some (.i64), sourceInit := some ([
     .constI64 0
    ]) },
   { init := .i64 0, declaredType := some (.i64), sourceInit := some ([
     .constI64 0
    ]) },
   { init := .i64 0, declaredType := some (.i64), sourceInit := some ([
     .constI64 0
    ]) },
   { init := .i64 0, declaredType := some (.i64), sourceInit := some ([
     .constI64 0
    ]) },
   { init := .i64 0, declaredType := some (.i64), sourceInit := some ([
     .constI64 0
    ]) }
  ],
  types := [
   { params := [.i64, .i64, .i64, .i64, .i64], results := [.i64] },
   { results := [.i64] },
   { results := [.i64] },
   { params := [.i64, .i64], results := [.i64, .i64] },
   { params := [.i64], results := [.i64] },
   {},
   { params := [.i64], results := [.i64] },
   { params := [.i64] }
  ],
  gcTypes := [
   { comp := .func ({ params := [.i64, .i64, .i64, .i64, .i64], results := [.i64] }) },
   { comp := .func ({ results := [.i64] }) },
   { comp := .func ({ results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64], results := [.i64, .i64] }) },
   { comp := .func ({ params := [.i64], results := [.i64] }) },
   { comp := .func ({}) },
   { comp := .func ({ params := [.i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64] }) }
  ],
  globalExports := [
   ("allocCount", 2),
   ("retainCount", 3),
   ("releaseCount", 4),
   ("freeCount", 5)
  ],
  memoryExports := [
   ("memory", 0)
  ]
}

end Project.ClobCancel
