import Project.Smalltalk.Proofs
import Lean.Util.CollectAxioms

-- Reject admitted proofs and additional axioms in every Smalltalk theorem,
-- including the dependencies of the listed results.
run_cmd do
  let env ← Lean.getEnv
  for (name, info) in env.constants.toList do
    if (`Project.Smalltalk).isPrefixOf name && info.isTheorem then
      for axiomName in ← Lean.collectAxioms name do
        unless axiomName == `propext || axiomName == `Quot.sound || axiomName == `Classical.choice do
          throwError "{name} depends on forbidden axiom {axiomName}"

#print axioms Project.Smalltalk.Memory.address_toNat
#print axioms Project.Smalltalk.Memory.cell_indices_distinct
#print axioms Project.Smalltalk.Memory.field_write_cell
#print axioms Project.Smalltalk.Allocation.allocateCell_read
#print axioms Project.Smalltalk.Allocation.allocateCell_field
#print axioms Project.Smalltalk.Allocation.allocateCell_preserves_other
#print axioms Project.Smalltalk.Allocation.allocateCell_register
#print axioms Project.Smalltalk.Allocation.allocateCell_shape
#print axioms Project.Smalltalk.FreeList.allocate_valid
#print axioms Project.Smalltalk.FreeList.allocate_empty_preserves_cells
#print axioms Project.Smalltalk.Sweep.finishCollection_preserves_marked
#print axioms Project.Smalltalk.SweepList.finishCollection_freeList
#print axioms Project.Smalltalk.MarkMemory.markReady_preserves_payload
#print axioms Project.Smalltalk.MarkMemory.markReady_work
#print axioms Project.Smalltalk.MarkMemory.mark_new
#print axioms Project.Smalltalk.Clear.cleared_marks
#print axioms Project.Smalltalk.Clear.cleared_payload
#print axioms Project.Smalltalk.Graph.sweep_correct
#print axioms Project.Smalltalk.Worklist.enqueue_room
#print axioms Project.Smalltalk.MarkInvariant.mark_holds
#print axioms Project.Smalltalk.MarkInvariant.roots_holds
#print axioms Project.Smalltalk.Worklist.top_word
#print axioms Project.Smalltalk.Worklist.pop_represents
#print axioms Project.Smalltalk.ScanMemory.scanCell_eq
#print axioms Project.Smalltalk.ScanInvariant.scan_holds
#print axioms Project.Smalltalk.Marking.marking_correct
#print axioms Project.Smalltalk.Collector.collect_correct
#print axioms Project.Smalltalk.Collector.collect_register
#print axioms Project.Smalltalk.CollectorPreservation.collect_valid
#print axioms Project.Smalltalk.CollectorPreservation.collect_reachable
#print axioms Project.Smalltalk.CollectorPreservation.collect_twice_payload
#print axioms Project.Smalltalk.Frame.retire_field
#print axioms Project.Smalltalk.Frame.advance_field
#print axioms Project.Smalltalk.Traversal.walk_path
#print axioms Project.Smalltalk.Traversal.lexical_path
#print axioms Project.Smalltalk.CallChain.onChain_correct
#print axioms Project.Smalltalk.Home.home_correct
#print axioms Project.Smalltalk.ReturnChecks.ret_dead
#print axioms Project.Smalltalk.ReturnChecks.ret_absent
#print axioms Project.Smalltalk.ReturnChecks.ret_accepted
#print axioms Project.Smalltalk.Unwind.unwind_go_prefix
#print axioms Project.Smalltalk.Unwind.returnReady_prefix
#print axioms Project.Smalltalk.Unwind.retireMany_field
#print axioms Project.Smalltalk.ReturnValue.returnCallerReady_delivers
#print axioms Project.Smalltalk.ReturnValue.returnReady_delivers
#print axioms Project.Smalltalk.ReturnValue.returnReady_finished
#print axioms Project.Smalltalk.Heap.fail_valid
#print axioms Project.Smalltalk.Reservation.reserve_correct
#print axioms Project.Smalltalk.Reservation.reserve_register
#print axioms Project.Smalltalk.ReturnReservation.reserve_prefix
#print axioms Project.Smalltalk.ReturnReservation.returnReserved_delivers
#print axioms Project.Smalltalk.ReturnReservation.ret_delivers
#print axioms Project.Smalltalk.ReturnReservation.ret_finished
#print axioms Project.Smalltalk.InitializationBase.capacity_bounds
#print axioms Project.Smalltalk.Seeding.init_cells
#print axioms Project.Smalltalk.InitializationGraph.init_graph_valid
#print axioms Project.Smalltalk.InitializationFree.init_free_list
#print axioms Project.Smalltalk.InitializationFree.init_valid
#print axioms Project.Smalltalk.InitializationFree.collect_init_valid
#print axioms Project.Smalltalk.HeapAllocation.allocate_valid
#print axioms Project.Smalltalk.HeapAllocation.allocateCell_reachable
#print axioms Project.Smalltalk.HeapAllocation.allocate_empty_valid
#print axioms Project.Smalltalk.HeapWrite.write_cell_valid
#print axioms Project.Smalltalk.HeapWrite.write_register_valid
#print axioms Project.Smalltalk.FrameHeap.advance_valid
#print axioms Project.Smalltalk.FrameHeap.retire_valid
#print axioms Project.Smalltalk.Reachability.localSlot_live
#print axioms Project.Smalltalk.Reachability.fieldSlot_live
#print axioms Project.Smalltalk.StackWrite.pop_valid
#print axioms Project.Smalltalk.StackWrite.storeSlot_valid
#print axioms Project.Smalltalk.StackPush.pushReady_delivers
#print axioms Project.Smalltalk.PushReservation.push_correct
#print axioms Project.Smalltalk.PushReservation.loadSlot_valid
#print axioms Project.Smalltalk.LiteralHeap.literalReady_valid
#print axioms Project.Smalltalk.LiteralHeap.literal_block_valid
#print axioms Project.Smalltalk.InstructionHeap.branch_valid
#print axioms Project.Smalltalk.ExecuteHeap.execute_covered_valid
#print axioms Project.Smalltalk.ExecuteHeap.step_covered_valid
#print axioms Project.Smalltalk.PointerTypes.write_cell_valid
#print axioms Project.Smalltalk.TypedCollection.collect_typed
#print axioms Project.Smalltalk.TypedCollection.init_typed
#print axioms Project.Smalltalk.TypedCollection.reserve_typed
#print axioms Project.Smalltalk.FrameTypes.retire_typed
#print axioms Project.Smalltalk.UnwindHeap.unwind_preserves
#print axioms Project.Smalltalk.TypedAllocation.allocate_typed
#print axioms Project.Smalltalk.ReturnCallerHeap.returnCaller_valid
#print axioms Project.Smalltalk.ReturnHeap.returnReserved_valid
#print axioms Project.Smalltalk.CallChainReachability.onChain_reachable
#print axioms Project.Smalltalk.PublicReturnHeap.ret_valid
#print axioms Project.Smalltalk.Construction.prepend_effect
#print axioms Project.Smalltalk.Construction.fillOne_effect
#print axioms Project.Smalltalk.ConstructionValues.prepend_values
#print axioms Project.Smalltalk.FillLoop.filling_progress
#print axioms Project.Smalltalk.FillLoop.filling_index
#print axioms Project.Smalltalk.FillLoop.filling_values
#print axioms Project.Smalltalk.FillLoop.filling_eq_pair
#print axioms Project.Smalltalk.ObjectConstruction.newReady_effect
#print axioms Project.Smalltalk.ArgumentLinks.send_argument
#print axioms Project.Smalltalk.ArgumentBinding.slotValue_valid_send
#print axioms Project.Smalltalk.ArgumentBinding.slotValue_valid_entry
#print axioms Project.Smalltalk.ArgumentBinding.bindOne_effect
#print axioms Project.Smalltalk.BindingPreservation.slotValue_transfer
#print axioms Project.Smalltalk.BindingLoop.slotValues_index
#print axioms Project.Smalltalk.BindingLoop.binding_progress
#print axioms Project.Smalltalk.BindingLoop.binding_index
#print axioms Project.Smalltalk.BindingLoop.binding_values
#print axioms Project.Smalltalk.BindingLoop.binding_eq_pair
#print axioms Project.Smalltalk.ActivationAllocation.publish_valid
#print axioms Project.Smalltalk.ActivationAllocation.allocate_effect
#print axioms Project.Smalltalk.ActivationConstruction.enterReady_effect
#print axioms Project.Smalltalk.ValidationLoop.loop_checks
#print axioms Project.Smalltalk.ProgramChecks.checks
#print axioms Project.Smalltalk.ProgramBounds.header
#print axioms Project.Smalltalk.ProgramBounds.class_bounds
#print axioms Project.Smalltalk.ProgramBounds.method_bounds
#print axioms Project.Smalltalk.ProgramBounds.entry_arity
#print axioms Project.Smalltalk.BootBudget.need_toNat
#print axioms Project.Smalltalk.BootBudget.entry_values
#print axioms Project.Smalltalk.BootConstruction.bootReady_effect
#print axioms Project.Smalltalk.BootHeap.bootValid_correct
#print axioms Project.Smalltalk.BootHeap.boot_valid
#print axioms Project.Smalltalk.BootHeap.boot_init_correct
#print axioms Project.Smalltalk.AdvanceTypes.advance_typed
#print axioms Project.Smalltalk.ArgumentTransfer.inputs_transfer
#print axioms Project.Smalltalk.ArgumentTransfer.slotValue_transfer
#print axioms Project.Smalltalk.CallConstruction.sendMethodReady_effect
#print axioms Project.Smalltalk.CallReservation.reserve_inputs
#print axioms Project.Smalltalk.CallHeap.callMethod_correct
#print axioms Project.Smalltalk.LookupStep.lookup_range
#print axioms Project.Smalltalk.LookupRound.fresh_scan
#print axioms Project.Smalltalk.LookupCorrect.validated_lookup
#print axioms Project.Smalltalk.LookupHierarchy.class_budget_sufficient
#print axioms Project.Smalltalk.Execution.run_resume
#print axioms Project.Smalltalk.Execution.run_stopped
