/-
  AUTO-GENERATED by `verifier emit`. Do not edit by hand.
-/

import Project.TalosPrelude

set_option maxRecDepth 1048576

namespace Project.ClobMatchFuel

open Wasm

def func0 : Wasm.Program :=
  [
  .localGet 4,
  .localSet 5,
  .localGet 5
 ]

def func0Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64], locals := [.i64], body := func0, results := [.i64], typeIdx := some 0 }

def func1 : Wasm.Program :=
  [
  .localGet 2,
  .localSet 5,
  .localGet 5
 ]

def func1Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64], locals := [.i64], body := func1, results := [.i64], typeIdx := some 1 }

def func2 : Wasm.Program :=
  [
  .localGet 0,
  .constI64 0,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 1,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .localSet 1,
  .localGet 1
 ]

def func2Def : Wasm.Function :=
  { params := [.i64], locals := [.i64], body := func2, results := [.i64], typeIdx := some 2 }

def func3 : Wasm.Program :=
  [
  .localGet 1,
  .localSet 5,
  .localGet 5
 ]

def func3Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64], locals := [.i64], body := func3, results := [.i64], typeIdx := some 3 }

def func4 : Wasm.Program :=
  [
  .localGet 3,
  .localSet 5,
  .localGet 5
 ]

def func4Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64], locals := [.i64], body := func4, results := [.i64], typeIdx := some 4 }

def func5 : Wasm.Program :=
  [
  .localGet 2,
  .constI64 0,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 1,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 1 [
   .localGet 8,
   .localGet 3,
   .leUI64,
   .iff 0 1 [
    .constI64 1
   ] [
    .constI64 0
   ] [] [.i64]
  ] [
   .localGet 3,
   .localGet 8,
   .leUI64,
   .iff 0 1 [
    .constI64 1
   ] [
    .constI64 0
   ] [] [.i64]
  ] [] [.i64],
  .localSet 10,
  .localGet 10
 ]

def func5Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], locals := [.i64], body := func5, results := [.i64], typeIdx := some 5 }

def func6 : Wasm.Program :=
  [
  .localGet 2,
  .localSet 10,
  .localGet 10,
  .call 2,
  .localSet 11,
  .localGet 7,
  .localGet 11,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 1 [
   .localGet 6,
   .localGet 1,
   .eqI64,
   .iff 0 1 [
    .constI64 1
   ] [
    .constI64 0
   ] [] [.i64],
   .constI64 0,
   .eqI64,
   .eqz,
   .eqz
  ] [
   .const 0
  ] [] [.i32],
  .iff 0 1 [
   .localGet 0,
   .localSet 12,
   .localGet 1,
   .localSet 13,
   .localGet 2,
   .localSet 14,
   .localGet 3,
   .localSet 15,
   .localGet 4,
   .localSet 16,
   .localGet 5,
   .localSet 17,
   .localGet 6,
   .localSet 18,
   .localGet 7,
   .localSet 19,
   .localGet 8,
   .localSet 20,
   .localGet 9,
   .localSet 21,
   .localGet 12,
   .localGet 13,
   .localGet 14,
   .localGet 15,
   .localGet 16,
   .localGet 17,
   .localGet 18,
   .localGet 19,
   .localGet 20,
   .localGet 21,
   .call 5,
   .constI64 0,
   .eqI64,
   .eqz
  ] [
   .const 0
  ] [] [.i32],
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .localSet 22,
  .localGet 22
 ]

def func6Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func6, results := [.i64], typeIdx := some 6 }

def func7 : Wasm.Program :=
  [
  .localGet 2,
  .constI64 0,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 1,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 1 [
   .localGet 8,
   .localGet 13,
   .ltUI64,
   .iff 0 1 [
    .constI64 1
   ] [
    .constI64 0
   ] [] [.i64]
  ] [
   .localGet 13,
   .localGet 8,
   .ltUI64,
   .iff 0 1 [
    .constI64 1
   ] [
    .constI64 0
   ] [] [.i64]
  ] [] [.i64],
  .localSet 15,
  .localGet 15
 ]

def func7Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], locals := [.i64], body := func7, results := [.i64], typeIdx := some 7 }

def func8 : Wasm.Program :=
  [
  .constI64 0,
  .localSet 11,
  .constI64 0,
  .localSet 14,
  .block 0 0 [
   .loop 0 0 [
    .localGet 0,
    .constI64 0,
    .eqI64,
    .eqz,
    .iff 0 1 [
     .localGet 14,
     .constI64 0,
     .eqI64
    ] [
     .const 0
    ] [] [.i32],
    .eqz,
    .br_if 1,
    .localGet 8,
    .localGet 2,
    .localSet 64,
    .localGet 64,
    .wrapI64,
    .load64 0,
    .ltUI64,
    .iff 0 0 [
     .localGet 2,
     .localSet 64,
     .localGet 8,
     .localSet 65,
     .localGet 65,
     .localGet 64,
     .wrapI64,
     .load64 0,
     .ltUI64,
     .iff 0 1 [
      .localGet 64,
      .localGet 65,
      .constI64 5,
      .mulI64,
      .constI64 1,
      .addI64,
      .constI64 8,
      .mulI64,
      .addI64,
      .wrapI64,
      .load64 0
     ] [
      .unreachable
     ] [] [.i64],
     .localSet 15,
     .localGet 2,
     .localSet 64,
     .localGet 8,
     .localSet 65,
     .localGet 65,
     .localGet 64,
     .wrapI64,
     .load64 0,
     .ltUI64,
     .iff 0 1 [
      .localGet 64,
      .localGet 65,
      .constI64 5,
      .mulI64,
      .constI64 2,
      .addI64,
      .constI64 8,
      .mulI64,
      .addI64,
      .wrapI64,
      .load64 0
     ] [
      .unreachable
     ] [] [.i64],
     .localSet 16,
     .localGet 2,
     .localSet 64,
     .localGet 8,
     .localSet 65,
     .localGet 65,
     .localGet 64,
     .wrapI64,
     .load64 0,
     .ltUI64,
     .iff 0 1 [
      .localGet 64,
      .localGet 65,
      .constI64 5,
      .mulI64,
      .constI64 3,
      .addI64,
      .constI64 8,
      .mulI64,
      .addI64,
      .wrapI64,
      .load64 0
     ] [
      .unreachable
     ] [] [.i64],
     .localSet 17,
     .localGet 2,
     .localSet 64,
     .localGet 8,
     .localSet 65,
     .localGet 65,
     .localGet 64,
     .wrapI64,
     .load64 0,
     .ltUI64,
     .iff 0 1 [
      .localGet 64,
      .localGet 65,
      .constI64 5,
      .mulI64,
      .constI64 4,
      .addI64,
      .constI64 8,
      .mulI64,
      .addI64,
      .wrapI64,
      .load64 0
     ] [
      .unreachable
     ] [] [.i64],
     .localSet 18,
     .localGet 2,
     .localSet 64,
     .localGet 8,
     .localSet 65,
     .localGet 65,
     .localGet 64,
     .wrapI64,
     .load64 0,
     .ltUI64,
     .iff 0 1 [
      .localGet 64,
      .localGet 65,
      .constI64 5,
      .mulI64,
      .constI64 5,
      .addI64,
      .constI64 8,
      .mulI64,
      .addI64,
      .wrapI64,
      .load64 0
     ] [
      .unreachable
     ] [] [.i64],
     .localSet 19,
     .localGet 9,
     .constI64 0,
     .eqI64,
     .iff 0 1 [
      .localGet 3,
      .localSet 20,
      .localGet 4,
      .localSet 21,
      .localGet 5,
      .localSet 22,
      .localGet 6,
      .localSet 23,
      .localGet 7,
      .localSet 24,
      .localGet 15,
      .localSet 25,
      .localGet 16,
      .localSet 26,
      .localGet 17,
      .localSet 27,
      .localGet 18,
      .localSet 28,
      .localGet 19,
      .localSet 29,
      .localGet 20,
      .localGet 21,
      .localGet 22,
      .localGet 23,
      .localGet 24,
      .localGet 25,
      .localGet 26,
      .localGet 27,
      .localGet 28,
      .localGet 29,
      .call 6,
      .localSet 30,
      .localGet 30,
      .constI64 1,
      .eqI64,
      .iff 0 1 [
       .constI64 1
      ] [
       .constI64 0
      ] [] [.i64],
      .constI64 0,
      .eqI64,
      .eqz,
      .iff 0 1 [
       .constI64 1
      ] [
       .constI64 0
      ] [] [.i64]
     ] [
      .localGet 3,
      .localSet 31,
      .localGet 4,
      .localSet 32,
      .localGet 5,
      .localSet 33,
      .localGet 6,
      .localSet 34,
      .localGet 7,
      .localSet 35,
      .localGet 15,
      .localSet 36,
      .localGet 16,
      .localSet 37,
      .localGet 17,
      .localSet 38,
      .localGet 18,
      .localSet 39,
      .localGet 19,
      .localSet 40,
      .localGet 31,
      .localGet 32,
      .localGet 33,
      .localGet 34,
      .localGet 35,
      .localGet 36,
      .localGet 37,
      .localGet 38,
      .localGet 39,
      .localGet 40,
      .call 6,
      .constI64 0,
      .eqI64,
      .eqz,
      .iff 0 1 [
       .localGet 5,
       .constI64 0,
       .eqI64,
       .iff 0 1 [
        .constI64 1
       ] [
        .constI64 0
       ] [] [.i64],
       .constI64 0,
       .eqI64,
       .eqz,
       .iff 0 1 [
        .constI64 1
       ] [
        .constI64 0
       ] [] [.i64],
       .constI64 1,
       .eqI64,
       .iff 0 1 [
        .constI64 1
       ] [
        .constI64 0
       ] [] [.i64],
       .constI64 0,
       .eqI64,
       .eqz,
       .iff 0 1 [
        .localGet 18,
        .localGet 2,
        .localSet 64,
        .localGet 10,
        .localSet 65,
        .localGet 65,
        .localGet 64,
        .wrapI64,
        .load64 0,
        .ltUI64,
        .iff 0 1 [
         .localGet 64,
         .localGet 65,
         .constI64 5,
         .mulI64,
         .constI64 4,
         .addI64,
         .constI64 8,
         .mulI64,
         .addI64,
         .wrapI64,
         .load64 0
        ] [
         .unreachable
        ] [] [.i64],
        .ltUI64,
        .iff 0 1 [
         .constI64 1
        ] [
         .constI64 0
        ] [] [.i64]
       ] [
        .localGet 2,
        .localSet 64,
        .localGet 10,
        .localSet 65,
        .localGet 65,
        .localGet 64,
        .wrapI64,
        .load64 0,
        .ltUI64,
        .iff 0 1 [
         .localGet 64,
         .localGet 65,
         .constI64 5,
         .mulI64,
         .constI64 4,
         .addI64,
         .constI64 8,
         .mulI64,
         .addI64,
         .wrapI64,
         .load64 0
        ] [
         .unreachable
        ] [] [.i64],
        .localGet 18,
        .ltUI64,
        .iff 0 1 [
         .constI64 1
        ] [
         .constI64 0
        ] [] [.i64]
       ] [] [.i64],
       .constI64 0,
       .eqI64,
       .eqz
      ] [
       .const 0
      ] [] [.i32],
      .iff 0 1 [
       .constI64 1
      ] [
       .constI64 0
      ] [] [.i64],
      .constI64 1,
      .eqI64,
      .iff 0 1 [
       .constI64 1
      ] [
       .constI64 0
      ] [] [.i64],
      .constI64 0,
      .eqI64,
      .eqz,
      .iff 0 1 [
       .constI64 1
      ] [
       .constI64 1
      ] [] [.i64]
     ] [] [.i64],
     .localSet 41,
     .localGet 9,
     .constI64 0,
     .eqI64,
     .iff 0 1 [
      .localGet 3,
      .localSet 20,
      .localGet 4,
      .localSet 21,
      .localGet 5,
      .localSet 22,
      .localGet 6,
      .localSet 23,
      .localGet 7,
      .localSet 24,
      .localGet 15,
      .localSet 25,
      .localGet 16,
      .localSet 26,
      .localGet 17,
      .localSet 27,
      .localGet 18,
      .localSet 28,
      .localGet 19,
      .localSet 29,
      .localGet 20,
      .localGet 21,
      .localGet 22,
      .localGet 23,
      .localGet 24,
      .localGet 25,
      .localGet 26,
      .localGet 27,
      .localGet 28,
      .localGet 29,
      .call 6,
      .localSet 30,
      .localGet 30,
      .constI64 1,
      .eqI64,
      .iff 0 1 [
       .constI64 1
      ] [
       .constI64 0
      ] [] [.i64],
      .constI64 0,
      .eqI64,
      .eqz,
      .iff 0 1 [
       .localGet 8
      ] [
       .constI64 0
      ] [] [.i64]
     ] [
      .localGet 3,
      .localSet 31,
      .localGet 4,
      .localSet 32,
      .localGet 5,
      .localSet 33,
      .localGet 6,
      .localSet 34,
      .localGet 7,
      .localSet 35,
      .localGet 15,
      .localSet 36,
      .localGet 16,
      .localSet 37,
      .localGet 17,
      .localSet 38,
      .localGet 18,
      .localSet 39,
      .localGet 19,
      .localSet 40,
      .localGet 31,
      .localGet 32,
      .localGet 33,
      .localGet 34,
      .localGet 35,
      .localGet 36,
      .localGet 37,
      .localGet 38,
      .localGet 39,
      .localGet 40,
      .call 6,
      .constI64 0,
      .eqI64,
      .eqz,
      .iff 0 1 [
       .localGet 5,
       .constI64 0,
       .eqI64,
       .iff 0 1 [
        .constI64 1
       ] [
        .constI64 0
       ] [] [.i64],
       .constI64 0,
       .eqI64,
       .eqz,
       .iff 0 1 [
        .constI64 1
       ] [
        .constI64 0
       ] [] [.i64],
       .constI64 1,
       .eqI64,
       .iff 0 1 [
        .constI64 1
       ] [
        .constI64 0
       ] [] [.i64],
       .constI64 0,
       .eqI64,
       .eqz,
       .iff 0 1 [
        .localGet 18,
        .localGet 2,
        .localSet 64,
        .localGet 10,
        .localSet 65,
        .localGet 65,
        .localGet 64,
        .wrapI64,
        .load64 0,
        .ltUI64,
        .iff 0 1 [
         .localGet 64,
         .localGet 65,
         .constI64 5,
         .mulI64,
         .constI64 4,
         .addI64,
         .constI64 8,
         .mulI64,
         .addI64,
         .wrapI64,
         .load64 0
        ] [
         .unreachable
        ] [] [.i64],
        .ltUI64,
        .iff 0 1 [
         .constI64 1
        ] [
         .constI64 0
        ] [] [.i64]
       ] [
        .localGet 2,
        .localSet 64,
        .localGet 10,
        .localSet 65,
        .localGet 65,
        .localGet 64,
        .wrapI64,
        .load64 0,
        .ltUI64,
        .iff 0 1 [
         .localGet 64,
         .localGet 65,
         .constI64 5,
         .mulI64,
         .constI64 4,
         .addI64,
         .constI64 8,
         .mulI64,
         .addI64,
         .wrapI64,
         .load64 0
        ] [
         .unreachable
        ] [] [.i64],
        .localGet 18,
        .ltUI64,
        .iff 0 1 [
         .constI64 1
        ] [
         .constI64 0
        ] [] [.i64]
       ] [] [.i64],
       .constI64 0,
       .eqI64,
       .eqz
      ] [
       .const 0
      ] [] [.i32],
      .iff 0 1 [
       .constI64 1
      ] [
       .constI64 0
      ] [] [.i64],
      .constI64 1,
      .eqI64,
      .iff 0 1 [
       .constI64 1
      ] [
       .constI64 0
      ] [] [.i64],
      .constI64 0,
      .eqI64,
      .eqz,
      .iff 0 1 [
       .localGet 8
      ] [
       .localGet 10
      ] [] [.i64]
     ] [] [.i64],
     .localSet 42,
     .localGet 1,
     .localSet 43,
     .localGet 2,
     .localSet 44,
     .localGet 3,
     .localSet 45,
     .localGet 4,
     .localSet 46,
     .localGet 5,
     .localSet 47,
     .localGet 6,
     .localSet 48,
     .localGet 7,
     .localSet 49,
     .localGet 8,
     .localSet 64,
     .constI64 1,
     .localSet 65,
     .localGet 64,
     .localGet 65,
     .addI64,
     .localTee 66,
     .localGet 64,
     .ltUI64,
     .iff 0 1 [
      .unreachable
     ] [
      .localGet 66
     ] [] [.i64],
     .localSet 50,
     .localGet 41,
     .localSet 51,
     .localGet 42,
     .localSet 52,
     .localGet 11,
     .constI64 0,
     .eqI64,
     .eqz,
     .iff 0 1 [
      .localGet 11,
      .localGet 43,
      .eqI64,
      .eqz
     ] [
      .const 0
     ] [] [.i32],
     .iff 0 0 [
      .localGet 11,
      .call 18
     ] [],
     .localGet 43,
     .localSet 53,
     .localGet 44,
     .localSet 54,
     .localGet 45,
     .localSet 55,
     .localGet 46,
     .localSet 56,
     .localGet 47,
     .localSet 57,
     .localGet 48,
     .localSet 58,
     .localGet 49,
     .localSet 59,
     .localGet 50,
     .localSet 60,
     .localGet 51,
     .localSet 61,
     .localGet 52,
     .localSet 62,
     .localGet 43,
     .localGet 11,
     .eqI64,
     .iff 0 1 [
      .localGet 43
     ] [
      .constI64 0
     ] [] [.i64],
     .localSet 63,
     .localGet 53,
     .localSet 1,
     .localGet 54,
     .localSet 2,
     .localGet 55,
     .localSet 3,
     .localGet 56,
     .localSet 4,
     .localGet 57,
     .localSet 5,
     .localGet 58,
     .localSet 6,
     .localGet 59,
     .localSet 7,
     .localGet 60,
     .localSet 8,
     .localGet 61,
     .localSet 9,
     .localGet 62,
     .localSet 10,
     .localGet 63,
     .localSet 11,
     .localGet 0,
     .constI64 1,
     .subI64,
     .localSet 0
    ] [
     .localGet 9,
     .localSet 12,
     .localGet 10,
     .localSet 13,
     .constI64 1,
     .localSet 14
    ],
    .br 0
   ]
  ],
  .localGet 14,
  .constI64 0,
  .eqI64,
  .iff 0 0 [
   .localGet 9,
   .localSet 12,
   .localGet 10,
   .localSet 13
  ] [],
  .localGet 12,
  .localGet 13
 ]

def func8Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func8, results := [.i64, .i64], typeIdx := some 8 }

def func9 : Wasm.Program :=
  [
  .localGet 1,
  .localSet 25,
  .localGet 25,
  .wrapI64,
  .load64 0,
  .localSet 22,
  .constI64 1,
  .localSet 23,
  .localGet 22,
  .localGet 23,
  .addI64,
  .localTee 24,
  .localGet 22,
  .ltUI64,
  .iff 0 1 [
   .unreachable
  ] [
   .localGet 24
  ] [] [.i64],
  .localSet 7,
  .localGet 0,
  .localSet 8,
  .localGet 1,
  .localSet 9,
  .localGet 2,
  .localSet 10,
  .localGet 3,
  .localSet 11,
  .localGet 4,
  .localSet 12,
  .localGet 5,
  .localSet 13,
  .localGet 6,
  .localSet 14,
  .constI64 0,
  .localSet 15,
  .constI64 0,
  .localSet 16,
  .constI64 0,
  .localSet 17,
  .localGet 7,
  .localGet 8,
  .localGet 9,
  .localGet 10,
  .localGet 11,
  .localGet 12,
  .localGet 13,
  .localGet 14,
  .localGet 15,
  .localGet 16,
  .localGet 17,
  .call 8,
  .localSet 19,
  .localSet 18,
  .localGet 18,
  .localSet 20,
  .localGet 19,
  .localSet 21,
  .localGet 20,
  .localGet 21
 ]

def func9Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func9, results := [.i64, .i64], typeIdx := some 9 }

def func10 : Wasm.Program :=
  [
  .localGet 0,
  .localSet 5,
  .localGet 1,
  .localSet 6,
  .localGet 5,
  .localGet 6
 ]

def func10Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64], locals := [.i64, .i64], body := func10, results := [.i64, .i64], typeIdx := some 10 }

def func11 : Wasm.Program :=
  [
  .localGet 4,
  .localSet 5,
  .localGet 5
 ]

def func11Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64], locals := [.i64], body := func11, results := [.i64], typeIdx := some 11 }

def func12 : Wasm.Program :=
  [
  .localGet 2,
  .localSet 5,
  .localGet 3,
  .localSet 6,
  .localGet 5,
  .localGet 6
 ]

def func12Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64], locals := [.i64, .i64], body := func12, results := [.i64, .i64], typeIdx := some 12 }

def func13 : Wasm.Program :=
  [
  .localGet 0,
  .localSet 5,
  .localGet 5
 ]

def func13Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64], locals := [.i64], body := func13, results := [.i64], typeIdx := some 13 }

/-- Exported function. -/
def func14 : Wasm.Program :=
  [
  .localGet 1,
  .localSet 9,
  .localGet 2,
  .localSet 10,
  .localGet 3,
  .localSet 11,
  .localGet 4,
  .localSet 12,
  .localGet 5,
  .localSet 13,
  .constI64 0,
  .localSet 14,
  .localGet 6,
  .localSet 15,
  .constI64 0,
  .localSet 16,
  .localGet 7,
  .localSet 17,
  .localGet 8,
  .localSet 18,
  .constI64 0,
  .localSet 19,
  .constI64 0,
  .localSet 20,
  .constI64 0,
  .localSet 24,
  .block 0 0 [
   .loop 0 0 [
    .localGet 0,
    .constI64 0,
    .eqI64,
    .eqz,
    .iff 0 1 [
     .localGet 24,
     .constI64 0,
     .eqI64
    ] [
     .const 0
    ] [] [.i32],
    .eqz,
    .br_if 1,
    .localGet 18,
    .constI64 0,
    .eqI64,
    .iff 0 1 [
     .constI64 1
    ] [
     .constI64 0
    ] [] [.i64],
    .constI64 1,
    .eqI64,
    .iff 0 1 [
     .constI64 1
    ] [
     .constI64 0
    ] [] [.i64],
    .constI64 0,
    .eqI64,
    .eqz,
    .iff 0 0 [
     .localGet 15,
     .localSet 21,
     .localGet 17,
     .localSet 22,
     .localGet 18,
     .localSet 23,
     .constI64 1,
     .localSet 24
    ] [
     .localGet 14,
     .localSet 25,
     .localGet 15,
     .localSet 26,
     .localGet 9,
     .localSet 27,
     .localGet 10,
     .localSet 28,
     .localGet 11,
     .localSet 29,
     .localGet 12,
     .localSet 30,
     .localGet 13,
     .localSet 31,
     .localGet 25,
     .localGet 26,
     .localGet 27,
     .localGet 28,
     .localGet 29,
     .localGet 30,
     .localGet 31,
     .call 9,
     .localSet 33,
     .localSet 32,
     .localGet 32,
     .constI64 0,
     .eqI64,
     .iff 0 0 [
      .localGet 15,
      .localSet 21,
      .localGet 17,
      .localSet 22,
      .localGet 18,
      .localSet 23,
      .constI64 1,
      .localSet 24
     ] [
      .localGet 15,
      .localSet 76,
      .localGet 33,
      .localSet 77,
      .localGet 77,
      .localGet 76,
      .wrapI64,
      .load64 0,
      .ltUI64,
      .iff 0 1 [
       .localGet 76,
       .localGet 77,
       .constI64 5,
       .mulI64,
       .constI64 1,
       .addI64,
       .constI64 8,
       .mulI64,
       .addI64,
       .wrapI64,
       .load64 0
      ] [
       .unreachable
      ] [] [.i64],
      .localSet 34,
      .localGet 15,
      .localSet 76,
      .localGet 33,
      .localSet 77,
      .localGet 77,
      .localGet 76,
      .wrapI64,
      .load64 0,
      .ltUI64,
      .iff 0 1 [
       .localGet 76,
       .localGet 77,
       .constI64 5,
       .mulI64,
       .constI64 2,
       .addI64,
       .constI64 8,
       .mulI64,
       .addI64,
       .wrapI64,
       .load64 0
      ] [
       .unreachable
      ] [] [.i64],
      .localSet 35,
      .localGet 15,
      .localSet 76,
      .localGet 33,
      .localSet 77,
      .localGet 77,
      .localGet 76,
      .wrapI64,
      .load64 0,
      .ltUI64,
      .iff 0 1 [
       .localGet 76,
       .localGet 77,
       .constI64 5,
       .mulI64,
       .constI64 3,
       .addI64,
       .constI64 8,
       .mulI64,
       .addI64,
       .wrapI64,
       .load64 0
      ] [
       .unreachable
      ] [] [.i64],
      .localSet 36,
      .localGet 15,
      .localSet 76,
      .localGet 33,
      .localSet 77,
      .localGet 77,
      .localGet 76,
      .wrapI64,
      .load64 0,
      .ltUI64,
      .iff 0 1 [
       .localGet 76,
       .localGet 77,
       .constI64 5,
       .mulI64,
       .constI64 4,
       .addI64,
       .constI64 8,
       .mulI64,
       .addI64,
       .wrapI64,
       .load64 0
      ] [
       .unreachable
      ] [] [.i64],
      .localSet 37,
      .localGet 15,
      .localSet 76,
      .localGet 33,
      .localSet 77,
      .localGet 77,
      .localGet 76,
      .wrapI64,
      .load64 0,
      .ltUI64,
      .iff 0 1 [
       .localGet 76,
       .localGet 77,
       .constI64 5,
       .mulI64,
       .constI64 5,
       .addI64,
       .constI64 8,
       .mulI64,
       .addI64,
       .wrapI64,
       .load64 0
      ] [
       .unreachable
      ] [] [.i64],
      .localSet 38,
      .localGet 38,
      .localGet 18,
      .leUI64,
      .iff 0 0 [
       .localGet 15,
       .localSet 39,
       .localGet 33,
       .localSet 40,
       .localGet 40,
       .localGet 39,
       .localSet 76,
       .localGet 76,
       .wrapI64,
       .load64 0,
       .ltUI64,
       .iff 0 1 [
        .localGet 39,
        .localSet 76,
        .localGet 40,
        .localSet 77,
        .localGet 76,
        .wrapI64,
        .load64 0,
        .localSet 78,
        .localGet 77,
        .localGet 78,
        .ltUI64,
        .iff 0 1 [
         .localGet 78,
         .constI64 1,
         .subI64,
         .localSet 81,
         .localGet 77,
         .constI64 5,
         .mulI64,
         .localSet 79,
         .localGet 81,
         .localGet 77,
         .subI64,
         .constI64 5,
         .mulI64,
         .localSet 80,
         .constI64 8,
         .localGet 81,
         .constI64 5,
         .mulI64,
         .constI64 8,
         .mulI64,
         .addI64,
         .constI64 7,
         .addI64,
         .constI64 8,
         .divUI64,
         .constI64 8,
         .mulI64,
         .localSet 86,
         .localGet 86,
         .constI64 8,
         .ltUI64,
         .iff 0 0 [
          .constI64 8,
          .localSet 86
         ] [],
         .constI64 0,
         .localSet 91,
         .constI64 0,
         .localSet 87,
         .globalGet 1,
         .localSet 88,
         .block 0 0 [
          .loop 0 0 [
           .localGet 88,
           .constI64 0,
           .eqI64,
           .br_if 1,
           .localGet 91,
           .constI64 0,
           .neI64,
           .br_if 1,
           .localGet 88,
           .constI64 32,
           .subI64,
           .wrapI64,
           .load64 0,
           .localSet 89,
           .localGet 88,
           .constI64 8,
           .subI64,
           .wrapI64,
           .load64 0,
           .localSet 90,
           .localGet 89,
           .localGet 86,
           .geUI64,
           .iff 0 0 [
            .localGet 87,
            .constI64 0,
            .eqI64,
            .iff 0 0 [
             .localGet 90,
             .globalSet 1
            ] [
             .localGet 87,
             .constI64 8,
             .subI64,
             .wrapI64,
             .localGet 90,
             .store64 0
            ],
            .localGet 88,
            .constI64 48,
            .subI64,
            .wrapI64,
            .constI64 5501223100278326855,
            .store64 0,
            .localGet 88,
            .constI64 40,
            .subI64,
            .wrapI64,
            .constI64 1,
            .store64 0,
            .localGet 88,
            .constI64 32,
            .subI64,
            .wrapI64,
            .localGet 89,
            .store64 0,
            .localGet 88,
            .constI64 24,
            .subI64,
            .wrapI64,
            .constI64 2,
            .store64 0,
            .localGet 88,
            .constI64 16,
            .subI64,
            .wrapI64,
            .constI64 5,
            .store64 0,
            .localGet 88,
            .constI64 8,
            .subI64,
            .wrapI64,
            .constI64 0,
            .store64 0,
            .localGet 88,
            .localSet 91
           ] [
            .localGet 88,
            .localSet 87,
            .localGet 90,
            .localSet 88
           ],
           .br 0
          ]
         ],
         .localGet 91,
         .constI64 0,
         .eqI64,
         .iff 0 0 [
          .globalGet 0,
          .constI64 48,
          .addI64,
          .localGet 86,
          .addI64,
          .localTee 89,
          .globalGet 0,
          .ltUI64,
          .iff 0 0 [
           .unreachable
          ] [],
          .localGet 89,
          .constI64 1,
          .subI64,
          .constI64 65536,
          .divUI64,
          .constI64 1,
          .addI64,
          .localSet 90,
          .memorySize,
          .extendUI32,
          .localGet 90,
          .ltUI64,
          .iff 0 0 [
           .localGet 90,
           .memorySize,
           .extendUI32,
           .subI64,
           .wrapI64,
           .memoryGrow,
           .const (-1),
           .eq,
           .iff 0 0 [
            .unreachable
           ] []
          ] [],
          .globalGet 0,
          .constI64 48,
          .addI64,
          .localSet 91,
          .localGet 89,
          .globalSet 0,
          .localGet 91,
          .constI64 48,
          .subI64,
          .wrapI64,
          .constI64 5501223100278326855,
          .store64 0,
          .localGet 91,
          .constI64 40,
          .subI64,
          .wrapI64,
          .constI64 1,
          .store64 0,
          .localGet 91,
          .constI64 32,
          .subI64,
          .wrapI64,
          .localGet 86,
          .store64 0,
          .localGet 91,
          .constI64 24,
          .subI64,
          .wrapI64,
          .constI64 2,
          .store64 0,
          .localGet 91,
          .constI64 16,
          .subI64,
          .wrapI64,
          .constI64 5,
          .store64 0,
          .localGet 91,
          .constI64 8,
          .subI64,
          .wrapI64,
          .constI64 0,
          .store64 0
         ] [],
         .globalGet 2,
         .constI64 1,
         .addI64,
         .globalSet 2,
         .localGet 91,
         .localSet 82,
         .localGet 82,
         .wrapI64,
         .localGet 81,
         .store64 0,
         .constI64 0,
         .localSet 83,
         .block 0 0 [
          .loop 0 0 [
           .localGet 83,
           .localGet 79,
           .geUI64,
           .br_if 1,
           .localGet 82,
           .localGet 83,
           .constI64 1,
           .addI64,
           .constI64 8,
           .mulI64,
           .addI64,
           .wrapI64,
           .localGet 76,
           .localGet 83,
           .constI64 1,
           .addI64,
           .constI64 8,
           .mulI64,
           .addI64,
           .wrapI64,
           .load64 0,
           .store64 0,
           .localGet 83,
           .constI64 1,
           .addI64,
           .localSet 83,
           .br 0
          ]
         ],
         .constI64 0,
         .localSet 83,
         .block 0 0 [
          .loop 0 0 [
           .localGet 83,
           .localGet 80,
           .geUI64,
           .br_if 1,
           .localGet 82,
           .localGet 79,
           .localGet 83,
           .addI64,
           .constI64 1,
           .addI64,
           .constI64 8,
           .mulI64,
           .addI64,
           .wrapI64,
           .localGet 76,
           .localGet 79,
           .constI64 5,
           .addI64,
           .localGet 83,
           .addI64,
           .constI64 1,
           .addI64,
           .constI64 8,
           .mulI64,
           .addI64,
           .wrapI64,
           .load64 0,
           .store64 0,
           .localGet 83,
           .constI64 1,
           .addI64,
           .localSet 83,
           .br 0
          ]
         ],
         .localGet 82
        ] [
         .localGet 76
        ] [] [.i64]
       ] [
        .unreachable
       ] [] [.i64],
       .localSet 44,
       .localGet 44,
       .localSet 45,
       .localGet 17,
       .localSet 42,
       .localGet 42,
       .localSet 76,
       .localGet 9,
       .localSet 82,
       .localGet 34,
       .localSet 83,
       .localGet 37,
       .localSet 84,
       .localGet 38,
       .localSet 85,
       .localGet 76,
       .wrapI64,
       .load64 0,
       .localSet 77,
       .localGet 77,
       .constI64 4,
       .mulI64,
       .localSet 78,
       .localGet 77,
       .constI64 1,
       .addI64,
       .localSet 79,
       .constI64 8,
       .localGet 79,
       .constI64 4,
       .mulI64,
       .constI64 8,
       .mulI64,
       .addI64,
       .constI64 7,
       .addI64,
       .constI64 8,
       .divUI64,
       .constI64 8,
       .mulI64,
       .localSet 88,
       .localGet 88,
       .constI64 8,
       .ltUI64,
       .iff 0 0 [
        .constI64 8,
        .localSet 88
       ] [],
       .constI64 0,
       .localSet 93,
       .constI64 0,
       .localSet 89,
       .globalGet 1,
       .localSet 90,
       .block 0 0 [
        .loop 0 0 [
         .localGet 90,
         .constI64 0,
         .eqI64,
         .br_if 1,
         .localGet 93,
         .constI64 0,
         .neI64,
         .br_if 1,
         .localGet 90,
         .constI64 32,
         .subI64,
         .wrapI64,
         .load64 0,
         .localSet 91,
         .localGet 90,
         .constI64 8,
         .subI64,
         .wrapI64,
         .load64 0,
         .localSet 92,
         .localGet 91,
         .localGet 88,
         .geUI64,
         .iff 0 0 [
          .localGet 89,
          .constI64 0,
          .eqI64,
          .iff 0 0 [
           .localGet 92,
           .globalSet 1
          ] [
           .localGet 89,
           .constI64 8,
           .subI64,
           .wrapI64,
           .localGet 92,
           .store64 0
          ],
          .localGet 90,
          .constI64 48,
          .subI64,
          .wrapI64,
          .constI64 5501223100278326855,
          .store64 0,
          .localGet 90,
          .constI64 40,
          .subI64,
          .wrapI64,
          .constI64 1,
          .store64 0,
          .localGet 90,
          .constI64 32,
          .subI64,
          .wrapI64,
          .localGet 91,
          .store64 0,
          .localGet 90,
          .constI64 24,
          .subI64,
          .wrapI64,
          .constI64 2,
          .store64 0,
          .localGet 90,
          .constI64 16,
          .subI64,
          .wrapI64,
          .constI64 4,
          .store64 0,
          .localGet 90,
          .constI64 8,
          .subI64,
          .wrapI64,
          .constI64 0,
          .store64 0,
          .localGet 90,
          .localSet 93
         ] [
          .localGet 90,
          .localSet 89,
          .localGet 92,
          .localSet 90
         ],
         .br 0
        ]
       ],
       .localGet 93,
       .constI64 0,
       .eqI64,
       .iff 0 0 [
        .globalGet 0,
        .constI64 48,
        .addI64,
        .localGet 88,
        .addI64,
        .localTee 91,
        .globalGet 0,
        .ltUI64,
        .iff 0 0 [
         .unreachable
        ] [],
        .localGet 91,
        .constI64 1,
        .subI64,
        .constI64 65536,
        .divUI64,
        .constI64 1,
        .addI64,
        .localSet 92,
        .memorySize,
        .extendUI32,
        .localGet 92,
        .ltUI64,
        .iff 0 0 [
         .localGet 92,
         .memorySize,
         .extendUI32,
         .subI64,
         .wrapI64,
         .memoryGrow,
         .const (-1),
         .eq,
         .iff 0 0 [
          .unreachable
         ] []
        ] [],
        .globalGet 0,
        .constI64 48,
        .addI64,
        .localSet 93,
        .localGet 91,
        .globalSet 0,
        .localGet 93,
        .constI64 48,
        .subI64,
        .wrapI64,
        .constI64 5501223100278326855,
        .store64 0,
        .localGet 93,
        .constI64 40,
        .subI64,
        .wrapI64,
        .constI64 1,
        .store64 0,
        .localGet 93,
        .constI64 32,
        .subI64,
        .wrapI64,
        .localGet 88,
        .store64 0,
        .localGet 93,
        .constI64 24,
        .subI64,
        .wrapI64,
        .constI64 2,
        .store64 0,
        .localGet 93,
        .constI64 16,
        .subI64,
        .wrapI64,
        .constI64 4,
        .store64 0,
        .localGet 93,
        .constI64 8,
        .subI64,
        .wrapI64,
        .constI64 0,
        .store64 0
       ] [],
       .globalGet 2,
       .constI64 1,
       .addI64,
       .globalSet 2,
       .localGet 93,
       .localSet 80,
       .localGet 80,
       .wrapI64,
       .localGet 79,
       .store64 0,
       .constI64 0,
       .localSet 81,
       .block 0 0 [
        .loop 0 0 [
         .localGet 81,
         .localGet 78,
         .geUI64,
         .br_if 1,
         .localGet 80,
         .localGet 81,
         .constI64 1,
         .addI64,
         .constI64 8,
         .mulI64,
         .addI64,
         .wrapI64,
         .localGet 76,
         .localGet 81,
         .constI64 1,
         .addI64,
         .constI64 8,
         .mulI64,
         .addI64,
         .wrapI64,
         .load64 0,
         .store64 0,
         .localGet 81,
         .constI64 1,
         .addI64,
         .localSet 81,
         .br 0
        ]
       ],
       .localGet 80,
       .localGet 77,
       .constI64 4,
       .mulI64,
       .constI64 1,
       .addI64,
       .constI64 8,
       .mulI64,
       .addI64,
       .wrapI64,
       .localGet 82,
       .store64 0,
       .localGet 80,
       .localGet 77,
       .constI64 4,
       .mulI64,
       .constI64 2,
       .addI64,
       .constI64 8,
       .mulI64,
       .addI64,
       .wrapI64,
       .localGet 83,
       .store64 0,
       .localGet 80,
       .localGet 77,
       .constI64 4,
       .mulI64,
       .constI64 3,
       .addI64,
       .constI64 8,
       .mulI64,
       .addI64,
       .wrapI64,
       .localGet 84,
       .store64 0,
       .localGet 80,
       .localGet 77,
       .constI64 4,
       .mulI64,
       .constI64 4,
       .addI64,
       .constI64 8,
       .mulI64,
       .addI64,
       .wrapI64,
       .localGet 85,
       .store64 0,
       .localGet 80,
       .localSet 46,
       .localGet 46,
       .localSet 47,
       .localGet 18,
       .localGet 38,
       .subI64,
       .localSet 48,
       .localGet 9,
       .localSet 49,
       .localGet 10,
       .localSet 50,
       .localGet 11,
       .localSet 51,
       .localGet 12,
       .localSet 52,
       .localGet 13,
       .localSet 53,
       .localGet 44,
       .localSet 54,
       .localGet 45,
       .localSet 55,
       .localGet 46,
       .localSet 56,
       .localGet 47,
       .localSet 57,
       .localGet 48,
       .localSet 58,
       .localGet 19,
       .constI64 0,
       .eqI64,
       .eqz,
       .iff 0 1 [
        .localGet 19,
        .localGet 54,
        .eqI64,
        .eqz
       ] [
        .const 0
       ] [] [.i32],
       .iff 0 1 [
        .localGet 19,
        .localGet 56,
        .eqI64,
        .eqz
       ] [
        .const 0
       ] [] [.i32],
       .iff 0 0 [
        .localGet 19,
        .call 18
       ] [],
       .localGet 20,
       .constI64 0,
       .eqI64,
       .eqz,
       .iff 0 1 [
        .localGet 20,
        .localGet 19,
        .eqI64,
        .eqz
       ] [
        .const 0
       ] [] [.i32],
       .iff 0 1 [
        .localGet 20,
        .localGet 54,
        .eqI64,
        .eqz
       ] [
        .const 0
       ] [] [.i32],
       .iff 0 1 [
        .localGet 20,
        .localGet 56,
        .eqI64,
        .eqz
       ] [
        .const 0
       ] [] [.i32],
       .iff 0 0 [
        .localGet 20,
        .call 18
       ] [],
       .localGet 49,
       .localSet 59,
       .localGet 50,
       .localSet 60,
       .localGet 51,
       .localSet 61,
       .localGet 52,
       .localSet 62,
       .localGet 53,
       .localSet 63,
       .localGet 54,
       .localSet 64,
       .localGet 55,
       .localSet 65,
       .localGet 56,
       .localSet 66,
       .localGet 57,
       .localSet 67,
       .localGet 58,
       .localSet 68,
       .localGet 54,
       .localGet 19,
       .eqI64,
       .iff 0 1 [
        .localGet 54
       ] [
        .localGet 54,
        .localGet 20,
        .eqI64,
        .iff 0 1 [
         .localGet 54
        ] [
         .constI64 0
        ] [] [.i64]
       ] [] [.i64],
       .localSet 69,
       .localGet 56,
       .localSet 70,
       .localGet 59,
       .localSet 9,
       .localGet 60,
       .localSet 10,
       .localGet 61,
       .localSet 11,
       .localGet 62,
       .localSet 12,
       .localGet 63,
       .localSet 13,
       .localGet 64,
       .localSet 14,
       .localGet 65,
       .localSet 15,
       .localGet 66,
       .localSet 16,
       .localGet 67,
       .localSet 17,
       .localGet 68,
       .localSet 18,
       .localGet 69,
       .localSet 19,
       .localGet 70,
       .localSet 20,
       .localGet 0,
       .constI64 1,
       .subI64,
       .localSet 0
      ] [
       .localGet 15,
       .localSet 71,
       .localGet 33,
       .localSet 72,
       .localGet 71,
       .localSet 76,
       .localGet 72,
       .localSet 77,
       .localGet 34,
       .localSet 82,
       .localGet 35,
       .localSet 83,
       .localGet 36,
       .localSet 84,
       .localGet 37,
       .localSet 85,
       .localGet 38,
       .localGet 18,
       .subI64,
       .localSet 86,
       .localGet 76,
       .wrapI64,
       .load64 0,
       .localSet 78,
       .localGet 77,
       .localGet 78,
       .ltUI64,
       .iff 0 1 [
        .localGet 78,
        .constI64 5,
        .mulI64,
        .localSet 79,
        .constI64 8,
        .localGet 78,
        .constI64 5,
        .mulI64,
        .constI64 8,
        .mulI64,
        .addI64,
        .constI64 7,
        .addI64,
        .constI64 8,
        .divUI64,
        .constI64 8,
        .mulI64,
        .localSet 89,
        .localGet 89,
        .constI64 8,
        .ltUI64,
        .iff 0 0 [
         .constI64 8,
         .localSet 89
        ] [],
        .constI64 0,
        .localSet 94,
        .constI64 0,
        .localSet 90,
        .globalGet 1,
        .localSet 91,
        .block 0 0 [
         .loop 0 0 [
          .localGet 91,
          .constI64 0,
          .eqI64,
          .br_if 1,
          .localGet 94,
          .constI64 0,
          .neI64,
          .br_if 1,
          .localGet 91,
          .constI64 32,
          .subI64,
          .wrapI64,
          .load64 0,
          .localSet 92,
          .localGet 91,
          .constI64 8,
          .subI64,
          .wrapI64,
          .load64 0,
          .localSet 93,
          .localGet 92,
          .localGet 89,
          .geUI64,
          .iff 0 0 [
           .localGet 90,
           .constI64 0,
           .eqI64,
           .iff 0 0 [
            .localGet 93,
            .globalSet 1
           ] [
            .localGet 90,
            .constI64 8,
            .subI64,
            .wrapI64,
            .localGet 93,
            .store64 0
           ],
           .localGet 91,
           .constI64 48,
           .subI64,
           .wrapI64,
           .constI64 5501223100278326855,
           .store64 0,
           .localGet 91,
           .constI64 40,
           .subI64,
           .wrapI64,
           .constI64 1,
           .store64 0,
           .localGet 91,
           .constI64 32,
           .subI64,
           .wrapI64,
           .localGet 92,
           .store64 0,
           .localGet 91,
           .constI64 24,
           .subI64,
           .wrapI64,
           .constI64 2,
           .store64 0,
           .localGet 91,
           .constI64 16,
           .subI64,
           .wrapI64,
           .constI64 5,
           .store64 0,
           .localGet 91,
           .constI64 8,
           .subI64,
           .wrapI64,
           .constI64 0,
           .store64 0,
           .localGet 91,
           .localSet 94
          ] [
           .localGet 91,
           .localSet 90,
           .localGet 93,
           .localSet 91
          ],
          .br 0
         ]
        ],
        .localGet 94,
        .constI64 0,
        .eqI64,
        .iff 0 0 [
         .globalGet 0,
         .constI64 48,
         .addI64,
         .localGet 89,
         .addI64,
         .localTee 92,
         .globalGet 0,
         .ltUI64,
         .iff 0 0 [
          .unreachable
         ] [],
         .localGet 92,
         .constI64 1,
         .subI64,
         .constI64 65536,
         .divUI64,
         .constI64 1,
         .addI64,
         .localSet 93,
         .memorySize,
         .extendUI32,
         .localGet 93,
         .ltUI64,
         .iff 0 0 [
          .localGet 93,
          .memorySize,
          .extendUI32,
          .subI64,
          .wrapI64,
          .memoryGrow,
          .const (-1),
          .eq,
          .iff 0 0 [
           .unreachable
          ] []
         ] [],
         .globalGet 0,
         .constI64 48,
         .addI64,
         .localSet 94,
         .localGet 92,
         .globalSet 0,
         .localGet 94,
         .constI64 48,
         .subI64,
         .wrapI64,
         .constI64 5501223100278326855,
         .store64 0,
         .localGet 94,
         .constI64 40,
         .subI64,
         .wrapI64,
         .constI64 1,
         .store64 0,
         .localGet 94,
         .constI64 32,
         .subI64,
         .wrapI64,
         .localGet 89,
         .store64 0,
         .localGet 94,
         .constI64 24,
         .subI64,
         .wrapI64,
         .constI64 2,
         .store64 0,
         .localGet 94,
         .constI64 16,
         .subI64,
         .wrapI64,
         .constI64 5,
         .store64 0,
         .localGet 94,
         .constI64 8,
         .subI64,
         .wrapI64,
         .constI64 0,
         .store64 0
        ] [],
        .globalGet 2,
        .constI64 1,
        .addI64,
        .globalSet 2,
        .localGet 94,
        .localSet 80,
        .localGet 80,
        .wrapI64,
        .localGet 78,
        .store64 0,
        .constI64 0,
        .localSet 81,
        .block 0 0 [
         .loop 0 0 [
          .localGet 81,
          .localGet 79,
          .geUI64,
          .br_if 1,
          .localGet 80,
          .localGet 81,
          .constI64 1,
          .addI64,
          .constI64 8,
          .mulI64,
          .addI64,
          .wrapI64,
          .localGet 76,
          .localGet 81,
          .constI64 1,
          .addI64,
          .constI64 8,
          .mulI64,
          .addI64,
          .wrapI64,
          .load64 0,
          .store64 0,
          .localGet 81,
          .constI64 1,
          .addI64,
          .localSet 81,
          .br 0
         ]
        ],
        .localGet 80,
        .localGet 77,
        .constI64 5,
        .mulI64,
        .constI64 1,
        .addI64,
        .constI64 8,
        .mulI64,
        .addI64,
        .wrapI64,
        .localGet 82,
        .store64 0,
        .localGet 80,
        .localGet 77,
        .constI64 5,
        .mulI64,
        .constI64 2,
        .addI64,
        .constI64 8,
        .mulI64,
        .addI64,
        .wrapI64,
        .localGet 83,
        .store64 0,
        .localGet 80,
        .localGet 77,
        .constI64 5,
        .mulI64,
        .constI64 3,
        .addI64,
        .constI64 8,
        .mulI64,
        .addI64,
        .wrapI64,
        .localGet 84,
        .store64 0,
        .localGet 80,
        .localGet 77,
        .constI64 5,
        .mulI64,
        .constI64 4,
        .addI64,
        .constI64 8,
        .mulI64,
        .addI64,
        .wrapI64,
        .localGet 85,
        .store64 0,
        .localGet 80,
        .localGet 77,
        .constI64 5,
        .mulI64,
        .constI64 5,
        .addI64,
        .constI64 8,
        .mulI64,
        .addI64,
        .wrapI64,
        .localGet 86,
        .store64 0,
        .localGet 80
       ] [
        .unreachable
       ] [] [.i64],
       .localSet 73,
       .localGet 73,
       .localSet 21,
       .localGet 17,
       .localSet 74,
       .localGet 74,
       .localSet 76,
       .localGet 9,
       .localSet 82,
       .localGet 34,
       .localSet 83,
       .localGet 37,
       .localSet 84,
       .localGet 18,
       .localSet 85,
       .localGet 76,
       .wrapI64,
       .load64 0,
       .localSet 77,
       .localGet 77,
       .constI64 4,
       .mulI64,
       .localSet 78,
       .localGet 77,
       .constI64 1,
       .addI64,
       .localSet 79,
       .constI64 8,
       .localGet 79,
       .constI64 4,
       .mulI64,
       .constI64 8,
       .mulI64,
       .addI64,
       .constI64 7,
       .addI64,
       .constI64 8,
       .divUI64,
       .constI64 8,
       .mulI64,
       .localSet 88,
       .localGet 88,
       .constI64 8,
       .ltUI64,
       .iff 0 0 [
        .constI64 8,
        .localSet 88
       ] [],
       .constI64 0,
       .localSet 93,
       .constI64 0,
       .localSet 89,
       .globalGet 1,
       .localSet 90,
       .block 0 0 [
        .loop 0 0 [
         .localGet 90,
         .constI64 0,
         .eqI64,
         .br_if 1,
         .localGet 93,
         .constI64 0,
         .neI64,
         .br_if 1,
         .localGet 90,
         .constI64 32,
         .subI64,
         .wrapI64,
         .load64 0,
         .localSet 91,
         .localGet 90,
         .constI64 8,
         .subI64,
         .wrapI64,
         .load64 0,
         .localSet 92,
         .localGet 91,
         .localGet 88,
         .geUI64,
         .iff 0 0 [
          .localGet 89,
          .constI64 0,
          .eqI64,
          .iff 0 0 [
           .localGet 92,
           .globalSet 1
          ] [
           .localGet 89,
           .constI64 8,
           .subI64,
           .wrapI64,
           .localGet 92,
           .store64 0
          ],
          .localGet 90,
          .constI64 48,
          .subI64,
          .wrapI64,
          .constI64 5501223100278326855,
          .store64 0,
          .localGet 90,
          .constI64 40,
          .subI64,
          .wrapI64,
          .constI64 1,
          .store64 0,
          .localGet 90,
          .constI64 32,
          .subI64,
          .wrapI64,
          .localGet 91,
          .store64 0,
          .localGet 90,
          .constI64 24,
          .subI64,
          .wrapI64,
          .constI64 2,
          .store64 0,
          .localGet 90,
          .constI64 16,
          .subI64,
          .wrapI64,
          .constI64 4,
          .store64 0,
          .localGet 90,
          .constI64 8,
          .subI64,
          .wrapI64,
          .constI64 0,
          .store64 0,
          .localGet 90,
          .localSet 93
         ] [
          .localGet 90,
          .localSet 89,
          .localGet 92,
          .localSet 90
         ],
         .br 0
        ]
       ],
       .localGet 93,
       .constI64 0,
       .eqI64,
       .iff 0 0 [
        .globalGet 0,
        .constI64 48,
        .addI64,
        .localGet 88,
        .addI64,
        .localTee 91,
        .globalGet 0,
        .ltUI64,
        .iff 0 0 [
         .unreachable
        ] [],
        .localGet 91,
        .constI64 1,
        .subI64,
        .constI64 65536,
        .divUI64,
        .constI64 1,
        .addI64,
        .localSet 92,
        .memorySize,
        .extendUI32,
        .localGet 92,
        .ltUI64,
        .iff 0 0 [
         .localGet 92,
         .memorySize,
         .extendUI32,
         .subI64,
         .wrapI64,
         .memoryGrow,
         .const (-1),
         .eq,
         .iff 0 0 [
          .unreachable
         ] []
        ] [],
        .globalGet 0,
        .constI64 48,
        .addI64,
        .localSet 93,
        .localGet 91,
        .globalSet 0,
        .localGet 93,
        .constI64 48,
        .subI64,
        .wrapI64,
        .constI64 5501223100278326855,
        .store64 0,
        .localGet 93,
        .constI64 40,
        .subI64,
        .wrapI64,
        .constI64 1,
        .store64 0,
        .localGet 93,
        .constI64 32,
        .subI64,
        .wrapI64,
        .localGet 88,
        .store64 0,
        .localGet 93,
        .constI64 24,
        .subI64,
        .wrapI64,
        .constI64 2,
        .store64 0,
        .localGet 93,
        .constI64 16,
        .subI64,
        .wrapI64,
        .constI64 4,
        .store64 0,
        .localGet 93,
        .constI64 8,
        .subI64,
        .wrapI64,
        .constI64 0,
        .store64 0
       ] [],
       .globalGet 2,
       .constI64 1,
       .addI64,
       .globalSet 2,
       .localGet 93,
       .localSet 80,
       .localGet 80,
       .wrapI64,
       .localGet 79,
       .store64 0,
       .constI64 0,
       .localSet 81,
       .block 0 0 [
        .loop 0 0 [
         .localGet 81,
         .localGet 78,
         .geUI64,
         .br_if 1,
         .localGet 80,
         .localGet 81,
         .constI64 1,
         .addI64,
         .constI64 8,
         .mulI64,
         .addI64,
         .wrapI64,
         .localGet 76,
         .localGet 81,
         .constI64 1,
         .addI64,
         .constI64 8,
         .mulI64,
         .addI64,
         .wrapI64,
         .load64 0,
         .store64 0,
         .localGet 81,
         .constI64 1,
         .addI64,
         .localSet 81,
         .br 0
        ]
       ],
       .localGet 80,
       .localGet 77,
       .constI64 4,
       .mulI64,
       .constI64 1,
       .addI64,
       .constI64 8,
       .mulI64,
       .addI64,
       .wrapI64,
       .localGet 82,
       .store64 0,
       .localGet 80,
       .localGet 77,
       .constI64 4,
       .mulI64,
       .constI64 2,
       .addI64,
       .constI64 8,
       .mulI64,
       .addI64,
       .wrapI64,
       .localGet 83,
       .store64 0,
       .localGet 80,
       .localGet 77,
       .constI64 4,
       .mulI64,
       .constI64 3,
       .addI64,
       .constI64 8,
       .mulI64,
       .addI64,
       .wrapI64,
       .localGet 84,
       .store64 0,
       .localGet 80,
       .localGet 77,
       .constI64 4,
       .mulI64,
       .constI64 4,
       .addI64,
       .constI64 8,
       .mulI64,
       .addI64,
       .wrapI64,
       .localGet 85,
       .store64 0,
       .localGet 80,
       .localSet 75,
       .localGet 75,
       .localSet 22,
       .constI64 0,
       .localSet 23,
       .constI64 1,
       .localSet 24
      ]
     ]
    ],
    .br 0
   ]
  ],
  .localGet 24,
  .constI64 0,
  .eqI64,
  .iff 0 0 [
   .localGet 15,
   .localSet 21,
   .localGet 17,
   .localSet 22,
   .localGet 18,
   .localSet 23
  ] [],
  .localGet 21,
  .localGet 22,
  .localGet 23
 ]

def func14Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func14, results := [.i64, .i64, .i64], typeIdx := some 14 }

/-- Exported function. -/
def func15 : Wasm.Program :=
  [
  .localGet 0,
  .constI64 7,
  .addI64,
  .constI64 8,
  .divUI64,
  .constI64 8,
  .mulI64,
  .localSet 1,
  .localGet 1,
  .constI64 8,
  .ltUI64,
  .iff 0 0 [
   .constI64 8,
   .localSet 1
  ] [],
  .constI64 0,
  .localSet 6,
  .constI64 0,
  .localSet 2,
  .globalGet 1,
  .localSet 3,
  .block 0 0 [
   .loop 0 0 [
    .localGet 3,
    .constI64 0,
    .eqI64,
    .br_if 1,
    .localGet 6,
    .constI64 0,
    .neI64,
    .br_if 1,
    .localGet 3,
    .constI64 32,
    .subI64,
    .wrapI64,
    .load64 0,
    .localSet 4,
    .localGet 3,
    .constI64 8,
    .subI64,
    .wrapI64,
    .load64 0,
    .localSet 5,
    .localGet 4,
    .localGet 1,
    .geUI64,
    .iff 0 0 [
     .localGet 2,
     .constI64 0,
     .eqI64,
     .iff 0 0 [
      .localGet 5,
      .globalSet 1
     ] [
      .localGet 2,
      .constI64 8,
      .subI64,
      .wrapI64,
      .localGet 5,
      .store64 0
     ],
     .localGet 3,
     .constI64 48,
     .subI64,
     .wrapI64,
     .constI64 5501223100278326855,
     .store64 0,
     .localGet 3,
     .constI64 40,
     .subI64,
     .wrapI64,
     .constI64 1,
     .store64 0,
     .localGet 3,
     .constI64 32,
     .subI64,
     .wrapI64,
     .localGet 4,
     .store64 0,
     .localGet 3,
     .constI64 24,
     .subI64,
     .wrapI64,
     .constI64 0,
     .store64 0,
     .localGet 3,
     .constI64 16,
     .subI64,
     .wrapI64,
     .constI64 0,
     .store64 0,
     .localGet 3,
     .constI64 8,
     .subI64,
     .wrapI64,
     .constI64 0,
     .store64 0,
     .localGet 3,
     .localSet 6
    ] [
     .localGet 3,
     .localSet 2,
     .localGet 5,
     .localSet 3
    ],
    .br 0
   ]
  ],
  .localGet 6,
  .constI64 0,
  .eqI64,
  .iff 0 0 [
   .globalGet 0,
   .constI64 48,
   .addI64,
   .localGet 1,
   .addI64,
   .localTee 4,
   .globalGet 0,
   .ltUI64,
   .iff 0 0 [
    .unreachable
   ] [],
   .localGet 4,
   .constI64 1,
   .subI64,
   .constI64 65536,
   .divUI64,
   .constI64 1,
   .addI64,
   .localSet 5,
   .memorySize,
   .extendUI32,
   .localGet 5,
   .ltUI64,
   .iff 0 0 [
    .localGet 5,
    .memorySize,
    .extendUI32,
    .subI64,
    .wrapI64,
    .memoryGrow,
    .const (-1),
    .eq,
    .iff 0 0 [
     .unreachable
    ] []
   ] [],
   .globalGet 0,
   .constI64 48,
   .addI64,
   .localSet 6,
   .localGet 4,
   .globalSet 0,
   .localGet 6,
   .constI64 48,
   .subI64,
   .wrapI64,
   .constI64 5501223100278326855,
   .store64 0,
   .localGet 6,
   .constI64 40,
   .subI64,
   .wrapI64,
   .constI64 1,
   .store64 0,
   .localGet 6,
   .constI64 32,
   .subI64,
   .wrapI64,
   .localGet 1,
   .store64 0,
   .localGet 6,
   .constI64 24,
   .subI64,
   .wrapI64,
   .constI64 0,
   .store64 0,
   .localGet 6,
   .constI64 16,
   .subI64,
   .wrapI64,
   .constI64 0,
   .store64 0,
   .localGet 6,
   .constI64 8,
   .subI64,
   .wrapI64,
   .constI64 0,
   .store64 0
  ] [],
  .globalGet 2,
  .constI64 1,
  .addI64,
  .globalSet 2,
  .localGet 6
 ]

def func15Def : Wasm.Function :=
  { params := [.i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64], body := func15, results := [.i64], typeIdx := some 15 }

/-- Exported function. -/
def func16 : Wasm.Program :=
  [
  .constI64 4096,
  .globalSet 0,
  .constI64 0,
  .globalSet 1,
  .constI64 0,
  .globalSet 2,
  .constI64 0,
  .globalSet 3,
  .constI64 0,
  .globalSet 4,
  .constI64 0,
  .globalSet 5
 ]

def func16Def : Wasm.Function :=
  { body := func16, typeIdx := some 16 }

/-- Exported function. -/
def func17 : Wasm.Program :=
  [
  .localGet 0,
  .constI64 0,
  .neI64,
  .iff 0 0 [
   .localGet 0,
   .constI64 48,
   .subI64,
   .wrapI64,
   .load64 0,
   .constI64 5501223100278326855,
   .neI64,
   .iff 0 0 [
    .unreachable
   ] [],
   .localGet 0,
   .constI64 40,
   .subI64,
   .wrapI64,
   .load64 0,
   .localSet 1,
   .localGet 1,
   .constI64 0,
   .eqI64,
   .iff 0 0 [
    .unreachable
   ] [],
   .globalGet 3,
   .constI64 1,
   .addI64,
   .globalSet 3,
   .localGet 0,
   .constI64 40,
   .subI64,
   .wrapI64,
   .localGet 1,
   .constI64 1,
   .addI64,
   .store64 0
  ] [],
  .localGet 0
 ]

def func17Def : Wasm.Function :=
  { params := [.i64], locals := [.i64], body := func17, results := [.i64], typeIdx := some 17 }

/-- Exported function. -/
def func18 : Wasm.Program :=
  [
  .localGet 0,
  .constI64 0,
  .eqI64,
  .iff 0 0 [
   .ret
  ] [],
  .localGet 0,
  .constI64 48,
  .subI64,
  .wrapI64,
  .load64 0,
  .constI64 5501223100278326855,
  .neI64,
  .iff 0 0 [
   .unreachable
  ] [],
  .localGet 0,
  .constI64 40,
  .subI64,
  .wrapI64,
  .load64 0,
  .localSet 1,
  .localGet 1,
  .constI64 0,
  .eqI64,
  .iff 0 0 [
   .unreachable
  ] [],
  .globalGet 4,
  .constI64 1,
  .addI64,
  .globalSet 4,
  .constI64 1,
  .localGet 1,
  .ltUI64,
  .iff 0 0 [
   .localGet 0,
   .constI64 40,
   .subI64,
   .wrapI64,
   .localGet 1,
   .constI64 1,
   .subI64,
   .store64 0,
   .ret
  ] [],
  .localGet 0,
  .constI64 24,
  .subI64,
  .wrapI64,
  .load64 0,
  .localSet 2,
  .localGet 2,
  .constI64 1,
  .eqI64,
  .iff 0 0 [
   .localGet 0,
   .constI64 16,
   .subI64,
   .wrapI64,
   .load64 0,
   .localSet 3,
   .localGet 0,
   .constI64 8,
   .subI64,
   .wrapI64,
   .load64 0,
   .localSet 5,
   .constI64 0,
   .localSet 6,
   .block 0 0 [
    .loop 0 0 [
     .localGet 6,
     .localGet 3,
     .geUI64,
     .br_if 1,
     .localGet 5,
     .localGet 6,
     .shrUI64,
     .constI64 1,
     .andI64,
     .constI64 0,
     .neI64,
     .iff 0 0 [
      .localGet 0,
      .localGet 6,
      .constI64 8,
      .mulI64,
      .addI64,
      .wrapI64,
      .load64 0,
      .localSet 8,
      .localGet 8,
      .call 18
     ] [],
     .localGet 6,
     .constI64 1,
     .addI64,
     .localSet 6,
     .br 0
    ]
   ]
  ] [],
  .localGet 2,
  .constI64 2,
  .eqI64,
  .iff 0 0 [
   .localGet 0,
   .wrapI64,
   .load64 0,
   .localSet 3,
   .localGet 0,
   .constI64 16,
   .subI64,
   .wrapI64,
   .load64 0,
   .localSet 4,
   .localGet 0,
   .constI64 8,
   .subI64,
   .wrapI64,
   .load64 0,
   .localSet 5,
   .constI64 0,
   .localSet 7,
   .block 0 0 [
    .loop 0 0 [
     .localGet 7,
     .localGet 3,
     .geUI64,
     .br_if 1,
     .constI64 0,
     .localSet 6,
     .block 0 0 [
      .loop 0 0 [
       .localGet 6,
       .localGet 4,
       .geUI64,
       .br_if 1,
       .localGet 5,
       .localGet 6,
       .shrUI64,
       .constI64 1,
       .andI64,
       .constI64 0,
       .neI64,
       .iff 0 0 [
        .localGet 0,
        .constI64 8,
        .addI64,
        .localGet 7,
        .localGet 4,
        .mulI64,
        .localGet 6,
        .addI64,
        .constI64 8,
        .mulI64,
        .addI64,
        .wrapI64,
        .load64 0,
        .localSet 8,
        .localGet 8,
        .call 18
       ] [],
       .localGet 6,
       .constI64 1,
       .addI64,
       .localSet 6,
       .br 0
      ]
     ],
     .localGet 7,
     .constI64 1,
     .addI64,
     .localSet 7,
     .br 0
    ]
   ]
  ] [],
  .globalGet 5,
  .constI64 1,
  .addI64,
  .globalSet 5,
  .localGet 0,
  .constI64 40,
  .subI64,
  .wrapI64,
  .constI64 0,
  .store64 0,
  .localGet 0,
  .constI64 8,
  .subI64,
  .wrapI64,
  .globalGet 1,
  .store64 0,
  .localGet 0,
  .globalSet 1
 ]

def func18Def : Wasm.Function :=
  { params := [.i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func18, typeIdx := some 18 }

def «module» : Wasm.Module :=
{
  funcs := [
   func0Def,
   func1Def,
   func2Def,
   func3Def,
   func4Def,
   func5Def,
   func6Def,
   func7Def,
   func8Def,
   func9Def,
   func10Def,
   func11Def,
   func12Def,
   func13Def,
   func14Def,
   func15Def,
   func16Def,
   func17Def,
   func18Def
  ],
  exports := [
   { name := "matchFuel", funcIdx := 14 },
   { name := "alloc", funcIdx := 15 },
   { name := "reset", funcIdx := 16 },
   { name := "retain", funcIdx := 17 },
   { name := "release", funcIdx := 18 },
   { name := "free", funcIdx := 18 }
  ],
  memory := some ({ pagesMin := 16 }),
  globals := [
   { init := .i64 4096, declaredType := some (.i64), sourceInit := some ([
     .constI64 4096
    ]) },
   { init := .i64 0, declaredType := some (.i64), sourceInit := some ([
     .constI64 0
    ]) },
   { init := .i64 0, declaredType := some (.i64), sourceInit := some ([
     .constI64 0
    ]) },
   { init := .i64 0, declaredType := some (.i64), sourceInit := some ([
     .constI64 0
    ]) },
   { init := .i64 0, declaredType := some (.i64), sourceInit := some ([
     .constI64 0
    ]) },
   { init := .i64 0, declaredType := some (.i64), sourceInit := some ([
     .constI64 0
    ]) }
  ],
  types := [
   { params := [.i64, .i64, .i64, .i64, .i64], results := [.i64] },
   { params := [.i64, .i64, .i64, .i64, .i64], results := [.i64] },
   { params := [.i64], results := [.i64] },
   { params := [.i64, .i64, .i64, .i64, .i64], results := [.i64] },
   { params := [.i64, .i64, .i64, .i64, .i64], results := [.i64] },
   { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64] },
   { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64] },
   { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64] },
   { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64, .i64] },
   { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64, .i64] },
   { params := [.i64, .i64, .i64, .i64, .i64], results := [.i64, .i64] },
   { params := [.i64, .i64, .i64, .i64, .i64], results := [.i64] },
   { params := [.i64, .i64, .i64, .i64, .i64], results := [.i64, .i64] },
   { params := [.i64, .i64, .i64, .i64, .i64], results := [.i64] },
   { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64, .i64, .i64] },
   { params := [.i64], results := [.i64] },
   {},
   { params := [.i64], results := [.i64] },
   { params := [.i64] }
  ],
  gcTypes := [
   { comp := .func ({ params := [.i64, .i64, .i64, .i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64, .i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64, .i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64, .i64], results := [.i64, .i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64, .i64], results := [.i64, .i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64, .i64, .i64] }) },
   { comp := .func ({ params := [.i64], results := [.i64] }) },
   { comp := .func ({}) },
   { comp := .func ({ params := [.i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64] }) }
  ],
  globalExports := [
   ("allocCount", 2),
   ("retainCount", 3),
   ("releaseCount", 4),
   ("freeCount", 5)
  ],
  memoryExports := [
   ("memory", 0)
  ]
}

end Project.ClobMatchFuel
