/-
  AUTO-GENERATED by `verifier emit`. Do not edit by hand.
-/

import Project.TalosPrelude

set_option maxRecDepth 1048576

namespace Project.EulerDynamicFlux

open Wasm

def func0 : Wasm.Program :=
  [
  .constI64 0,
  .localGet 0,
  .ltUI64,
  .iff 0 1 [
   .localGet 0,
   .constI64 9218868437227405312,
   .ltUI64
  ] [
   .const 0
  ] [] [.i32],
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .localSet 1,
  .localGet 1
 ]

def func0Def : Wasm.Function :=
  { params := [.i64], locals := [.i64], body := func0, results := [.i64], typeIdx := some 0 }

def func1 : Wasm.Program :=
  [
  .localGet 0,
  .constI64 9223372036854775807,
  .andI64,
  .localSet 1,
  .localGet 1
 ]

def func1Def : Wasm.Function :=
  { params := [.i64], locals := [.i64], body := func1, results := [.i64], typeIdx := some 1 }

def func2 : Wasm.Program :=
  [
  .localGet 0,
  .localSet 1,
  .localGet 1,
  .call 1,
  .constI64 9218868437227405312,
  .ltUI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .localSet 2,
  .localGet 2
 ]

def func2Def : Wasm.Function :=
  { params := [.i64], locals := [.i64, .i64], body := func2, results := [.i64], typeIdx := some 2 }

def func3 : Wasm.Program :=
  [
  .localGet 0,
  .localSet 3,
  .localGet 3,
  .call 0,
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 1 [
   .localGet 1,
   .localSet 4,
   .localGet 4,
   .call 2,
   .constI64 0,
   .eqI64,
   .eqz
  ] [
   .const 0
  ] [] [.i32],
  .iff 0 1 [
   .localGet 2,
   .localSet 5,
   .localGet 5,
   .call 0,
   .constI64 0,
   .eqI64,
   .eqz
  ] [
   .const 0
  ] [] [.i32],
  .iff 0 1 [
   .localGet 1,
   .localSet 6,
   .localGet 6,
   .call 1,
   .localGet 0,
   .leUI64
  ] [
   .const 0
  ] [] [.i32],
  .iff 0 1 [
   .localGet 0,
   .localGet 2,
   .leUI64
  ] [
   .const 0
  ] [] [.i32],
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .localSet 7,
  .localGet 7
 ]

def func3Def : Wasm.Function :=
  { params := [.i64, .i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64], body := func3, results := [.i64], typeIdx := some 3 }

def func4 : Wasm.Program :=
  [
  .constI64 1,
  .localSet 0,
  .constI64 0,
  .localSet 1,
  .constI64 0,
  .localSet 2,
  .constI64 0,
  .localSet 3,
  .constI64 0,
  .localSet 4,
  .constI64 0,
  .localSet 5,
  .constI64 0,
  .localSet 6,
  .localGet 0,
  .localGet 1,
  .localGet 2,
  .localGet 3,
  .localGet 4,
  .localGet 5,
  .localGet 6
 ]

def func4Def : Wasm.Function :=
  { locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func4, results := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], typeIdx := some 4 }

def func5 : Wasm.Program :=
  [
  .localGet 0,
  .localSet 3,
  .localGet 1,
  .localSet 4,
  .localGet 2,
  .localSet 5,
  .localGet 3,
  .localGet 4,
  .localGet 5,
  .call 3,
  .localSet 6,
  .localGet 6,
  .constI64 1,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 0 [
   .localGet 1,
   .f64ReinterpretI64,
   .localGet 0,
   .f64ReinterpretI64,
   .f64Div,
   .i64ReinterpretF64,
   .localSet 7,
   .localGet 1,
   .f64ReinterpretI64,
   .localGet 7,
   .f64ReinterpretI64,
   .f64Mul,
   .i64ReinterpretF64,
   .localSet 8,
   .constI64 4602678819172646912,
   .f64ReinterpretI64,
   .localGet 8,
   .f64ReinterpretI64,
   .f64Mul,
   .i64ReinterpretF64,
   .localSet 9,
   .localGet 2,
   .f64ReinterpretI64,
   .localGet 9,
   .f64ReinterpretI64,
   .f64Sub,
   .i64ReinterpretF64,
   .localSet 10,
   .localGet 7,
   .localSet 11,
   .localGet 11,
   .call 2,
   .constI64 0,
   .eqI64,
   .eqz,
   .iff 0 1 [
    .localGet 8,
    .localSet 12,
    .localGet 12,
    .call 2,
    .constI64 0,
    .eqI64,
    .eqz
   ] [
    .const 0
   ] [] [.i32],
   .iff 0 1 [
    .localGet 9,
    .localSet 13,
    .localGet 13,
    .call 2,
    .constI64 0,
    .eqI64,
    .eqz
   ] [
    .const 0
   ] [] [.i32],
   .iff 0 1 [
    .localGet 10,
    .localSet 14,
    .localGet 14,
    .call 0,
    .constI64 0,
    .eqI64,
    .eqz
   ] [
    .const 0
   ] [] [.i32],
   .iff 0 1 [
    .constI64 1
   ] [
    .constI64 0
   ] [] [.i64],
   .constI64 1,
   .eqI64,
   .iff 0 1 [
    .constI64 1
   ] [
    .constI64 0
   ] [] [.i64],
   .constI64 0,
   .eqI64,
   .eqz,
   .iff 0 0 [
    .constI64 4600877379321698714,
    .f64ReinterpretI64,
    .localGet 10,
    .f64ReinterpretI64,
    .f64Mul,
    .i64ReinterpretF64,
    .localSet 15,
    .localGet 15,
    .f64ReinterpretI64,
    .localGet 0,
    .f64ReinterpretI64,
    .f64Div,
    .i64ReinterpretF64,
    .localSet 16,
    .constI64 4608983858650965606,
    .f64ReinterpretI64,
    .localGet 16,
    .f64ReinterpretI64,
    .f64Mul,
    .i64ReinterpretF64,
    .localSet 17,
    .localGet 15,
    .localSet 18,
    .localGet 18,
    .call 0,
    .constI64 0,
    .eqI64,
    .eqz,
    .iff 0 1 [
     .localGet 16,
     .localSet 19,
     .localGet 19,
     .call 0,
     .constI64 0,
     .eqI64,
     .eqz
    ] [
     .const 0
    ] [] [.i32],
    .iff 0 1 [
     .localGet 17,
     .localSet 20,
     .localGet 20,
     .call 0,
     .constI64 0,
     .eqI64,
     .eqz
    ] [
     .const 0
    ] [] [.i32],
    .iff 0 1 [
     .constI64 1
    ] [
     .constI64 0
    ] [] [.i64],
    .constI64 1,
    .eqI64,
    .iff 0 1 [
     .constI64 1
    ] [
     .constI64 0
    ] [] [.i64],
    .constI64 0,
    .eqI64,
    .eqz,
    .iff 0 0 [
     .localGet 17,
     .f64ReinterpretI64,
     .f64Sqrt,
     .i64ReinterpretF64,
     .localSet 21,
     .localGet 7,
     .localSet 22,
     .localGet 22,
     .call 1,
     .f64ReinterpretI64,
     .localGet 21,
     .f64ReinterpretI64,
     .f64Add,
     .i64ReinterpretF64,
     .localSet 23,
     .localGet 8,
     .f64ReinterpretI64,
     .localGet 15,
     .f64ReinterpretI64,
     .f64Add,
     .i64ReinterpretF64,
     .localSet 24,
     .localGet 2,
     .f64ReinterpretI64,
     .localGet 15,
     .f64ReinterpretI64,
     .f64Add,
     .i64ReinterpretF64,
     .localSet 25,
     .localGet 7,
     .f64ReinterpretI64,
     .localGet 25,
     .f64ReinterpretI64,
     .f64Mul,
     .i64ReinterpretF64,
     .localSet 26,
     .localGet 21,
     .localSet 27,
     .localGet 27,
     .call 0,
     .constI64 0,
     .eqI64,
     .eqz,
     .iff 0 1 [
      .localGet 23,
      .localSet 28,
      .localGet 28,
      .call 0,
      .constI64 0,
      .eqI64,
      .eqz
     ] [
      .const 0
     ] [] [.i32],
     .iff 0 1 [
      .localGet 24,
      .localSet 29,
      .localGet 29,
      .call 2,
      .constI64 0,
      .eqI64,
      .eqz
     ] [
      .const 0
     ] [] [.i32],
     .iff 0 1 [
      .localGet 25,
      .localSet 30,
      .localGet 30,
      .call 2,
      .constI64 0,
      .eqI64,
      .eqz
     ] [
      .const 0
     ] [] [.i32],
     .iff 0 1 [
      .localGet 26,
      .localSet 31,
      .localGet 31,
      .call 2,
      .constI64 0,
      .eqI64,
      .eqz
     ] [
      .const 0
     ] [] [.i32],
     .iff 0 1 [
      .constI64 1
     ] [
      .constI64 0
     ] [] [.i64],
     .constI64 1,
     .eqI64,
     .iff 0 1 [
      .constI64 1
     ] [
      .constI64 0
     ] [] [.i64],
     .constI64 0,
     .eqI64,
     .eqz,
     .iff 0 0 [
      .constI64 0,
      .localSet 60,
      .localGet 7,
      .localSet 61,
      .localGet 15,
      .localSet 62,
      .localGet 23,
      .localSet 63,
      .localGet 1,
      .localSet 64,
      .localGet 24,
      .localSet 65,
      .localGet 26,
      .localSet 66
     ] [
      .call 4,
      .localSet 38,
      .localSet 37,
      .localSet 36,
      .localSet 35,
      .localSet 34,
      .localSet 33,
      .localSet 32,
      .localGet 32,
      .localSet 60,
      .localGet 33,
      .localSet 61,
      .localGet 34,
      .localSet 62,
      .localGet 35,
      .localSet 63,
      .localGet 36,
      .localSet 64,
      .localGet 37,
      .localSet 65,
      .localGet 38,
      .localSet 66
     ]
    ] [
     .call 4,
     .localSet 45,
     .localSet 44,
     .localSet 43,
     .localSet 42,
     .localSet 41,
     .localSet 40,
     .localSet 39,
     .localGet 39,
     .localSet 60,
     .localGet 40,
     .localSet 61,
     .localGet 41,
     .localSet 62,
     .localGet 42,
     .localSet 63,
     .localGet 43,
     .localSet 64,
     .localGet 44,
     .localSet 65,
     .localGet 45,
     .localSet 66
    ]
   ] [
    .call 4,
    .localSet 52,
    .localSet 51,
    .localSet 50,
    .localSet 49,
    .localSet 48,
    .localSet 47,
    .localSet 46,
    .localGet 46,
    .localSet 60,
    .localGet 47,
    .localSet 61,
    .localGet 48,
    .localSet 62,
    .localGet 49,
    .localSet 63,
    .localGet 50,
    .localSet 64,
    .localGet 51,
    .localSet 65,
    .localGet 52,
    .localSet 66
   ]
  ] [
   .call 4,
   .localSet 59,
   .localSet 58,
   .localSet 57,
   .localSet 56,
   .localSet 55,
   .localSet 54,
   .localSet 53,
   .localGet 53,
   .localSet 60,
   .localGet 54,
   .localSet 61,
   .localGet 55,
   .localSet 62,
   .localGet 56,
   .localSet 63,
   .localGet 57,
   .localSet 64,
   .localGet 58,
   .localSet 65,
   .localGet 59,
   .localSet 66
  ],
  .localGet 60,
  .localGet 61,
  .localGet 62,
  .localGet 63,
  .localGet 64,
  .localGet 65,
  .localGet 66
 ]

def func5Def : Wasm.Function :=
  { params := [.i64, .i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func5, results := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], typeIdx := some 5 }

def func6 : Wasm.Program :=
  [
  .localGet 0,
  .localSet 7,
  .localGet 7
 ]

def func6Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], locals := [.i64], body := func6, results := [.i64], typeIdx := some 6 }

def func7 : Wasm.Program :=
  [
  .localGet 3,
  .localSet 7,
  .localGet 7
 ]

def func7Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], locals := [.i64], body := func7, results := [.i64], typeIdx := some 7 }

def func8 : Wasm.Program :=
  [
  .constI64 1,
  .localSet 0,
  .constI64 0,
  .localSet 1,
  .localGet 0,
  .localGet 1
 ]

def func8Def : Wasm.Function :=
  { locals := [.i64, .i64], body := func8, results := [.i64, .i64], typeIdx := some 8 }

def func9 : Wasm.Program :=
  [
  .localGet 0,
  .localSet 5,
  .localGet 5,
  .call 0,
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 1 [
   .localGet 1,
   .localSet 6,
   .localGet 6,
   .call 2,
   .constI64 0,
   .eqI64,
   .eqz
  ] [
   .const 0
  ] [] [.i32],
  .iff 0 1 [
   .localGet 2,
   .localSet 7,
   .localGet 7,
   .call 2,
   .constI64 0,
   .eqI64,
   .eqz
  ] [
   .const 0
  ] [] [.i32],
  .iff 0 1 [
   .localGet 3,
   .localSet 8,
   .localGet 8,
   .call 2,
   .constI64 0,
   .eqI64,
   .eqz
  ] [
   .const 0
  ] [] [.i32],
  .iff 0 1 [
   .localGet 4,
   .localSet 9,
   .localGet 9,
   .call 2,
   .constI64 0,
   .eqI64,
   .eqz
  ] [
   .const 0
  ] [] [.i32],
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 1,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 0 [
   .localGet 1,
   .f64ReinterpretI64,
   .localGet 2,
   .f64ReinterpretI64,
   .f64Add,
   .i64ReinterpretF64,
   .localSet 10,
   .constI64 4602678819172646912,
   .f64ReinterpretI64,
   .localGet 10,
   .f64ReinterpretI64,
   .f64Mul,
   .i64ReinterpretF64,
   .localSet 11,
   .localGet 4,
   .f64ReinterpretI64,
   .localGet 3,
   .f64ReinterpretI64,
   .f64Sub,
   .i64ReinterpretF64,
   .localSet 12,
   .localGet 0,
   .f64ReinterpretI64,
   .localGet 12,
   .f64ReinterpretI64,
   .f64Mul,
   .i64ReinterpretF64,
   .localSet 13,
   .constI64 4602678819172646912,
   .f64ReinterpretI64,
   .localGet 13,
   .f64ReinterpretI64,
   .f64Mul,
   .i64ReinterpretF64,
   .localSet 14,
   .localGet 11,
   .f64ReinterpretI64,
   .localGet 14,
   .f64ReinterpretI64,
   .f64Sub,
   .i64ReinterpretF64,
   .localSet 15,
   .localGet 10,
   .localSet 16,
   .localGet 16,
   .call 2,
   .constI64 0,
   .eqI64,
   .eqz,
   .iff 0 1 [
    .localGet 11,
    .localSet 17,
    .localGet 17,
    .call 2,
    .constI64 0,
    .eqI64,
    .eqz
   ] [
    .const 0
   ] [] [.i32],
   .iff 0 1 [
    .localGet 12,
    .localSet 18,
    .localGet 18,
    .call 2,
    .constI64 0,
    .eqI64,
    .eqz
   ] [
    .const 0
   ] [] [.i32],
   .iff 0 1 [
    .localGet 13,
    .localSet 19,
    .localGet 19,
    .call 2,
    .constI64 0,
    .eqI64,
    .eqz
   ] [
    .const 0
   ] [] [.i32],
   .iff 0 1 [
    .localGet 14,
    .localSet 20,
    .localGet 20,
    .call 2,
    .constI64 0,
    .eqI64,
    .eqz
   ] [
    .const 0
   ] [] [.i32],
   .iff 0 1 [
    .localGet 15,
    .localSet 21,
    .localGet 21,
    .call 2,
    .constI64 0,
    .eqI64,
    .eqz
   ] [
    .const 0
   ] [] [.i32],
   .iff 0 1 [
    .constI64 1
   ] [
    .constI64 0
   ] [] [.i64],
   .constI64 1,
   .eqI64,
   .iff 0 1 [
    .constI64 1
   ] [
    .constI64 0
   ] [] [.i64],
   .constI64 0,
   .eqI64,
   .eqz,
   .iff 0 0 [
    .constI64 0,
    .localSet 26,
    .localGet 15,
    .localSet 27
   ] [
    .call 8,
    .localSet 23,
    .localSet 22,
    .localGet 22,
    .localSet 26,
    .localGet 23,
    .localSet 27
   ]
  ] [
   .call 8,
   .localSet 25,
   .localSet 24,
   .localGet 24,
   .localSet 26,
   .localGet 25,
   .localSet 27
  ],
  .localGet 26,
  .localGet 27
 ]

def func9Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func9, results := [.i64, .i64], typeIdx := some 9 }

def func10 : Wasm.Program :=
  [
  .localGet 4,
  .localSet 7,
  .localGet 7
 ]

def func10Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], locals := [.i64], body := func10, results := [.i64], typeIdx := some 10 }

def func11 : Wasm.Program :=
  [
  .localGet 5,
  .localSet 7,
  .localGet 7
 ]

def func11Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], locals := [.i64], body := func11, results := [.i64], typeIdx := some 11 }

def func12 : Wasm.Program :=
  [
  .localGet 6,
  .localSet 7,
  .localGet 7
 ]

def func12Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], locals := [.i64], body := func12, results := [.i64], typeIdx := some 12 }

def func13 : Wasm.Program :=
  [
  .localGet 0,
  .localSet 2,
  .localGet 2
 ]

def func13Def : Wasm.Function :=
  { params := [.i64, .i64], locals := [.i64], body := func13, results := [.i64], typeIdx := some 13 }

def func14 : Wasm.Program :=
  [
  .localGet 1,
  .localSet 2,
  .localGet 2
 ]

def func14Def : Wasm.Function :=
  { params := [.i64, .i64], locals := [.i64], body := func14, results := [.i64], typeIdx := some 14 }

def func15 : Wasm.Program :=
  [
  .constI64 1,
  .localSet 0,
  .constI64 0,
  .localSet 1,
  .constI64 0,
  .localSet 2,
  .constI64 0,
  .localSet 3,
  .constI64 0,
  .localSet 4,
  .localGet 0,
  .localGet 1,
  .localGet 2,
  .localGet 3,
  .localGet 4
 ]

def func15Def : Wasm.Function :=
  { locals := [.i64, .i64, .i64, .i64, .i64], body := func15, results := [.i64, .i64, .i64, .i64, .i64], typeIdx := some 15 }

/-- Exported function. -/
def func16 : Wasm.Program :=
  [
  .localGet 0,
  .localSet 6,
  .localGet 1,
  .localSet 7,
  .localGet 2,
  .localSet 8,
  .localGet 6,
  .localGet 7,
  .localGet 8,
  .call 5,
  .localSet 15,
  .localSet 14,
  .localSet 13,
  .localSet 12,
  .localSet 11,
  .localSet 10,
  .localSet 9,
  .localGet 9,
  .localSet 16,
  .localGet 12,
  .localSet 19,
  .localGet 13,
  .localSet 20,
  .localGet 14,
  .localSet 21,
  .localGet 15,
  .localSet 22,
  .localGet 16,
  .constI64 0,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 1,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 0 [
   .localGet 3,
   .localSet 23,
   .localGet 4,
   .localSet 24,
   .localGet 5,
   .localSet 25,
   .localGet 23,
   .localGet 24,
   .localGet 25,
   .call 5,
   .localSet 32,
   .localSet 31,
   .localSet 30,
   .localSet 29,
   .localSet 28,
   .localSet 27,
   .localSet 26,
   .localGet 26,
   .localSet 33,
   .localGet 29,
   .localSet 36,
   .localGet 30,
   .localSet 37,
   .localGet 31,
   .localSet 38,
   .localGet 32,
   .localSet 39,
   .localGet 33,
   .constI64 0,
   .eqI64,
   .iff 0 1 [
    .constI64 1
   ] [
    .constI64 0
   ] [] [.i64],
   .constI64 1,
   .eqI64,
   .iff 0 1 [
    .constI64 1
   ] [
    .constI64 0
   ] [] [.i64],
   .constI64 0,
   .eqI64,
   .eqz,
   .iff 0 0 [
    .localGet 19,
    .localGet 36,
    .leUI64,
    .iff 0 1 [
     .localGet 36
    ] [
     .localGet 19
    ] [] [.i64],
    .localSet 40,
    .localGet 40,
    .localSet 41,
    .localGet 20,
    .localSet 42,
    .localGet 37,
    .localSet 43,
    .localGet 0,
    .localSet 44,
    .localGet 3,
    .localSet 45,
    .localGet 41,
    .localGet 42,
    .localGet 43,
    .localGet 44,
    .localGet 45,
    .call 9,
    .localSet 47,
    .localSet 46,
    .localGet 46,
    .localSet 48,
    .localGet 47,
    .localSet 49,
    .localGet 40,
    .localSet 50,
    .localGet 21,
    .localSet 51,
    .localGet 38,
    .localSet 52,
    .localGet 1,
    .localSet 53,
    .localGet 4,
    .localSet 54,
    .localGet 50,
    .localGet 51,
    .localGet 52,
    .localGet 53,
    .localGet 54,
    .call 9,
    .localSet 56,
    .localSet 55,
    .localGet 55,
    .localSet 57,
    .localGet 56,
    .localSet 58,
    .localGet 40,
    .localSet 59,
    .localGet 22,
    .localSet 60,
    .localGet 39,
    .localSet 61,
    .localGet 2,
    .localSet 62,
    .localGet 5,
    .localSet 63,
    .localGet 59,
    .localGet 60,
    .localGet 61,
    .localGet 62,
    .localGet 63,
    .call 9,
    .localSet 65,
    .localSet 64,
    .localGet 64,
    .localSet 66,
    .localGet 65,
    .localSet 67,
    .localGet 48,
    .constI64 0,
    .eqI64,
    .iff 0 1 [
     .constI64 1
    ] [
     .constI64 0
    ] [] [.i64],
    .constI64 0,
    .eqI64,
    .eqz,
    .iff 0 1 [
     .localGet 57,
     .constI64 0,
     .eqI64,
     .iff 0 1 [
      .constI64 1
     ] [
      .constI64 0
     ] [] [.i64],
     .constI64 0,
     .eqI64,
     .eqz
    ] [
     .const 0
    ] [] [.i32],
    .iff 0 1 [
     .localGet 66,
     .constI64 0,
     .eqI64,
     .iff 0 1 [
      .constI64 1
     ] [
      .constI64 0
     ] [] [.i64],
     .constI64 0,
     .eqI64,
     .eqz
    ] [
     .const 0
    ] [] [.i32],
    .iff 0 1 [
     .constI64 1
    ] [
     .constI64 0
    ] [] [.i64],
    .constI64 1,
    .eqI64,
    .iff 0 1 [
     .constI64 1
    ] [
     .constI64 0
    ] [] [.i64],
    .constI64 0,
    .eqI64,
    .eqz,
    .iff 0 0 [
     .constI64 0,
     .localSet 83,
     .localGet 49,
     .localSet 84,
     .localGet 58,
     .localSet 85,
     .localGet 67,
     .localSet 86,
     .localGet 40,
     .localSet 87
    ] [
     .call 15,
     .localSet 72,
     .localSet 71,
     .localSet 70,
     .localSet 69,
     .localSet 68,
     .localGet 68,
     .localSet 83,
     .localGet 69,
     .localSet 84,
     .localGet 70,
     .localSet 85,
     .localGet 71,
     .localSet 86,
     .localGet 72,
     .localSet 87
    ]
   ] [
    .call 15,
    .localSet 77,
    .localSet 76,
    .localSet 75,
    .localSet 74,
    .localSet 73,
    .localGet 73,
    .localSet 83,
    .localGet 74,
    .localSet 84,
    .localGet 75,
    .localSet 85,
    .localGet 76,
    .localSet 86,
    .localGet 77,
    .localSet 87
   ]
  ] [
   .call 15,
   .localSet 82,
   .localSet 81,
   .localSet 80,
   .localSet 79,
   .localSet 78,
   .localGet 78,
   .localSet 83,
   .localGet 79,
   .localSet 84,
   .localGet 80,
   .localSet 85,
   .localGet 81,
   .localSet 86,
   .localGet 82,
   .localSet 87
  ],
  .localGet 83,
  .localGet 84,
  .localGet 85,
  .localGet 86,
  .localGet 87
 ]

def func16Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func16, results := [.i64, .i64, .i64, .i64, .i64], typeIdx := some 16 }

/-- Exported function. -/
def func17 : Wasm.Program :=
  [
  .localGet 0,
  .constI64 7,
  .addI64,
  .constI64 8,
  .divUI64,
  .constI64 8,
  .mulI64,
  .localSet 1,
  .localGet 1,
  .constI64 8,
  .ltUI64,
  .iff 0 0 [
   .constI64 8,
   .localSet 1
  ] [],
  .constI64 0,
  .localSet 6,
  .constI64 0,
  .localSet 2,
  .globalGet 1,
  .localSet 3,
  .block 0 0 [
   .loop 0 0 [
    .localGet 3,
    .constI64 0,
    .eqI64,
    .br_if 1,
    .localGet 6,
    .constI64 0,
    .neI64,
    .br_if 1,
    .localGet 3,
    .constI64 32,
    .subI64,
    .wrapI64,
    .load64 0,
    .localSet 4,
    .localGet 3,
    .constI64 8,
    .subI64,
    .wrapI64,
    .load64 0,
    .localSet 5,
    .localGet 4,
    .localGet 1,
    .geUI64,
    .iff 0 0 [
     .localGet 2,
     .constI64 0,
     .eqI64,
     .iff 0 0 [
      .localGet 5,
      .globalSet 1
     ] [
      .localGet 2,
      .constI64 8,
      .subI64,
      .wrapI64,
      .localGet 5,
      .store64 0
     ],
     .localGet 3,
     .constI64 48,
     .subI64,
     .wrapI64,
     .constI64 5501223100278326855,
     .store64 0,
     .localGet 3,
     .constI64 40,
     .subI64,
     .wrapI64,
     .constI64 1,
     .store64 0,
     .localGet 3,
     .constI64 32,
     .subI64,
     .wrapI64,
     .localGet 4,
     .store64 0,
     .localGet 3,
     .constI64 24,
     .subI64,
     .wrapI64,
     .constI64 0,
     .store64 0,
     .localGet 3,
     .constI64 16,
     .subI64,
     .wrapI64,
     .constI64 0,
     .store64 0,
     .localGet 3,
     .constI64 8,
     .subI64,
     .wrapI64,
     .constI64 0,
     .store64 0,
     .localGet 3,
     .localSet 6
    ] [
     .localGet 3,
     .localSet 2,
     .localGet 5,
     .localSet 3
    ],
    .br 0
   ]
  ],
  .localGet 6,
  .constI64 0,
  .eqI64,
  .iff 0 0 [
   .globalGet 0,
   .constI64 48,
   .addI64,
   .localGet 1,
   .addI64,
   .localTee 4,
   .globalGet 0,
   .ltUI64,
   .iff 0 0 [
    .unreachable
   ] [],
   .localGet 4,
   .constI64 1,
   .subI64,
   .constI64 65536,
   .divUI64,
   .constI64 1,
   .addI64,
   .localSet 5,
   .memorySize,
   .extendUI32,
   .localGet 5,
   .ltUI64,
   .iff 0 0 [
    .localGet 5,
    .memorySize,
    .extendUI32,
    .subI64,
    .wrapI64,
    .memoryGrow,
    .const (-1),
    .eq,
    .iff 0 0 [
     .unreachable
    ] []
   ] [],
   .globalGet 0,
   .constI64 48,
   .addI64,
   .localSet 6,
   .localGet 4,
   .globalSet 0,
   .localGet 6,
   .constI64 48,
   .subI64,
   .wrapI64,
   .constI64 5501223100278326855,
   .store64 0,
   .localGet 6,
   .constI64 40,
   .subI64,
   .wrapI64,
   .constI64 1,
   .store64 0,
   .localGet 6,
   .constI64 32,
   .subI64,
   .wrapI64,
   .localGet 1,
   .store64 0,
   .localGet 6,
   .constI64 24,
   .subI64,
   .wrapI64,
   .constI64 0,
   .store64 0,
   .localGet 6,
   .constI64 16,
   .subI64,
   .wrapI64,
   .constI64 0,
   .store64 0,
   .localGet 6,
   .constI64 8,
   .subI64,
   .wrapI64,
   .constI64 0,
   .store64 0
  ] [],
  .globalGet 2,
  .constI64 1,
  .addI64,
  .globalSet 2,
  .localGet 6
 ]

def func17Def : Wasm.Function :=
  { params := [.i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64], body := func17, results := [.i64], typeIdx := some 17 }

/-- Exported function. -/
def func18 : Wasm.Program :=
  [
  .constI64 4096,
  .globalSet 0,
  .constI64 0,
  .globalSet 1,
  .constI64 0,
  .globalSet 2,
  .constI64 0,
  .globalSet 3,
  .constI64 0,
  .globalSet 4,
  .constI64 0,
  .globalSet 5
 ]

def func18Def : Wasm.Function :=
  { body := func18, typeIdx := some 18 }

/-- Exported function. -/
def func19 : Wasm.Program :=
  [
  .localGet 0,
  .constI64 0,
  .neI64,
  .iff 0 0 [
   .localGet 0,
   .constI64 48,
   .subI64,
   .wrapI64,
   .load64 0,
   .constI64 5501223100278326855,
   .neI64,
   .iff 0 0 [
    .unreachable
   ] [],
   .localGet 0,
   .constI64 40,
   .subI64,
   .wrapI64,
   .load64 0,
   .localSet 1,
   .localGet 1,
   .constI64 0,
   .eqI64,
   .iff 0 0 [
    .unreachable
   ] [],
   .globalGet 3,
   .constI64 1,
   .addI64,
   .globalSet 3,
   .localGet 0,
   .constI64 40,
   .subI64,
   .wrapI64,
   .localGet 1,
   .constI64 1,
   .addI64,
   .store64 0
  ] [],
  .localGet 0
 ]

def func19Def : Wasm.Function :=
  { params := [.i64], locals := [.i64], body := func19, results := [.i64], typeIdx := some 19 }

/-- Exported function. -/
def func20 : Wasm.Program :=
  [
  .localGet 0,
  .constI64 0,
  .eqI64,
  .iff 0 0 [
   .ret
  ] [],
  .localGet 0,
  .constI64 48,
  .subI64,
  .wrapI64,
  .load64 0,
  .constI64 5501223100278326855,
  .neI64,
  .iff 0 0 [
   .unreachable
  ] [],
  .localGet 0,
  .constI64 40,
  .subI64,
  .wrapI64,
  .load64 0,
  .localSet 1,
  .localGet 1,
  .constI64 0,
  .eqI64,
  .iff 0 0 [
   .unreachable
  ] [],
  .globalGet 4,
  .constI64 1,
  .addI64,
  .globalSet 4,
  .constI64 1,
  .localGet 1,
  .ltUI64,
  .iff 0 0 [
   .localGet 0,
   .constI64 40,
   .subI64,
   .wrapI64,
   .localGet 1,
   .constI64 1,
   .subI64,
   .store64 0,
   .ret
  ] [],
  .localGet 0,
  .constI64 24,
  .subI64,
  .wrapI64,
  .load64 0,
  .localSet 2,
  .localGet 2,
  .constI64 1,
  .eqI64,
  .iff 0 0 [
   .localGet 0,
   .constI64 16,
   .subI64,
   .wrapI64,
   .load64 0,
   .localSet 3,
   .localGet 0,
   .constI64 8,
   .subI64,
   .wrapI64,
   .load64 0,
   .localSet 5,
   .constI64 0,
   .localSet 6,
   .block 0 0 [
    .loop 0 0 [
     .localGet 6,
     .localGet 3,
     .geUI64,
     .br_if 1,
     .localGet 5,
     .localGet 6,
     .shrUI64,
     .constI64 1,
     .andI64,
     .constI64 0,
     .neI64,
     .iff 0 0 [
      .localGet 0,
      .localGet 6,
      .constI64 8,
      .mulI64,
      .addI64,
      .wrapI64,
      .load64 0,
      .localSet 8,
      .localGet 8,
      .call 20
     ] [],
     .localGet 6,
     .constI64 1,
     .addI64,
     .localSet 6,
     .br 0
    ]
   ]
  ] [],
  .localGet 2,
  .constI64 2,
  .eqI64,
  .iff 0 0 [
   .localGet 0,
   .wrapI64,
   .load64 0,
   .localSet 3,
   .localGet 0,
   .constI64 16,
   .subI64,
   .wrapI64,
   .load64 0,
   .localSet 4,
   .localGet 0,
   .constI64 8,
   .subI64,
   .wrapI64,
   .load64 0,
   .localSet 5,
   .constI64 0,
   .localSet 7,
   .block 0 0 [
    .loop 0 0 [
     .localGet 7,
     .localGet 3,
     .geUI64,
     .br_if 1,
     .constI64 0,
     .localSet 6,
     .block 0 0 [
      .loop 0 0 [
       .localGet 6,
       .localGet 4,
       .geUI64,
       .br_if 1,
       .localGet 5,
       .localGet 6,
       .shrUI64,
       .constI64 1,
       .andI64,
       .constI64 0,
       .neI64,
       .iff 0 0 [
        .localGet 0,
        .constI64 8,
        .addI64,
        .localGet 7,
        .localGet 4,
        .mulI64,
        .localGet 6,
        .addI64,
        .constI64 8,
        .mulI64,
        .addI64,
        .wrapI64,
        .load64 0,
        .localSet 8,
        .localGet 8,
        .call 20
       ] [],
       .localGet 6,
       .constI64 1,
       .addI64,
       .localSet 6,
       .br 0
      ]
     ],
     .localGet 7,
     .constI64 1,
     .addI64,
     .localSet 7,
     .br 0
    ]
   ]
  ] [],
  .globalGet 5,
  .constI64 1,
  .addI64,
  .globalSet 5,
  .localGet 0,
  .constI64 40,
  .subI64,
  .wrapI64,
  .constI64 0,
  .store64 0,
  .localGet 0,
  .constI64 8,
  .subI64,
  .wrapI64,
  .globalGet 1,
  .store64 0,
  .localGet 0,
  .globalSet 1
 ]

def func20Def : Wasm.Function :=
  { params := [.i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func20, typeIdx := some 20 }

def «module» : Wasm.Module :=
{
  funcs := [
   func0Def,
   func1Def,
   func2Def,
   func3Def,
   func4Def,
   func5Def,
   func6Def,
   func7Def,
   func8Def,
   func9Def,
   func10Def,
   func11Def,
   func12Def,
   func13Def,
   func14Def,
   func15Def,
   func16Def,
   func17Def,
   func18Def,
   func19Def,
   func20Def
  ],
  exports := [
   { name := "fluxCheckedBits", funcIdx := 16 },
   { name := "alloc", funcIdx := 17 },
   { name := "reset", funcIdx := 18 },
   { name := "retain", funcIdx := 19 },
   { name := "release", funcIdx := 20 },
   { name := "free", funcIdx := 20 }
  ],
  memory := some ({ pagesMin := 16 }),
  globals := [
   { init := .i64 4096, declaredType := some (.i64), sourceInit := some ([
     .constI64 4096
    ]) },
   { init := .i64 0, declaredType := some (.i64), sourceInit := some ([
     .constI64 0
    ]) },
   { init := .i64 0, declaredType := some (.i64), sourceInit := some ([
     .constI64 0
    ]) },
   { init := .i64 0, declaredType := some (.i64), sourceInit := some ([
     .constI64 0
    ]) },
   { init := .i64 0, declaredType := some (.i64), sourceInit := some ([
     .constI64 0
    ]) },
   { init := .i64 0, declaredType := some (.i64), sourceInit := some ([
     .constI64 0
    ]) }
  ],
  types := [
   { params := [.i64], results := [.i64] },
   { params := [.i64], results := [.i64] },
   { params := [.i64], results := [.i64] },
   { params := [.i64, .i64, .i64], results := [.i64] },
   { results := [.i64, .i64, .i64, .i64, .i64, .i64, .i64] },
   { params := [.i64, .i64, .i64], results := [.i64, .i64, .i64, .i64, .i64, .i64, .i64] },
   { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64] },
   { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64] },
   { results := [.i64, .i64] },
   { params := [.i64, .i64, .i64, .i64, .i64], results := [.i64, .i64] },
   { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64] },
   { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64] },
   { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64] },
   { params := [.i64, .i64], results := [.i64] },
   { params := [.i64, .i64], results := [.i64] },
   { results := [.i64, .i64, .i64, .i64, .i64] },
   { params := [.i64, .i64, .i64, .i64, .i64, .i64], results := [.i64, .i64, .i64, .i64, .i64] },
   { params := [.i64], results := [.i64] },
   {},
   { params := [.i64], results := [.i64] },
   { params := [.i64] }
  ],
  gcTypes := [
   { comp := .func ({ params := [.i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64], results := [.i64] }) },
   { comp := .func ({ results := [.i64, .i64, .i64, .i64, .i64, .i64, .i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64], results := [.i64, .i64, .i64, .i64, .i64, .i64, .i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64] }) },
   { comp := .func ({ results := [.i64, .i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64, .i64], results := [.i64, .i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64], results := [.i64] }) },
   { comp := .func ({ results := [.i64, .i64, .i64, .i64, .i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64, .i64, .i64], results := [.i64, .i64, .i64, .i64, .i64] }) },
   { comp := .func ({ params := [.i64], results := [.i64] }) },
   { comp := .func ({}) },
   { comp := .func ({ params := [.i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64] }) }
  ],
  globalExports := [
   ("allocCount", 2),
   ("retainCount", 3),
   ("releaseCount", 4),
   ("freeCount", 5)
  ],
  memoryExports := [
   ("memory", 0)
  ]
}

end Project.EulerDynamicFlux
