import Project.ProofKit.Allocation
import Project.ProofKit.FixedArrayAllocator
import Project.ProofKit.FixedArrayAllocatorWindow
import Project.ProofKit.FixedArrayFilterLt
import Project.ProofKit.FixedArrayMapAdd
import Project.ProofKit.FixedArraySingletonWrapper
import Project.ProofKit.ScalarTransition
import Project.ProofKit.ScalarTransitionU64

#check Array.size_eq_one_iff
#check Nat.gcd_comm
#check Nat.gcd_rec
#check Nat.mod_lt
#check Project.ProofKit.Allocation.bumpFacts
#check Project.ProofKit.FixedArrayAllocator.region_spec
#check Project.ProofKit.FixedArrayAllocatorWindow.region_spec
#check Project.ProofKit.FixedArrayAllocatorWindow.region_spec_withTail
#check Project.ProofKit.FixedArrayFilterLt.heapReserveBytes
#check Project.ProofKit.FixedArrayFilterLt.wrapperProgram
#check Project.ProofKit.FixedArrayFilterLt.wrapperProgram_spec
#check Project.ProofKit.FixedArrayMapAdd.expected
#check Project.ProofKit.FixedArrayMapAdd.wrapperProgram
#check Project.ProofKit.FixedArrayMapAdd.wrapperProgram_spec
#check Project.ProofKit.FixedArraySingletonWrapper.wrapperProgram
#check Project.ProofKit.FixedArraySingletonWrapper.wrapperProgram_spec
#check Project.ProofKit.ScalarTransition.CounterTransition.decrement_add_increment
#check Project.ProofKit.ScalarTransition.CounterTransition.decrement_toNat_lt
#check Project.ProofKit.ScalarTransition.CounterTransition.postTestProgram_spec
#check Project.ProofKit.ScalarTransition.postTestProgram_spec
#check UInt64.toNat_mod
