import Project.ProofKit.Allocation
import Project.ProofKit.Array
import Project.ProofKit.Control
import Project.ProofKit.FixedArrayAllocator
import Project.ProofKit.FixedArrayAllocatorWindow
import Project.ProofKit.FixedArrayCapacity
import Project.ProofKit.FixedArrayFilterLt
import Project.ProofKit.FixedArrayFold
import Project.ProofKit.FixedArrayFoldBody
import Project.ProofKit.FixedArrayLengthDispatch
import Project.ProofKit.FixedArrayMapAdd
import Project.ProofKit.FixedArrayPairResult
import Project.ProofKit.FixedArrayResult
import Project.ProofKit.FixedArraySingletonWrapper
import Project.ProofKit.FixedArrayTraversalInput
import Project.ProofKit.Frame
import Project.ProofKit.GuardedBackEdge
import Project.ProofKit.Memory
import Project.ProofKit.ScalarTransition
import Project.ProofKit.ScalarTransitionU64

#check Array.size_eq_one_iff
#check Nat.gcd_comm
#check Nat.gcd_rec
#check Nat.mod_lt
#check Project.ProofKit.Allocation.bumpFacts
#check Project.ProofKit.ArrayFold.foldPrefix
#check Project.ProofKit.ArrayFold.foldPrefix_size
#check Project.ProofKit.ArrayFold.foldPrefix_succ
#check Project.ProofKit.FixedArrayAllocator.region_spec
#check Project.ProofKit.FixedArrayAllocatorWindow.allocFrame_get_root
#check Project.ProofKit.FixedArrayAllocatorWindow.allocFrame_locals_length
#check Project.ProofKit.FixedArrayAllocatorWindow.allocFrame_params
#check Project.ProofKit.FixedArrayAllocatorWindow.allocFrame_values
#check Project.ProofKit.FixedArrayAllocatorWindow.constantCapacityRegion_spec_withTail
#check Project.ProofKit.FixedArrayAllocatorWindow.region_spec
#check Project.ProofKit.FixedArrayAllocatorWindow.region_spec_withTail
#check Project.ProofKit.FixedArrayCapacity.capacityFrame
#check Project.ProofKit.FixedArrayCapacity.capacityFrame_get_capacity
#check Project.ProofKit.FixedArrayCapacity.capacityFrame_internal_get_capacity
#check Project.ProofKit.FixedArrayCapacity.capacityFrame_locals_length
#check Project.ProofKit.FixedArrayCapacity.capacityFrame_params
#check Project.ProofKit.FixedArrayCapacity.capacityFrame_values
#check Project.ProofKit.FixedArrayCapacity.constantProgram_spec
#check Project.ProofKit.FixedArrayCapacity.normalizedCapacity
#check Project.ProofKit.FixedArrayCapacity.normalizedCapacity_toNat_ge_eight
#check Project.ProofKit.FixedArrayFilterLt.heapReserveBytes
#check Project.ProofKit.FixedArrayFilterLt.wrapperProgram
#check Project.ProofKit.FixedArrayFilterLt.wrapperProgram_spec
#check Project.ProofKit.FixedArrayFold.forwardSetupFrame
#check Project.ProofKit.FixedArrayFold.forwardSetupProgram_spec
#check Project.ProofKit.FixedArrayFold.resultFrame
#check Project.ProofKit.FixedArrayFold.resultFrame_get_of_ne
#check Project.ProofKit.FixedArrayFold.resultFrame_get_result
#check Project.ProofKit.FixedArrayFold.resultFrame_locals_length
#check Project.ProofKit.FixedArrayFold.resultFrame_params
#check Project.ProofKit.FixedArrayFold.resultFrame_values
#check Project.ProofKit.FixedArrayFold.resultProgram_spec
#check Project.ProofKit.FixedArrayFold.singletonResultPost
#check Project.ProofKit.FixedArrayFold.singletonResultProgram
#check Project.ProofKit.FixedArrayFold.singletonResultProgram_spec
#check Project.ProofKit.FixedArrayFold.singletonResultProgram_spec_to
#check Project.ProofKit.FixedArrayFoldBody.continuingGuardedProgram_spec
#check Project.ProofKit.FixedArrayLengthDispatch.eqProgram_spec
#check Project.ProofKit.FixedArrayLengthDispatch.leProgram_spec
#check Project.ProofKit.FixedArrayLengthDispatch.program_spec
#check Project.ProofKit.FixedArrayMapAdd.expected
#check Project.ProofKit.FixedArrayMapAdd.wrapperProgram
#check Project.ProofKit.FixedArrayMapAdd.wrapperProgram_spec
#check Project.ProofKit.FixedArrayPairResult.input_preserved_by_alloc
#check Project.ProofKit.FixedArrayResult.emptyStore_at
#check Project.ProofKit.FixedArrayResult.finishProgram_spec
#check Project.ProofKit.FixedArrayResult.lengthStore_spec
#check Project.ProofKit.FixedArrayResult.pairStore_at
#check Project.ProofKit.FixedArrayResult.payloadStore_spec
#check Project.ProofKit.FixedArrayResult.singletonStore_at
#check Project.ProofKit.FixedArraySingletonWrapper.wrapperProgram
#check Project.ProofKit.FixedArraySingletonWrapper.wrapperProgram_spec
#check Project.ProofKit.FixedArrayTraversalInput.continuingProgram_exit_spec
#check Project.ProofKit.FixedArrayTraversalInput.continuingProgram_spec
#check Project.ProofKit.FixedArrayTraversalInput.dynamicProgram_spec
#check Project.ProofKit.FixedArrayTraversalInput.program_spec
#check Project.ProofKit.Frame.ext
#check Project.ProofKit.Frame.internal_getElem?_of_get
#check Project.ProofKit.Frame.internal_getElem_of_get
#check Project.ProofKit.Frame.withValues_get
#check Project.ProofKit.Frame.withValues_locals
#check Project.ProofKit.Frame.withValues_params
#check Project.ProofKit.Frame.withValues_values
#check Project.ProofKit.Memory.read64_write64_disjoint
#check Project.ProofKit.ScalarTransition.CounterTransition.decrement_add_increment
#check Project.ProofKit.ScalarTransition.CounterTransition.decrement_toNat_lt
#check Project.ProofKit.ScalarTransition.CounterTransition.postTestProgram_spec
#check Project.ProofKit.ScalarTransition.guardedBackEdgeProgram
#check Project.ProofKit.ScalarTransition.guardedBackEdgeProgram_spec
#check Project.ProofKit.ScalarTransition.postTestProgram_spec
#check Project.ProofKit.UInt64Array.At.frameBefore
#check Project.ProofKit.UInt64Array.At.generatedElement
#check Project.ProofKit.UInt64Array.At.write64After
#check Project.ProofKit.UInt64Array.pair
#check Project.ProofKit.UInt64Array.singleton
#check UInt64.toNat_mod
#check Wasm.TerminatesWith.of_wp_entry_for
#check Wasm.wp.conseq
#check Wasm.wp_loop_cons
