import Project.Gpt2QuantizedCached.Program
import Project.ProofKit.Annotation
import Project.ProofKit.PackedAppend

set_option maxRecDepth 32768

namespace Project.Gpt2QuantizedCached.CachedHidden
open Wasm Project.ProofKit

def layerBody : Wasm.Program :=
  (Annotation.resolve func58 [⟨59, .block⟩, ⟨0, .loop⟩]).getD []

def activeCode : Wasm.Program :=
  (Annotation.resolve func58 [⟨59, .block⟩, ⟨0, .loop⟩, ⟨38, .thenBranch⟩]).getD []

def embeddingCode : Wasm.Program :=
  [.localGet 0,
   .localSet 8,
   .localGet 1,
   .localSet 9,
   .localGet 2,
   .localSet 10,
   .localGet 6,
   .localSet 11,
   .localGet 7,
   .localSet 12,
   .localGet 8,
   .localGet 9,
   .localGet 10,
   .localGet 11,
   .localGet 12,
   .call 30,
   .localSet 15,
   .localSet 14,
   .localSet 13,
   .localGet 13,
   .localSet 16,
   .localGet 14,
   .localSet 17,
   .localGet 15,
   .localSet 18,
   .constI64 0,
   .localSet 19,
   .constI64 0,
   .localSet 20,
   .constI64 0,
   .localSet 21,
   .constI64 0,
   .localSet 22,
   .constI64 0,
   .localSet 127,
   .constI64 12,
   .localSet 128,
   .constI64 1,
   .localSet 129,
   .localGet 16,
   .localSet 88,
   .localGet 88,
   .localSet 23,
   .localGet 17,
   .localSet 24,
   .localGet 18,
   .localSet 25,
   .localGet 19,
   .localSet 91,
   .localGet 91,
   .localSet 26,
   .localGet 20,
   .localSet 27,
   .localGet 21,
   .localSet 28,
   .localGet 22,
   .localSet 29,
   .constI64 0,
   .localSet 151]

def layerPrepareCode : Wasm.Program :=
  [.localGet 127,
   .localSet 30,
   .localGet 23,
   .localSet 31,
   .localGet 24,
   .localSet 32,
   .localGet 25,
   .localSet 33,
   .localGet 26,
   .localSet 34,
   .localGet 27,
   .localSet 35,
   .localGet 28,
   .localSet 36,
   .localGet 29,
   .localSet 37,
   .localGet 34,
   .localSet 38,
   .localGet 35,
   .localSet 39,
   .localGet 36,
   .localSet 40,
   .localGet 37,
   .localSet 41]

def layerCallCode : Wasm.Program :=
  [.localGet 0,
   .localSet 42,
   .localGet 1,
   .localSet 43,
   .localGet 2,
   .localSet 44,
   .localGet 31,
   .localSet 45,
   .localGet 32,
   .localSet 46,
   .localGet 33,
   .localSet 47,
   .localGet 3,
   .localSet 48,
   .localGet 4,
   .localSet 49,
   .localGet 5,
   .localSet 50,
   .localGet 30,
   .localSet 51,
   .localGet 7,
   .localSet 52,
   .localGet 42,
   .localGet 43,
   .localGet 44,
   .localGet 45,
   .localGet 46,
   .localGet 47,
   .localGet 48,
   .localGet 49,
   .localGet 50,
   .localGet 51,
   .localGet 52,
   .call 54,
   .localSet 59,
   .localSet 58,
   .localSet 57,
   .localSet 56,
   .localSet 55,
   .localSet 54,
   .localSet 53,
   .localGet 53,
   .localSet 60,
   .localGet 54,
   .localSet 61,
   .localGet 55,
   .localSet 62,
   .localGet 56,
   .localSet 63,
   .localGet 58,
   .localSet 65,
   .localGet 59,
   .localSet 66,
   .localGet 60,
   .localSet 67,
   .localGet 61,
   .localSet 68,
   .localGet 62,
   .localSet 69,
   .localGet 63,
   .localSet 70,
   .localGet 39,
   .localSet 71,
   .localGet 40,
   .localSet 72,
   .localGet 65,
   .localSet 73,
   .localGet 66,
   .localSet 74,
   .localGet 71,
   .localSet 130,
   .localGet 72,
   .localSet 131,
   .localGet 73,
   .localSet 132,
   .localGet 74,
   .localSet 133]

def layerResultCode : Wasm.Program :=
  [.localSet 76,
   .localGet 76,
   .localSet 77,
   .localGet 72,
   .localGet 74,
   .addI64,
   .localSet 78,
   .localGet 68,
   .localSet 79,
   .localGet 69,
   .localSet 80,
   .localGet 70,
   .localSet 81,
   .localGet 76,
   .localSet 82,
   .localGet 77,
   .localSet 83,
   .localGet 78,
   .localSet 84,
   .localGet 67,
   .localSet 85]

theorem emitted_embedding : func58.take 59 = embeddingCode := rfl

theorem emitted_layerLoop : (func58.drop 59).take 1 = [.block 0 0 [.loop 0 0 layerBody]] := rfl

theorem emitted_layerPrepare : (layerBody.drop 4).take 24 = layerPrepareCode := rfl

theorem emitted_layerCall : activeCode.take 77 = layerCallCode := rfl

theorem emitted_layerAppend : (activeCode.drop 77).take 40 = PackedAppend.program 130 := rfl

theorem emitted_layerResult : (activeCode.drop 117).take 21 = layerResultCode := rfl

end Project.Gpt2QuantizedCached.CachedHidden
