/-
  AUTO-GENERATED by `verifier emit`. Do not edit by hand.
-/

import Project.TalosPrelude

set_option maxRecDepth 1048576

namespace Project.EulerOutwardMaximum

open Wasm

def func0 : Wasm.Program :=
  [
  .localGet 0,
  .localSet 2,
  .localGet 2
 ]

def func0Def : Wasm.Function :=
  { params := [.i64, .i64], locals := [.i64], body := func0, results := [.i64], typeIdx := some 0 }

def func1 : Wasm.Program :=
  [
  .localGet 1,
  .localSet 2,
  .localGet 2
 ]

def func1Def : Wasm.Function :=
  { params := [.i64, .i64], locals := [.i64], body := func1, results := [.i64], typeIdx := some 1 }

def func2 : Wasm.Program :=
  [
  .constI64 1,
  .localSet 0,
  .constI64 0,
  .localSet 1,
  .localGet 0,
  .localGet 1
 ]

def func2Def : Wasm.Function :=
  { locals := [.i64, .i64], body := func2, results := [.i64, .i64], typeIdx := some 2 }

def func3 : Wasm.Program :=
  [
  .localGet 0,
  .constI64 0,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 1 [
   .localGet 2,
   .constI64 0,
   .eqI64,
   .iff 0 1 [
    .constI64 1
   ] [
    .constI64 0
   ] [] [.i64],
   .constI64 0,
   .eqI64,
   .eqz
  ] [
   .const 0
  ] [] [.i32],
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 1,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 0 [
   .constI64 0,
   .localSet 6,
   .localGet 1,
   .localGet 3,
   .leUI64,
   .iff 0 1 [
    .localGet 3
   ] [
    .localGet 1
   ] [] [.i64],
   .localSet 7
  ] [
   .call 2,
   .localSet 5,
   .localSet 4,
   .localGet 4,
   .localSet 6,
   .localGet 5,
   .localSet 7
  ],
  .localGet 6,
  .localGet 7
 ]

def func3Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64], locals := [.i64, .i64, .i64, .i64], body := func3, results := [.i64, .i64], typeIdx := some 3 }

def func4 : Wasm.Program :=
  [
  .constI64 0,
  .localGet 0,
  .ltUI64,
  .iff 0 1 [
   .localGet 0,
   .constI64 9218868437227405312,
   .ltUI64
  ] [
   .const 0
  ] [] [.i32],
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .localSet 1,
  .localGet 1
 ]

def func4Def : Wasm.Function :=
  { params := [.i64], locals := [.i64], body := func4, results := [.i64], typeIdx := some 4 }

def func5 : Wasm.Program :=
  [
  .localGet 0,
  .constI64 9223372036854775807,
  .andI64,
  .localSet 1,
  .localGet 1
 ]

def func5Def : Wasm.Function :=
  { params := [.i64], locals := [.i64], body := func5, results := [.i64], typeIdx := some 5 }

def func6 : Wasm.Program :=
  [
  .localGet 0,
  .localSet 1,
  .localGet 1,
  .call 5,
  .constI64 9218868437227405312,
  .ltUI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .localSet 2,
  .localGet 2
 ]

def func6Def : Wasm.Function :=
  { params := [.i64], locals := [.i64, .i64], body := func6, results := [.i64], typeIdx := some 6 }

def func7 : Wasm.Program :=
  [
  .localGet 0,
  .localSet 4,
  .localGet 4,
  .call 4,
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 1 [
   .localGet 1,
   .localSet 5,
   .localGet 5,
   .call 6,
   .constI64 0,
   .eqI64,
   .eqz
  ] [
   .const 0
  ] [] [.i32],
  .iff 0 1 [
   .localGet 2,
   .localSet 6,
   .localGet 6,
   .call 6,
   .constI64 0,
   .eqI64,
   .eqz
  ] [
   .const 0
  ] [] [.i32],
  .iff 0 1 [
   .localGet 3,
   .localSet 7,
   .localGet 7,
   .call 4,
   .constI64 0,
   .eqI64,
   .eqz
  ] [
   .const 0
  ] [] [.i32],
  .iff 0 1 [
   .localGet 1,
   .localSet 8,
   .localGet 8,
   .call 5,
   .localGet 0,
   .leUI64
  ] [
   .const 0
  ] [] [.i32],
  .iff 0 1 [
   .localGet 2,
   .localSet 9,
   .localGet 9,
   .call 5,
   .localGet 0,
   .leUI64
  ] [
   .const 0
  ] [] [.i32],
  .iff 0 1 [
   .localGet 0,
   .localGet 3,
   .ltUI64
  ] [
   .const 0
  ] [] [.i32],
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .localSet 10,
  .localGet 10
 ]

def func7Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func7, results := [.i64], typeIdx := some 7 }

def func8 : Wasm.Program :=
  [
  .constI64 0,
  .localGet 0,
  .ltUI64,
  .iff 0 1 [
   .localGet 0,
   .constI64 9218868437227405312,
   .ltUI64
  ] [
   .const 0
  ] [] [.i32],
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .localSet 1,
  .localGet 1
 ]

def func8Def : Wasm.Function :=
  { params := [.i64], locals := [.i64], body := func8, results := [.i64], typeIdx := some 8 }

def func9 : Wasm.Program :=
  [
  .localGet 0,
  .constI64 9223372036854775807,
  .andI64,
  .localSet 1,
  .localGet 1
 ]

def func9Def : Wasm.Function :=
  { params := [.i64], locals := [.i64], body := func9, results := [.i64], typeIdx := some 9 }

def func10 : Wasm.Program :=
  [
  .localGet 0,
  .localSet 1,
  .localGet 1,
  .call 9,
  .constI64 9218868437227405312,
  .ltUI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .localSet 2,
  .localGet 2
 ]

def func10Def : Wasm.Function :=
  { params := [.i64], locals := [.i64, .i64], body := func10, results := [.i64], typeIdx := some 10 }

def func11 : Wasm.Program :=
  [
  .localGet 0,
  .localGet 1,
  .ltUI64,
  .iff 0 1 [
   .localGet 1
  ] [
   .localGet 0
  ] [] [.i64],
  .localSet 2,
  .localGet 2
 ]

def func11Def : Wasm.Function :=
  { params := [.i64, .i64], locals := [.i64], body := func11, results := [.i64], typeIdx := some 11 }

def func12 : Wasm.Program :=
  [
  .localGet 0,
  .localSet 1,
  .localGet 1,
  .call 9,
  .localSet 3,
  .constI64 4503599627370496,
  .localSet 4,
  .localGet 4,
  .constI64 0,
  .eqI64,
  .iff 0 1 [
   .constI64 0
  ] [
   .localGet 3,
   .localGet 4,
   .divUI64
  ] [] [.i64],
  .localSet 2,
  .localGet 2
 ]

def func12Def : Wasm.Function :=
  { params := [.i64], locals := [.i64, .i64, .i64, .i64], body := func12, results := [.i64], typeIdx := some 12 }

def func13 : Wasm.Program :=
  [
  .localGet 0,
  .localSet 4,
  .localGet 4,
  .call 12,
  .localSet 5,
  .localGet 5,
  .localSet 6,
  .localGet 1,
  .localSet 7,
  .localGet 7,
  .call 12,
  .localSet 8,
  .localGet 8,
  .localSet 9,
  .localGet 6,
  .localGet 9,
  .call 11,
  .localSet 10,
  .localGet 10,
  .localSet 11,
  .localGet 2,
  .localSet 12,
  .localGet 12,
  .call 12,
  .localSet 13,
  .localGet 13,
  .localSet 14,
  .localGet 3,
  .localSet 15,
  .localGet 15,
  .call 12,
  .localSet 16,
  .localGet 16,
  .localSet 17,
  .localGet 14,
  .localGet 17,
  .call 11,
  .localSet 18,
  .localGet 18,
  .localSet 19,
  .localGet 11,
  .localGet 19,
  .call 11,
  .localSet 20,
  .localGet 20,
  .localSet 21,
  .localGet 21
 ]

def func13Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func13, results := [.i64], typeIdx := some 13 }

def func14 : Wasm.Program :=
  [
  .localGet 0,
  .localSet 2,
  .localGet 2,
  .call 9,
  .localSet 3,
  .localGet 3,
  .constI64 0,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 1 [
   .const 1
  ] [
   .constI64 0,
   .localGet 0,
   .localSet 4,
   .localGet 4,
   .call 12,
   .ltUI64,
   .iff 0 1 [
    .localGet 1,
    .localGet 0,
    .localSet 5,
    .localGet 5,
    .call 12,
    .constI64 1021,
    .addI64,
    .ltUI64
   ] [
    .const 0
   ] [] [.i32]
  ] [] [.i32],
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .localSet 6,
  .localGet 6
 ]

def func14Def : Wasm.Function :=
  { params := [.i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64], body := func14, results := [.i64], typeIdx := some 14 }

def func15 : Wasm.Program :=
  [
  .localGet 0,
  .localSet 2,
  .localGet 2,
  .call 12,
  .constI64 1021,
  .addI64,
  .localGet 1,
  .leUI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .localSet 3,
  .localGet 3
 ]

def func15Def : Wasm.Function :=
  { params := [.i64, .i64], locals := [.i64, .i64], body := func15, results := [.i64], typeIdx := some 15 }

def func16 : Wasm.Program :=
  [
  .localGet 0,
  .localSet 2,
  .localGet 1,
  .localSet 3,
  .localGet 2,
  .localGet 3,
  .call 14,
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 1 [
   .const 1
  ] [
   .localGet 0,
   .localSet 4,
   .localGet 1,
   .localSet 5,
   .localGet 4,
   .localGet 5,
   .call 15,
   .constI64 0,
   .eqI64,
   .eqz
  ] [] [.i32],
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .localSet 6,
  .localGet 6
 ]

def func16Def : Wasm.Function :=
  { params := [.i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64], body := func16, results := [.i64], typeIdx := some 16 }

def func17 : Wasm.Program :=
  [
  .localGet 0,
  .f64ReinterpretI64,
  .localGet 3,
  .f64ReinterpretI64,
  .f64Mul,
  .i64ReinterpretF64,
  .localSet 4,
  .localGet 1,
  .f64ReinterpretI64,
  .localGet 1,
  .f64ReinterpretI64,
  .f64Mul,
  .i64ReinterpretF64,
  .localSet 5,
  .localGet 2,
  .f64ReinterpretI64,
  .localGet 2,
  .f64ReinterpretI64,
  .f64Mul,
  .i64ReinterpretF64,
  .localSet 6,
  .localGet 5,
  .f64ReinterpretI64,
  .localGet 6,
  .f64ReinterpretI64,
  .f64Add,
  .i64ReinterpretF64,
  .localSet 7,
  .constI64 4602678819172646912,
  .f64ReinterpretI64,
  .localGet 7,
  .f64ReinterpretI64,
  .f64Mul,
  .i64ReinterpretF64,
  .localSet 8,
  .localGet 4,
  .f64ReinterpretI64,
  .localGet 8,
  .f64ReinterpretI64,
  .f64Sub,
  .i64ReinterpretF64,
  .localSet 9,
  .localGet 9
 ]

def func17Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64], body := func17, results := [.i64], typeIdx := some 17 }

def func18 : Wasm.Program :=
  [
  .localGet 0,
  .localSet 2,
  .localGet 2,
  .call 9,
  .localSet 3,
  .localGet 3,
  .constI64 0,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 1,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 1 [
   .constI64 0
  ] [
   .localGet 0,
   .localSet 4,
   .localGet 4,
   .call 12,
   .constI64 1021,
   .addI64,
   .localGet 1,
   .subI64,
   .constI64 4503599627370496,
   .mulI64,
   .localGet 0,
   .localSet 5,
   .localGet 5,
   .call 9,
   .localSet 7,
   .constI64 4503599627370496,
   .localSet 8,
   .localGet 8,
   .constI64 0,
   .eqI64,
   .iff 0 1 [
    .localGet 7
   ] [
    .localGet 7,
    .localGet 8,
    .remUI64
   ] [] [.i64],
   .addI64
  ] [] [.i64],
  .localSet 6,
  .localGet 6
 ]

def func18Def : Wasm.Function :=
  { params := [.i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func18, results := [.i64], typeIdx := some 18 }

def func19 : Wasm.Program :=
  [
  .localGet 0,
  .localSet 2,
  .localGet 1,
  .localSet 3,
  .localGet 2,
  .localGet 3,
  .call 14,
  .localSet 4,
  .localGet 4,
  .constI64 1,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 0 [
   .localGet 0,
   .localSet 5,
   .localGet 1,
   .localSet 6,
   .localGet 5,
   .localGet 6,
   .call 18,
   .localSet 7,
   .localGet 7,
   .localSet 8
  ] [
   .constI64 0,
   .localSet 8
  ],
  .localGet 8
 ]

def func19Def : Wasm.Function :=
  { params := [.i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func19, results := [.i64], typeIdx := some 19 }

def func20 : Wasm.Program :=
  [
  .localGet 0,
  .localSet 4,
  .localGet 1,
  .localSet 5,
  .localGet 2,
  .localSet 6,
  .localGet 3,
  .localSet 7,
  .localGet 4,
  .localGet 5,
  .localGet 6,
  .localGet 7,
  .call 13,
  .localSet 8,
  .localGet 8,
  .localSet 9,
  .localGet 0,
  .localSet 10,
  .localGet 9,
  .localSet 11,
  .localGet 10,
  .localGet 11,
  .call 18,
  .localSet 12,
  .localGet 12,
  .localSet 13,
  .localGet 1,
  .localSet 14,
  .localGet 9,
  .localSet 15,
  .localGet 14,
  .localGet 15,
  .call 19,
  .localSet 16,
  .localGet 16,
  .localSet 17,
  .localGet 2,
  .localSet 18,
  .localGet 9,
  .localSet 19,
  .localGet 18,
  .localGet 19,
  .call 19,
  .localSet 20,
  .localGet 20,
  .localSet 21,
  .localGet 3,
  .localSet 22,
  .localGet 9,
  .localSet 23,
  .localGet 22,
  .localGet 23,
  .call 18,
  .localSet 24,
  .localGet 24,
  .localSet 25,
  .localGet 13,
  .localGet 17,
  .localGet 21,
  .localGet 25,
  .call 17,
  .localSet 26,
  .localGet 26,
  .localSet 27,
  .localGet 27
 ]

def func20Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func20, results := [.i64], typeIdx := some 20 }

def func21 : Wasm.Program :=
  [
  .localGet 0,
  .localSet 4,
  .localGet 4,
  .call 8,
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 1 [
   .localGet 1,
   .localSet 5,
   .localGet 5,
   .call 10,
   .constI64 0,
   .eqI64,
   .eqz
  ] [
   .const 0
  ] [] [.i32],
  .iff 0 1 [
   .localGet 2,
   .localSet 6,
   .localGet 6,
   .call 10,
   .constI64 0,
   .eqI64,
   .eqz
  ] [
   .const 0
  ] [] [.i32],
  .iff 0 1 [
   .localGet 3,
   .localSet 7,
   .localGet 7,
   .call 8,
   .constI64 0,
   .eqI64,
   .eqz
  ] [
   .const 0
  ] [] [.i32],
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 1,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 0 [
   .localGet 0,
   .localSet 8,
   .localGet 1,
   .localSet 9,
   .localGet 2,
   .localSet 10,
   .localGet 3,
   .localSet 11,
   .localGet 8,
   .localGet 9,
   .localGet 10,
   .localGet 11,
   .call 13,
   .localSet 12,
   .localGet 12,
   .localSet 13,
   .localGet 0,
   .localSet 14,
   .localGet 13,
   .localSet 15,
   .localGet 14,
   .localGet 15,
   .call 14,
   .constI64 0,
   .eqI64,
   .eqz,
   .iff 0 1 [
    .localGet 1,
    .localSet 16,
    .localGet 13,
    .localSet 17,
    .localGet 16,
    .localGet 17,
    .call 16,
    .constI64 0,
    .eqI64,
    .eqz
   ] [
    .const 0
   ] [] [.i32],
   .iff 0 1 [
    .localGet 2,
    .localSet 18,
    .localGet 13,
    .localSet 19,
    .localGet 18,
    .localGet 19,
    .call 16,
    .constI64 0,
    .eqI64,
    .eqz
   ] [
    .const 0
   ] [] [.i32],
   .iff 0 1 [
    .localGet 3,
    .localSet 20,
    .localGet 13,
    .localSet 21,
    .localGet 20,
    .localGet 21,
    .call 14,
    .constI64 0,
    .eqI64,
    .eqz
   ] [
    .const 0
   ] [] [.i32],
   .iff 0 1 [
    .constI64 1
   ] [
    .constI64 0
   ] [] [.i64],
   .constI64 1,
   .eqI64,
   .iff 0 1 [
    .constI64 1
   ] [
    .constI64 0
   ] [] [.i64],
   .constI64 0,
   .eqI64,
   .eqz,
   .iff 0 0 [
    .localGet 0,
    .localSet 22,
    .localGet 1,
    .localSet 23,
    .localGet 2,
    .localSet 24,
    .localGet 3,
    .localSet 25,
    .localGet 22,
    .localGet 23,
    .localGet 24,
    .localGet 25,
    .call 20,
    .localSet 26,
    .localGet 26,
    .localSet 27,
    .localGet 27,
    .localSet 28,
    .localGet 28,
    .call 8,
    .constI64 0,
    .eqI64,
    .eqz,
    .iff 0 1 [
     .constI64 4386506037058863104,
     .localGet 27,
     .ltUI64
    ] [
     .const 0
    ] [] [.i32],
    .iff 0 1 [
     .constI64 1
    ] [
     .constI64 0
    ] [] [.i64],
    .localSet 29
   ] [
    .constI64 0,
    .localSet 29
   ]
  ] [
   .constI64 0,
   .localSet 29
  ],
  .localGet 29
 ]

def func21Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func21, results := [.i64], typeIdx := some 21 }

def func22 : Wasm.Program :=
  [
  .localGet 0,
  .localSet 4,
  .localGet 1,
  .localSet 5,
  .localGet 2,
  .localSet 6,
  .localGet 3,
  .localSet 7,
  .localGet 4,
  .localGet 5,
  .localGet 6,
  .localGet 7,
  .call 7,
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 1 [
   .const 1
  ] [
   .localGet 0,
   .localSet 8,
   .localGet 1,
   .localSet 9,
   .localGet 2,
   .localSet 10,
   .localGet 3,
   .localSet 11,
   .localGet 8,
   .localGet 9,
   .localGet 10,
   .localGet 11,
   .call 21,
   .constI64 0,
   .eqI64,
   .eqz
  ] [] [.i32],
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .localSet 12,
  .localGet 12
 ]

def func22Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func22, results := [.i64], typeIdx := some 22 }

def func23 : Wasm.Program :=
  [
  .localGet 0,
  .constI64 9223372036854775808,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 1 [
   .constI64 1
  ] [
   .localGet 0,
   .constI64 9223372036854775808,
   .ltUI64,
   .iff 0 1 [
    .localGet 0,
    .constI64 1,
    .addI64
   ] [
    .localGet 0,
    .constI64 1,
    .subI64
   ] [] [.i64]
  ] [] [.i64],
  .localSet 1,
  .localGet 1
 ]

def func23Def : Wasm.Function :=
  { params := [.i64], locals := [.i64], body := func23, results := [.i64], typeIdx := some 23 }

def func24 : Wasm.Program :=
  [
  .localGet 0,
  .constI64 0,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 1 [
   .constI64 9223372036854775809
  ] [
   .localGet 0,
   .constI64 9223372036854775808,
   .ltUI64,
   .iff 0 1 [
    .localGet 0,
    .constI64 1,
    .subI64
   ] [
    .localGet 0,
    .constI64 1,
    .addI64
   ] [] [.i64]
  ] [] [.i64],
  .localSet 1,
  .localGet 1
 ]

def func24Def : Wasm.Function :=
  { params := [.i64], locals := [.i64], body := func24, results := [.i64], typeIdx := some 24 }

def func25 : Wasm.Program :=
  [
  .localGet 0,
  .constI64 1,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 0 [
   .localGet 1,
   .localSet 2,
   .localGet 2,
   .call 23,
   .localSet 3,
   .localGet 3,
   .localSet 6
  ] [
   .localGet 1,
   .localSet 4,
   .localGet 4,
   .call 24,
   .localSet 5,
   .localGet 5,
   .localSet 6
  ],
  .localGet 6
 ]

def func25Def : Wasm.Function :=
  { params := [.i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64], body := func25, results := [.i64], typeIdx := some 25 }

def func26 : Wasm.Program :=
  [
  .localGet 1,
  .localSet 2,
  .localGet 2,
  .call 10,
  .localSet 3,
  .localGet 3,
  .constI64 1,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 0 [
   .localGet 0,
   .localSet 4,
   .localGet 1,
   .localSet 5,
   .localGet 4,
   .localGet 5,
   .call 25,
   .localSet 6,
   .localGet 6,
   .localSet 7,
   .localGet 7,
   .localSet 8,
   .localGet 8,
   .call 10,
   .localSet 9,
   .localGet 9,
   .constI64 1,
   .eqI64,
   .iff 0 1 [
    .constI64 1
   ] [
    .constI64 0
   ] [] [.i64],
   .constI64 0,
   .eqI64,
   .eqz,
   .iff 0 0 [
    .constI64 0,
    .localSet 14,
    .localGet 7,
    .localSet 15
   ] [
    .call 2,
    .localSet 11,
    .localSet 10,
    .localGet 10,
    .localSet 14,
    .localGet 11,
    .localSet 15
   ]
  ] [
   .call 2,
   .localSet 13,
   .localSet 12,
   .localGet 12,
   .localSet 14,
   .localGet 13,
   .localSet 15
  ],
  .localGet 14,
  .localGet 15
 ]

def func26Def : Wasm.Function :=
  { params := [.i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func26, results := [.i64, .i64], typeIdx := some 26 }

def func27 : Wasm.Program :=
  [
  .localGet 1,
  .localSet 3,
  .localGet 3,
  .call 10,
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 1 [
   .localGet 2,
   .localSet 4,
   .localGet 4,
   .call 10,
   .constI64 0,
   .eqI64,
   .eqz
  ] [
   .const 0
  ] [] [.i32],
  .iff 0 1 [
   .constI64 0,
   .localGet 2,
   .localSet 5,
   .localGet 5,
   .call 9,
   .ltUI64
  ] [
   .const 0
  ] [] [.i32],
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 1,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 0 [
   .localGet 0,
   .localSet 6,
   .localGet 1,
   .f64ReinterpretI64,
   .localGet 2,
   .f64ReinterpretI64,
   .f64Div,
   .i64ReinterpretF64,
   .localSet 7,
   .localGet 6,
   .localGet 7,
   .call 26,
   .localSet 9,
   .localSet 8,
   .localGet 8,
   .localSet 12,
   .localGet 9,
   .localSet 13
  ] [
   .call 2,
   .localSet 11,
   .localSet 10,
   .localGet 10,
   .localSet 12,
   .localGet 11,
   .localSet 13
  ],
  .localGet 12,
  .localGet 13
 ]

def func27Def : Wasm.Function :=
  { params := [.i64, .i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func27, results := [.i64, .i64], typeIdx := some 27 }

def func28 : Wasm.Program :=
  [
  .localGet 1,
  .localSet 3,
  .localGet 3,
  .call 10,
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 1 [
   .localGet 2,
   .localSet 4,
   .localGet 4,
   .call 10,
   .constI64 0,
   .eqI64,
   .eqz
  ] [
   .const 0
  ] [] [.i32],
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 1,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 0 [
   .localGet 0,
   .localSet 5,
   .localGet 1,
   .f64ReinterpretI64,
   .localGet 2,
   .f64ReinterpretI64,
   .f64Mul,
   .i64ReinterpretF64,
   .localSet 6,
   .localGet 5,
   .localGet 6,
   .call 26,
   .localSet 8,
   .localSet 7,
   .localGet 7,
   .localSet 11,
   .localGet 8,
   .localSet 12
  ] [
   .call 2,
   .localSet 10,
   .localSet 9,
   .localGet 9,
   .localSet 11,
   .localGet 10,
   .localSet 12
  ],
  .localGet 11,
  .localGet 12
 ]

def func28Def : Wasm.Function :=
  { params := [.i64, .i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func28, results := [.i64, .i64], typeIdx := some 28 }

def func29 : Wasm.Program :=
  [
  .localGet 1,
  .localSet 3,
  .localGet 3,
  .call 10,
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 1 [
   .localGet 2,
   .localSet 4,
   .localGet 4,
   .call 10,
   .constI64 0,
   .eqI64,
   .eqz
  ] [
   .const 0
  ] [] [.i32],
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 1,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 0 [
   .localGet 0,
   .localSet 5,
   .localGet 1,
   .f64ReinterpretI64,
   .localGet 2,
   .f64ReinterpretI64,
   .f64Add,
   .i64ReinterpretF64,
   .localSet 6,
   .localGet 5,
   .localGet 6,
   .call 26,
   .localSet 8,
   .localSet 7,
   .localGet 7,
   .localSet 11,
   .localGet 8,
   .localSet 12
  ] [
   .call 2,
   .localSet 10,
   .localSet 9,
   .localGet 9,
   .localSet 11,
   .localGet 10,
   .localSet 12
  ],
  .localGet 11,
  .localGet 12
 ]

def func29Def : Wasm.Function :=
  { params := [.i64, .i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func29, results := [.i64, .i64], typeIdx := some 29 }

def func30 : Wasm.Program :=
  [
  .constI64 0,
  .localSet 3,
  .localGet 1,
  .localSet 4,
  .localGet 1,
  .localSet 5,
  .localGet 3,
  .localGet 4,
  .localGet 5,
  .call 28,
  .localSet 7,
  .localSet 6,
  .localGet 6,
  .localSet 8,
  .localGet 7,
  .localSet 9,
  .constI64 0,
  .localSet 10,
  .localGet 2,
  .localSet 11,
  .localGet 2,
  .localSet 12,
  .localGet 10,
  .localGet 11,
  .localGet 12,
  .call 28,
  .localSet 14,
  .localSet 13,
  .localGet 13,
  .localSet 15,
  .localGet 14,
  .localSet 16,
  .localGet 8,
  .constI64 0,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 1 [
   .localGet 15,
   .constI64 0,
   .eqI64,
   .iff 0 1 [
    .constI64 1
   ] [
    .constI64 0
   ] [] [.i64],
   .constI64 0,
   .eqI64,
   .eqz
  ] [
   .const 0
  ] [] [.i32],
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 1,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 0 [
   .constI64 0,
   .localSet 17,
   .localGet 9,
   .localSet 18,
   .localGet 16,
   .localSet 19,
   .localGet 17,
   .localGet 18,
   .localGet 19,
   .call 29,
   .localSet 21,
   .localSet 20,
   .localGet 20,
   .localSet 22,
   .localGet 21,
   .localSet 23,
   .localGet 22,
   .constI64 0,
   .eqI64,
   .iff 0 1 [
    .constI64 1
   ] [
    .constI64 0
   ] [] [.i64],
   .constI64 1,
   .eqI64,
   .iff 0 1 [
    .constI64 1
   ] [
    .constI64 0
   ] [] [.i64],
   .constI64 0,
   .eqI64,
   .eqz,
   .iff 0 0 [
    .constI64 0,
    .localSet 24,
    .constI64 4602678819172646912,
    .localSet 25,
    .localGet 23,
    .localSet 26,
    .localGet 24,
    .localGet 25,
    .localGet 26,
    .call 28,
    .localSet 28,
    .localSet 27,
    .localGet 27,
    .localSet 29,
    .localGet 28,
    .localSet 30,
    .localGet 29,
    .constI64 0,
    .eqI64,
    .iff 0 1 [
     .constI64 1
    ] [
     .constI64 0
    ] [] [.i64],
    .constI64 1,
    .eqI64,
    .iff 0 1 [
     .constI64 1
    ] [
     .constI64 0
    ] [] [.i64],
    .constI64 0,
    .eqI64,
    .eqz,
    .iff 0 0 [
     .constI64 0,
     .localSet 31,
     .localGet 30,
     .localSet 32,
     .localGet 0,
     .localSet 33,
     .localGet 31,
     .localGet 32,
     .localGet 33,
     .call 27,
     .localSet 35,
     .localSet 34,
     .localGet 34,
     .localSet 42,
     .localGet 35,
     .localSet 43
    ] [
     .call 2,
     .localSet 37,
     .localSet 36,
     .localGet 36,
     .localSet 42,
     .localGet 37,
     .localSet 43
    ]
   ] [
    .call 2,
    .localSet 39,
    .localSet 38,
    .localGet 38,
    .localSet 42,
    .localGet 39,
    .localSet 43
   ]
  ] [
   .call 2,
   .localSet 41,
   .localSet 40,
   .localGet 40,
   .localSet 42,
   .localGet 41,
   .localSet 43
  ],
  .localGet 42,
  .localGet 43
 ]

def func30Def : Wasm.Function :=
  { params := [.i64, .i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func30, results := [.i64, .i64], typeIdx := some 30 }

def func31 : Wasm.Program :=
  [
  .localGet 1,
  .localSet 3,
  .localGet 3,
  .call 10,
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 1 [
   .localGet 2,
   .localSet 4,
   .localGet 4,
   .call 10,
   .constI64 0,
   .eqI64,
   .eqz
  ] [
   .const 0
  ] [] [.i32],
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 1,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 0 [
   .localGet 0,
   .localSet 5,
   .localGet 1,
   .f64ReinterpretI64,
   .localGet 2,
   .f64ReinterpretI64,
   .f64Sub,
   .i64ReinterpretF64,
   .localSet 6,
   .localGet 5,
   .localGet 6,
   .call 26,
   .localSet 8,
   .localSet 7,
   .localGet 7,
   .localSet 11,
   .localGet 8,
   .localSet 12
  ] [
   .call 2,
   .localSet 10,
   .localSet 9,
   .localGet 9,
   .localSet 11,
   .localGet 10,
   .localSet 12
  ],
  .localGet 11,
  .localGet 12
 ]

def func31Def : Wasm.Function :=
  { params := [.i64, .i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func31, results := [.i64, .i64], typeIdx := some 31 }

def func32 : Wasm.Program :=
  [
  .localGet 0,
  .localSet 4,
  .localGet 1,
  .localSet 5,
  .localGet 2,
  .localSet 6,
  .localGet 4,
  .localGet 5,
  .localGet 6,
  .call 30,
  .localSet 8,
  .localSet 7,
  .localGet 7,
  .localSet 9,
  .localGet 8,
  .localSet 10,
  .localGet 9,
  .constI64 0,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 1,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 0 [
   .constI64 1,
   .localSet 11,
   .localGet 3,
   .localSet 12,
   .localGet 10,
   .localSet 13,
   .localGet 11,
   .localGet 12,
   .localGet 13,
   .call 31,
   .localSet 15,
   .localSet 14,
   .localGet 14,
   .localSet 18,
   .localGet 15,
   .localSet 19
  ] [
   .call 2,
   .localSet 17,
   .localSet 16,
   .localGet 16,
   .localSet 18,
   .localGet 17,
   .localSet 19
  ],
  .localGet 18,
  .localGet 19
 ]

def func32Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func32, results := [.i64, .i64], typeIdx := some 32 }

def func33 : Wasm.Program :=
  [
  .localGet 0,
  .localSet 4,
  .localGet 1,
  .localSet 5,
  .localGet 2,
  .localSet 6,
  .localGet 3,
  .localSet 7,
  .localGet 4,
  .localGet 5,
  .localGet 6,
  .localGet 7,
  .call 32,
  .localSet 9,
  .localSet 8,
  .localGet 8,
  .localSet 10,
  .localGet 9,
  .localSet 11,
  .localGet 10,
  .constI64 0,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 1,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 0 [
   .constI64 1,
   .localSet 12,
   .constI64 4600877379321698714,
   .localSet 13,
   .localGet 11,
   .localSet 14,
   .localGet 12,
   .localGet 13,
   .localGet 14,
   .call 28,
   .localSet 16,
   .localSet 15,
   .localGet 15,
   .localSet 19,
   .localGet 16,
   .localSet 20
  ] [
   .call 2,
   .localSet 18,
   .localSet 17,
   .localGet 17,
   .localSet 19,
   .localGet 18,
   .localSet 20
  ],
  .localGet 19,
  .localGet 20
 ]

def func33Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func33, results := [.i64, .i64], typeIdx := some 33 }

def func34 : Wasm.Program :=
  [
  .localGet 0,
  .localSet 4,
  .localGet 1,
  .localSet 5,
  .localGet 2,
  .localSet 6,
  .localGet 3,
  .localSet 7,
  .localGet 4,
  .localGet 5,
  .localGet 6,
  .localGet 7,
  .call 33,
  .localSet 9,
  .localSet 8,
  .localGet 8,
  .localSet 10,
  .localGet 9,
  .localSet 11,
  .localGet 10,
  .constI64 0,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 1,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 0 [
   .constI64 1,
   .localSet 12,
   .localGet 11,
   .localSet 13,
   .localGet 0,
   .localSet 14,
   .localGet 12,
   .localGet 13,
   .localGet 14,
   .call 27,
   .localSet 16,
   .localSet 15,
   .localGet 15,
   .localSet 17,
   .localGet 16,
   .localSet 18,
   .localGet 17,
   .constI64 0,
   .eqI64,
   .iff 0 1 [
    .constI64 1
   ] [
    .constI64 0
   ] [] [.i64],
   .constI64 1,
   .eqI64,
   .iff 0 1 [
    .constI64 1
   ] [
    .constI64 0
   ] [] [.i64],
   .constI64 0,
   .eqI64,
   .eqz,
   .iff 0 0 [
    .constI64 1,
    .localSet 19,
    .constI64 4608983858650965607,
    .localSet 20,
    .localGet 18,
    .localSet 21,
    .localGet 19,
    .localGet 20,
    .localGet 21,
    .call 28,
    .localSet 23,
    .localSet 22,
    .localGet 22,
    .localSet 28,
    .localGet 23,
    .localSet 29
   ] [
    .call 2,
    .localSet 25,
    .localSet 24,
    .localGet 24,
    .localSet 28,
    .localGet 25,
    .localSet 29
   ]
  ] [
   .call 2,
   .localSet 27,
   .localSet 26,
   .localGet 26,
   .localSet 28,
   .localGet 27,
   .localSet 29
  ],
  .localGet 28,
  .localGet 29
 ]

def func34Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func34, results := [.i64, .i64], typeIdx := some 34 }

def func35 : Wasm.Program :=
  [
  .localGet 1,
  .localSet 2,
  .localGet 2,
  .call 10,
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 1 [
   .localGet 1,
   .constI64 9223372036854775808,
   .leUI64
  ] [
   .const 0
  ] [] [.i32],
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 1,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 0 [
   .localGet 0,
   .localSet 3,
   .localGet 1,
   .f64ReinterpretI64,
   .f64Sqrt,
   .i64ReinterpretF64,
   .localSet 4,
   .localGet 3,
   .localGet 4,
   .call 26,
   .localSet 6,
   .localSet 5,
   .localGet 5,
   .localSet 9,
   .localGet 6,
   .localSet 10
  ] [
   .call 2,
   .localSet 8,
   .localSet 7,
   .localGet 7,
   .localSet 9,
   .localGet 8,
   .localSet 10
  ],
  .localGet 9,
  .localGet 10
 ]

def func35Def : Wasm.Function :=
  { params := [.i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func35, results := [.i64, .i64], typeIdx := some 35 }

def func36 : Wasm.Program :=
  [
  .localGet 0,
  .localSet 4,
  .localGet 1,
  .localSet 5,
  .localGet 2,
  .localSet 6,
  .localGet 3,
  .localSet 7,
  .localGet 4,
  .localGet 5,
  .localGet 6,
  .localGet 7,
  .call 34,
  .localSet 9,
  .localSet 8,
  .localGet 8,
  .localSet 10,
  .localGet 9,
  .localSet 11,
  .localGet 10,
  .constI64 0,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 1,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 0 [
   .constI64 1,
   .localSet 12,
   .localGet 11,
   .localSet 13,
   .localGet 12,
   .localGet 13,
   .call 35,
   .localSet 15,
   .localSet 14,
   .localGet 14,
   .localSet 18,
   .localGet 15,
   .localSet 19
  ] [
   .call 2,
   .localSet 17,
   .localSet 16,
   .localGet 16,
   .localSet 18,
   .localGet 17,
   .localSet 19
  ],
  .localGet 18,
  .localGet 19
 ]

def func36Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func36, results := [.i64, .i64], typeIdx := some 36 }

def func37 : Wasm.Program :=
  [
  .localGet 0,
  .localSet 4,
  .localGet 1,
  .localSet 5,
  .localGet 2,
  .localSet 6,
  .localGet 3,
  .localSet 7,
  .localGet 4,
  .localGet 5,
  .localGet 6,
  .localGet 7,
  .call 22,
  .localSet 8,
  .localGet 8,
  .constI64 1,
  .eqI64,
  .iff 0 1 [
   .constI64 1
  ] [
   .constI64 0
  ] [] [.i64],
  .constI64 0,
  .eqI64,
  .eqz,
  .iff 0 0 [
   .constI64 1,
   .localSet 9,
   .localGet 1,
   .localSet 10,
   .localGet 10,
   .call 9,
   .localSet 11,
   .localGet 11,
   .localSet 12,
   .localGet 0,
   .localSet 13,
   .localGet 9,
   .localGet 12,
   .localGet 13,
   .call 27,
   .localSet 15,
   .localSet 14,
   .localGet 14,
   .localSet 16,
   .localGet 15,
   .localSet 17,
   .localGet 0,
   .localSet 18,
   .localGet 1,
   .localSet 19,
   .localGet 2,
   .localSet 20,
   .localGet 3,
   .localSet 21,
   .localGet 18,
   .localGet 19,
   .localGet 20,
   .localGet 21,
   .call 36,
   .localSet 23,
   .localSet 22,
   .localGet 22,
   .localSet 24,
   .localGet 23,
   .localSet 25,
   .localGet 16,
   .constI64 0,
   .eqI64,
   .iff 0 1 [
    .constI64 1
   ] [
    .constI64 0
   ] [] [.i64],
   .constI64 0,
   .eqI64,
   .eqz,
   .iff 0 1 [
    .localGet 24,
    .constI64 0,
    .eqI64,
    .iff 0 1 [
     .constI64 1
    ] [
     .constI64 0
    ] [] [.i64],
    .constI64 0,
    .eqI64,
    .eqz
   ] [
    .const 0
   ] [] [.i32],
   .iff 0 1 [
    .constI64 1
   ] [
    .constI64 0
   ] [] [.i64],
   .constI64 1,
   .eqI64,
   .iff 0 1 [
    .constI64 1
   ] [
    .constI64 0
   ] [] [.i64],
   .constI64 0,
   .eqI64,
   .eqz,
   .iff 0 0 [
    .constI64 1,
    .localSet 26,
    .localGet 17,
    .localSet 27,
    .localGet 25,
    .localSet 28,
    .localGet 26,
    .localGet 27,
    .localGet 28,
    .call 29,
    .localSet 30,
    .localSet 29,
    .localGet 29,
    .localSet 35,
    .localGet 30,
    .localSet 36
   ] [
    .call 2,
    .localSet 32,
    .localSet 31,
    .localGet 31,
    .localSet 35,
    .localGet 32,
    .localSet 36
   ]
  ] [
   .call 2,
   .localSet 34,
   .localSet 33,
   .localGet 33,
   .localSet 35,
   .localGet 34,
   .localSet 36
  ],
  .localGet 35,
  .localGet 36
 ]

def func37Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func37, results := [.i64, .i64], typeIdx := some 37 }

def func38 : Wasm.Program :=
  [
  .localGet 0,
  .localSet 4,
  .localGet 4
 ]

def func38Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64], locals := [.i64], body := func38, results := [.i64], typeIdx := some 38 }

def func39 : Wasm.Program :=
  [
  .localGet 1,
  .localSet 4,
  .localGet 4
 ]

def func39Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64], locals := [.i64], body := func39, results := [.i64], typeIdx := some 39 }

def func40 : Wasm.Program :=
  [
  .localGet 2,
  .localSet 4,
  .localGet 4
 ]

def func40Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64], locals := [.i64], body := func40, results := [.i64], typeIdx := some 40 }

def func41 : Wasm.Program :=
  [
  .localGet 3,
  .localSet 4,
  .localGet 4
 ]

def func41Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64], locals := [.i64], body := func41, results := [.i64], typeIdx := some 41 }

/-- Exported function. -/
def func42 : Wasm.Program :=
  [
  .localGet 0,
  .localSet 8,
  .localGet 1,
  .localSet 9,
  .localGet 2,
  .localSet 10,
  .localGet 3,
  .localSet 11,
  .localGet 8,
  .localGet 9,
  .localGet 10,
  .localGet 11,
  .call 37,
  .localSet 13,
  .localSet 12,
  .localGet 12,
  .localSet 14,
  .localGet 13,
  .localSet 15,
  .localGet 4,
  .localSet 16,
  .localGet 5,
  .localSet 17,
  .localGet 6,
  .localSet 18,
  .localGet 7,
  .localSet 19,
  .localGet 16,
  .localGet 17,
  .localGet 18,
  .localGet 19,
  .call 37,
  .localSet 21,
  .localSet 20,
  .localGet 20,
  .localSet 22,
  .localGet 21,
  .localSet 23,
  .localGet 14,
  .localGet 15,
  .localGet 22,
  .localGet 23,
  .call 3,
  .localSet 25,
  .localSet 24,
  .localGet 24,
  .localSet 26,
  .localGet 25,
  .localSet 27,
  .localGet 26,
  .localGet 27
 ]

def func42Def : Wasm.Function :=
  { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func42, results := [.i64, .i64], typeIdx := some 42 }

/-- Exported function. -/
def func43 : Wasm.Program :=
  [
  .localGet 0,
  .constI64 7,
  .addI64,
  .constI64 8,
  .divUI64,
  .constI64 8,
  .mulI64,
  .localSet 1,
  .localGet 1,
  .constI64 8,
  .ltUI64,
  .iff 0 0 [
   .constI64 8,
   .localSet 1
  ] [],
  .constI64 0,
  .localSet 6,
  .constI64 0,
  .localSet 2,
  .globalGet 1,
  .localSet 3,
  .block 0 0 [
   .loop 0 0 [
    .localGet 3,
    .constI64 0,
    .eqI64,
    .br_if 1,
    .localGet 6,
    .constI64 0,
    .neI64,
    .br_if 1,
    .localGet 3,
    .constI64 32,
    .subI64,
    .wrapI64,
    .load64 0,
    .localSet 4,
    .localGet 3,
    .constI64 8,
    .subI64,
    .wrapI64,
    .load64 0,
    .localSet 5,
    .localGet 4,
    .localGet 1,
    .geUI64,
    .iff 0 0 [
     .localGet 2,
     .constI64 0,
     .eqI64,
     .iff 0 0 [
      .localGet 5,
      .globalSet 1
     ] [
      .localGet 2,
      .constI64 8,
      .subI64,
      .wrapI64,
      .localGet 5,
      .store64 0
     ],
     .localGet 3,
     .constI64 48,
     .subI64,
     .wrapI64,
     .constI64 5501223100278326855,
     .store64 0,
     .localGet 3,
     .constI64 40,
     .subI64,
     .wrapI64,
     .constI64 1,
     .store64 0,
     .localGet 3,
     .constI64 32,
     .subI64,
     .wrapI64,
     .localGet 4,
     .store64 0,
     .localGet 3,
     .constI64 24,
     .subI64,
     .wrapI64,
     .constI64 0,
     .store64 0,
     .localGet 3,
     .constI64 16,
     .subI64,
     .wrapI64,
     .constI64 0,
     .store64 0,
     .localGet 3,
     .constI64 8,
     .subI64,
     .wrapI64,
     .constI64 0,
     .store64 0,
     .localGet 3,
     .localSet 6
    ] [
     .localGet 3,
     .localSet 2,
     .localGet 5,
     .localSet 3
    ],
    .br 0
   ]
  ],
  .localGet 6,
  .constI64 0,
  .eqI64,
  .iff 0 0 [
   .globalGet 0,
   .constI64 48,
   .addI64,
   .localGet 1,
   .addI64,
   .localTee 4,
   .globalGet 0,
   .ltUI64,
   .iff 0 0 [
    .unreachable
   ] [],
   .localGet 4,
   .constI64 1,
   .subI64,
   .constI64 65536,
   .divUI64,
   .constI64 1,
   .addI64,
   .localSet 5,
   .memorySize,
   .extendUI32,
   .localGet 5,
   .ltUI64,
   .iff 0 0 [
    .localGet 5,
    .memorySize,
    .extendUI32,
    .subI64,
    .wrapI64,
    .memoryGrow,
    .const (-1),
    .eq,
    .iff 0 0 [
     .unreachable
    ] []
   ] [],
   .globalGet 0,
   .constI64 48,
   .addI64,
   .localSet 6,
   .localGet 4,
   .globalSet 0,
   .localGet 6,
   .constI64 48,
   .subI64,
   .wrapI64,
   .constI64 5501223100278326855,
   .store64 0,
   .localGet 6,
   .constI64 40,
   .subI64,
   .wrapI64,
   .constI64 1,
   .store64 0,
   .localGet 6,
   .constI64 32,
   .subI64,
   .wrapI64,
   .localGet 1,
   .store64 0,
   .localGet 6,
   .constI64 24,
   .subI64,
   .wrapI64,
   .constI64 0,
   .store64 0,
   .localGet 6,
   .constI64 16,
   .subI64,
   .wrapI64,
   .constI64 0,
   .store64 0,
   .localGet 6,
   .constI64 8,
   .subI64,
   .wrapI64,
   .constI64 0,
   .store64 0
  ] [],
  .globalGet 2,
  .constI64 1,
  .addI64,
  .globalSet 2,
  .localGet 6
 ]

def func43Def : Wasm.Function :=
  { params := [.i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64], body := func43, results := [.i64], typeIdx := some 43 }

/-- Exported function. -/
def func44 : Wasm.Program :=
  [
  .constI64 4096,
  .globalSet 0,
  .constI64 0,
  .globalSet 1,
  .constI64 0,
  .globalSet 2,
  .constI64 0,
  .globalSet 3,
  .constI64 0,
  .globalSet 4,
  .constI64 0,
  .globalSet 5
 ]

def func44Def : Wasm.Function :=
  { body := func44, typeIdx := some 44 }

/-- Exported function. -/
def func45 : Wasm.Program :=
  [
  .localGet 0,
  .constI64 0,
  .neI64,
  .iff 0 0 [
   .localGet 0,
   .constI64 48,
   .subI64,
   .wrapI64,
   .load64 0,
   .constI64 5501223100278326855,
   .neI64,
   .iff 0 0 [
    .unreachable
   ] [],
   .localGet 0,
   .constI64 40,
   .subI64,
   .wrapI64,
   .load64 0,
   .localSet 1,
   .localGet 1,
   .constI64 0,
   .eqI64,
   .iff 0 0 [
    .unreachable
   ] [],
   .globalGet 3,
   .constI64 1,
   .addI64,
   .globalSet 3,
   .localGet 0,
   .constI64 40,
   .subI64,
   .wrapI64,
   .localGet 1,
   .constI64 1,
   .addI64,
   .store64 0
  ] [],
  .localGet 0
 ]

def func45Def : Wasm.Function :=
  { params := [.i64], locals := [.i64], body := func45, results := [.i64], typeIdx := some 45 }

/-- Exported function. -/
def func46 : Wasm.Program :=
  [
  .localGet 0,
  .constI64 0,
  .eqI64,
  .iff 0 0 [
   .ret
  ] [],
  .localGet 0,
  .constI64 48,
  .subI64,
  .wrapI64,
  .load64 0,
  .constI64 5501223100278326855,
  .neI64,
  .iff 0 0 [
   .unreachable
  ] [],
  .localGet 0,
  .constI64 40,
  .subI64,
  .wrapI64,
  .load64 0,
  .localSet 1,
  .localGet 1,
  .constI64 0,
  .eqI64,
  .iff 0 0 [
   .unreachable
  ] [],
  .globalGet 4,
  .constI64 1,
  .addI64,
  .globalSet 4,
  .constI64 1,
  .localGet 1,
  .ltUI64,
  .iff 0 0 [
   .localGet 0,
   .constI64 40,
   .subI64,
   .wrapI64,
   .localGet 1,
   .constI64 1,
   .subI64,
   .store64 0,
   .ret
  ] [],
  .localGet 0,
  .constI64 24,
  .subI64,
  .wrapI64,
  .load64 0,
  .localSet 2,
  .localGet 2,
  .constI64 1,
  .eqI64,
  .iff 0 0 [
   .localGet 0,
   .constI64 16,
   .subI64,
   .wrapI64,
   .load64 0,
   .localSet 3,
   .localGet 0,
   .constI64 8,
   .subI64,
   .wrapI64,
   .load64 0,
   .localSet 5,
   .constI64 0,
   .localSet 6,
   .block 0 0 [
    .loop 0 0 [
     .localGet 6,
     .localGet 3,
     .geUI64,
     .br_if 1,
     .localGet 5,
     .localGet 6,
     .shrUI64,
     .constI64 1,
     .andI64,
     .constI64 0,
     .neI64,
     .iff 0 0 [
      .localGet 0,
      .localGet 6,
      .constI64 8,
      .mulI64,
      .addI64,
      .wrapI64,
      .load64 0,
      .localSet 8,
      .localGet 8,
      .call 46
     ] [],
     .localGet 6,
     .constI64 1,
     .addI64,
     .localSet 6,
     .br 0
    ]
   ]
  ] [],
  .localGet 2,
  .constI64 2,
  .eqI64,
  .iff 0 0 [
   .localGet 0,
   .wrapI64,
   .load64 0,
   .localSet 3,
   .localGet 0,
   .constI64 16,
   .subI64,
   .wrapI64,
   .load64 0,
   .localSet 4,
   .localGet 0,
   .constI64 8,
   .subI64,
   .wrapI64,
   .load64 0,
   .localSet 5,
   .constI64 0,
   .localSet 7,
   .block 0 0 [
    .loop 0 0 [
     .localGet 7,
     .localGet 3,
     .geUI64,
     .br_if 1,
     .constI64 0,
     .localSet 6,
     .block 0 0 [
      .loop 0 0 [
       .localGet 6,
       .localGet 4,
       .geUI64,
       .br_if 1,
       .localGet 5,
       .localGet 6,
       .shrUI64,
       .constI64 1,
       .andI64,
       .constI64 0,
       .neI64,
       .iff 0 0 [
        .localGet 0,
        .constI64 8,
        .addI64,
        .localGet 7,
        .localGet 4,
        .mulI64,
        .localGet 6,
        .addI64,
        .constI64 8,
        .mulI64,
        .addI64,
        .wrapI64,
        .load64 0,
        .localSet 8,
        .localGet 8,
        .call 46
       ] [],
       .localGet 6,
       .constI64 1,
       .addI64,
       .localSet 6,
       .br 0
      ]
     ],
     .localGet 7,
     .constI64 1,
     .addI64,
     .localSet 7,
     .br 0
    ]
   ]
  ] [],
  .globalGet 5,
  .constI64 1,
  .addI64,
  .globalSet 5,
  .localGet 0,
  .constI64 40,
  .subI64,
  .wrapI64,
  .constI64 0,
  .store64 0,
  .localGet 0,
  .constI64 8,
  .subI64,
  .wrapI64,
  .globalGet 1,
  .store64 0,
  .localGet 0,
  .globalSet 1
 ]

def func46Def : Wasm.Function :=
  { params := [.i64], locals := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], body := func46, typeIdx := some 46 }

def «module» : Wasm.Module :=
{
  funcs := [
   func0Def,
   func1Def,
   func2Def,
   func3Def,
   func4Def,
   func5Def,
   func6Def,
   func7Def,
   func8Def,
   func9Def,
   func10Def,
   func11Def,
   func12Def,
   func13Def,
   func14Def,
   func15Def,
   func16Def,
   func17Def,
   func18Def,
   func19Def,
   func20Def,
   func21Def,
   func22Def,
   func23Def,
   func24Def,
   func25Def,
   func26Def,
   func27Def,
   func28Def,
   func29Def,
   func30Def,
   func31Def,
   func32Def,
   func33Def,
   func34Def,
   func35Def,
   func36Def,
   func37Def,
   func38Def,
   func39Def,
   func40Def,
   func41Def,
   func42Def,
   func43Def,
   func44Def,
   func45Def,
   func46Def
  ],
  exports := [
   { name := "interfaceUpper", funcIdx := 42 },
   { name := "alloc", funcIdx := 43 },
   { name := "reset", funcIdx := 44 },
   { name := "retain", funcIdx := 45 },
   { name := "release", funcIdx := 46 },
   { name := "free", funcIdx := 46 }
  ],
  memory := some ({ pagesMin := 16 }),
  globals := [
   { init := .i64 4096, declaredType := some (.i64), sourceInit := some ([
     .constI64 4096
    ]) },
   { init := .i64 0, declaredType := some (.i64), sourceInit := some ([
     .constI64 0
    ]) },
   { init := .i64 0, declaredType := some (.i64), sourceInit := some ([
     .constI64 0
    ]) },
   { init := .i64 0, declaredType := some (.i64), sourceInit := some ([
     .constI64 0
    ]) },
   { init := .i64 0, declaredType := some (.i64), sourceInit := some ([
     .constI64 0
    ]) },
   { init := .i64 0, declaredType := some (.i64), sourceInit := some ([
     .constI64 0
    ]) }
  ],
  types := [
   { params := [.i64, .i64], results := [.i64] },
   { params := [.i64, .i64], results := [.i64] },
   { results := [.i64, .i64] },
   { params := [.i64, .i64, .i64, .i64], results := [.i64, .i64] },
   { params := [.i64], results := [.i64] },
   { params := [.i64], results := [.i64] },
   { params := [.i64], results := [.i64] },
   { params := [.i64, .i64, .i64, .i64], results := [.i64] },
   { params := [.i64], results := [.i64] },
   { params := [.i64], results := [.i64] },
   { params := [.i64], results := [.i64] },
   { params := [.i64, .i64], results := [.i64] },
   { params := [.i64], results := [.i64] },
   { params := [.i64, .i64, .i64, .i64], results := [.i64] },
   { params := [.i64, .i64], results := [.i64] },
   { params := [.i64, .i64], results := [.i64] },
   { params := [.i64, .i64], results := [.i64] },
   { params := [.i64, .i64, .i64, .i64], results := [.i64] },
   { params := [.i64, .i64], results := [.i64] },
   { params := [.i64, .i64], results := [.i64] },
   { params := [.i64, .i64, .i64, .i64], results := [.i64] },
   { params := [.i64, .i64, .i64, .i64], results := [.i64] },
   { params := [.i64, .i64, .i64, .i64], results := [.i64] },
   { params := [.i64], results := [.i64] },
   { params := [.i64], results := [.i64] },
   { params := [.i64, .i64], results := [.i64] },
   { params := [.i64, .i64], results := [.i64, .i64] },
   { params := [.i64, .i64, .i64], results := [.i64, .i64] },
   { params := [.i64, .i64, .i64], results := [.i64, .i64] },
   { params := [.i64, .i64, .i64], results := [.i64, .i64] },
   { params := [.i64, .i64, .i64], results := [.i64, .i64] },
   { params := [.i64, .i64, .i64], results := [.i64, .i64] },
   { params := [.i64, .i64, .i64, .i64], results := [.i64, .i64] },
   { params := [.i64, .i64, .i64, .i64], results := [.i64, .i64] },
   { params := [.i64, .i64, .i64, .i64], results := [.i64, .i64] },
   { params := [.i64, .i64], results := [.i64, .i64] },
   { params := [.i64, .i64, .i64, .i64], results := [.i64, .i64] },
   { params := [.i64, .i64, .i64, .i64], results := [.i64, .i64] },
   { params := [.i64, .i64, .i64, .i64], results := [.i64] },
   { params := [.i64, .i64, .i64, .i64], results := [.i64] },
   { params := [.i64, .i64, .i64, .i64], results := [.i64] },
   { params := [.i64, .i64, .i64, .i64], results := [.i64] },
   { params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64, .i64] },
   { params := [.i64], results := [.i64] },
   {},
   { params := [.i64], results := [.i64] },
   { params := [.i64] }
  ],
  gcTypes := [
   { comp := .func ({ params := [.i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64], results := [.i64] }) },
   { comp := .func ({ results := [.i64, .i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64], results := [.i64, .i64] }) },
   { comp := .func ({ params := [.i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64], results := [.i64, .i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64], results := [.i64, .i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64], results := [.i64, .i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64], results := [.i64, .i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64], results := [.i64, .i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64], results := [.i64, .i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64], results := [.i64, .i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64], results := [.i64, .i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64], results := [.i64, .i64] }) },
   { comp := .func ({ params := [.i64, .i64], results := [.i64, .i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64], results := [.i64, .i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64], results := [.i64, .i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64, .i64, .i64, .i64, .i64, .i64, .i64, .i64], results := [.i64, .i64] }) },
   { comp := .func ({ params := [.i64], results := [.i64] }) },
   { comp := .func ({}) },
   { comp := .func ({ params := [.i64], results := [.i64] }) },
   { comp := .func ({ params := [.i64] }) }
  ],
  globalExports := [
   ("allocCount", 2),
   ("retainCount", 3),
   ("releaseCount", 4),
   ("freeCount", 5)
  ],
  memoryExports := [
   ("memory", 0)
  ]
}

end Project.EulerOutwardMaximum
