import Project.TinyGpt2Hidden.ArtifactBody75Part1

namespace Project.TinyGpt2Hidden.Artifact
open Wasm.Binary

attribute [local cbv_opaque] artifactBytes artifactData
attribute [local cbv_eval] artifactBytes_data artifactBytes_size

@[cbv_eval] theorem sequence75_22_t_tail40 :
    instructionSequenceAt 298 true { bytes := artifactBytes, pos := 15489, limit := 15544 } =
      .ok (([Wasm.Binary.Instr.localGet 6,
 Wasm.Binary.Instr.i64Const 32,
 Wasm.Binary.Instr.i64Sub,
 Wasm.Binary.Instr.i32WrapI64,
 Wasm.Binary.Instr.localGet 1,
 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
 Wasm.Binary.Instr.localGet 6,
 Wasm.Binary.Instr.i64Const 24,
 Wasm.Binary.Instr.i64Sub,
 Wasm.Binary.Instr.i32WrapI64,
 Wasm.Binary.Instr.i64Const 0,
 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
 Wasm.Binary.Instr.localGet 6,
 Wasm.Binary.Instr.i64Const 16,
 Wasm.Binary.Instr.i64Sub,
 Wasm.Binary.Instr.i32WrapI64,
 Wasm.Binary.Instr.i64Const 0,
 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
 Wasm.Binary.Instr.localGet 6,
 Wasm.Binary.Instr.i64Const 8,
 Wasm.Binary.Instr.i64Sub,
 Wasm.Binary.Instr.i32WrapI64,
 Wasm.Binary.Instr.i64Const 0,
 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 }], .end), { bytes := artifactBytes, pos := 15534, limit := 15544 }) := by
  cbv

@[cbv_eval] theorem sequence75_22_t_tail32 :
    instructionSequenceAt 306 true { bytes := artifactBytes, pos := 15464, limit := 15544 } =
      .ok (([Wasm.Binary.Instr.i64Const 5501223100278326855,
 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
 Wasm.Binary.Instr.localGet 6,
 Wasm.Binary.Instr.i64Const 40,
 Wasm.Binary.Instr.i64Sub,
 Wasm.Binary.Instr.i32WrapI64,
 Wasm.Binary.Instr.i64Const 1,
 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
 Wasm.Binary.Instr.localGet 6,
 Wasm.Binary.Instr.i64Const 32,
 Wasm.Binary.Instr.i64Sub,
 Wasm.Binary.Instr.i32WrapI64,
 Wasm.Binary.Instr.localGet 1,
 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
 Wasm.Binary.Instr.localGet 6,
 Wasm.Binary.Instr.i64Const 24,
 Wasm.Binary.Instr.i64Sub,
 Wasm.Binary.Instr.i32WrapI64,
 Wasm.Binary.Instr.i64Const 0,
 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
 Wasm.Binary.Instr.localGet 6,
 Wasm.Binary.Instr.i64Const 16,
 Wasm.Binary.Instr.i64Sub,
 Wasm.Binary.Instr.i32WrapI64,
 Wasm.Binary.Instr.i64Const 0,
 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
 Wasm.Binary.Instr.localGet 6,
 Wasm.Binary.Instr.i64Const 8,
 Wasm.Binary.Instr.i64Sub,
 Wasm.Binary.Instr.i32WrapI64,
 Wasm.Binary.Instr.i64Const 0,
 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 }], .end), { bytes := artifactBytes, pos := 15534, limit := 15544 }) := by
  cbv

@[cbv_eval] theorem sequence75_22_t_tail24 :
    instructionSequenceAt 314 true { bytes := artifactBytes, pos := 15451, limit := 15544 } =
      .ok (([Wasm.Binary.Instr.i64Add,
 Wasm.Binary.Instr.localSet 6,
 Wasm.Binary.Instr.localGet 4,
 Wasm.Binary.Instr.globalSet 0,
 Wasm.Binary.Instr.localGet 6,
 Wasm.Binary.Instr.i64Const 48,
 Wasm.Binary.Instr.i64Sub,
 Wasm.Binary.Instr.i32WrapI64,
 Wasm.Binary.Instr.i64Const 5501223100278326855,
 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
 Wasm.Binary.Instr.localGet 6,
 Wasm.Binary.Instr.i64Const 40,
 Wasm.Binary.Instr.i64Sub,
 Wasm.Binary.Instr.i32WrapI64,
 Wasm.Binary.Instr.i64Const 1,
 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
 Wasm.Binary.Instr.localGet 6,
 Wasm.Binary.Instr.i64Const 32,
 Wasm.Binary.Instr.i64Sub,
 Wasm.Binary.Instr.i32WrapI64,
 Wasm.Binary.Instr.localGet 1,
 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
 Wasm.Binary.Instr.localGet 6,
 Wasm.Binary.Instr.i64Const 24,
 Wasm.Binary.Instr.i64Sub,
 Wasm.Binary.Instr.i32WrapI64,
 Wasm.Binary.Instr.i64Const 0,
 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
 Wasm.Binary.Instr.localGet 6,
 Wasm.Binary.Instr.i64Const 16,
 Wasm.Binary.Instr.i64Sub,
 Wasm.Binary.Instr.i32WrapI64,
 Wasm.Binary.Instr.i64Const 0,
 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
 Wasm.Binary.Instr.localGet 6,
 Wasm.Binary.Instr.i64Const 8,
 Wasm.Binary.Instr.i64Sub,
 Wasm.Binary.Instr.i32WrapI64,
 Wasm.Binary.Instr.i64Const 0,
 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 }], .end), { bytes := artifactBytes, pos := 15534, limit := 15544 }) := by
  cbv

@[cbv_eval] theorem sequence75_22_t_tail16 :
    instructionSequenceAt 322 true { bytes := artifactBytes, pos := 15420, limit := 15544 } =
      .ok (([Wasm.Binary.Instr.localSet 5,
 Wasm.Binary.Instr.memorySize 0,
 Wasm.Binary.Instr.i64ExtendI32U,
 Wasm.Binary.Instr.localGet 5,
 Wasm.Binary.Instr.i64LtU,
 Wasm.Binary.Instr.iff
   (Wasm.Binary.BlockType.empty)
   [Wasm.Binary.Instr.localGet 5,
    Wasm.Binary.Instr.memorySize 0,
    Wasm.Binary.Instr.i64ExtendI32U,
    Wasm.Binary.Instr.i64Sub,
    Wasm.Binary.Instr.i32WrapI64,
    Wasm.Binary.Instr.memoryGrow 0,
    Wasm.Binary.Instr.i32Const (-1),
    Wasm.Binary.Instr.i32Eq,
    Wasm.Binary.Instr.iff (Wasm.Binary.BlockType.empty) [Wasm.Binary.Instr.unreachable] none]
   none,
 Wasm.Binary.Instr.globalGet 0,
 Wasm.Binary.Instr.i64Const 48,
 Wasm.Binary.Instr.i64Add,
 Wasm.Binary.Instr.localSet 6,
 Wasm.Binary.Instr.localGet 4,
 Wasm.Binary.Instr.globalSet 0,
 Wasm.Binary.Instr.localGet 6,
 Wasm.Binary.Instr.i64Const 48,
 Wasm.Binary.Instr.i64Sub,
 Wasm.Binary.Instr.i32WrapI64,
 Wasm.Binary.Instr.i64Const 5501223100278326855,
 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
 Wasm.Binary.Instr.localGet 6,
 Wasm.Binary.Instr.i64Const 40,
 Wasm.Binary.Instr.i64Sub,
 Wasm.Binary.Instr.i32WrapI64,
 Wasm.Binary.Instr.i64Const 1,
 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
 Wasm.Binary.Instr.localGet 6,
 Wasm.Binary.Instr.i64Const 32,
 Wasm.Binary.Instr.i64Sub,
 Wasm.Binary.Instr.i32WrapI64,
 Wasm.Binary.Instr.localGet 1,
 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
 Wasm.Binary.Instr.localGet 6,
 Wasm.Binary.Instr.i64Const 24,
 Wasm.Binary.Instr.i64Sub,
 Wasm.Binary.Instr.i32WrapI64,
 Wasm.Binary.Instr.i64Const 0,
 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
 Wasm.Binary.Instr.localGet 6,
 Wasm.Binary.Instr.i64Const 16,
 Wasm.Binary.Instr.i64Sub,
 Wasm.Binary.Instr.i32WrapI64,
 Wasm.Binary.Instr.i64Const 0,
 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
 Wasm.Binary.Instr.localGet 6,
 Wasm.Binary.Instr.i64Const 8,
 Wasm.Binary.Instr.i64Sub,
 Wasm.Binary.Instr.i32WrapI64,
 Wasm.Binary.Instr.i64Const 0,
 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 }], .end), { bytes := artifactBytes, pos := 15534, limit := 15544 }) := by
  cbv

@[cbv_eval] theorem sequence75_22_t_tail8 :
    instructionSequenceAt 330 true { bytes := artifactBytes, pos := 15403, limit := 15544 } =
      .ok (([Wasm.Binary.Instr.iff (Wasm.Binary.BlockType.empty) [Wasm.Binary.Instr.unreachable] none,
 Wasm.Binary.Instr.localGet 4,
 Wasm.Binary.Instr.i64Const 1,
 Wasm.Binary.Instr.i64Sub,
 Wasm.Binary.Instr.i64Const 65536,
 Wasm.Binary.Instr.i64DivU,
 Wasm.Binary.Instr.i64Const 1,
 Wasm.Binary.Instr.i64Add,
 Wasm.Binary.Instr.localSet 5,
 Wasm.Binary.Instr.memorySize 0,
 Wasm.Binary.Instr.i64ExtendI32U,
 Wasm.Binary.Instr.localGet 5,
 Wasm.Binary.Instr.i64LtU,
 Wasm.Binary.Instr.iff
   (Wasm.Binary.BlockType.empty)
   [Wasm.Binary.Instr.localGet 5,
    Wasm.Binary.Instr.memorySize 0,
    Wasm.Binary.Instr.i64ExtendI32U,
    Wasm.Binary.Instr.i64Sub,
    Wasm.Binary.Instr.i32WrapI64,
    Wasm.Binary.Instr.memoryGrow 0,
    Wasm.Binary.Instr.i32Const (-1),
    Wasm.Binary.Instr.i32Eq,
    Wasm.Binary.Instr.iff (Wasm.Binary.BlockType.empty) [Wasm.Binary.Instr.unreachable] none]
   none,
 Wasm.Binary.Instr.globalGet 0,
 Wasm.Binary.Instr.i64Const 48,
 Wasm.Binary.Instr.i64Add,
 Wasm.Binary.Instr.localSet 6,
 Wasm.Binary.Instr.localGet 4,
 Wasm.Binary.Instr.globalSet 0,
 Wasm.Binary.Instr.localGet 6,
 Wasm.Binary.Instr.i64Const 48,
 Wasm.Binary.Instr.i64Sub,
 Wasm.Binary.Instr.i32WrapI64,
 Wasm.Binary.Instr.i64Const 5501223100278326855,
 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
 Wasm.Binary.Instr.localGet 6,
 Wasm.Binary.Instr.i64Const 40,
 Wasm.Binary.Instr.i64Sub,
 Wasm.Binary.Instr.i32WrapI64,
 Wasm.Binary.Instr.i64Const 1,
 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
 Wasm.Binary.Instr.localGet 6,
 Wasm.Binary.Instr.i64Const 32,
 Wasm.Binary.Instr.i64Sub,
 Wasm.Binary.Instr.i32WrapI64,
 Wasm.Binary.Instr.localGet 1,
 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
 Wasm.Binary.Instr.localGet 6,
 Wasm.Binary.Instr.i64Const 24,
 Wasm.Binary.Instr.i64Sub,
 Wasm.Binary.Instr.i32WrapI64,
 Wasm.Binary.Instr.i64Const 0,
 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
 Wasm.Binary.Instr.localGet 6,
 Wasm.Binary.Instr.i64Const 16,
 Wasm.Binary.Instr.i64Sub,
 Wasm.Binary.Instr.i32WrapI64,
 Wasm.Binary.Instr.i64Const 0,
 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
 Wasm.Binary.Instr.localGet 6,
 Wasm.Binary.Instr.i64Const 8,
 Wasm.Binary.Instr.i64Sub,
 Wasm.Binary.Instr.i32WrapI64,
 Wasm.Binary.Instr.i64Const 0,
 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 }], .end), { bytes := artifactBytes, pos := 15534, limit := 15544 }) := by
  cbv

@[cbv_eval] theorem sequence75_22_t_tail0 :
    instructionSequenceAt 338 true { bytes := artifactBytes, pos := 15390, limit := 15544 } =
      .ok (([Wasm.Binary.Instr.globalGet 0,
 Wasm.Binary.Instr.i64Const 48,
 Wasm.Binary.Instr.i64Add,
 Wasm.Binary.Instr.localGet 1,
 Wasm.Binary.Instr.i64Add,
 Wasm.Binary.Instr.localTee 4,
 Wasm.Binary.Instr.globalGet 0,
 Wasm.Binary.Instr.i64LtU,
 Wasm.Binary.Instr.iff (Wasm.Binary.BlockType.empty) [Wasm.Binary.Instr.unreachable] none,
 Wasm.Binary.Instr.localGet 4,
 Wasm.Binary.Instr.i64Const 1,
 Wasm.Binary.Instr.i64Sub,
 Wasm.Binary.Instr.i64Const 65536,
 Wasm.Binary.Instr.i64DivU,
 Wasm.Binary.Instr.i64Const 1,
 Wasm.Binary.Instr.i64Add,
 Wasm.Binary.Instr.localSet 5,
 Wasm.Binary.Instr.memorySize 0,
 Wasm.Binary.Instr.i64ExtendI32U,
 Wasm.Binary.Instr.localGet 5,
 Wasm.Binary.Instr.i64LtU,
 Wasm.Binary.Instr.iff
   (Wasm.Binary.BlockType.empty)
   [Wasm.Binary.Instr.localGet 5,
    Wasm.Binary.Instr.memorySize 0,
    Wasm.Binary.Instr.i64ExtendI32U,
    Wasm.Binary.Instr.i64Sub,
    Wasm.Binary.Instr.i32WrapI64,
    Wasm.Binary.Instr.memoryGrow 0,
    Wasm.Binary.Instr.i32Const (-1),
    Wasm.Binary.Instr.i32Eq,
    Wasm.Binary.Instr.iff (Wasm.Binary.BlockType.empty) [Wasm.Binary.Instr.unreachable] none]
   none,
 Wasm.Binary.Instr.globalGet 0,
 Wasm.Binary.Instr.i64Const 48,
 Wasm.Binary.Instr.i64Add,
 Wasm.Binary.Instr.localSet 6,
 Wasm.Binary.Instr.localGet 4,
 Wasm.Binary.Instr.globalSet 0,
 Wasm.Binary.Instr.localGet 6,
 Wasm.Binary.Instr.i64Const 48,
 Wasm.Binary.Instr.i64Sub,
 Wasm.Binary.Instr.i32WrapI64,
 Wasm.Binary.Instr.i64Const 5501223100278326855,
 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
 Wasm.Binary.Instr.localGet 6,
 Wasm.Binary.Instr.i64Const 40,
 Wasm.Binary.Instr.i64Sub,
 Wasm.Binary.Instr.i32WrapI64,
 Wasm.Binary.Instr.i64Const 1,
 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
 Wasm.Binary.Instr.localGet 6,
 Wasm.Binary.Instr.i64Const 32,
 Wasm.Binary.Instr.i64Sub,
 Wasm.Binary.Instr.i32WrapI64,
 Wasm.Binary.Instr.localGet 1,
 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
 Wasm.Binary.Instr.localGet 6,
 Wasm.Binary.Instr.i64Const 24,
 Wasm.Binary.Instr.i64Sub,
 Wasm.Binary.Instr.i32WrapI64,
 Wasm.Binary.Instr.i64Const 0,
 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
 Wasm.Binary.Instr.localGet 6,
 Wasm.Binary.Instr.i64Const 16,
 Wasm.Binary.Instr.i64Sub,
 Wasm.Binary.Instr.i32WrapI64,
 Wasm.Binary.Instr.i64Const 0,
 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
 Wasm.Binary.Instr.localGet 6,
 Wasm.Binary.Instr.i64Const 8,
 Wasm.Binary.Instr.i64Sub,
 Wasm.Binary.Instr.i32WrapI64,
 Wasm.Binary.Instr.i64Const 0,
 Wasm.Binary.Instr.i64Store { align := 3, offset := 0 }], .end), { bytes := artifactBytes, pos := 15534, limit := 15544 }) := by
  cbv

@[cbv_opaque] def body75Tail28 : List Instr := []

@[cbv_eval] theorem sequence75_tail28 :
    instructionSequenceAt 334 false { bytes := artifactBytes, pos := 15543, limit := 15544 } =
      .ok ((body75Tail28, .end), { bytes := artifactBytes, pos := 15544, limit := 15544 }) := by
  change _ = (Except.ok (([], .end), { bytes := artifactBytes, pos := 15544, limit := 15544 }) : Except Error ((List Instr × Terminator) × Cursor))
  cbv

@[cbv_opaque] def body75Tail24 : List Instr := ([Wasm.Binary.Instr.i64Const 1, Wasm.Binary.Instr.i64Add, Wasm.Binary.Instr.globalSet 2, Wasm.Binary.Instr.localGet 6] ++ body75Tail28)

@[cbv_eval] theorem sequence75_tail24 :
    instructionSequenceAt 338 false { bytes := artifactBytes, pos := 15536, limit := 15544 } =
      .ok ((body75Tail24, .end), { bytes := artifactBytes, pos := 15544, limit := 15544 }) := by
  change _ = (Except.ok ((([Wasm.Binary.Instr.i64Const 1, Wasm.Binary.Instr.i64Add, Wasm.Binary.Instr.globalSet 2, Wasm.Binary.Instr.localGet 6] ++ body75Tail28), .end), { bytes := artifactBytes, pos := 15544, limit := 15544 }) : Except Error ((List Instr × Terminator) × Cursor))
  cbv

@[cbv_opaque] def body75Tail16 : List Instr := ([Wasm.Binary.Instr.globalGet 1,
 Wasm.Binary.Instr.localSet 3,
 Wasm.Binary.Instr.block
   (Wasm.Binary.BlockType.empty)
   [Wasm.Binary.Instr.loop
      (Wasm.Binary.BlockType.empty)
      [Wasm.Binary.Instr.localGet 3,
       Wasm.Binary.Instr.i64Const 0,
       Wasm.Binary.Instr.i64Eq,
       Wasm.Binary.Instr.brIf 1,
       Wasm.Binary.Instr.localGet 6,
       Wasm.Binary.Instr.i64Const 0,
       Wasm.Binary.Instr.i64Ne,
       Wasm.Binary.Instr.brIf 1,
       Wasm.Binary.Instr.localGet 3,
       Wasm.Binary.Instr.i64Const 32,
       Wasm.Binary.Instr.i64Sub,
       Wasm.Binary.Instr.i32WrapI64,
       Wasm.Binary.Instr.i64Load { align := 3, offset := 0 },
       Wasm.Binary.Instr.localSet 4,
       Wasm.Binary.Instr.localGet 3,
       Wasm.Binary.Instr.i64Const 8,
       Wasm.Binary.Instr.i64Sub,
       Wasm.Binary.Instr.i32WrapI64,
       Wasm.Binary.Instr.i64Load { align := 3, offset := 0 },
       Wasm.Binary.Instr.localSet 5,
       Wasm.Binary.Instr.localGet 4,
       Wasm.Binary.Instr.localGet 1,
       Wasm.Binary.Instr.i64GeU,
       Wasm.Binary.Instr.iff
         (Wasm.Binary.BlockType.empty)
         [Wasm.Binary.Instr.localGet 2,
          Wasm.Binary.Instr.i64Const 0,
          Wasm.Binary.Instr.i64Eq,
          Wasm.Binary.Instr.iff
            (Wasm.Binary.BlockType.empty)
            [Wasm.Binary.Instr.localGet 5, Wasm.Binary.Instr.globalSet 1]
            (some [Wasm.Binary.Instr.localGet 2,
              Wasm.Binary.Instr.i64Const 8,
              Wasm.Binary.Instr.i64Sub,
              Wasm.Binary.Instr.i32WrapI64,
              Wasm.Binary.Instr.localGet 5,
              Wasm.Binary.Instr.i64Store { align := 3, offset := 0 }]),
          Wasm.Binary.Instr.localGet 3,
          Wasm.Binary.Instr.i64Const 48,
          Wasm.Binary.Instr.i64Sub,
          Wasm.Binary.Instr.i32WrapI64,
          Wasm.Binary.Instr.i64Const 5501223100278326855,
          Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
          Wasm.Binary.Instr.localGet 3,
          Wasm.Binary.Instr.i64Const 40,
          Wasm.Binary.Instr.i64Sub,
          Wasm.Binary.Instr.i32WrapI64,
          Wasm.Binary.Instr.i64Const 1,
          Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
          Wasm.Binary.Instr.localGet 3,
          Wasm.Binary.Instr.i64Const 32,
          Wasm.Binary.Instr.i64Sub,
          Wasm.Binary.Instr.i32WrapI64,
          Wasm.Binary.Instr.localGet 4,
          Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
          Wasm.Binary.Instr.localGet 3,
          Wasm.Binary.Instr.i64Const 24,
          Wasm.Binary.Instr.i64Sub,
          Wasm.Binary.Instr.i32WrapI64,
          Wasm.Binary.Instr.i64Const 0,
          Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
          Wasm.Binary.Instr.localGet 3,
          Wasm.Binary.Instr.i64Const 16,
          Wasm.Binary.Instr.i64Sub,
          Wasm.Binary.Instr.i32WrapI64,
          Wasm.Binary.Instr.i64Const 0,
          Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
          Wasm.Binary.Instr.localGet 3,
          Wasm.Binary.Instr.i64Const 8,
          Wasm.Binary.Instr.i64Sub,
          Wasm.Binary.Instr.i32WrapI64,
          Wasm.Binary.Instr.i64Const 0,
          Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
          Wasm.Binary.Instr.localGet 3,
          Wasm.Binary.Instr.localSet 6]
         (some [Wasm.Binary.Instr.localGet 3,
           Wasm.Binary.Instr.localSet 2,
           Wasm.Binary.Instr.localGet 5,
           Wasm.Binary.Instr.localSet 3]),
       Wasm.Binary.Instr.br 0]],
 Wasm.Binary.Instr.localGet 6,
 Wasm.Binary.Instr.i64Const 0,
 Wasm.Binary.Instr.i64Eq,
 Wasm.Binary.Instr.iff
   (Wasm.Binary.BlockType.empty)
   [Wasm.Binary.Instr.globalGet 0,
    Wasm.Binary.Instr.i64Const 48,
    Wasm.Binary.Instr.i64Add,
    Wasm.Binary.Instr.localGet 1,
    Wasm.Binary.Instr.i64Add,
    Wasm.Binary.Instr.localTee 4,
    Wasm.Binary.Instr.globalGet 0,
    Wasm.Binary.Instr.i64LtU,
    Wasm.Binary.Instr.iff (Wasm.Binary.BlockType.empty) [Wasm.Binary.Instr.unreachable] none,
    Wasm.Binary.Instr.localGet 4,
    Wasm.Binary.Instr.i64Const 1,
    Wasm.Binary.Instr.i64Sub,
    Wasm.Binary.Instr.i64Const 65536,
    Wasm.Binary.Instr.i64DivU,
    Wasm.Binary.Instr.i64Const 1,
    Wasm.Binary.Instr.i64Add,
    Wasm.Binary.Instr.localSet 5,
    Wasm.Binary.Instr.memorySize 0,
    Wasm.Binary.Instr.i64ExtendI32U,
    Wasm.Binary.Instr.localGet 5,
    Wasm.Binary.Instr.i64LtU,
    Wasm.Binary.Instr.iff
      (Wasm.Binary.BlockType.empty)
      [Wasm.Binary.Instr.localGet 5,
       Wasm.Binary.Instr.memorySize 0,
       Wasm.Binary.Instr.i64ExtendI32U,
       Wasm.Binary.Instr.i64Sub,
       Wasm.Binary.Instr.i32WrapI64,
       Wasm.Binary.Instr.memoryGrow 0,
       Wasm.Binary.Instr.i32Const (-1),
       Wasm.Binary.Instr.i32Eq,
       Wasm.Binary.Instr.iff (Wasm.Binary.BlockType.empty) [Wasm.Binary.Instr.unreachable] none]
      none,
    Wasm.Binary.Instr.globalGet 0,
    Wasm.Binary.Instr.i64Const 48,
    Wasm.Binary.Instr.i64Add,
    Wasm.Binary.Instr.localSet 6,
    Wasm.Binary.Instr.localGet 4,
    Wasm.Binary.Instr.globalSet 0,
    Wasm.Binary.Instr.localGet 6,
    Wasm.Binary.Instr.i64Const 48,
    Wasm.Binary.Instr.i64Sub,
    Wasm.Binary.Instr.i32WrapI64,
    Wasm.Binary.Instr.i64Const 5501223100278326855,
    Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
    Wasm.Binary.Instr.localGet 6,
    Wasm.Binary.Instr.i64Const 40,
    Wasm.Binary.Instr.i64Sub,
    Wasm.Binary.Instr.i32WrapI64,
    Wasm.Binary.Instr.i64Const 1,
    Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
    Wasm.Binary.Instr.localGet 6,
    Wasm.Binary.Instr.i64Const 32,
    Wasm.Binary.Instr.i64Sub,
    Wasm.Binary.Instr.i32WrapI64,
    Wasm.Binary.Instr.localGet 1,
    Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
    Wasm.Binary.Instr.localGet 6,
    Wasm.Binary.Instr.i64Const 24,
    Wasm.Binary.Instr.i64Sub,
    Wasm.Binary.Instr.i32WrapI64,
    Wasm.Binary.Instr.i64Const 0,
    Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
    Wasm.Binary.Instr.localGet 6,
    Wasm.Binary.Instr.i64Const 16,
    Wasm.Binary.Instr.i64Sub,
    Wasm.Binary.Instr.i32WrapI64,
    Wasm.Binary.Instr.i64Const 0,
    Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
    Wasm.Binary.Instr.localGet 6,
    Wasm.Binary.Instr.i64Const 8,
    Wasm.Binary.Instr.i64Sub,
    Wasm.Binary.Instr.i32WrapI64,
    Wasm.Binary.Instr.i64Const 0,
    Wasm.Binary.Instr.i64Store { align := 3, offset := 0 }]
   none,
 Wasm.Binary.Instr.globalGet 2] ++ body75Tail24)

@[cbv_eval] theorem sequence75_tail16 :
    instructionSequenceAt 346 false { bytes := artifactBytes, pos := 15215, limit := 15544 } =
      .ok ((body75Tail16, .end), { bytes := artifactBytes, pos := 15544, limit := 15544 }) := by
  change _ = (Except.ok ((([Wasm.Binary.Instr.globalGet 1,
 Wasm.Binary.Instr.localSet 3,
 Wasm.Binary.Instr.block
   (Wasm.Binary.BlockType.empty)
   [Wasm.Binary.Instr.loop
      (Wasm.Binary.BlockType.empty)
      [Wasm.Binary.Instr.localGet 3,
       Wasm.Binary.Instr.i64Const 0,
       Wasm.Binary.Instr.i64Eq,
       Wasm.Binary.Instr.brIf 1,
       Wasm.Binary.Instr.localGet 6,
       Wasm.Binary.Instr.i64Const 0,
       Wasm.Binary.Instr.i64Ne,
       Wasm.Binary.Instr.brIf 1,
       Wasm.Binary.Instr.localGet 3,
       Wasm.Binary.Instr.i64Const 32,
       Wasm.Binary.Instr.i64Sub,
       Wasm.Binary.Instr.i32WrapI64,
       Wasm.Binary.Instr.i64Load { align := 3, offset := 0 },
       Wasm.Binary.Instr.localSet 4,
       Wasm.Binary.Instr.localGet 3,
       Wasm.Binary.Instr.i64Const 8,
       Wasm.Binary.Instr.i64Sub,
       Wasm.Binary.Instr.i32WrapI64,
       Wasm.Binary.Instr.i64Load { align := 3, offset := 0 },
       Wasm.Binary.Instr.localSet 5,
       Wasm.Binary.Instr.localGet 4,
       Wasm.Binary.Instr.localGet 1,
       Wasm.Binary.Instr.i64GeU,
       Wasm.Binary.Instr.iff
         (Wasm.Binary.BlockType.empty)
         [Wasm.Binary.Instr.localGet 2,
          Wasm.Binary.Instr.i64Const 0,
          Wasm.Binary.Instr.i64Eq,
          Wasm.Binary.Instr.iff
            (Wasm.Binary.BlockType.empty)
            [Wasm.Binary.Instr.localGet 5, Wasm.Binary.Instr.globalSet 1]
            (some [Wasm.Binary.Instr.localGet 2,
              Wasm.Binary.Instr.i64Const 8,
              Wasm.Binary.Instr.i64Sub,
              Wasm.Binary.Instr.i32WrapI64,
              Wasm.Binary.Instr.localGet 5,
              Wasm.Binary.Instr.i64Store { align := 3, offset := 0 }]),
          Wasm.Binary.Instr.localGet 3,
          Wasm.Binary.Instr.i64Const 48,
          Wasm.Binary.Instr.i64Sub,
          Wasm.Binary.Instr.i32WrapI64,
          Wasm.Binary.Instr.i64Const 5501223100278326855,
          Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
          Wasm.Binary.Instr.localGet 3,
          Wasm.Binary.Instr.i64Const 40,
          Wasm.Binary.Instr.i64Sub,
          Wasm.Binary.Instr.i32WrapI64,
          Wasm.Binary.Instr.i64Const 1,
          Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
          Wasm.Binary.Instr.localGet 3,
          Wasm.Binary.Instr.i64Const 32,
          Wasm.Binary.Instr.i64Sub,
          Wasm.Binary.Instr.i32WrapI64,
          Wasm.Binary.Instr.localGet 4,
          Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
          Wasm.Binary.Instr.localGet 3,
          Wasm.Binary.Instr.i64Const 24,
          Wasm.Binary.Instr.i64Sub,
          Wasm.Binary.Instr.i32WrapI64,
          Wasm.Binary.Instr.i64Const 0,
          Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
          Wasm.Binary.Instr.localGet 3,
          Wasm.Binary.Instr.i64Const 16,
          Wasm.Binary.Instr.i64Sub,
          Wasm.Binary.Instr.i32WrapI64,
          Wasm.Binary.Instr.i64Const 0,
          Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
          Wasm.Binary.Instr.localGet 3,
          Wasm.Binary.Instr.i64Const 8,
          Wasm.Binary.Instr.i64Sub,
          Wasm.Binary.Instr.i32WrapI64,
          Wasm.Binary.Instr.i64Const 0,
          Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
          Wasm.Binary.Instr.localGet 3,
          Wasm.Binary.Instr.localSet 6]
         (some [Wasm.Binary.Instr.localGet 3,
           Wasm.Binary.Instr.localSet 2,
           Wasm.Binary.Instr.localGet 5,
           Wasm.Binary.Instr.localSet 3]),
       Wasm.Binary.Instr.br 0]],
 Wasm.Binary.Instr.localGet 6,
 Wasm.Binary.Instr.i64Const 0,
 Wasm.Binary.Instr.i64Eq,
 Wasm.Binary.Instr.iff
   (Wasm.Binary.BlockType.empty)
   [Wasm.Binary.Instr.globalGet 0,
    Wasm.Binary.Instr.i64Const 48,
    Wasm.Binary.Instr.i64Add,
    Wasm.Binary.Instr.localGet 1,
    Wasm.Binary.Instr.i64Add,
    Wasm.Binary.Instr.localTee 4,
    Wasm.Binary.Instr.globalGet 0,
    Wasm.Binary.Instr.i64LtU,
    Wasm.Binary.Instr.iff (Wasm.Binary.BlockType.empty) [Wasm.Binary.Instr.unreachable] none,
    Wasm.Binary.Instr.localGet 4,
    Wasm.Binary.Instr.i64Const 1,
    Wasm.Binary.Instr.i64Sub,
    Wasm.Binary.Instr.i64Const 65536,
    Wasm.Binary.Instr.i64DivU,
    Wasm.Binary.Instr.i64Const 1,
    Wasm.Binary.Instr.i64Add,
    Wasm.Binary.Instr.localSet 5,
    Wasm.Binary.Instr.memorySize 0,
    Wasm.Binary.Instr.i64ExtendI32U,
    Wasm.Binary.Instr.localGet 5,
    Wasm.Binary.Instr.i64LtU,
    Wasm.Binary.Instr.iff
      (Wasm.Binary.BlockType.empty)
      [Wasm.Binary.Instr.localGet 5,
       Wasm.Binary.Instr.memorySize 0,
       Wasm.Binary.Instr.i64ExtendI32U,
       Wasm.Binary.Instr.i64Sub,
       Wasm.Binary.Instr.i32WrapI64,
       Wasm.Binary.Instr.memoryGrow 0,
       Wasm.Binary.Instr.i32Const (-1),
       Wasm.Binary.Instr.i32Eq,
       Wasm.Binary.Instr.iff (Wasm.Binary.BlockType.empty) [Wasm.Binary.Instr.unreachable] none]
      none,
    Wasm.Binary.Instr.globalGet 0,
    Wasm.Binary.Instr.i64Const 48,
    Wasm.Binary.Instr.i64Add,
    Wasm.Binary.Instr.localSet 6,
    Wasm.Binary.Instr.localGet 4,
    Wasm.Binary.Instr.globalSet 0,
    Wasm.Binary.Instr.localGet 6,
    Wasm.Binary.Instr.i64Const 48,
    Wasm.Binary.Instr.i64Sub,
    Wasm.Binary.Instr.i32WrapI64,
    Wasm.Binary.Instr.i64Const 5501223100278326855,
    Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
    Wasm.Binary.Instr.localGet 6,
    Wasm.Binary.Instr.i64Const 40,
    Wasm.Binary.Instr.i64Sub,
    Wasm.Binary.Instr.i32WrapI64,
    Wasm.Binary.Instr.i64Const 1,
    Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
    Wasm.Binary.Instr.localGet 6,
    Wasm.Binary.Instr.i64Const 32,
    Wasm.Binary.Instr.i64Sub,
    Wasm.Binary.Instr.i32WrapI64,
    Wasm.Binary.Instr.localGet 1,
    Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
    Wasm.Binary.Instr.localGet 6,
    Wasm.Binary.Instr.i64Const 24,
    Wasm.Binary.Instr.i64Sub,
    Wasm.Binary.Instr.i32WrapI64,
    Wasm.Binary.Instr.i64Const 0,
    Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
    Wasm.Binary.Instr.localGet 6,
    Wasm.Binary.Instr.i64Const 16,
    Wasm.Binary.Instr.i64Sub,
    Wasm.Binary.Instr.i32WrapI64,
    Wasm.Binary.Instr.i64Const 0,
    Wasm.Binary.Instr.i64Store { align := 3, offset := 0 },
    Wasm.Binary.Instr.localGet 6,
    Wasm.Binary.Instr.i64Const 8,
    Wasm.Binary.Instr.i64Sub,
    Wasm.Binary.Instr.i32WrapI64,
    Wasm.Binary.Instr.i64Const 0,
    Wasm.Binary.Instr.i64Store { align := 3, offset := 0 }]
   none,
 Wasm.Binary.Instr.globalGet 2] ++ body75Tail24), .end), { bytes := artifactBytes, pos := 15544, limit := 15544 }) : Except Error ((List Instr × Terminator) × Cursor))
  cbv

@[cbv_opaque] def body75Tail8 : List Instr := ([Wasm.Binary.Instr.localGet 1,
 Wasm.Binary.Instr.i64Const 8,
 Wasm.Binary.Instr.i64LtU,
 Wasm.Binary.Instr.iff (Wasm.Binary.BlockType.empty) [Wasm.Binary.Instr.i64Const 8, Wasm.Binary.Instr.localSet 1] none,
 Wasm.Binary.Instr.i64Const 0,
 Wasm.Binary.Instr.localSet 6,
 Wasm.Binary.Instr.i64Const 0,
 Wasm.Binary.Instr.localSet 2] ++ body75Tail16)

@[cbv_eval] theorem sequence75_tail8 :
    instructionSequenceAt 354 false { bytes := artifactBytes, pos := 15195, limit := 15544 } =
      .ok ((body75Tail8, .end), { bytes := artifactBytes, pos := 15544, limit := 15544 }) := by
  change _ = (Except.ok ((([Wasm.Binary.Instr.localGet 1,
 Wasm.Binary.Instr.i64Const 8,
 Wasm.Binary.Instr.i64LtU,
 Wasm.Binary.Instr.iff (Wasm.Binary.BlockType.empty) [Wasm.Binary.Instr.i64Const 8, Wasm.Binary.Instr.localSet 1] none,
 Wasm.Binary.Instr.i64Const 0,
 Wasm.Binary.Instr.localSet 6,
 Wasm.Binary.Instr.i64Const 0,
 Wasm.Binary.Instr.localSet 2] ++ body75Tail16), .end), { bytes := artifactBytes, pos := 15544, limit := 15544 }) : Except Error ((List Instr × Terminator) × Cursor))
  cbv

@[cbv_opaque] def body75Tail0 : List Instr := ([Wasm.Binary.Instr.localGet 0,
 Wasm.Binary.Instr.i64Const 7,
 Wasm.Binary.Instr.i64Add,
 Wasm.Binary.Instr.i64Const 8,
 Wasm.Binary.Instr.i64DivU,
 Wasm.Binary.Instr.i64Const 8,
 Wasm.Binary.Instr.i64Mul,
 Wasm.Binary.Instr.localSet 1] ++ body75Tail8)

@[cbv_eval] theorem sequence75_tail0 :
    instructionSequenceAt 362 false { bytes := artifactBytes, pos := 15182, limit := 15544 } =
      .ok ((body75Tail0, .end), { bytes := artifactBytes, pos := 15544, limit := 15544 }) := by
  change _ = (Except.ok ((([Wasm.Binary.Instr.localGet 0,
 Wasm.Binary.Instr.i64Const 7,
 Wasm.Binary.Instr.i64Add,
 Wasm.Binary.Instr.i64Const 8,
 Wasm.Binary.Instr.i64DivU,
 Wasm.Binary.Instr.i64Const 8,
 Wasm.Binary.Instr.i64Mul,
 Wasm.Binary.Instr.localSet 1] ++ body75Tail8), .end), { bytes := artifactBytes, pos := 15544, limit := 15544 }) : Except Error ((List Instr × Terminator) × Cursor))
  cbv

end Project.TinyGpt2Hidden.Artifact
