;; Small R7RS host compiler for the arena VM; output is a JSON array of word strings.
(import (scheme base) (scheme cxr) (scheme read) (scheme write) (scheme file)
        (scheme process-context))

(define instructions '())
(define functions '())
(define descriptors '())
(define next-name 0)
(define next-label 0)
(define opcodes '(word bool unit callcc load store close drop jump branch
                 binary call tailcall ret global))
(define primitives '((+ . 0) (- . 1) (< . 2) (= . 3)))
(define syntax '(lambda if begin set! let define quote))

(define (fresh-name)
  (set! next-name (+ next-name 1)) next-name)
(define (fresh-ids names)
  (if (null? names) '()
      (let ((id (fresh-name))) (cons id (fresh-ids (cdr names))))))
(define (fresh-label)
  (set! next-label (+ next-label 1))
  (string->symbol (string-append "label" (number->string next-label))))
(define (opcode name)
  (let loop ((xs opcodes) (i 0))
    (if (eq? (car xs) name) i (loop (cdr xs) (+ i 1)))))
(define (emit! op . operands)
  (let ((a (if (null? operands) 0 (car operands)))
        (b (if (< (length operands) 2) 0 (cadr operands))))
    (set! instructions (cons (list (opcode op) a b 0) instructions))))
(define (label! name)
  (set! instructions (cons (list 'label name) instructions)))
(define (finish! tail?) (if tail? (emit! 'ret)))
(define (check-length form n)
  (if (not (= (length form) n)) (error "wrong form length" form)))
(define (check-names names)
  (if (not (list? names)) (error "fixed parameter list required" names))
  (let loop ((xs names) (seen '()))
    (if (pair? xs)
        (begin
          (if (or (not (symbol? (car xs))) (memq (car xs) syntax)
                  (memq (car xs) seen))
              (error "invalid or duplicate binding" (car xs)))
          (loop (cdr xs) (cons (car xs) seen))))))

;; A context holds this lambda's parameters and the IDs it must capture.
;; IDs are unique per lexical binding, including shadowed names.
(define (reference! id context)
  (if (and context (not (memv id (vector-ref context 0)))
           (not (memv id (vector-ref context 1))))
      (vector-set! context 1 (cons id (vector-ref context 1)))))
(define (binding name env context)
  (let ((entry (assq name env)))
    (if (not entry) (error "unbound variable" name))
    (reference! (cdr entry) context)
    (cdr entry)))

(define (sequence! forms env tail? context)
  (cond ((null? forms) (emit! 'unit) (finish! tail?))
        ((null? (cdr forms)) (expression! (car forms) env tail? context))
        (else (expression! (car forms) env #f context) (emit! 'drop)
              (sequence! (cdr forms) env tail? context))))

(define (lambda! form env outer-context)
  (if (< (length form) 3) (error "lambda needs a body" form))
  (let* ((params (cadr form))
         (_ (check-names params))
         (ids (fresh-ids params))
         (local-env (append (map cons params ids) env))
         (context (vector ids '()))
         (entry (fresh-label))
         (saved instructions))
    ;; Compile the body separately so captures are known before emitting close.
    (set! instructions '())
    (sequence! (cddr form) local-env #t context)
    (set! functions (cons (cons (list 'label entry) (reverse instructions)) functions))
    (set! instructions saved)
    (let* ((captures (reverse (vector-ref context 1)))
           (index (length descriptors))
           (desc (append (list (length ids)) ids
                         (list (length captures)) captures)))
      ;; Creating a nested closure also uses its captures in the enclosing lambda.
      (for-each (lambda (id) (reference! id outer-context)) captures)
      (set! descriptors (append descriptors (list desc)))
      (emit! 'close entry (cons 'descriptor index)))))

(define (expression! expr env tail? context)
  (cond
    ((boolean? expr) (emit! 'bool (if expr 1 0)) (finish! tail?))
    ((number? expr)
     (if (not (and (integer? expr) (exact? expr)
                   (<= 0 expr 18446744073709551615)))
         (error "literal must be an unsigned 64-bit integer" expr))
     (emit! 'word expr) (finish! tail?))
    ((symbol? expr)
     (cond ((assq expr env) (emit! 'load (binding expr env context)))
           ((memq expr '(call/cc call-with-current-continuation)) (emit! 'callcc))
           ((assq expr primitives)
            (lambda! (list 'lambda '(a b) (list expr 'a 'b)) env context))
           (else (error "unbound variable" expr)))
     (finish! tail?))
    ((or (not (list? expr)) (null? expr)) (error "unsupported expression" expr))
    ((eq? (car expr) 'lambda) (lambda! expr env context) (finish! tail?))
    ((eq? (car expr) 'begin) (sequence! (cdr expr) env tail? context))
    ((eq? (car expr) 'if)
     (if (not (or (= (length expr) 3) (= (length expr) 4)))
         (error "if needs two or three expressions" expr))
     (let ((otherwise (fresh-label)) (done (fresh-label)))
       (expression! (cadr expr) env #f context)
       (emit! 'branch otherwise)
       (expression! (caddr expr) env tail? context)
       (if (not tail?) (emit! 'jump done))
       (label! otherwise)
       (if (= (length expr) 4)
           (expression! (cadddr expr) env tail? context)
           (begin (emit! 'unit) (finish! tail?)))
       (if (not tail?) (label! done))))
    ((eq? (car expr) 'set!)
     (check-length expr 3)
     (let ((id (binding (cadr expr) env context)))
       (expression! (caddr expr) env #f context)
       (emit! 'store id) (finish! tail?)))
    ((eq? (car expr) 'let)
     (if (or (< (length expr) 3) (not (list? (cadr expr))))
         (error "ordinary let with a body required" expr))
     (let ((bindings (cadr expr)))
       (for-each (lambda (b)
                   (if (not (and (list? b) (= (length b) 2)))
                       (error "invalid let binding" b))) bindings)
       (check-names (map car bindings))
       (expression! (cons (cons 'lambda (cons (map car bindings) (cddr expr)))
                          (map cadr bindings)) env tail? context)))
    ((memq (car expr) '(define quote)) (error "unsupported expression form" expr))
    ((and (symbol? (car expr)) (not (assq (car expr) env))
          (assq (car expr) primitives))
     (check-length expr 3)
     (expression! (cadr expr) env #f context)
     (expression! (caddr expr) env #f context)
     (emit! 'binary (cdr (assq (car expr) primitives))) (finish! tail?))
    (else
     (expression! (car expr) env #f context)
     (for-each (lambda (arg) (expression! arg env #f context)) (cdr expr))
     (emit! (if tail? 'tailcall 'call) (length (cdr expr))))))

(define (definition? form)
  (and (pair? form) (eq? (car form) 'define)))
(define (normalize-definition form)
  (if (or (not (list? form)) (< (length form) 3))
      (error "invalid definition" form))
  (if (pair? (cadr form))
      (list 'define (caadr form) (cons 'lambda (cons (cdadr form) (cddr form))))
      (begin (check-length form 3) form)))
(define (compile-program forms)
  (let* ((forms (map (lambda (f) (if (definition? f) (normalize-definition f) f)) forms))
         (definitions (let loop ((xs forms))
                        (cond ((null? xs) '())
                              ((definition? (car xs)) (cons (cadar xs) (loop (cdr xs))))
                              (else (loop (cdr xs))))))
         (_ (check-names definitions))
         (env (map cons definitions (fresh-ids definitions))))
    ;; Allocate all global locations before evaluating any initializer.
    (for-each (lambda (b) (emit! 'unit) (emit! 'global (cdr b)) (emit! 'drop)) env)
    (let loop ((xs forms))
      (if (null? xs)
          (begin (emit! 'unit) (emit! 'ret))
          (let ((last? (null? (cdr xs))) (f (car xs)))
            (if (definition? f)
                (begin (expression! (caddr f) env #f #f)
                       (emit! 'store (cdr (assq (cadr f) env)))
                       (if last? (emit! 'ret) (emit! 'drop)))
                (begin (expression! f env last? #f)
                       (if (not last?) (emit! 'drop))))
            (if (not last?) (loop (cdr xs))))))
    (assemble (append (reverse instructions) (apply append (reverse functions))))))

(define (assemble ir)
  (let ((labels '()) (code '()) (count 0) (offsets '()))
    (for-each (lambda (i)
                (if (eq? (car i) 'label)
                    (set! labels (cons (cons (cadr i) count) labels))
                    (begin (set! code (cons i code)) (set! count (+ count 1))))) ir)
    (let loop ((ds descriptors) (offset (+ 1 (* 4 count))))
      (if (pair? ds)
          (begin (set! offsets (append offsets (list offset)))
                 (loop (cdr ds) (+ offset (length (car ds)))))))
    (let ((resolve (lambda (x)
                     (cond ((symbol? x) (cdr (assq x labels)))
                           ((pair? x) (list-ref offsets (cdr x)))
                           (else x)))))
      (cons count (append (apply append (map (lambda (i) (map resolve i)) (reverse code)))
                          (apply append descriptors))))))

(define (read-program path)
  (call-with-input-file path
    (lambda (port)
      (let loop ((forms '()))
        (let ((form (read port)))
          (if (eof-object? form) (reverse forms) (loop (cons form forms))))))))
(define (write-json words)
  (display "[")
  (let loop ((xs words) (separator ""))
    (if (pair? xs)
        (begin (display separator) (write (number->string (car xs)))
               (loop (cdr xs) ","))))
  (display "]") (newline))

(if (not (= (length (command-line)) 2))
    (error "usage: scheme-compile.scm SOURCE.scm"))
(write-json (compile-program (read-program (cadr (command-line)))))
